### PR TITLE
Adds heads of staff cloaks, adds them to the loadout.

### PR DESCRIPTION
**Pull request by Kholdstare34**
Adds heads of staff cloaks for colony director, head of personnel, chief medical officer, chief engineer, research director, and quartermaster, and adds them to the loadout. 

Images: https://imgur.com/a/fjrOU?grid

### CODE REVIEW

**Comment by Anewbe** [comment]
Are there non-Head of Staff variants, or just for important people?

**Comment by Wutnold124** [comment]
considering that the title says "adds heads of staff cloaks" and not "adds cloaks" i'd assume the latter

**Comment by Belsima** [comment]
give only the CMO one tesh sprites

**Comment by Anewbe** [comment]
Nevermind.

Please make a default /obj/item/clothing/accessory/poncho/roles/cloak item and set body_parts_covered = null ?

**Pull request merged**
