### PR TITLE
THE MINI FIST-PUNCH UPDATE

### PR DESCRIPTION
**Pull request by Anewbe**
**REWORKS SOME BACKGROUND CODE RELATING TO HAND-TO-HAND COMBAT.**

- **FOR DEVS, THIS MEANS THAT YOU CAN, IF DESIRED, MAKE NEW SPECIES RELATED MELEE ATTACKS THAT DO DAMAGE OTHER THAN BRUTE. YOU CAN MAKE GLOVES THAT DO DAMAGE OTHER THAN BRUTE, IF YOU WANT. MORE TO COME WHEN I REMEMBER WHAT IT IS I WANTED TO CODE NEXT.**

- **FOR PLAYERS, THIS MEANS YOUR HANDGEAR MATTERS, JUST A LITTLE. RINGS AND CERTAIN GLOVES ADD A LITTLE BIT OF DAMAGE TO EVERY PUNCH. NUMBERS ARE SUBJECT TO TWEAKS, AT STAFF DISCRETION.**
- **ALSO FOR PLAYERS, BRASS KNUCKLES ARE NOW A TYPE OF GLOVE. THEY HURT A BIT LESS THAN BEFORE, BECAUSE IT'S A BIT HARDER TO STEAL SOMEONE'S GLOVES.**

[I CAST FIST](https://www.youtube.com/watch?v=m7RosIoQisA)

### CODE REVIEW

**Comment by BillyBangles** [comment]
_L I G H T N I N G   F I S T S_

**Comment by mistyLuminescence** [comment]
**GOOD PR**

**Comment by BillyBangles** [comment]
brb gonna go make lightning gauntlets once this gets merged

**Comment by Anewbe** [comment]
**BILLY YOU'RE GONNA NEED TO WAIT FOR THE NEXT MINI FIST-PUNCH UPDATE BEFORE THAT'LL BE DOABLE IN A WAY THAT'S ACTUALLY POSSIBLE TO BALANCE.**

**BECAUSE I'VE ALREADY THOUGHT UP WAYS TO ADD FUNCTIONALITY, BUT UNTIL THIS IS MERGED I CAN'T DO ANYTHING FUN WITH IT.**

**AND ADDING FEATURES TO OPEN PRS IS BAD.**

**Comment by BillyBangles** [comment]
**I APPRECIATE YOUR CONCERN ANEWBE AND I WOULD LIKE TO SAY THAT I AM A VERY PATIENT INDIVIDUAL AND CAN RESPECT THE FACT THAT THIS FEATURE HAS SOME WORK TO BE DONE

YOU ARE DOING A GOOD JOB AND I APPRECIATE YOU AND YOUR WORK AND WOULD LIKE YOU TO KNOW THAT LIGHTNING FISTS WILL BE RAD AS HELL.**

**Comment by Atermonera** [comment]
**I EXPECT ENTERTAINMENT FROM THIS CHANGELOG ENTRY, ON THE SCALE OF THE REST OF THIS PR**

**Comment by Atermonera** [comment]
**WAIT A SECOND THERE'S ALREADY ONE IN HERE, FUCK**

**Comment by Anewbe** [comment]
**MY KNUCKLES HAVE FORESIGHT**

**Comment by Atermonera** [comment]
**WHILE REVIEWING THE CODE, I HAD THE THOUGHT TO READ ALL OF THIS IN A GORON VOICE, BROTHER. IT WAS VERY ENTERTAINING. THE CODE LOOKS FINE.**

**Pull request merged**
