### PR TITLE
Re-adds Serena's April Fools Taj sprites

### PR DESCRIPTION
**Pull request by Serithi**
Because they're actually nice sprites.

Originally from https://github.com/PolarisSS13/Polaris/pull/1321

### CODE REVIEW

**Comment by Anewbe** [comment]
Gonna need to talk to the Loremaster 'bout this.

**Comment by Atermonera** [comment]
Lore head or catlord? Because unless that's already changed again, isn't Serithi catlord?

**Comment by Anewbe** [comment]
That's the joke, ya dingus.

**Comment by OhEmGee** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASSAAAAAASAAAAAAAAAAAAA

**Comment by Earthykiller127** [comment]
>minecraft avatar

**Comment by Spacemanspark** [comment]
Please no.
It was a joke for a reason.

**Comment by nachomeep** [comment]
setting up my pr to give dionae boobs now

**Comment by Nienhaus** [comment]
I fixed the sprite for you guys.

**Pull request merged**
