### PR TITLE
Adds maglights

### PR DESCRIPTION
**Pull request by Sabess**
Available in sec lockers and hacked autolathe.
Does less damage than sec batons and other weapons that are available in the hacked autolathe, but lights up.

### CODE REVIEW

**Comment by Anewbe** [comment]
Had something similar on tg a while back, very much a fan... But you may want to tone down the damage, 13's pretty high, in my opinion.

**Comment by Lorwp** [comment]
13 is a bit high, Maybe lower it to something like `8`. Otherwise this has my :+1:

**Comment by Sabess** [comment]
Don't agree, it's all relative. It's only available to two departments. Both of these departments have items that do more damage.

**Comment by Lorwp** [comment]
i guess so, though it does feel a bit weird to have a flashlight be a melee weapon.

**Comment by Zuhayr** [comment]
13 is extremely excessive for a flashlight.

**Comment by Sabess** [comment]
Disagree, but I'll tweak it down seeing as a fair few people want it that way.

**Comment by Nienhaus** [comment]
I should really make a v3 Maglite. But it's still nice to see the sprite used.

**Comment by Zuhayr** [comment]
Leery of approving this but unclear if that's just bias or not, paging @Neerti @EmperorJon @Datraen for final approval.

**Comment by OhEmGee** [comment]
>13 is extremely excessive for a flashlight
have you guys SEEN a maglight IRL? The heavier ones could be used to bludgeon somone into submission, they're like the same as your run of the mill claw hammer in terms of bludgeoning

i'd say 10 (which is the same as the toolbox) would be a good median

**Comment by Sabess** [comment]
It was changed to ten if you'll have another look at the code. :P

**Pull request closed without merging**
