### PR TITLE
Reinforced snowball fix.

### PR DESCRIPTION
**Pull request by MisterLayne**
Fixes the reinforced snowball so it doesn't take so long to create. Also comments out the 'reinf-snowball' icon_state until I (or someone else) make an icon for that.

### CODE REVIEW

**Comment by MisterLayne** [comment]
Are changelogs a _needed_ thing now? If so, I have no idea how to do them.

**Comment by BillyBangles** [comment]
Check html/changelogs/example.yml. Explains the whole thing. It's easier than it looks.

**Comment by Atermonera** [comment]
All you guys have to do is copy a file, rename it, and fill out some stuff in it.
And then whenever I notice there's a few (Usually starts around 5) changelog files sitting in the folder, I run the script and update the actual changelog

**Comment by Schnayy** [comment]
Let's not have code that results in spriteless items. I did make a sprite for it that you can use, however. https://i.imgur.com/iDgiejF.png

**Comment by Belsima** [comment]
It wouldn't be spriteless, it'd use the sprite of its base.

**Comment by Schnayy** [comment]
I mostly say that bc it was put in, in the first place, with no sprites.

**Comment by MisterLayne** [comment]
@Schnayy It's not spriteless, it is using the parent sprite. Also- It was not intended to be put in with no sprites. I have no clue why my reinforced snowball sprites weren't part of the first commit. I'll handle the sprites in a later commit, and probably just clean up the snowball code to be better placed, etc.

**Comment by MisterLayne** [comment]
@Atermonera changelog done

**Pull request merged**
