### PR TITLE
Adds changelogs for recent things + updates changelogs

### PR DESCRIPTION
**Pull request by Yoshax**
Does it all in the one PR because I'm a monster.

### CODE REVIEW

**Comment by SinTwo** [comment]
You monster.

**Comment by EmperorJon** [comment]
Actually it says Readstyrker! I'll leave it for now in case Yosh wants to correct it.

**Comment by Yoshax** [comment]
Fix'd.

**Comment by EmperorJon** [comment]
It still says Redstyrker  :P

**Pull request merged**
