### PR TITLE
Adds skintone to FBPs

### PR DESCRIPTION
**Pull request by Anewbe**
Sort of based on what Baystation did.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
How well does it work? :o

**Comment by Anewbe** [comment]
Should be the same as a human, worked in testing.

**Comment by SilverTalismen** [comment]
Awesome! Will be great for Veymed- Which I'm assuming is the only brand it works for xD

**Comment by Anewbe** [comment]
Yep.

**Pull request merged**
