### PR TITLE
Allows detectives to take an optional revolver + some other stuff

### PR DESCRIPTION
**Pull request by Sabess**
Did I do this right?? I'm so confused right now.

I'm gonna like assume this worked.

Okay, so this replaces the detective guns with a box that allows you to choose between the pistol and the revolver. Revolver is .45 and has 7 shots, just like the pistol. Also added a few .45 speedloaders around security, in the autolathe and for antags in-case it's an antagdetective who wants lethals. Also added a glock sprite to the .45 because I found it and it's cool. 

Thanks to Anewbe and Neerti for doing the hard parts of the code and Mechoid for sprite help and general help and stuff thanks.

### CODE REVIEW

**Comment by Anewbe** [comment]
Did you run the map merger?

**Comment by Wickedtemp** [comment]
...can you add one more thing to the changed files, so it's 10,000?

**Comment by Sabess** [comment]
fixed (i hope)

**Comment by Sabess** [comment]
broke the resprite/rename thing due to a typo right after testing but before actually dusting things off and PRing it, I'm derp, fixed now

**Comment by Mark9013100** [comment]
glocks are the shittiest handguns in the world, P E A S H O O T E R S

**Comment by sabiram** [comment]
I made the Webley icon originally, so I'm glad to see it being used even beyond bay. If you want, I added a more traditional colour scheme and improved the shading on the silver one a little.

If you want them: (classic gun is in guns.dmi, silver one is in uniques.dmi)
https://github.com/Baystation12/Baystation12/pull/19264

**Comment by Sabess** [comment]
Thanks! I'll probably add that as a "Webley, Dark" thing for more variation.

**Pull request merged**
