### PR TITLE
Revert "Adds a new death sound for mice."

### PR DESCRIPTION
**Pull request by Anewbe**
Reverts PolarisSS13/Polaris#3781

Been getting complaints about the sounds.

### CODE REVIEW

**Comment by Belsima** [comment]
Could I ask what the complaints were? If it's about volume, I can adjust that.

**Comment by Anewbe** [comment]
It's loud and it doesn't sound like what people think a mouse sounds like.

**Comment by Belsima** [comment]
its... literally a recording of a mouse

**Comment by Anewbe** [comment]
It's annoying.

**Comment by Belsima** [comment]
Eh, fair enough.

**Comment by Wickedtemp** [comment]
It...just sounds like a mouse. Tbh I think people just have the sound too high. I'm indifferent towards the change, but I thought I'd add my two cents, I'm not hearing the "banshee screech" people are claiming.

**Comment by Woodratt** [comment]
The death sound is eh, okay. The sound that you get when you step on one is loud as hell and just doesn't sound right.

**Comment by Belsima** [comment]
I'll fix that. One moment.

**Pull request closed without merging**
