### PR TITLE
Fixes lung rupturing in partial pressure or overpressure

### PR DESCRIPTION
**Pull request by Techhead0**
Also deals with a runtime

Alternative to #2759

### CODE REVIEW

**Comment by Anewbe** [comment]
Travis says:
> code/modules/mob/living/carbon/human/life.dm:372:error: missing condition
> code/modules/mob/living/carbon/human/life.dm:373:error: proc definition not allowed inside another proc

**Comment by Anewbe** [comment]
Are you sure this fixes the runtime?

**Comment by Techhead0** [comment]
The runtime was because it would check `breath.total_moles` in situations where `breath` didn't exist. (Line 349) The `return` at the end of `if(!breath || (breath.total_moles == 0) || suiciding)` ensures that if `breath` doesn't exist, then it won't reach the later `breath.total_moles` comparisons.

**Comment by Anewbe** [comment]
If it works better than the other one I'll merge it, I'm just trying to parse the code.

Still not totally sure why the second block of code is placed where it is.

**Comment by Techhead0** [comment]
It is where it is to take advantage of preexisting checks for `should_have_organ(O_LUNGS)` and `L.is_bruised()`.

**Comment by Anewbe** [comment]
Something I've found (that I consider an issue) in testing these PRs is that lungs will frequently pop if the person goes into hardcrit, which I don't think is intended.

**Comment by Techhead0** [comment]
People in crit had been passing a `null` breath to `handle_breath()`. [See this proc.](https://github.com/PolarisSS13/Polaris/blob/0bb15b27324a371804f8f625708cbe8bb03b00e0/code/modules/mob/living/carbon/breathe.dm#L8)

Without a runtime fix, this would cause a runtime (`null.total_moles`), aborting `handle_breath()` before any chance of lung rupturing. With any fix in, lung-popping is a risk of crit.

I'll include a quickfix so that null breaths don't pop lungs but vacuums do.

**Comment by Anewbe** [comment]
That'd be appreciated.

**Pull request merged**
