### PR TITLE
Adds Colorable Apron & Tesh Labcoat

### PR DESCRIPTION
**Pull request by KasparoVy**
Adds a white colourable version of the blue apron
Adds a Teshari-fitted labcoat with an existing unused sprite and enables it for colouration in the loadout

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
Haha you beat me to adding a recolorable smock

**Comment by KasparoVy** [comment]
I saw the white smock while I was poking around in there and figured it'd be a good idea haha, may as well!

**Comment by Greenjoe12345** [comment]
So what should be done to stop our two prs from adding the same things?
I can remove adding the colorable smock and footwraps on mine, keeping the colorable cloak, undercoat and heterochomia?

**Comment by KasparoVy** [comment]
@Greenjoe12345 No worries I'll take it out of mine, no changes needed on yours

**Comment by Greenjoe12345** [comment]
Alright cool, you just add the apron and labcoat then, and I'll have to get Travis to stop hating my PR

**Comment by KasparoVy** [comment]
Oh right, conflicts - will resolve, cheers

**Comment by KasparoVy** [comment]
Alright good to go

**Pull request merged**
