### PR TITLE
Sell materials to Cargo!

### PR DESCRIPTION
**Pull request by mistyLuminescence**
Long story short, you can now sell the following materials to Cargo, for the following prices:
Diamond: 20/sheet
Metallic hydrogen: 15/sheet
Uranium: 10/sheet
Platinum: 5/sheet <-- already exists
Phoron: 5/sheet <-- already exists
Osmium: 4/sheet
Gold: 4/sheet
Silver: 3/sheet
Deuterium: 2/sheet
Tritium: 1/sheet
Thalers: 0.02/sheet (50:1) <-- already exists

This means that all those miners out there can still get rewarded for their hard work even when there's nobody in Science. Prices subject to change.

Also, lots of spaces turned into tabs. That's just how things should be done, dammit.

### CODE REVIEW

**Comment by Cyantime** [comment]
Deuterium is a literally infinite resource, you might not want to give any points for it.

**Comment by mistyLuminescence** [comment]
how have I looked through the chem files this many times and only just now noticed this
stand by

**Comment by mistyLuminescence** [comment]
required_reagents = list("water" = 10, "coolant" = 3, "foaming_agent" = 2)
catalysts = list("hydrophoron" = 5)

Also, coolant and kelotane now no longer spam admins when synthesised.
(why was this even a thing?? still applies to nitroglycerin. y'all still get pinged when someone's big-bomb-makin'.)

**Comment by Nalarac** [comment]
I'm not sure about uranium being worth that much to sell. It's fairly easy to get when mining.

**Comment by mistyLuminescence** [comment]
Never actually gone mining, just basing them off the R&D values. Maybe 7 (more than phoron, less than current)?

**Comment by Anewbe** [comment]
This is not going to be merged, at this time.
We don't want more reasons for Research to end up with nothing. If we do end up looking into this in the future, it will be done differently.

**Pull request closed without merging**
