### PR TITLE
Adds 12 new futuristic loadout clothing items + colour variants

### PR DESCRIPTION
**Pull request by Cerebulon**
Mostly 'modern' (Meaning, futuristic bullshit) casual clothes + a few traditional Indian and Japanese things.
https://i.gyazo.com/20b34b91d609be53ae99440d48ef85fd.png
https://i.gyazo.com/fdb9861dd2c5ab3cec3c4d93cbe9aa14.png

from left to right top to bottom:
Work pants (orange, blue, white, green, red)
Sleek overalls
Sari (Green, red)
Modern Wrap Jacket
Ascetic Garb
Asymmetrical Jacket (Blue, green, purple)
Cowled Vest
Kamishimo
Jingasa (Japanese rain hat)
Maang Tikka (Indian head jewellery)
Thin-frame glasses
Rimless glasses

Uniforms/outfits:
Workpants
front: https://i.gyazo.com/f490443c93bbd0138023c3a5f8b66f88.png
back: https://i.gyazo.com/947b39a0a2d32fb529f4e448c698b4c3.png
side: https://i.gyazo.com/471ac0a9701ce7fb906ecfb46ca0cc04.png

Sleek Overalls
front: https://i.gyazo.com/4b1c18ea8ebc6ce77be83818b1520dfd.png
side: https://i.gyazo.com/c0e6ad3fd2c570094a2627c8c1b859de.png

Sari
front green: https://i.gyazo.com/6519d1ddaa59935821e78b4b035d1f83.png
back red: https://i.gyazo.com/cd76a00cce279d9d4318e3e3dc3914dc.png

Modern Wrap Coat
https://i.gyazo.com/c4af46dc25fbcd6a9040545b956f75c8.png
https://i.gyazo.com/6776fea80ae2c4c196252f3366b59e09.png
https://i.gyazo.com/611ce118855d523da46fe3271e0528c3.png
https://i.gyazo.com/0ba6f20fed2535e269c8128216f3bbce.png

Ascetic Garb
pictured front with thin-frame glasses
https://i.gyazo.com/6c9984b5da65024613ed525f97fab81a.png

'Accessories'
Asymmetric jackets (Blue, purple, green)
(pictured green with orange work pants)
https://i.gyazo.com/b59eb3b2314f4d7b903d2ee0ab98b68e.png
https://i.gyazo.com/1d6f2e15d29cb7ec0c426dcfaf484ee6.png
https://i.gyazo.com/58d9a9a82c51bdb83dea385dcefc8f16.png
https://i.gyazo.com/8eb94c218fa3f38ef61433e5b9de84d3.png

Cowled Vest:
(pictured with yellow work pants)
front: https://i.gyazo.com/f4b1eb328c6d53e5ee0e6b6a872f6d14.png
back: https://i.gyazo.com/b1c49053bfd24408ff2f3ae15dce26b0.png

suit:
Kamishimo
(pictured with jingasa hat)
front: https://i.gyazo.com/4a05cc2176985cd95b1c8657ef4bd162.png
back: https://i.gyazo.com/7375d2eb1df8ea2394f8be1594cbb460.png
side: https://i.gyazo.com/3199b527ee79cb5be84d254aa73c913b.png

Maang Tikka
https://i.gyazo.com/8eda9ecc53eca417ac0b34d11ff5f08d.png

Oh and everything has teshsprites except the jackets and vest iirc

### CODE REVIEW

**Comment by SubberTheFabulous** [comment]
I will now forever love you.

**Comment by elgeonmb** [comment]
this pleases new kyoto

**Comment by lolman360** [comment]
thank you kanye, very cool

((is shitposting on prs still allowed or will i get slapped for it))

**Comment by Cerebulon** [comment]
Well that was a weird fuckin conflict. Should be fixed.

**Pull request merged**
