### PR TITLE
AI can speak station languages

### PR DESCRIPTION
**Pull request by Atermonera**

### CODE REVIEW

**Comment by Atermonera** [comment]
Conflict was because my branch hasn't updated since the start of summer when I started onto VR, and I don't much want to update my branch until that's done to prevent loss of work

**Comment by Atermonera** [comment]
Oh, and tested: [https://puu.sh/xIG8g/0ab24b4cbd.png](https://puu.sh/xIG8g/0ab24b4cbd.png)

**Comment by Mechoid** [comment]
Skrellian-make AI's can infact be dionae-an.. Dionan. Dionaean. One of those, in 'brainmode', so allowing them to have rootspeak when they *are* Dionaea should probably be left in.

**Comment by Anewbe** [comment]
I stand corrected.

**Comment by Atermonera** [comment]
I believe the correct plural for a pile of qt nymphs is 'piles of qt nymphs'

**Comment by SilverTalismen** [comment]
But from what I know of Diona, a massive machine is needed to just translate their local rootspeak, and their global rootspeak is done via like, raidation waves or something I believe so it can't be detected?

**Comment by Anewbe** [comment]
Diona can be AI, according to the LoreMaster. And the AI's a pretty massive machine.

**Comment by SilverTalismen** [comment]
Diona- don't have brains to be AI though? They can't even be borged..

**Comment by Anewbe** [comment]
*shrug Bring it up with Elgeon.

**Comment by elgeonmb** [comment]
Even a software/positronic AI would be able to speak Rootsong. It constitutes a sufficiently large translation machine.

**Comment by SilverTalismen** [comment]
My only issue is them being able to pick up the Global varient that is silent, the Global Rootspeak?

I guess I just enjoy the Tree's having a neat and silent language to talk to eachother without having to have a AI or something listen in on or talk to them through it.

**Comment by Anewbe** [comment]
I've seen RootGlobal used maybe twice, tbh.

**Comment by SilverTalismen** [comment]
I use it whenever I play Diona and we ever have another Diona.

**Comment by Anewbe** [comment]
Actually, let me toss in some clarity: The AI can only get Rootspeak if the character slot is Diona, if I'm reading this right.

**Comment by Atermonera** [comment]
Afaict rootspeak is restricted rather than whitelisted, so only diona-ai can take it.

**Pull request merged**
