### PR TITLE
Adds mob sprites for the headsets

### PR DESCRIPTION
**Pull request by Mark9013100**
Implements on-mob sprites for the normal headsets.

Normal:

Security:

Medical:

Engineering:

Service:

Command/Science:

Cargo:

Also renames the ERT headset and gives it the unused centcom sprite:

*Also comments out the unused medical research and roboticist headsets.

### CODE REVIEW

**Comment by Yoshax** [comment]
I dunno if I'm the only person, but I kinda like them not having sprites. Gives a nice clean look ;-;

Also you probably shouldn't that out, it's not causing any problems, and can be spawned by admins or such for stuffs. Is no real need to comment it out.

**Comment by Mark9013100** [comment]
I'll un-comment it out then.

**Comment by Datraen** [comment]
Is this above or below the hair layer?

**Comment by Mark9013100** [comment]
Goes above.

**Comment by Anewbe** [comment]
If only there was a way to have it both visible and invisible... 
Because I like this in theory, but in practice I don't want that sticking up from my head.

**Comment by mwerezak** [comment]
What happened to the original headset mob sprites? Those were pretty subtle, I liked them.

**Comment by Mark9013100** [comment]
It was inconsistent, as only the default headset had a sprite while the rest didn't(excluding the bowman headsets).

**Comment by mwerezak** [comment]
Just a matter of adding some colours right?

**Comment by Datraen** [comment]
Yeah, I figured it was above based on how headtail decorations are.

I'm against this entirely. It will be an issue with Skrell headtails.

**Comment by nachomeep** [comment]
I'd love this if it were under the hair layer. Also, I just want consistency between the default existing and these not.

**Pull request closed without merging**
