### PR TITLE
Jukebox Hacking. Again. Now with 100% less copyrights.

### PR DESCRIPTION
**Pull request by SpadesNeil**
https://github.com/PolarisSS13/Polaris/pull/2355 again but without Bandit Radio because no one is returning my god damn emails because GSC World is out of business.

So here's a version without Bandit Radio so there's no more copyright issues.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Oh god someone squash this please.

**Comment by Iamgoofball** [comment]
If GSC World is out of business it's probably public domain

**Comment by SpadesNeil** [comment]
If you can confirm that to be fact, I'm going to scream, but then thank you.

**Comment by SpadesNeil** [comment]
Oh! I'll do that.

Don't be afraid to merge this in the mean time. If I get confirmation on bandit_radio.ogg I can always just add it later.

**Comment by Mark9013100** [comment]
cheeki breeki iva damke

**Comment by SpadesNeil** [comment]
Apparently I'm a dumbass and didn't remove Bandit Radio. Now it's removed.

**Comment by Datraen** [comment]
clown.ogg is amazing and deserves the squash commit.

**Comment by Anewbe** [comment]
If clown.ogg is like clown.wav, I'm in.
Also, if russianrapdisco.ogg isn't the parody mentioned in the other PR, gonna need info on it.
Tertiary thing, Conflicts.
Other than that, looks fine to me.

**Comment by redstryker** [comment]
*whispers*
Changelog

**Comment by Anewbe** [comment]
Right, that.

**Comment by SpadesNeil** [comment]
> Conflicting files
> polaris.dme

rustle

> _whispers_
> Changelog

youbequiet

> If clown.ogg is like clown.wav, I'm in.
> Also, if russianrapdisco.ogg isn't the parody mentioned in the other PR, gonna need info on it.
> Tertiary thing, Conflicts.
> Other than that, looks fine to me.

RussianRapDisco **is** the parody I mentioned. It's perfectly fine and legal in the copyright department.

Anyway lemmie fix that changelog and fix the conflict.

**Comment by SpadesNeil** [comment]
Ok, conflict fixed.

**Comment by SpadesNeil** [comment]
NOW it's fixed... And it's good to merg--....

......

I forgot the fucking changelog, didn't I?

22-spongebob-school-hall-monitor

**Comment by SpadesNeil** [comment]
Okay _now_ it's done. For real this time.

Someone please squash this shit dear god it's a mess.

**Pull request merged**
