### PR TITLE
Food fluff

### PR DESCRIPTION
**Pull request by elgeonmb**
Gives fluff descriptions to everything in the Getmore vendor, also twobread.

Also removes the "Jargon 4" reference in the skrellsnaks description. I think that's a developmental legacy or something?

(god I hope this passes Travis)

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Well it didn't pass, guess this is a..*Travis*ty?

**Comment by Anewbe** [comment]
code/modules/examine/descriptions/food.dm:4:error: missing expression

**Comment by elgeonmb** [comment]
screaming

**Comment by elgeonmb** [comment]
are you satisfied, you cold machine

**Pull request merged**
