### PR TITLE
Edits the sprites for the prescription sec and med HUDs

### PR DESCRIPTION
**Pull request by Mark9013100**
The original sprites seem a bit fashioned together, so hopefully this improves them a tiny bit.

### CODE REVIEW

**Comment by Zuhayr** [comment]
Pics?

**Comment by Mark9013100** [comment]
Sure, just gimme a sec.

**Comment by Mark9013100** [comment]
Right, here:
Old sec hud sprite:

New sec hud sprite:

Old med hud sprite:

New med hud sprite:


Personally, I found the "normal" lens to clash with the other half of the sprite.

**Comment by Mark9013100** [comment]
Now for the mob sprites:
Old med hud:

New:

Old sec hud:

New:

**Comment by Datraen** [comment]
Personally I like these more.

**Comment by Hubblenaut** [comment]
If you change the prescription HUD on-mob sprite to red, you should probably do the same with the normal one. Same goes for the medical one, looks more transparent than normal.

**Comment by Mark9013100** [comment]
Right, I'll get to that after this PR, considering I can't rebase worth a damn.

**Comment by Hubblenaut** [comment]
finish commit with fixes to secondlast commit
´reset head --hard´
´rebase -i HEAD~2 (number of commits for rebase)´
change your latest commit to 'fixup'.

**Pull request merged**
