### PR TITLE
PENGUINS ARE FROM EARTH

### PR DESCRIPTION
**Pull request by elgeonmb**
Capitalize THIS, Anewbe, I Dare You

### CODE REVIEW

**Comment by lolman360** [comment]
inb4 closed for improper title

**Comment by Mechoid** [comment]
Fixed.

**Comment by elgeonmb** [comment]
Coward

**Comment by Anewbe** [comment]
Look again, boyo.

**Comment by Atermonera** [comment]
Is this one of those PRs where each dev has to take a turn making this worse?

**Comment by lolman360** [comment]
we need to invent an upperer case

**Comment by mistyLuminescence** [comment]
**ᴘᴇɴɢᴜɪɴs ᴀʀᴇ ғʀᴏᴍ ᴇᴀʀᴛʜ**

**Pull request merged**
