### PR TITLE
Admin logs graffiti and crayon drawings

### PR DESCRIPTION
**Pull request by GeneriedJenelle**
Tells you when and where players graffiti in admin log files. Also tells you what letters they are drawing.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
I got a bad feeling about this new addition to admin logs where there's already a high amount of it for other things downstream. Clogging up said admins' logs is where this is going to lead.

**Comment by GeneriedJenelle** [comment]
> I got a bad feeling about this new addition to admin logs where there's already a high amount of it for other things downstream. Clogging up said admins' logs is where this is going to lead.
@TheFurryFeline 
I could potentially make it a config thing, just in case perhaps?

**Comment by TheFurryFeline** [comment]
Could be a good way to go about it.

On Feb 6, 2020 18:56, "GeneriedJenelle" <notifications@github.com> wrote:

I got a bad feeling about this new addition to admin logs where there's
already a high amount of it for other things downstream. Clogging up said
admins' logs is where this is going to lead.
@TheFurryFeline <https://github.com/TheFurryFeline>
I could potentially make it a config thing, just in case perhaps?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/PolarisSS13/Polaris/pull/6671?email_source=notifications&email_token=AJGMTY5UWZDJGXYKKJ5NN23RBSPRDA5CNFSM4KQLH3B2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELBHJCQ#issuecomment-583169162>,
or unsubscribe

**Comment by GeneriedJenelle** [comment]
image
Not sure what happened, but I think github's broke damn. 

You can tell it's fake because I'm only that productive on Sunday nights.

**Comment by TheFurryFeline** [comment]
What in the devil? Conflicts and yet it ain't saying WHAT'S conflicting??? Commits are wack, too..... Try closing/reopening?

**Comment by Atermonera** [comment]
image
the plot thickens?

**Comment by GeneriedJenelle** [comment]
The PR was thick @Atermonera - after three lines of spicy code it was just too much.

**Comment by GeneriedJenelle** [comment]
Lemme see if deleting the cursed branch will allow it to be exorcised from this world.

**Comment by TheFurryFeline** [comment]
Might as well start it over at this point. Oof.

**Pull request closed without merging**
