### PR TITLE
unix2dos polaris.dme

### PR DESCRIPTION
**Pull request by GinjaNinja32**

### CODE REVIEW

**Comment by zaredman** [comment]
For us idiots -- What exactly is this, @GinjaNinja32 ?

**Comment by Spookerton** [comment]
It changes line endings in the project from \n to \r\n, because mixed line endings are bad, and convention in baycode and thus what, like, 90% of existing code is \r\n

**Comment by PsiOmegaDelta** [comment]
It's also the case that map merge tool outputs Windows newlines in both *nix and Windows systems, which can lead to fairly major diffs if someone commits maps with Unix line endings.

**Comment by GinjaNinja32** [comment]
it changes polaris.dme from \n to \r\n because DM/BYOND save \r\n and every time I go to commit it I have to dos2unix it to get git to accept that I barely changed it.

**Pull request merged**
