### PR TITLE
Fixes Power in VR Den PoI + minor adjustements

### PR DESCRIPTION
**Pull request by SubberTheFabulous**
Exactly what it says on the tin. The APC is now properly powering the zone and SMES is properly powering the APC.

Also made minor adjustements to the PoI itself, added a guard.

### CODE REVIEW

**Comment by Atermonera** [comment]
Any chance you can format it in TGM? Not a requirement for PoIs but certainly more readable.

**Comment by SubberTheFabulous** [comment]
I should be able to do that, but I genuinely do not remember how to, with submaps.

**Comment by Spookerton** [comment]
@SubberTheFabulous Open the map with strongdmm, make sure the output format is TGM in options, and re-save it.

<https://github.com/SpaiR/StrongDMM/releases/tag/v2.7.0.alpha>

or if 2.x crashes on you, the last 1.x:
<https://github.com/SpaiR/StrongDMM/releases/tag/v1.9.1>

**Comment by Spookerton** [comment]
Drafted. Needs format conversion.

**Review by Atermonera — APPROVED** [review]

**Pull request merged**
