### PR TITLE
Borgs can climb

### PR DESCRIPTION
**Pull request by Anewbe**
Mostly tables

### CODE REVIEW

**Comment by Arokha** [comment]
LAW #5 DOWN BOY, DON'T GET ON TABLES

**Comment by Anewbe** [comment]
YOU CAN'T STOP ME

**Comment by Mechoid** [comment]
Law 6: The floor is lava.

**Comment by Leshana** [comment]
Allowing some borgs to do it, but for dogborgs it should instead have another if that prints a "You aren't allowed on the table" message.

**Comment by Anewbe** [comment]
We don't have dogborgs as a separate thing.

**Comment by Atermonera** [comment]
"KERBEROS NO! BAD DOGS!"

**Comment by Arokha** [comment]
> We don't have dogborgs as a separate thing.

Wait do you have dogborgs at all? I was mostly joking but you saying 'separate thing' makes me wonder if you have them as altsprites for medical borg or something.

**Comment by Atermonera** [comment]
There's Tin Can and there's Kerberos, both of which are custom Borg sprites that're based on dogs in the code (Ian and Spice, respectively)

**Pull request merged**
