### PR TITLE
Can now apply handcuffs to oneself.

### PR DESCRIPTION
**Pull request by LorenLuke**
Fixes inability to handcuff yourself.

### CODE REVIEW

**Comment by Anewbe** [comment]
Breaks a bug that was fixed.

**Comment by LorenLuke** [comment]
@Anewbe What bug is that?

**Comment by Atermonera** [comment]
Looks like you're removing an adjacency check that prevents borgs from telecuffing dudes on the other side of the room

**Comment by LorenLuke** [comment]
@Atermonera Literally no idea how that happened.

@Anewbe Should be good now.

**Comment by Anewbe** [comment]
Did you test this?

**Comment by LorenLuke** [comment]
@Anewbe I did in the form first delivered. Given that the only thing is the addition of two lines in the code, and the desired outcome being achieved, I think it's safe to say it's good to go.

**Pull request merged**
