### PR TITLE
Adds portable freezers to med lockers

### PR DESCRIPTION
**Pull request by Mark9013100**
Adds portable freezers to the following medical lockers:
medical doctor's locker
paramedic locker
CMO's locker

### CODE REVIEW

**Comment by Yoshax** [comment]
Add them to cargo orderable if they aren't already?

**Comment by Mark9013100** [comment]
Every time I tried to, when I tested it, the cargo shuttle would come empty. Better safe than sorry.

**Comment by NortonDK** [comment]
What is a portable freezer and what use does it have?

**Comment by Zuhayr** [comment]
:+1:

**Comment by Mark9013100** [comment]
@NortonDK A portable freezer can be used to store organs and limbs on the go, without the fear of them rotting.

**Comment by sabiram** [comment]
Also known as a 'cooler'

**Comment by Mark9013100** [comment]
And also so you can store beer like the irresponsible sociopath you are.

**Pull request merged**
