### PR TITLE
Various Borg Changes

### PR DESCRIPTION
**Pull request by Anewbe**
Adds a number of tools to some of the borg modules
 * Security module gets pepper-spray and more taser shots
 * Crisis and Surgeon modules get a more useful selection of medicines, and a gripper that holds and preserves organs
 * Service module gets a rolling pin and kitchen knife
 * Clerical module gets stamps, and new emag items
 * Construction module gets a welder and floor tiles
 * Engineer module gets a floor painter
 * Research Module gets tools to repair FBPs and make mechs, the organ gripper from above, and a gripper specifically for holding mech parts

Thanks Mechoid for the gripper sprites

### CODE REVIEW

**Comment by Zuhayr** [comment]
The first gripper, for maint drones, was a hack. I really think it's a bad idea to constantly add more variants.

**Comment by Yoshax** [comment]
Honestly, you'd be be offer just axing the two engineering modules and turning them into one, better module.

**Comment by Kelenius** [comment]
>Honestly, you'd be be off just axing the two engineering modules and turning them into one, better module.

**Comment by Zuhayr** [comment]
Enjoy the return of Engineering being grossly overpowered and overequipped compared to every other module.

**Comment by Yoshax** [comment]
Do the same with medical. Borgs need some love.

**Comment by martin509** [comment]
What new chems do medborgs get?

**Comment by Neerti** [comment]
Travis might be upset at your comments lacking a , at the end.

**Comment by Neerti** [comment]
Bit hesitant about the research module getting even stronger, but we'll see how this goes, I suppose.

**Pull request merged**
