### PR TITLE
Prosthetics don't require research

### PR DESCRIPTION
**Pull request by Anewbe**
Having them tied to research made them unfortunately difficult to actually create.

### CODE REVIEW

**Comment by Yoshax** [comment]
Not removing it from the cell and eyes too, aren't those required?

**Comment by Anewbe** [comment]
I didn't think there was a req on them, I will correct that later, good catch.

**Comment by Searif** [comment]
Eyes are, cell is not

**Comment by Anewbe** [comment]
According to the code it's both.

**Pull request merged**
