### PR TITLE
Allows objects to be made uncatchable

### PR DESCRIPTION
**Pull request by Heroman3003**
Additional var and check in catching code.

Also fixes missiles fired being catchable what the hell.

### CODE REVIEW

**Comment by Neerti** [comment]
Not sure if this is a bit redundant with ``catch_chance = 0`` being possible, but this might be better at future-proofing, with regards to mobs being able to influence ``catch_chance`` in the hypothetical future.

**Comment by chaoko99** [comment]
Perhaps it would've been smarter to make the rocket launcher into a projectile weapon though.

**Comment by Heroman3003** [comment]
@Neerti catch_chance is not an item var, but car defined in this proc. The only thing on item that affects catching is 'sharp' var that reduces the catch chance by 50, but also has a lot of its own effects. I would have set catch_chance of item to 0, but items plain dont use that.

**Comment by Neerti** [comment]
@Heroman3003 I'm a dummy then.

**Pull request merged**
