### PR TITLE
Adds fingerless gloves.

### PR DESCRIPTION
**Pull request by Belsima**
Taken from Eros.

image
image

### CODE REVIEW

**Comment by Anewbe** [comment]
If we can find a way to make these leave fingerprints, that'd be cool.

**Comment by Anewbe** [comment]
Any thoughts on my last comment, or no?

**Comment by Belsima** [comment]
I'll look into it this week.

**Comment by Anewbe** [comment]
<3

**Comment by Belsima** [comment]
I am not a programmer and I found no code from any codebase regarding gloves that leave fingerprints, sorry.

**Pull request merged**
