### PR TITLE
Lowers Human Minimum Age To 16

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Exactly what it says on the tin.

### CODE REVIEW

**Comment by OhEmGee** [comment]
we really should have a public vote about this

**Comment by SpadesNeil** [comment]
Gotta ask. Why would a 16-year-old be on a highly dangerous orbital research station? Not exactly your mom-and-pop pizza parlor. I mean, IRL, there's laws against these kind of work conditions, but I know that we're in like the 26th century on the outer fringes of human inhabited space and NanoTrasen probably doesn't care but...

... I don't know, this seems like a very bad idea that only serves to allow 16-year-old players to have self-insert characters of an accurate age.

**Comment by Zuhayr** [comment]
>Why would a 16-year-old be on a highly dangerous orbital research station?
Polaris is set on a colony.

**Comment by SpadesNeil** [comment]
Sorry, I'm an idiot. Disregard my opinion.

**Comment by SpadesNeil** [comment]
Wait, I thought it was an asteroid. Therefore, in orbit. Or am I really that out of the loop? If so, disregard my opinion.

**Comment by ParadoxSpace** [comment]
yeah see i figured that 16 was the age where like
'hello congrats you can finally visit the work level'

**Comment by SpadesNeil** [comment]
>yeah see i figured that 16 was the age where like
>'hello congrats you can finally visit the work level

Hm, I suppose that makes sense. Very well.

**Comment by Verarch** [comment]
I'd be for it as long as there's restrictions on jobs for 16 year olds. I doesn't make sense for a 16yo to be a skilled medical doctor, or a security officer trusted with potentially lethal weaponry if they haven't even graduated school.

**Comment by SpadesNeil** [comment]
I'd agree, but I also take it to an extreme when I say 16-year-olds should be hard coded to be restricted to assistant only.

**Comment by EmperorJon** [comment]
I have word that this isn't going to be happening.

**Pull request closed without merging**
