### PR TITLE
Updates Southern Cross for recent PRs

### PR DESCRIPTION
**Pull request by mistyLuminescence**
Updates Southern Cross for recent PRs:

Updates blue plushie file path to the new one (4190 - Bugfix!)
Updates psychiatrist locker to the new one (4202)
Adds vials to CMO office (4209)
Adds .45 speedloaders to firing range (practice), armory (rubber), tactical armory (lethal) (4217)

Additionally, adds the new cloaks, as well as collectable 'Space Life'-brand action figures, to the Command staff dorms on the bridge level, adds a door to the Detective's office from the Security foyer (locked to Detective access), and moves the medical 'Best Doctor' plaque to in front of the CMO's office.

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
Door's there so detectives can do some cool noir stuff where they open the door, a client walks in, they tint the windows, and someone does this Hemingway-style monologue about legs and smoking and bullets. Can remove it if that's not a thing we want?

**Comment by Woodratt** [comment]
Eh, picture of the door to the detective's office? 

Also I'd recommend removing the cloaks and action figures.

**Comment by mistyLuminescence** [comment]
@Woodratt [Picture](https://image.prntscr.com/image/OrxQOc2yRMeXep4V_yBpSA.png), ft. the Detective talking to a client who really wants something investigated... and a passerby who really doesn't.

 Removing the cloaks/action figures when I get home.

**Comment by mistyLuminescence** [comment]
Updated, sorry about that - I forgot to push the changes to the PR. Safe to merge now.

**Pull request merged**
