### PR TITLE
teshari spase suit update

### PR DESCRIPTION
**Pull request by KBraid**
replaces placeholder teshari space suit and adds matching helmet

### CODE REVIEW

**Comment by Cerebulon** [comment]
Goofy ill-fitting sprites were kind of intentional to indicate that there isn't purpose-made stuff for Tesh. I'm planning on reverting the radiation suit change and implementing the 'tailored fit' suit as a specific custom-order alternative in the same way as the adaptive voidsuits are exclusive of tesh due to tesh's non-humanoid shape, and would prefer this were a separate item also.
Generic space suits especially so since they don't even usually have Taj/Unathi sprites afaik? They're on-size-fits-all in the uncomfortable way only one-size-fits-all products can ever achieve.

**Comment by KBraid** [comment]
alright, that's fair! If you do implament tesh spesific space suits plese feel free to use my sprites! also, another reason i made these was i noticed that when tesh wear the space suit helmet, they don't wear anything.

________________________________

**Comment by Atermonera** [comment]
@KBraid this still has merge conflicts, any plans on fixing those?

**Comment by KBraid** [comment]
i'll see if i can get some time to work on it, in the mean time i will close this pull.

**Pull request closed without merging**
