### PR TITLE
Makes janicarts hold more water

### PR DESCRIPTION
**Pull request by Cameron653**
So you don't have to run back to grab some more water every 20 seconds while cleaning up dirt.

### CODE REVIEW

**Comment by Anewbe** [comment]
Eh, maybe 250, or 300? 500 is half a water tank, seems a bit excessive.

**Comment by Cameron653** [comment]
Changed to 300

**Comment by Belsima** [comment]
What of the smaller one? Should it be increased too?

**Comment by Cameron653** [comment]
Smaller one? I don't play janitor, but I got a request to increase the janicart. If there's a smaller janicart then please link me to it and I'll also change it.

**Comment by Belsima** [comment]
https://github.com/Cameron653/Polaris/blob/7783afdd0672ec5679d2fc7e75b68f044f4efb9d/code/game/objects/structures/mop_bucket.dm

The mopbucket. Utterly useless as of now.

**Pull request merged**
