### PR TITLE
Adds Cash Registers, Retail Scanners and Prices

### PR DESCRIPTION
**Pull request by Hubblenaut**
# Economy Update
Image Image
- [x] Adds Retail Scanners.
- [x] Adds Cash Registers.
- [x] Cash tweaked to now always act like bundles.
- [x] Adds prices for a base selection of regularly traded items.
- [x] Mapping.

## Price Lists
These are all prices I have noted so far, roughly oriented on real life prices in US Dollar. List is open for discussion.

Beverages|Price
-------|-------
Soda, Beer and Similar | 2 þ
Hot Drinks; Coffee and Co | 3 þ
Cocktails | 4 þ
Liquors | 5 þ
Wines | 8 þ

Food|Price|Food|Price
-------|------|-------|------
Any Burger | 2 þ | Any Sandwich | 3 þ
Any Pie | 4 þ | Any Soup | 3 þ
Any Bread | 5 þ | Any Bread Slice | 1 þ
Any Cake | 5 þ | Any Cake Slice | 1 þ
Any Pizza | 5 þ | Any Pizza Slice | 1 þ
Any Cookie | 1 þ | Any Meal | 5 þ

### Retail Scanner
 - Hit it on or with items to add them for a purchase.
 - Hit it with an ID card or E-Wallet to see total price.
 - Hit it with the same ID/E-Wallet again to confirm and pay.
 - Clicking in hand will open an informative interface with
  - a log of all purchases made.
  - a button to set a custom order.
  - a button to unlock the device with command access.
  - a button to delete the log, if unlocked.
  - a button to change the receiving account, if unlocked.

### Cash Register
Features not included or different than the retail scanner in **bold**.
 - Hit it with items or **click and drag entities to it** to add items for a purchase.
 - Hit it with an ID card, E-Wallet **or cash** to see the total price.
 - Hit it with the same ID/E-Wallet/**Cash bundle** again to confirm and pay.
 - Clicking on it will open an informative interface with
  - a log of all purchases made.
  - a button to set a custom order.
  - a button to unlock the machine with command access.
  - a button to elete the log, if unlocked.
  - a button to change the receiving account, if unlocked.
  - **a button to unlock the cash box, if unlocked.**
 - **Alt-Clicking or using the verb open-cash-box will open/close the machine's cash box.**
 - **Examining the machine while the cash box is open will do a count of the cash.**
 - **Clicking the machine while the cash box is open and filled will remove the cash from it.**
 - **Clicking the machine while the cash box is open and empty will simply close it.**
 - **Clicking the machine while the cash box is open with cash in hand will sort it in.**
 - **Clicking the machine with a wrench will (un)secure it to(from) the floor. 20 tick delay.**

## Mapping
**Cash Registers**
 - Kitchen counter
 - Bar counter
 - Café
 - SpacePort Cafeteria
 - SpacePort Bar

**Retail Scanners**
 - 2x in bar backroom
 - 1x in kitchen locker
 - 1x in staff meeting room
 - 1x in cargo office
 - 1x in library

**All EFTPOS devices have been removed from maps.**

## Sprites
Image
Both the retail scanner and the cash register have sprites for all directions and an animation for a successful purchase.
Additionally, the retail scanner has a scanning animation and the cash register icons for an opened cash box, both filled and empty.
**All credits go to Bishop/Pawn.**

## Interface
Image

### CODE REVIEW

**Comment by sabiram** [comment]
I recommend making the currency sign something on a basic English keyboard instead of the thorn

**Comment by Hubblenaut** [comment]
Thorn can be typed on paper using the macro &thorn or Alt+0254. I don't use an English keyboard myself, but this is the currency sign preferred after several threads back on the bay-forums and I don't mind it myself.

Head of Staff input welcome.

**Comment by nachomeep** [comment]
Can't we just use $ for simplicity?

**Comment by Hubblenaut** [comment]
It's the dollar sign though, and I'm not sure if we want to establish our fictive money as dollar again. Besides, you can still write Thalers out, like players have been doing it. The currency sign is only used on the device interfaces.

**Comment by Spookerton** [comment]
thalers and thorns are something I personally hate, but staffly we've discussed it to death and I'm outnumbered.

**Comment by Lorwp** [comment]
looks good, will add that there's a Scanner in the Warden's office, before people panic.

**Comment by Datraen** [comment]
Map was updated, I was under the impression this was still being debated.
Will merge when the conflicts are resolved, sorry about that.

**Pull request merged**
