### PR TITLE
Corrects missing ..() in New()

### PR DESCRIPTION
**Pull request by Kelenius**

### CODE REVIEW

**Comment by Dragor** [comment]
Can someone explain what this actually does without lame memes?

**Comment by Kelenius** [comment]
``New()`` that doesn't call ``..()`` is a VERY BAD THING that could break the entire game.

**Comment by Zuhayr** [comment]
Shit PR title. Good change. For the sake of people with notifications can you make your PR titles informative or at least not fucking stupid please.

**Comment by Neerti** [comment]
In the future, please have

**Pull request merged**
