### PR TITLE
Replaces more macros.

### PR DESCRIPTION
**Pull request by Cameron653**
Same premise as https://github.com/PolarisSS13/Polaris/pull/3574

- Replaces \red \green \blue and \black with ```<font color='COLOR'>```
- Replaces \b (bold) with ```<B>``` and ```</B>```in a few places
- Replaces \italic with ```<i>``` and ```</i>``` in a single place (Really. This was a thing?)
- Puts a period at the end of a few sentences.
- Adds a few minor coder comments in places

Ready for merge after someone reviews this.

### CODE REVIEW

**Comment by Cameron653** [comment]
Alright, went ahead and fixed everything.

Please tell me if you find those last 4 macros, because they're not \red \blue \green \black \b or \i as far as I can see, and I have 0 idea what the hell ^mc is.

**Comment by Anewbe** [comment]
This ready to go?

**Comment by Cameron653** [comment]
As far as I can see, yes.

**Comment by Anewbe** [comment]
Tested?

**Pull request merged**
