### PR TITLE
Adds robotics labcoat.

### PR DESCRIPTION
**Pull request by nachomeep**
Also adjusts wardrobe to be consistent with the roundstart equipment, because they don't get scientists satchels or bags

Stolen from: https://github.com/ErosResearchPlatform/Eros/pull/5

http://i.imgur.com/tBMv6Hh.png

### CODE REVIEW

**Comment by nachomeep** [comment]
I knew I shouldn't have made a last-minute change without compiling.

**Comment by Anewbe** [comment]
I'm not sure this is an improvement, actually. The current roboticist setup looks good (in my opinion) because of the contrast between the white labcoat and the red and black of the actual uniform. This would just sort of turn the whole body into a black and red curtain.

**Comment by nachomeep** [comment]
Fair enough. I really don't like contrast, personally. I'll wait for another comment or two telling me its bad before shutting it down.

**Comment by nachomeep** [comment]
Labcoat is no longer mapped or in loadout.

**Pull request closed without merging**
