### PR TITLE
Adds giant crabs

### PR DESCRIPTION
**Pull request by Anewbe**
They're non-hostile until attacked, then they swarm and wreck face.

Long term I want to make a variant that follows people around and makes menacing sounds, but I don't feel like spending time in simple_animal.dm any time soon.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
What do the sprites look like? I bet they look crabulous

**Comment by Anewbe** [comment]
They're pretty crabulous, for something that was made by a person I was repeatedly screaming at them to make me crab sprites.

**Comment by SilverTalismen** [comment]
Any chance a screenshot can be given?

**Comment by Anewbe** [comment]
I have trouble with screenshots, unfortunately. If you have byond installed you should be able to open up animals.dmi from this PR and look for it in there.

**Comment by Magneld** [comment]
Do they have weak points.
(I'm sorry)

**Comment by Anewbe** [comment]
They do, it's called "Follow Code".

**Comment by Neerti** [comment]
Giant grab

**Comment by SilverTalismen** [comment]
Looks great, good job spriter!

**Pull request merged**
