### PR TITLE
Changes Space Helmet Cameras to a Verb

### PR DESCRIPTION
**Pull request by Nalarac**
You no longer enable the helmet camera when toggling helmet lights.

The verb is located in the <strike>IC</strike> **Object** tab.
The camera can be deactivated and reactivated with the verb after initial activation.
The user is set each time the camera is activated, so a new user can be scanned to the suit's camera.

Changes some lines to use to_chat

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
As a side note, I like this a LOT. Would make getting helmet lights turned on one click rather than the usual 2!

**Comment by Anewbe** [comment]
I agree on the Object thought.
Have you tested full that the camera shuts off properly?

**Comment by Nalarac** [comment]
Yes, the camera does shut off properly.

**Comment by TheFurryFeline** [comment]
> Yes, the camera does shut off properly.
> 
> Also, this is not a thing for hardsuits. This is for all space suit helmets that have a camera inside of them (it just happens that we only have cameras in the rigs).

Yeah, I rechecked the code and it's weird. Go figure.

**Pull request merged**
