### PR TITLE
Updates language syllables and text.

### PR DESCRIPTION
**Pull request by nachomeep**
It's self-explanatory. Updates the syllables for a few, and adds some flavor text.

### CODE REVIEW

**Comment by nachomeep** [comment]
May add syllables for Tradeband later. Can't figure out what the hell to do for it, though. Maybe esperanto?

**Comment by elgeonmb** [comment]
As imperial executor of lore and whatnot--

While more languages are neat, they are also messy, do not merge.

**Comment by nachomeep** [comment]
I didn't add any.

**Comment by nachomeep** [comment]
I've also lowered the name character limit to what it originally was prior to https://github.com/PolarisSS13/Polaris/pull/1528 because I've been told too-long names aren't okay.

**Comment by nachomeep** [comment]
I've tested a bunch of overly long names, and average length names with middle names. 26 was perfect for most of them. At worst people will need to drop middle names, and Dionae'll get screwed.

**Comment by Anewbe** [comment]
If you really think that's an issue, make it a separate PR.

**Comment by nachomeep** [comment]
Righto.

**Comment by Anewbe** [comment]
Why was this closed?

**Comment by nachomeep** [comment]
Unintentional. Oops.

**Comment by nachomeep** [comment]
Misclicked on my phone, I think.

**Pull request merged**
