### PR TITLE
Weak attacks no longer can damage windows

### PR DESCRIPTION
**Pull request by SpadesNeil**
Attacks with a force less than 5 for normal windows, or 10 for reinforced windows, no longer does any damage to the glass.

The exact number can change, just the goal of this is to stop (especially prisoners) from slapping a pane of glass with a pair of shoes until it shatters. Go ahead. Smack a pane of reinforced glass as many times as you want IRL with your sneaker. You're generally not going to damage it in the course of a day.

We already can't damage windows by punching them for obvious reasons. If your weapon does around the same or less damage than a punch, it shouldn't hurt the window either.

### CODE REVIEW

**Comment by Cyantime** [comment]
This only applies to thrown objects in it's current state, you want the attackby() section for normal weapon strikes.

**Comment by SpadesNeil** [comment]
I'll fix that shortly, then. I had a feeling I was missing something.

**Comment by SpadesNeil** [comment]
There we go.

**Comment by SilverTalismen** [comment]
This is great! Before it was a real pain in the glass to keep most prisoners.

**Comment by SpadesNeil** [comment]
>This is great! Before it was a real pain in the glass to keep most prisoners.

Go back to your hole and stay there until I get back. :T

**Comment by Neerti** [comment]
@Anewbe Does this still need more staff input?

**Comment by SpadesNeil** [comment]
Keep in mind, 5-10 was just a number I came up with. Change it to whatever seems reasonable. I just don't like prisoners being able to slap the shit out of windows with their shoes.

**Comment by SpadesNeil** [comment]
So what's the word on this?

**Comment by Woodratt** [comment]
There was comments about maybe allowing regular windows still be smashed but that was just talk. It seems to be fine with folks staff end. Sorry that this is taking so long.

**Comment by chaoko99** [comment]
for the record, a drunken Teshari can still smash a window by running into it. Kinda weird.

**Pull request merged**
