### PR TITLE
Fixes inconsistent hair highlight icons

### PR DESCRIPTION
**Pull request by Verkister**
The newer hairstyles can now be tinted darker than light grey. Also trimmed a couple duplicates.

### CODE REVIEW

**Review by Atermonera — APPROVED** [review]

**Comment by Atermonera** [comment]
@Verkister merge conflicts

**Comment by Verkister** [comment]
Should be good now.

**Review by Spookerton — CHANGES_REQUESTED** [review]
Aaaand again.

**Comment by Spookerton** [comment]
Just while I collect an IDB result

**Comment by Spookerton** [comment]
Ayep, I'm not fixing that

**Comment by Verkister** [comment]
These are dmi files they cannot be merged, just overwritten.

**Comment by Verkister** [comment]
Just gonna remake this

**Pull request closed without merging**
