### PR TITLE
Change Vent Pump/Scrubbers to Retro-like with actual fanblades

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Does what it says.

Sprites courtesy of CHOMPStation

### CODE REVIEW

**Comment by parasitoide** [comment]
imo these actually look worse, the pump especially seems to be a loss in detail for the sake of cooler animations

**Comment by Rykka-Stormheart** [comment]
> imo these actually look worse, the pump especially seems to be a loss in detail for the sake of cooler animations

Perhaps! But I figured porting it wouldn't hurt, and people can levy their opinions and such! <3

**Comment by Atermonera** [comment]
Scrubbers, the bright green when siphoning is important, as it draws visual attention to something that requires immediate attention by anyone in the room. Much harder to see with this darker red.
Also sort of an issue with the vents, where it's much harder to see whether it's blowing out or in, but less of an issue for them.

**Comment by Anewbe** [comment]
Images should be put in the first post where possible, please.

**Comment by chaoko99** [comment]
Personally, I don't like them. I was never a fan of these fans. They're from TG and all that (See: I don't think they're license compliant..?). They just don't fit in with the other sprites.

I don't really think "Chompers uses them" is a good metric for porting things. I've been seeing a lot of that.

**Comment by MisterLayne** [comment]
Should have before/after images in the original post.
Also, not a huge fan of the change in sprites.

**Comment by Neerti** [comment]
There's an icon diff thing now among where Travis reports.

**Comment by TheFurryFeline** [comment]
IconDiffBot's always been a thing but it frequently didn't work properly for a long time along with MapDiffBot

**Comment by Tename** [comment]
Gotta say I don't really like them. I have never really been under the impression that this server followed the whole retro design(Example: PDA sprites, Nifs, most of the medical equipment, and more.) and I don't really think they would fit with the current design.

**Comment by Atermonera** [comment]
It's only a few weeks old for us

**Comment by TheFurryFeline** [comment]
Fair nuff.

**Comment by Atermonera** [comment]
Because I apparently haven't properly asked this, but could you rename the new sprites to not-replace the old ones, because general consensus indicates that we don't want to switch over to their use entirely?
Sorry for taking so long to actually get back to this, school was stressful and busy.

**Comment by Rykka-Stormheart** [comment]
> Because I apparently haven't properly asked this, but could you rename the new sprites to not-replace the old ones, because general consensus indicates that we don't want to switch over to their use entirely?
> Sorry for taking so long to actually get back to this, school was stressful and busy.

I could do when I have time! <3

**Comment by TheFurryFeline** [comment]
Oh, I was gonna edit the files for Rykka, but turns out that it's a slightly different fork repo. No access to your fork for this repo.

**Comment by TheFurryFeline** [comment]
Ugh, that's not really... Working. Getting dmi conflicts just opening the PR on the branch.

**Comment by Rykka-Stormheart** [comment]
> Because I apparently haven't properly asked this, but could you rename the new sprites to not-replace the old ones, because general consensus indicates that we don't want to switch over to their use entirely?
> Sorry for taking so long to actually get back to this, school was stressful and busy.
> 
> (DNM so that I remember to check on this)

This has been done

**Pull request merged**
