### PR TITLE
Hacked borgs can no longer be locked down

### PR DESCRIPTION
**Pull request by Anewbe**
NOV 21ST EDIT: I changed how this works, the Scrambled Equipment Module should no longer prevent lockdown.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Finally, hopefully we will see a fix for hacked/Antag borg camera's too, unless its been fixed already.

**Comment by Anewbe** [comment]
Not yet, but sooner or later. I have that one guy who really likes borgs looking into it.

**Comment by Nalarac** [comment]
The emagged items var was originally intended to allow for the scrambled equipment module to give cyborgs the unique items without having any other effects.

**Comment by Anewbe** [comment]
Do they happen to have another var that tracks if they've been hacked or emagged, then?

**Comment by Mechoid** [comment]
That would be 'emag' or 'emagged'. But, then again, it's an upgrade requiring diamond and illegal tech to make.

**Comment by Anewbe** [comment]
Yeah, I don't particularly mind the Scrambled Module doing this.

**Pull request merged**
