### PR TITLE
Various map changes

### PR DESCRIPTION
**Pull request by Yoshax**
This PR presents several changes.

First change is such: https://i.gyazo.com/50aede130174c047492712bd791501f4.png
EVA has been expanded in either direction. One of each of the Hazmat and Biohazard voidsuits have been mapped into the Engineering and Medical spots. These are special suits, with modified numbers.

The Hazmat has:
list("melee" = 30, "bullet" = 5, "laser" = 20, "energy" = 5, "bomb" = 50, "bio" = 100, "rad" = 100)
It has lower normal armor in exchange for being completely radiation proof and higher bomb protection. The idea behind these numbers is that the radiation protection and bomb protection allow it to work in more dangerous areas, such as areas struck by radioactive meteors.

The Biohazard has:
list("melee" = 45, "bullet" = 5, "laser" = 10, "energy" = 5, "bomb" = 15, "bio" = 100, "rad" = 75)
It has lower laser and bomb armor in exchange for slightly higher melee damage and increased radiation protection. The idea behind the higher melee is that it may be used for dealing, or have been used for dealing with rowdy patients in virus-ridden areas.

Security have been given a third normal suit due to there being a lack of fancy suits to provide them. Some items have been added into maintenance below to compensate the walls changing.

Second change is fairly minor and is this: https://i.gyazo.com/7bef1e72e240b1ab766d356ab0cf647f.png
The rock has been cleared from the middle, as it looked kinda odd. That's really all.

Before the last change is presented, I would like to note some small several changes have been made in maintenance, a few small more crates, and in addition mesons have been added to the unused hallway in maintenance at the top right of the map. In addition, the cable from the APC has been led up into the unused tunnel.

The last change, and likely the biggest, and most controversial is this: https://i.gyazo.com/d578ecc51ac399b6133bbc040a449ebe.png
The captain's armor has been unmapped. In its place, there is a photocopier and a few small other changes in the captain's office. They now get a fancy three-color ink pen in their backroom, along with some more paper. I understand this will likely be controversial, but I feel the armor is long unnecessary and is in need of removal.

Thank you for reading this and taking the time to consider my PR.

### CODE REVIEW

**Comment by redstryker** [comment]
👍

**Comment by SpadesNeil** [comment]
I would swear the Captain's armor was already stored in the locker.

If it's not, how about we at least move it over to the Vault? Or just stick it in the locker.

**Comment by Neerti** [comment]
I was under the impression that [the new suits added were cosmetic sprites that the suit cycling machine](https://github.com/PolarisSS13/Polaris/pull/2434)[ could make and not be suits in their own right.](https://github.com/PolarisSS13/Polaris/pull/2445)

Not too sure how I feel about a third sec suit as well.

Cappy's space armor being removed I'm actually okay with, but in the picture provided it appears you also removed the antique laser gun, which you failed to mention in the text, and I'd rather not have that removed, since it's a pretty nice weapon for antags or really desperate command to use.

**Comment by Yoshax** [comment]
They are normally just recolors, but I have added these two in to give those ones just a little more flavor. It was add a third sec suit or leave the space, which looked really awkward.

And yes, I did remove the antique laser gun, and yes, my mistake not mentioning it, I had wrote quite a lot and over-looked it. I removed it because there's no reason for the captain to have it, and it's horribly out of place. If you so wish for there to be a gun, then it should be replaced with something sensible.

**Comment by redstryker** [comment]
If it means anything, I, as the creator of the RadSuits and BioSuits, approve of the 'flavor' that Yosh gave them.  Also, I do plan to have Sec variations of voidsuits, so *shrug*?

**Comment by SpadesNeil** [comment]
What's not sensible about a Captain owning an antique laser gun? :-1:

**Comment by redstryker** [comment]
https://media.giphy.com/media/11JbaLzOXsg6Fq/giphy.gif

**Comment by nachomeep** [comment]
I'm all for captain's suit removal, and supportive of the EVA changes, but I still don't see why the laser gun was removed. It was nice in really _fucked_ situations.

**Comment by Anewbe** [comment]
I like the changes in the Captain's Office proper (armor could be renamed and moved to the vault, or something, to give another target in there), but the rest I'm not a fan of.

**Comment by Yoshax** [comment]
I fail to see why you are all against the removal of the armor. It is an old relic from past times where the expectations and job of the captain was vastly different. There is no need for the armor to exist any longer, the captain is provided with a vest and helmet in their closet, which is more than sufficient. The captain should not be in situations that warrant a bizarre full-suit of armor. If they do, then can acquire it through normal channels like everyone else. It being in the vault makes no more sense than it being in the captain's office. Why would you have random armor in the vault? The laser follows this same course. The captain is already provided with a firearm and does not need a special one that is out of place, especially not one that is so strange. It is meant to be an antique yet it recharges itself, which is something saved for prototype science weapons, and is not fitting on an antique. Both items encourage the job to played in a way that is neither positive or wanted in the environment we have.

The EVA changes are positive and present some added flavor to the suits Redstyrker has made, they are not massive nor largely impacting. The third security suit can be removed if it is such a bother, but I do not believe it will be largely impacting. As for the other changes within EVA, I insist upon them to present more flavor than just recolors to the suits, and to put their sprites to use.

I urge you all to reconsider your opinions and see that these changes are beneficial to the atmosphere and environment of the server.

**Comment by SpadesNeil** [comment]
I am fine with the removal of the armor, but I am adamantly against removal of the laser pistol. It's a trophy piece that is symbolic to the role of station commander and it is iconic in Space Station 13 its self.

I don't care if the pistol doesn't even function. I don't want to see the display case removed.

**Comment by Yoshax** [comment]
Just because something is iconic does not mean we should move away from it. Shitting on the floor was also iconic to the game, as are/were clowns/mimes, and all suchlike. Yet we have moved away from those, and their respective tropes because they are not suited in the environment we want to push. Something being iconic is no reason to not consider changing or removing it. Why should we be stuck in the old stereotypes, beliefs, and tropes?

**Comment by Screemonster** [comment]
Wasn't the antique laser thing supposed to be something along the lines of that one episode of firefly with the antique collector who's got a priceless antique raygun in an alarmed glass case, and the crew sneak in disguised as trash collectors to steal it?

**Comment by SpadesNeil** [comment]
There's iconic, and there's obnoxious. You removed previously obnoxious features. Big difference there.

I still want to see the antique laser stay and so do other people. I would, however, be completely in support of removing its auto recharge feature.

**Comment by Yoshax** [comment]
The issues remains then of the captain having an additional, unnecessary weapon that is not suited to the job. This is not a ship that darts through space, committing exciting adventures. It's a boring colony. The captain is not some high holy figure that deserves overly special attention or treatment.

**Comment by Hubblenaut** [comment]
I'd like to chime in for the fairly large nonvocal party that doesn't care much one or the other if the antique laser gun is going to be removed or not.

**Comment by SpadesNeil** [comment]
Removal of the laser will also break antag objectives so if you're going to disregard the controversy and ignore opinions, at least fix that before merging this.

**Pull request closed without merging**
