### PR TITLE
Drone brains work like posibrains

### PR DESCRIPTION
**Pull request by Anewbe**
#2141

### CODE REVIEW

**Comment by Yoshax** [comment]
Seems kinda messy to just duplicate all of the code again.

**Comment by Neerti** [comment]
Might be best to base the 'shove a ghost inside this' code on the /mmi/digital/ part, of which I believe posibrains and circuitbrains both inherit from.

**Comment by Yoshax** [comment]
You could port Bay's Ghost Traps which basically do this 1000% better.

**Comment by Anewbe** [comment]
Porting is hard/scary, was going to do what Neerti said.

**Pull request closed without merging**
