### PR TITLE
Adds Actor's Guild

### PR DESCRIPTION
**Pull request by Kearel**
The Actor's Guild is an alternate spawn point/job for players who wish
to put on entertainment without affecting the round by taking up a job
slot or getting in the way of others.

Basically how it works is the actor's spawn using the antagonist system (much like ERT does). They come equipped with their own radio channel that is broadcasted on intercoms near each entertainment monitor. The Actor's Guild was placed on CentComm and comes equipped with various props and a movable camera.

### CODE REVIEW

**Comment by Minijar** [comment]
This will seem fun but what's to stop the entire crew being part of this? A lot of people will want to join it.

**Comment by PsiOmegaDelta** [comment]
In this particular PR there is a hardcap of 10 people in the guild. This number can be adjusted if you're concerned.

**Comment by Kearel** [comment]
Alright I'm still getting map conflicts. No idea why.

**Comment by Kearel** [comment]
I'm gonna close this. I can't figure how how to fix this conflict. I might attempt this PR again in the future.

**Pull request closed without merging**
