### PR TITLE
Fixes Taj/Unathi being unable to eat mice.

### PR DESCRIPTION
**Pull request by Anewbe**
Taj/Unathi will now be able to eat mice and lizards again.

Adds two mob_helper checks for mob size, istiny and ismini.

EDIT: Teshari can also eat mice and lizards again/now.

### CODE REVIEW

**Comment by Nerezza** [comment]
What about Teshari?

**Comment by Anewbe** [comment]
They're not edible, but yes, they can eat mice and lizards too. Editing title.

**Comment by Yoshax** [comment]
If all these species can eat mice, why can't humans?

**Comment by PJB3005** [comment]
Because humans have some level of dignity `:^)`

**Comment by Nerezza** [comment]
I'd imagine it's because humans aren't so beastly as the beast races so they can't eat them raw. They can still take a kitchen knife to the mice, butcher them, cook that, and eat that if they want... Actually they could eat the butchered meat too I guess?

Honestly, I didn't know Tajaran and Unathi could eat mice also. I only knew Teshari could since they're pretty much the beastiest of beasties on the station, literally speaking of course.

**Comment by sabiram** [comment]
A human is fully capable of eating a mouse whole

**Comment by Zuhayr** [comment]
It was added for gameplay variance.

**Pull request merged**
