### PR TITLE
Port of Bay's Port of Apollo's Port of tgstation's Cooking System

### PR DESCRIPTION
**Pull request by Datraen**
Baystation12/Baystation12#13466 + some fixes, compatibility with our snack code.

Also I can't spell compatibility sometimes, neat.

figqahc 1

### CODE REVIEW

**Comment by Datraen** [comment]
As far as how far the rabbit hole goes as far as porting is concerned, I can't tell. It was directly committed to Apollo's code base with no hint of where it came from.

**Comment by Raptor1628** [comment]
They're ported from /tg/ with some mods Apollo made, mostly for sanity iirc.

**Comment by ursamedium** [comment]
No more magic microwaves for everything make me far more excited than I should be.

**Comment by Yoshax** [comment]
So, @Datraen, how does this change cooking as is?

**Comment by Datraen** [comment]
This doesn't change existing cooking, it adds more ways to cook on top of it.

Microwaves are still magical, but you can cook different foods using any ingredients in the specific machinery on the specific setting.
For example:
A box of deep fried vanilla ice cream flavored cereal.
Reishi personal pizzas
Cherry Jelly food.
Berry flavored chocolate bars

**Comment by Datraen** [comment]
Also expecting conflicts with #1995, due to changes brought by that.

**Pull request merged**
