### PR TITLE
Adjusts HoS' locker capacity & moves CE's office camera

### LINKED ISSUE #1355: HoS' locker is overstocked
#### Brief description of the issue
HoS' locker is overstocked
#### What you expected to happen
When I open and close it, all items would fit
#### What actually happened
Some were left outside
#### Steps to reproduce
Duh
#### Additional info:
 - **Server Revision**: 4eff2f8d10eb9fa747b45b68d4183e3041ae44c2

### LINKED ISSUE #1356: AI can't access supermatter ejection button due to new camera placement
#### Brief description of the issue
Since the CE's office camera was moved to make room for an extra door, it no longer has line of sight to the alcove containing the button for ejecting the supermatter. This prevents the AI from ejecting the supermatter if necessary.

#### What you expected to happen
To be able to see and access the button like usual as an AI

#### What actually happened
Unable to see the button and thus access it as an AI

#### Steps to reproduce
Be an AI, look at the CE's office.

### PR DESCRIPTION
**Pull request by Yoshax**
Fixes #1356 
Fixes #1355

### CODE REVIEW

**Comment by Hubblenaut** [comment]
Adjusting a single locker's capacity is a very snowflakey fix there...

**Comment by Yoshax** [comment]
I could adjust the capacity of the locker's definition instead, I guess.

**Comment by Hubblenaut** [comment]
Eh, that'd still be giving a single locker a snowflake capacity.
It might be better to just equally increase capacity of all - or to separate HoS' gear into two.

**Comment by Yoshax** [comment]
Changing the capacity of every locker isn't a small change and trying to cram another locker into the already cramped office isn't going to happen.

**Comment by Hubblenaut** [comment]
Why does this issue exist in the first place? We should already be having lockers adjusting their capacity to what is needed on spawn as a band-aid fix. I think that should be looked into.

**Comment by Yoshax** [comment]
Feel free.

**Pull request merged**
