### PR TITLE
EAL given to Cyborgs, AI and pAI.

### PR DESCRIPTION
**Pull request by Datraen**
Does what the title describes.
This time with more pAI understanding EAL and no accidental DME changes.

### CODE REVIEW

**Comment by Neerti** [comment]
What's going on with the changelog change?

**Comment by Datraen** [comment]
Just updating the changelog? Shouldn't do much of anything else, since it should delete after being read?

**Comment by Zuhayr** [comment]
You should be making a new .yml per change.

**Comment by Datraen** [comment]
Alright, good to know.

**Comment by Neerti** [comment]
:+1: with Travis.

**Pull request merged**
