### PR TITLE
Makes secret not bad

### PR DESCRIPTION
**Pull request by Yoshax**
#haitusbreaker

### CODE REVIEW

**Comment by Hubblenaut** [comment]
GLORY FOR YOSHAX

**Comment by SparklySheep** [comment]
This is a long overdue change. :+1:

**Comment by Yoshax** [comment]
If this isn't wanted, then I propose my counter-proposal which is removing extended from secret. Having both changes together would be best, imo. Right now, any round before like 8pm GMT ends up being voted secrets which ends up being extended 75% of the time, or is a dice roll between extended and auto-traitor. If there was a chance to get something a tad more exciting than a coin flip for extended, people might ready more.

People don't vote secret to play extended. A lot of votes end in secret because extended has a chance of win and everyone voting for other modes than dogpiles together to have secret win.

**Comment by EmperorJon** [comment]
For the ones which require one player, does that include the antag? I can't remember.

**Comment by Yoshax** [comment]
I am not sure. I believe it's without.

**Comment by EmperorJon** [comment]
What I don't want to see is 1 person ninja, wiz etc. where the only person joining becomes the antag. Not only is that entirely pointless but it also means if 1 person votes secret and joins they have 100% chance of being forced to be the antag when that happens.

**Comment by Yoshax** [comment]
Then it's simple. We remove extended from secret, and the ninja requirements etc stay as they are.

**Comment by Chnkr** [comment]
:+1: x :100:

**Comment by PsiOmegaDelta** [comment]
Alternative suggestion at this point: Remove the required_players_secret var.

**Pull request merged**
