### PR TITLE
Fixes booze bible

### PR DESCRIPTION
**Pull request by SpadesNeil**
It didn't spawn with usable money. That's fixed now.

### CODE REVIEW

**Comment by Anewbe** [comment]
If I'm reading this right, it makes every bible spawn with 300 spacemoney. Is there a way to have that randomized?

**Comment by SpadesNeil** [comment]
Probably. I'd make it so the base spacecash define did this, but I'm not sure how without breaking the other stuff. This is just a fix for the time being.

**Comment by Anewbe** [comment]
Do you mind if I take a crack at it, then?

**Comment by SpadesNeil** [comment]
Go for it. If you got a better version of this, I can always close this.

**Comment by Anewbe** [comment]
Alright, if I do manage to make a thing, I'll link it here.

**Comment by SpadesNeil** [comment]
Sounds good!

**Comment by Anewbe** [comment]
Got nothing right now, gonna merge this.

**Pull request merged**
