### PR TITLE
Added new panel for loadout.

### PR DESCRIPTION
**Pull request by Zuhayr**
Loadout now has its own panel.

image

Also cleaned up a ton of the existing definitions to inherit a cost and category properly.

### CODE REVIEW

**Comment by Zuhayr** [comment]
DNM again while I try Neerti's suggestion.

**Comment by comma** [comment]
This is badly needed for the pile of swag polaris has :V

**Comment by EmperorJon** [comment]
Excellent.

**Comment by Lorwp** [comment]
:horse:

**Pull request merged**
