### PR TITLE
armband go onto outer suit

### PR DESCRIPTION
**Pull request by Yoshax**

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Maybe make it do as belts do and add a toggle to switch layers?

**Comment by Yoshax** [comment]
verb bloat is bad

**Comment by SilverTalismen** [comment]
True, but it could simply bea right click option and not a object option?

**Comment by Yoshax** [comment]
It's the same and unnecessary, this does the job without having to be messy

**Comment by SilverTalismen** [comment]
True, it was mostly a thought ^^

**Pull request merged**
