### PR TITLE
Adds sprites to internals boxes.

### PR DESCRIPTION
**Pull request by Belsima**
Ported from https://github.com/vgstation-coders/vgstation13/pull/13117.

### CODE REVIEW

**Comment by Anewbe** [comment]
The sprites aren't super clear on what they're supposed to be, in my opinion.

**Comment by Belsima** [comment]
It says O2 in red letters.

**Comment by Belsima** [comment]
Not red. Shit. I mean white.

**Comment by Belsima** [comment]
What would you rather it be @anewbe?

**Comment by Anewbe** [comment]
I'm just not sure that the sprite needs to be changed, in general.

**Comment by Belsima** [comment]
You can close this if you don't want it, in that case.

**Pull request closed without merging**
