### PR TITLE
Reverts chemistry and nanoui back to processes due to slowness

### PR DESCRIPTION
**Pull request by Heroman3003**
The conversion to subsystems was with a good heart, but the extreme slowdown in workings of reactions and nanoui updates makes it feel plain bad. In addition to that nanoui not initializing if you are around too early is also extreme annoyance. In general, this conversion just made both systems ultra-slow. Revert keeps other subsystem conversions and any refactors/code cleanups done along the way, only reversing it for nanoui and chemistry subsystems.

### CODE REVIEW

**Comment by Wickedtemp** [comment]
Chemistry is a job that you can spend an hour on even with zero lag. 

If it were any longer, even *I'd* have a hard time having fun with it.

**Comment by Neerti** [comment]
@kevinz000 says they're looking into the issues from those things being made into substations, and I'd rather that they/someone else fix the subsystems instead of going back to processes, since it gets in the way of the eventual future goal of removing processes in favor of pure subsystems.

So hopefully kevins delivers.

**Comment by Heroman3003** [comment]
I agree with that, but until that fix is up and tested, I am just leaving this PR to hang, just in case.

**Comment by Wickedtemp** [comment]
Is there any issue with merging this as a temporary solution until kevinz is done with the actual fix?

**Comment by Wickedtemp** [comment]
Update. I actually played a bit. Holy *fuck* it's bad. This needs to get fixed ASAP.

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=1Isjgc0oX0s

**Comment by Atermonera** [comment]
#6151 is merged

**Pull request closed without merging**
