### PR TITLE
Makeover Kit

### PR DESCRIPTION
**Pull request by mistyLuminescence**
Adds the makeover kit to the traitor uplink (5 TC) and infiltrator null crate bundle. It's a tiny box with a mirror and some contact lenses inside, for styling your hair and changing your eye color. Pretty good for disguises too, if you can duck into a side room and give yourself a magenta floor-length braid and bright red eyes before Security catches you.

Does *not* change fur or scales color for nonhuman races- it's just the hair and eyes.

### CODE REVIEW

**Comment by Wickedtemp** [comment]
Considering you can basically already do this in any mirror, go for it

**Comment by Atermonera** [comment]
Per the May 26th staff meeting, we are not interested in this object as something generally available to crew, especially for only 1 loadout point. We would accept it as an antag-only item for 5 TCs.
Reasons include, but may not be limited to:

- 1 point is distinctly low, for something leaning toward antagonists with sufficient mechanics to replace a common in-game structure.
- Allows someone to change their distinct outward appearance (minus skin-color) at any location for free.
- Mirrors' uses have, generally, no urgency. Radiation, Clone-hair, Choosing the wrong hair at loadout, changing hair for an event, and Traitor gimmicks were brought up.
- Would again, be an -amazing- cheap antag tool.
- (Organic) eye color is likely a security restriction.

**Comment by mistyLuminescence** [comment]
:+1: PR updated, now available for 5 TC (and in the infiltrator bundle in null crates- the one with the chameleon kit and agent ID).

**Comment by DasIrrlicht** [comment]
By the way, can one add it next to the holokit in the illegal ressearch printable by R&D?

**Comment by Atermonera** [comment]
Would require further discussion.

**Pull request merged**
