### PR TITLE
Overhauls bot AI

### PR DESCRIPTION
**Pull request by Kelenius**
Instead of every bot defining its own AI, it's now defined at the base level and broken into individual functions.
Bot movement speed is now a variable.
Everything related to patrols has been removed. I will return to this later. It's currently broken anyway.
Signals and signal listeners sent to the hell where they belong.

Fixes:
Floorbots will now cover asteroid tiles.
Farmbots will now correctly navigate to the trays.

### CODE REVIEW

**Comment by Kelenius** [comment]
Ping.

**Comment by Kelenius** [comment]
Ping.

**Comment by Kelenius** [comment]
Ping...

**Comment by Zuhayr** [comment]
>Disconnected by peer.

**Pull request merged**
