### PR TITLE
Corrects pipe examine info.

### PR DESCRIPTION
**Pull request by Cyantime**
I noticed this and was unreasonably bothered by it.

### CODE REVIEW

**Comment by Anewbe** [comment]
Is that how it actually works? I thought the 300 kPa was a hard limit.

**Comment by Cyantime** [comment]
If you make a pressure chamber over a highly pressurized pipe, you can unwrench it fine.

**Comment by Anewbe** [comment]
Nice.

**Comment by Neerti** [comment]
If I recall correctly, the limit is the current atmosphere pressure + 2 atmospheres but I could be wrong.

**Pull request merged**
