### PR TITLE
Wallet Expansion!

### PR DESCRIPTION
**Pull request by mistyLuminescence**
Expands wallets to be able to hold a wider variety of tiny objects.

- ID cards
- Cigarettes
- Pens
- Tape recorder tapes [x]
- PDA cartridges [x]
- Radio encryption keys [x]
- Vials [x]
- Seeds
- Bruise packs and ointments
- Coins
- Dice
- Disks
- Implanters
- Lighters
- Matches
- Fingerprint cards [x]
- Straws and cocktail sticks [x]
- Haircombs [x]
- Playing cards [x]
- Keys [x]
- Lipsticks [x]
- Sheets of paper
- Pens
- Photos
- Droppers
- Swab/fingerprint results [x]
- Screwdrivers
- Stamps
- Permits
- Badges [x]

([x] = new)
Changelog is included.

### CODE REVIEW

**Comment by Atermonera** [comment]
_Looks at wallet_
Those are very short/small
- scalpels
- syringes
- Rolls of duct tape (Those things are bigger than my wallet by a noticeable degree)
- Rolls of tape in general (I have 2 roll of tapes in front of me and they're both too large to fit in my wallet)
- Straws
- GPSs (Figure they're size on the order of cellphones or old portable gaming devices like the Gameboy. Batteries, screen, etc, tend to be large for devices that need to stay on for a while and output human-readable text)
- _Possibly_ hailers (I don't have a very good mental image of how big they are admittedly)

Those're my $0.02

**Comment by elgeonmb** [comment]
I'd also question if rounded things made of breakable materials could like...... actually fit in a wallet...

**Comment by Woodratt** [comment]
My take on it.

Camera Bug - No, balance reason
GPS – No, balance and size reason
Tape recorder tapes – On the large side, but I guess on could get one or two into their wallet
Security hailer – No, size reason
PDA Cartridges – Seems fine
Radio encryption key – Seems fine
Vials – Why? Sliding towards no. 
Pills – No, balance reason
Syringes – No, balance and size reason
Duct-tape – No, size reason
Swab kits and fingerprint cards – Swab kits I’m leading towards no, cards are fine
Straws and cocktail sticks – Seems fine
Haircombs – Seems fine
Playing cards – Seems fine
Keys – Seems fine
Lipsticks – Seems fine
Swab/fingerprint results – Are these a paper? If so, is fine
Scalpels – No, balance and size reason
Rolls of tape – No, size reason
Bosun whistle – No, Size reason
Badges – Seems fine.

**Comment by mistyLuminescence** [comment]
RE size reason: these are all tiny items, if they're actually small instead we should probably represent that in the code. Will go over the list soon and edit.

**Comment by Arokha** [comment]
Some of those being ITEMSIZE_TINY seems a little absurd, so I'd agree with that they should be made ITEMSIZE_SMALL if DUCT TAPE is seriously marked as tiny.

**Comment by mistyLuminescence** [comment]
I'd be down for it, but probably out of scope for this PR. A tiny item is, apparently, anything from a pill to a roll of duct-tape, while a small item is anything from a pair of glasses to a pistol. Consistency is hard.

**Comment by Anewbe** [comment]
So the first thing that a few of us noticed immediately is that this is a blatant Medical buff, but isn't at all advertised as one. Instead, you've taken the buffs, added just enough window dressing to claim it's a general buff, and presented it in the least transparent way possible.
If this were made by damn near anyone else I'd be able to put it off to incompetence, but you've proven by now that you can't be trusted _not_ to try to sneak things past us. Don't try it again.

**Comment by mistyLuminescence** [comment]
You know that scene on The Office where Jim looks into the camera? That's me right now. If you have feedback for the proposed changes, I'm happy to hear them, but that wasn't feedback at all. If we're talking about people not being transparent with their PRs, that's definitely an issue, but not one present here - *every* proposed change was listed in the opening post, and every suggestion was followed through with. 

I'm not saying you should judge a PR on its own merit instead of on perceived hostilities and an acute sense of paranoia, but that's exactly what I'm saying. This PR was specifically requested by a Security player who wanted to be able to store their badge in their wallet like an IRL cop. If you have any genuine issues with the PR, I'm more than happy to hear them and amend the proposal.

Next question?

**Comment by Mechoid** [comment]
This PR has been re-opened after a _heated_ discussion in the Discord, regarding changes to it in and of itself. Specific contention seemed to be vials remaining.

**Comment by Mechoid** [comment]
Flagged as Staff Input for review on April 1st based on the content of the PR as of writing this comment and future modifications, rather than any discussion held in this github thread prior to my re-opening of it.

**Pull request merged**
