### PR TITLE
Add cooldown to pen clicks

### PR DESCRIPTION
**Pull request by Arokha**
Fixes https://github.com/VOREStation/VOREStation/issues/7000

### CODE REVIEW

**Comment by Atermonera** [comment]
travis

**Comment by Arokha** [comment]
Uses code from the move/click refactor PR

**Comment by Arokha** [comment]
Can you re-blep travis now that the other PR is done?

**Comment by Arokha** [comment]
You can restart travis on this now and it should compile fine now that move/click code is in.

Also you can call it bikeshed but it brings the server to it's knees if someone AHK's it, because there's no cooldown at all.

**Comment by Atermonera** [comment]
It's bikeshed because I recognize it as a fix that's necessary, but one which will enrage a fair few people that treasure the ability to spamclick pens without doing it to the point it kills the server.

**Pull request merged**
