### PR TITLE
Armor can hold helmets in suit storage

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Due to the way the armor system works, this is not a good idea.

**Comment by SpadesNeil** [comment]
Wait, do you get armor from clothing equipped in that slot?

**Comment by Anewbe** [comment]
Shouldn't, no. Pretty sure the suit storage slot is basically just a pocket.

**Comment by SpadesNeil** [comment]
Only reason I ask is because I've noticed other stat effects like slowdown being applied when an item is held in open hand for example. I vaguely recall a similar effect when I var-edited an item to fit in a pocket but this was _way_ back when I was still using Bay code.

**Comment by Anewbe** [comment]
Worse comes to worst we fix it.

**Pull request merged**
