### PR TITLE
Readds access restrictions to supply computer

### PR DESCRIPTION
**Pull request by Atermonera**
Because apparently we're not allowed to have nice things

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
Isn't that what the access-locked door to the cargo office is for?

**Comment by Atermonera** [comment]
Since I removed the access lock, I've heard repeated complaints about people breaking in to use it, making cargo irrelevant.

**Comment by FenodyreeAv** [comment]
*Making use of cargo during lowpop rounds when there is no cargo, HoP, or Captain.

**Comment by Naidh** [comment]
Short of Engineering doing their thing when there isn't actually Cargo or someone capable of fulfilling that post present (e.g. Site Manager, Head of Personnel, anyone with native Cargo access, synthetics), I haven't really seen any break-ins necessitating this from my side of things.

**Pull request merged**
