### PR TITLE
Updates most of the device sprites.

### PR DESCRIPTION
**Pull request by nachomeep**
http://i.imgur.com/91IqbVH.png

Stolen entirely from https://github.com/Endless-Horizon/CEV-Eris

### CODE REVIEW

**Comment by nachomeep** [comment]
I lied about commiting less, apparently.

**Comment by Anewbe** [comment]
Will need to pass this around to the staff.

**Comment by Arokha** [comment]
Looks neat!

**Comment by Screemonster** [comment]
I like some of them, not so keen on others, and would _really_ prefer if the existing sprites were left in the .dmi rather than outright deleted. Just rename them to (sprite)_old or something.

**Comment by nachomeep** [comment]
I'm waiting for feedback of which to keep the old ones for. I, personally, don't like keeping old sprites- bloat that isn't needed. I won't be doing that unless a dev tells me to.

**Comment by Anewbe** [comment]
Some of these sprites are nice, but we would like to keep the old sprites in use, at least for now. However, if you can rework this PR to instead just add the new sprites for later use, we may have use for them in some capacity further down the road.

**Comment by nachomeep** [comment]
Righto. I'll go ahead and do that [later im busy now].

**Comment by nachomeep** [comment]
I love these sprites, but some people have been complaining about taking Eris sprites. I'm just gonna close it to avoid their wrath, considering they'd probably end up in limbo like half of suits.dmI anyway.

**Comment by Arokha** [comment]
Aww. I liked a lot of 'em.

**Pull request closed without merging**
