### PR TITLE
Converts colorable species into the combo blend mode.

### PR DESCRIPTION
**Pull request by Verkister**
-Unathi, Tajaran, Skrell, and Teshari now use mult+add combo blending.
-As do their tails, tail anims, and extra tesh feathers.
-No issues detected on latest test runs.
kuva
(before/after)
Taj/una/tesh below tweaked after first preview.
kuva
kuva
kuva

### CODE REVIEW

**Comment by Belsima** [comment]
Comparison?

**Comment by Verkister** [comment]
comparison preview thingy added

**Comment by Vek-Tsarya** [comment]
I feel like it's a downgrade for Teshari, but the rest are clear improvements.

**Comment by Belsima** [comment]
I don't like the look for Teshari on this, honestly. Or Tajara.

**Comment by Verkister** [comment]
Yeah Taj definitely needs some tweaking. Tesh and una could be tweaked brighter too, but that's the only fault I'm noticing.

**Comment by Neerti** [comment]
I like the new blending, personally.

**Comment by elgeonmb** [comment]
Prometheans are also colorable

**Comment by Belsima** [comment]
I like it fine, now.

**Comment by Belsima** [comment]
I wonder; what's currently used for colorable loadout items? Just curious if this could be applied there as well.

**Comment by Neerti** [comment]
Presumably it uses the default method which IIRC is the additive blend.

**Comment by Verkister** [comment]
Seems they use the default color var defined as multiply at icons.dm line 780

**Comment by Verkister** [comment]
Done figuring out the item coloring stuffs for one test item. Ready to follow up with the rest some time soon.
kuva
kuva

**Comment by Belsima** [comment]
you're a wondrous person

**Pull request merged**
