### PR TITLE
Adds Directional Shields

### PR DESCRIPTION
**Pull request by Neerti**
Implements shields which block projectiles from outside, but allow projectiles to leave from inside.
Also adds a projector item which makes these, in two variants, rectangle and line.  It was made an item so that down the road making stationary/wearable/etc versions will be easier as they can just contain the item.
Currently there is no way to obtain this without adminspawn.  I have Future Plans(tm) for these.
Gif of shields in action

### CODE REVIEW

**Comment by Anewbe** [comment]
Does it run on a charge, or just constantly project?

**Comment by Neerti** [comment]
The basic version implemented has a health system and it self charges.

**Comment by Anewbe** [comment]
But the item itself never runs dry?

**Comment by Neerti** [comment]
Its essentially self recharging.

**Comment by Magneld** [comment]
Does it block mobs also or only shots?

**Comment by Anewbe** [comment]
Only shots. Mobs and throw objects should be able to pass.

**Pull request merged**
