### PR TITLE
Adds multiple organ-related chemicals.

### PR DESCRIPTION
**Pull request by Mechoid**
Adds four quite advanced organ-repair chemicals, and two advanced organ rejection chemicals.

Organ Meds:
- Daxons repair twice as much as peridaxon, and have unique adverse reactions to being used with it, and one other -daxon in a chain.

Respirodaxon
	required_reagents = list("dexalinp" = 2, "biomass" = 2, "phoron" = 1)
	catalysts = list("phoron" = 5)
	inhibitors = list("dexalin" = 1)
	result_amount = 2

Lungs, Voicebox, Gas Bladder

Gastirodaxon
	required_reagents = list("carthatoline" = 1, "biomass" = 2, "tungsten" = 2)
	catalysts = list("phoron" = 5)
	inhibitors = list("lithium" = 1)
	result_amount = 3

Appendix, Nutrient Vessel, Plasma Vessel, Polyp 

Hepanephrodaxon
	required_reagents = list("carthatoline" = 2, "biomass" = 2, "lithium" = 1)
	catalysts = list("phoron" = 5)
	inhibitors = list("tungsten" = 1)
	result_amount = 2

Liver, Kidneys, Appendix, Acid Gland, Hive Node

Cordradaxon
	required_reagents = list("potassium_chlorophoride" = 1, "biomass" = 2, "bicaridine" = 2)
	catalysts = list("phoron" = 5)
	inhibitors = list("clonexadone" = 1)
	result_amount = 2

Heart, Response Node, Anchor Segment, Egg Sac

Immunosuppressants [Anti-Rejection]
- Require a certain dose to be maintained to process.
- Cause toxic buildup scaling inversely with their effectiveness per species.

Immunosuprizine
	required_reagents = list("corophizine" = 1, "tungsten" = 1, "sacid" = 1)
	catalysts = list("phoron" = 5)
	result_amount = 2

Mods: Diona 0.25, Promethean 0.75, Skrell 1.5, Unathi 1.75, Tajara 2.0

Malish-Qualem
	required_reagents = list("immunosuprizine" = 1, "qerr_quem" = 1, "inaprovaline" = 1)
	catalysts = list("phoron" = 5)
	result_amount = 2

Mods: Non-Skrell 0.5, Skrell 1.0

### CODE REVIEW

**Comment by Wickedtemp** [comment]
As someone who loves Medical and Chemistry, I... really don't think these are necessary, at all, and will only result in more complaints about how Chemistry makes everything else in Medical useless.  A reagent for organ rejection would be neat, but even with more complex recipes, it's still just not something that's needed at all. Adding special niche chems for every single organ just seems like a bit much.

**Comment by Novacat** [comment]
I can see why there would be a desired for more specialized chems, but, Alkysine and Imidazoline are great because they are both cheaper and better than the general-purpose organ treatment chem, not requiring phoron. These new ones likely will not be used all that much, due to both the complex recipes, and requiring a lot of phoron and protein, which are better off going to other places.

**Comment by Mechoid** [comment]
Without making it largely based on RNG and using carpotoxin, or making it rely on Explorers or an RNG event for spidertoxin, Respirodaxon uses straight phoron as a placeholder for a future [Thing]. That [Thing] I don't know but have ideas on. Otherwise, it's an amazing chemical for people going into breaches with no internals, relying on inaprovaline, dex, and bicaridine to keep their body from ripping itself apart, if someone really wants to.

If a Chemist has the tools to make these chemicals, and medical doesn't mind using the phoron / biomass to make these instead of making peri / filling the cloner and bioprinter, that's a decision they can make. These are more effective than Peri and do not have the confusion effect it has as a balance due to affecting all organs, instead having side-effects for being used with Peri or one other -daxon as said. The side-effects also make them potent antag tools if someone wants to use them for that.

Immunosuprizine and the skrell version are mostly for in-round regular transplants and Antags doing weird things. Them existing in their niche really doesn't affect anything, since there's no other use for them but poisoning or transplants. I'm looking at you Ethylredox.

If you deem the phoron better used elsewhere or just want peri, wonderful, don't use it for these. Their existence is have a well-supplied chemist be able to better supplement Surgeons if they're unable to handle patient load or nonexistent, or be used where Peri would, but can't or is inefficient.

They'll also be subject to tweaking like anything else. If one is far more effective in certain situations or Never Sees Use, I will probably touch them more.

**Comment by Atermonera** [comment]
Chem naming suggestions because some of those sound wierd:
Respirodaxon -> Resprodaxon
Gastirodaxon -> Gastirodaxon
Cordradaxon -> Cordraxon (yes its not strictly -daxon but "-druh-DA-" sounds wierd in the middle of a word)

**Pull request merged**
