### PR TITLE
Ports some cat hair or something

### PR DESCRIPTION
**Pull request by Yoshax**
Ports Aurorastation/Aurora.3#393

### CODE REVIEW

**Comment by Anewbe** [comment]
IIRC this is 1950s cat-wife hair... Not sure if want.

**Comment by Neerti** [comment]
Think this one is up for @Dragor to decide.

**Comment by ParadoxSpace** [comment]
Tajara Curly
http://puu.sh/pNmma/ce0e052975.png
http://puu.sh/pNmjf/68c817e1e6.png

Tajara Housewife
http://puu.sh/pNmmU/9b545f6be1.png
http://puu.sh/pNmjX/8d86f4c8ac.png

Tajara Victory Curls
http://puu.sh/pNmnZ/21bca4cb66.png
http://puu.sh/pNmkk/3127fb8946.png

Tajara Bob
http://puu.sh/pNmp0/0889370840.png
http://puu.sh/pNmkT/6223acc05c.png

Tajara Finger Curls
http://puu.sh/pNmpZ/1fb41b306b.png
http://puu.sh/pNmlA/4d6d074ece.png

Because I lack access to a cat, I want you to pretend for me that these are on one.

**Comment by Iamgoofball** [comment]
throw the hairstyles on a test mob

**Comment by mwerezak** [comment]
I remember seeing some screenshots on an actual mob a while back, and Anewbe's description is quite accurate.

**Comment by Yoshax** [comment]
I don't see how it's up to a lorehandler, tbqh. It's not North Korea. There's not a government regulated 6 hairstyles to choose from. The sprites aren't utterly poor quality like some of the ones we have, and as such, should be fine.

**Comment by zekesulastin** [comment]
cathair

**Comment by Anewbe** [comment]
Actually those look pretty nice on the body, disregard my earlier reservations.

**Comment by serenemelody** [comment]
The Codex Catstartes supports this decision.

**Pull request merged**
