### PR TITLE
Don't give synthetics the survival kit

### PR DESCRIPTION
**Pull request by Arokha**
What're they gonna do with it, anyway? Other than just make a pile of them in arrivals.

### CODE REVIEW

**Comment by Anewbe** [comment]
The box itself is actually pretty nice to have...

**Comment by SilverTalismen** [comment]
Yeah atleast leave them the box, I myself use it as a synthetic for engineering or to store minor stuff in

**Comment by Arokha** [comment]
Ok, lemme do that.

**Comment by Arokha** [comment]
There. So, you get an empty box if you're a synth. And if you wanted to be crazy could add more conditions if there were ever more box types that showed up.

**Comment by PsiOmegaDelta** [comment]
Well, from an OSHA point-of-view it makes some sense to enforce that everyone in an artificially pressurized environment have emergency equipment even if they may not personally have use for it.
You know, if case a synth happens to common across an unconscious meatbag colleague in a room currently experiencing drastic pressure loss.

**Comment by Anewbe** [comment]
I'm fine with it going either way, honestly. I can poll some folks and see who wants what, if y'all want that.

**Comment by Arokha** [comment]
I mean. Shouldn't everyone also get a suit cooler then? Or Vox phoron tanks? You're generally not required to wear PPD for OTHER PEOPLE on OSHA worksites.

**Comment by nachomeep** [comment]
No. Because suit coolers are big and unwieldy, and Vox don't exist as crew-members.

**Comment by Arokha** [comment]
Well. Do what you will with it.

**Pull request merged**
