### PR TITLE
Adds JackeryFox's Industrial Welder sprites

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by Hubblenaut** [comment]
Looks a bit weird, to be honest

**Comment by Yoshax** [comment]
Seems kinda odd it goes normal sprite -> this sprite -> normal sprites, for the three levels of welder.

**Comment by Anewbe** [comment]
The only hugetank welder I can think of is in Robotics, and I think that one deserves a sprite of its own, because it holds 4 times as much fuel as the base. I was considering adding the new one to that as well, but I thought it still didn't look quite right.

**Comment by ursamedium** [comment]
ind ind2 indh indh1
Since there wasn't a sprite preview in the pr

**Comment by SinTwo** [comment]
I'm am quite opposed to this new sprite; it looks like there's a growth or something on the handle.

**Comment by SpadesNeil** [comment]
It looks fugly. :-1:

**Comment by Anewbe** [comment]
225px-neutral_president
Really fine with either sprite, seems to be mostly negative reactions.

**Comment by JackeryFox** [comment]
Aye don't worry, I suck at everything anyways.

**Comment by mwerezak** [comment]
The sprite would be improved IMO by reducing the amount of clutter decoration on the welder. More detail is not always better, especially when you're restricted to 32 x 32.

**Comment by ursamedium** [comment]
It's a little murky, color-wise, imo, too. The yellow and red kind of bleed into each other.

**Comment by JackeryFox** [comment]
Eh, just delete it. It's all a waste of time, dunno why I even bothered with it.

**Comment by Anewbe** [comment]
That's not true, Fox, it looks pretty cool on its own, or I wouldn't have made this PR in the first place.

**Comment by Verarch** [comment]
I honestly prefer this sprite. Maybe could use a bit work, but IMO, it's good.

**Comment by Datraen** [comment]
Putting my two cents in: it's a good attempt, not a bad sprite, just not sure how much of an improvement it really is.

**Pull request closed without merging**
