### PR TITLE
Upgrades IAA

### PR DESCRIPTION
**Pull request by Yoshax**
As per #1005 & #1049 

DNM whilst pending feedback and suggestions.

### CODE REVIEW

**Comment by Minijar** [comment]
Cheers yosh, unsure how you got this to work on git.

**Comment by Yoshax** [comment]
I just cherry-picked the commit from your PR, and then merged master into the branch I cherry-picked the commit into.

**Comment by Zuhayr** [comment]
I am not sure how much of a fan I am of 'Sol Gov Representative' as a term. It feels kinda clunky - and I think it's generally written as Solgov? The PR is fine so I'll give it a :+1: when it's ready for merge but I feel like it needs a better alt-title.

**Comment by Minijar** [comment]
Perhaps SolGov Official ?

**Comment by Yoshax** [comment]
I'll change it, just not sure to what. Hard to pick a word. Also awaiting staff feedback as per http://ss13polaris.com/forums/viewtopic.php?f=61&t=547

**Comment by OhEmGee** [comment]
I think the official term for Sol Gov is Sol Central.

**Comment by Spookerton** [comment]
(it isn't)

**Comment by Infixx** [comment]
I'd say keep IAA as is and then add sol government representative if anyone has played paradise station they have a

**Pull request closed without merging**
