### PR TITLE
Ater poi3

### PR DESCRIPTION
**Pull request by Atermonera**
Package Bomb detonators can now be re-bound to new package bombs by hitting the new bomb. Only one bomb can be bound at a time. This is necessary for Blast Mine 1, and was discussed at the staff meeting. Shouldn't really have much impact on the uplink item because that gives you a fresh detonator that's pre-bound whenever you buy a bomb.
Not tested yet, will get to that.

Adds various PoIs:
Supply Drop 1
Supply Drop 2
Ration Cache
Blast Mine 1

### CODE REVIEW

**Comment by Atermonera** [comment]
It's `poi3` because the first two attempts were eaten by merge attempts hyper-inflating the diff

**Comment by Arokha** [comment]
Travis build #1 failed because you referenced Southern Cross objects/defines outside of Southern Cross. Build #1 attempts to compile all submaps without using a particular main map, to ensure there's no cross-contamination between the two in terms of item/object usage.

**Comment by Atermonera** [comment]
Aaaaand once again, attempting to merge-master to fix the conflicts bloats the diff to ungodly proportions.

**Comment by Atermonera** [comment]
Then we just do another one with the web editor to ACTUALLY fix the conflicts, because dark, arcane magics fuel git

**Comment by Atermonera** [comment]
Could've sworn I fixed those tiles *grumble*

**Comment by Atermonera** [comment]
***Angry grumbling***

**Pull request merged**
