### PR TITLE
changelog

### PR DESCRIPTION
**Pull request by Atermonera**

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Aaaa, what happened with my third changelog there?

**Comment by Atermonera** [comment]
Omitted during proofreading. 1, it's just a typo. 2, it doesn't describe any mechanical or lore changes that players need to be aware of. 3, because I remember writing this in one of my updates once upon an shortly after I figured out how to use the script (#4755): ater's guidelines to changelogs

I should probably put it on the wiki somewhere.

**Comment by Atermonera** [comment]
Update: I have put it on the wiki [wiki](https://github.com/PolarisSS13/Polaris/wiki/How-to-Into-Changelog)

**Comment by TheFurryFeline** [comment]
Alrighty, fair nuff.

On Jan 26, 2020 20:09, "Atermonera" <notifications@github.com> wrote:

Omitted during proofreading. 1, it's just a typo. 2, it doesn't describe
any mechanical or lore changes that players need to be aware of. 3, because
I remember writing this in one of my updates once upon an shortly after I
figured out how to use the script (#4755
<https://github.com/PolarisSS13/Polaris/pull/4755>): [image: ater's
guidelines to changelogs]
<https://camo.githubusercontent.com/4a6b9074a195da0f93068dcc3230c3f38da9f65a/68747470733a2f2f7075752e73682f4634366e312f313034373839613061362e706e67>

I should probably put it on the wiki somewhere.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/PolarisSS13/Polaris/pull/6643?email_source=notifications&email_token=AJGMTY5W3KHHENF5GNZUYGTQ7YX3DA5CNFSM4KJ45NRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ6CZQY#issuecomment-578563267>,
or unsubscribe

**Comment by TheFurryFeline** [comment]
Oh. As for the wiki..... I've tried to access it several times over the last couple years with no success. Always come up with a  connection reset error `ERR_CONNECTION_RESET` It's irked me to no end.

**Pull request merged**
