### PR TITLE
Removes Chemspill volatile fuel. Makes N2O an oxidizer.

### PR DESCRIPTION
**Pull request by chaoko99**
Except for that one thing that legitimately needs it to function.

also makes N2o an oxidizer, because it *is.*

### CODE REVIEW

**Comment by Cyantime** [comment]
What's wrong with volatile fuel? It's an additional hazard like plasma, but without the contamination and blinding.

**Comment by chaoko99** [comment]
>What's wrong with volatile fuel? It's an additional hazard like plasma, but without the contamination and blinding.

Well. It's a snowflake gas that clogs up atmospherics, is a pain in the ass to clean up... And why the fuck are you saying that spilt phoron shouldn't be hazardous. I don't know if you know the BASICS OF CHEMISTRY OR ANYTHING BUT

88f

**Comment by Cyantime** [comment]
Spilled plasma liquid should turn into plasma gas, yeah. But why remove fuel from the random gas spill event? And you didn't actually make spilled plasma turn into plasma gas, only the new hydrogen-plasma thing for the r-ust.

**Comment by chaoko99** [comment]
Whoops. My bad. I'll fix that now.

>But why remove fuel from the random gas spill event?

I don't know. It just seemed like the smart thing to do. I can revert that.

**Comment by Cyantime** [comment]
(Also the sneaky change to make N2O an oxidiser should be documented)

**Comment by chaoko99** [comment]
Shit, did I forget to save that line?

**Comment by chaoko99** [comment]
readded gas leak fuel.

**Comment by Cyantime** [comment]
Spilled plasma liquid still creates volatile fuel.

**Comment by chaoko99** [comment]
FICLOMG 

I pushed the wrong file entirely.

**Pull request merged**
