### PR TITLE
Colorblindness

### PR DESCRIPTION
**Pull request by Arokha**
Adds it! In three traits. I assume there's nothing else I need to do to add it to your traits? If so, lemme know.

### CODE REVIEW

**Comment by Arokha** [comment]
Can you restart that travis build? It's whatever PoI has an active edge causing it.

**Comment by Belsima** [comment]
Have you fixed Monochromacy?

**Comment by Arokha** [comment]
Fixed in what way?

**Comment by Belsima** [comment]
It just plain didn't work, IIRC, no? except on HUD items

**Comment by Arokha** [comment]
All forms of colorblindness were broken on Vorestation after the planes update. I fixed that over there, and at the same time split this off so Polaris could use it here.

**Comment by Arokha** [comment]
Thankye whoever reran travis.

**Comment by Atermonera** [comment]
_Shakes boot angrily at travis_

**Comment by KasparoVy** [comment]
How the heck did you calculate those matrices? :thinking: 
It took me forever to figure out Taj/Vulp colourblindness and I'm pretty sure I went about it HELLA WRONG

**Pull request merged**
