### PR TITLE
A Load of Armor Changes

### PR DESCRIPTION
**Pull request by Neerti**
Here's a large list of changes.
* Bulletproof vest renamed bullet resistant vest
* **Adds helmet variants for ablative and bullet resistant armor.**
* **Adds new armor type, called combat armor**, which is better than the security vest but worse than tactical armor.
  * Combat armor stats are 50 melee/50 bullet/50 laser/30 bomb.  Compare to tactical, which is 70/65/65/40 (including the tac jumpsuit).
* **Adds two new pieces of armor, arm guards and leg guards**, which protect the arms and legs against harm, at the cost of some slowdown.
  * Arm/leg guards are available for riot, bullet resistant, ablative, and combat.
  * Arm and leg guards go on your hands and feet, respectively.
  * Clothing which would have covered what the arm/leg guards cover cannot be worn at the same time, and vise versa, meaning you cannot wear a spacesuit and arm or leg guards at the same time and receive massive protection.
* **Tactical armory has been removed.  Tactical armor can still be obtained at cargo, for a premium.**
* Riot suit split into riot vest, riot arm guards, and riot leg guards.
* **Riot shields can now attempt to block projectiles**, as they once did previously.  However, piercing projectiles are able to go through the shield, still resulting in a hit but for reduced damage.
  * Pistol-tier ammo will not pierce a shield.
  * Rifle-tier ammo will go through and do half damage.
  * All lasers go through and do half damage.
  * Crazy armor-pen projectiles go through and do full damage (sniper bullets, xray)
* Armor sets (ablative, bullet-resistant, riot, combat) can now be individually ordered at cargo.
  * Crates which previously provided armor (e.g. LWAP crate providing ablative) no longer provide armor.
  * Tactical Armor crate increased in cost to 60 points.
* Adds new uplink category for armor.
  * Moves armor vest to the new category.
  * Adds a set of combat armor to the uplink, in the armor category.
* Starting helmet and vest for security's bullet protection increased.  Laser and melee protection decreased, to equal 40/30/30
* Heavy vest is now 50/40/40.
* **Armory and Secure Armory remodeled to accommodate the increase of armor available.**  A preview is here: http://puu.sh/nvZnJ/ad34d37184.png  Everything that was in the old armory is still in the new one, sans some useless flash rounds that was bloating up the ammo pile.  Note that the revolvers you see in the image are not actual revolvers, but that is the icon used for the randomspawn ballistic guns.
* Flashers now available in the Armory instead of the Secure Armory.
* Experimental energy gear crate renamed because e-guns are hardly experimental and it was misleading.
* Experimental armor crate removed, as you can order armor individually now, also misleading.

Helmet sprites by Anewbie.

I probably forgot a few things but that should be everything.

### CODE REVIEW

**Comment by OhEmGee** [comment]
A great change. Kinda sad to see the old armory go, though. I liked the design.

**Comment by Magneld** [comment]
I still think those really should be revolvers :c

**Comment by Datraen** [comment]
Will check when I get home.

**Comment by Anewbe** [comment]
+1

**Comment by Datraen** [comment]
:+1:

**Comment by Mark9013100** [comment]
Love it, but I will admit, a bit worried that there's now four sets of bulletproof/ablative armor.

**Pull request merged**
