### PR TITLE
Removes the password to delist the server

### PR DESCRIPTION
**Pull request by Yoshax**
We really need a better way of doing this.

### CODE REVIEW

**Comment by Spookerton** [comment]
We're going to see if -invisible works first.

**Comment by Yoshax** [comment]
PR's here if you need it.

**Comment by Anewbe** [comment]
:+1: :+1:

**Comment by Spookerton** [comment]
Invisible does it, but we should probably do this anyway so that our lewd downstreams don't accidentally cry tears of blood if they have odd startup parameters.

**Pull request merged**
