### PR TITLE
Adds a detective belt and other edits for security

### PR DESCRIPTION
**Pull request by Mark9013100**
Adds the Forensic utility belt for detectives, can be found in the detective's closet and from the forensic investigation equipment crate.
Gives black gloves to security officers, to help avoid contaminating evidence with their fingerprints.
Increases the amount of station bounced radios, flashlights, and crowbars in the brig.

### CODE REVIEW

**Comment by Minijar** [comment]
Why does a forensic guy need a belt? They have a crime scene kit to carry everything.

**Comment by Mark9013100** [comment]
The belt is more convenient than the kit, having to carry around a briefcase everywhere isn't so practical.

**Comment by NortonDK** [comment]
The kit can only whats in it from the beginning, some more slots in it would be nice!

**Comment by Neerti** [comment]
This will also help stop certain people from foaming at the mouth because a detective grabbed a secbelt, since now that slot's occupied by the forensics one.

**Pull request merged**
