### PR TITLE
Make blood loss/heart removal make sense

### PR DESCRIPTION
**Pull request by Arokha**
Right now it gives you 300 toxin damage "to be sure" you die. That's a little odd. Especially on health scanners after someone has bled to death. And you can't do heart transplants. We can do heart transplants now in 2017. 3500 per year. Pretty sure they won't forget how by 2561 or whatever.

This makes having no heart or too little blood do 75 oxyloss per tick. Enough to kill you eight seconds if you have no special care. It becomes 15 per tick with dexP which is fast enough to kill you "pretty fastly" and slow enough you can swap out a heart in surgery.

With dexP+dex+tric it becomes a meager 10ish per tick, but an inevitable 10 per tick as they are literally now full of every oxyloss removing drug in the game. So you can survive a part of a minute, max, with not enough blood. You're still paralyzed and eye_blurry for most of it. You should probably be in surgery.

### CODE REVIEW

**Comment by Arokha** [comment]
Ok. This is going to make me sound dumb.

@Anewbe How do changelog pls?
Can I just copy someone's and add it in a commit?

**Comment by Anewbe** [comment]
So there should be a bunch of .yml files in a folder called polaris/html/changelogs. Copy the one called example.yml, and there should be further instructions in there.

**Comment by Arokha** [comment]
This is right, yes?

**Comment by Anewbe** [comment]
Yep

**Comment by Anewbe** [comment]
Just remembered something, you'll need to go into either organs/organ.dm and redo how vital organs work, or you need to go to wherever the heart organ is defined and remove the vital tag, otherwise they'll still just die.

**Comment by Arokha** [comment]
Yeah, just brain, I was surprised at that too.

**Pull request merged**
