### PR TITLE
Let them finally eat cake

### LINKED ISSUE #6776: Chaos cake base layer impossible to make.
#### Brief description of the issue
You cannot finish the first step to a chaos cake.

#### What you expected to happen
Delicious cake.

#### What actually happened
Burnt mess.

#### Steps to reproduce
Suffer for an hour getting the ingredients only to fail.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

I believe it's because poisonberries do not have a kitchen tag.

### LINKED ISSUE #6777: Chaos cake has no sprite.
#### Brief description of the issue
Chaos cake has no sprite.

#### What you expected to happen
To stack the cake layers.

#### What actually happened
Cake does a vanishing act.

#### Steps to reproduce
Place a layer onto the chaos cake. Watch it disappear right before your very eyes!

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Was this even tested?

### PR DESCRIPTION
**Pull request by Schnayy**
Fixes #6777 and fixes #6776 

I only tested making the first layer and the last layer, as well as all the sprites, because if I go through and bake every layer of this cake right now I will cry.

### CODE REVIEW

**Comment by Heroman3003** [comment]
I don't really like idea of removing poisonberries being usable in normal berry recipies. That was a fun feature, IMO, similar to using poison apples in regular apple recipies.

**Comment by Atermonera** [comment]
I mean, on the one hand, that should have been a consideration when the original author was first designing the cake. A simple fix would be to just add recipe datums for the recipes using berries that instead uses poisonberries.
I think the best fix would be to make the kitchen_tags a list object, since they're all strings. That would require tweaking the definitions of all the seed datums, and modifying the logic of the recipe processing to check against lists instead.

**Comment by Schnayy** [comment]
Apologies if my code is crap but that should keep poisonberries an alternative. I also switched PB&J to use cherry jelly instead of berry juice, as I believe was originally intended.

**Comment by TheFurryFeline** [comment]
Suggest also editing OP to be `fixes #6776` due to the way GitHub keywords work with closing issues.

**Pull request merged**
