### PR TITLE
Replaces water + welding tank sprites with sprites from Aurora

### PR DESCRIPTION
**Pull request by listerla**
DNM until staff meeting because these sprites were controversial in the past.

### CODE REVIEW

**Comment by lbnesquik** [comment]
Can we actually see them?

**Comment by listerla** [comment]
image

**Comment by lbnesquik** [comment]
I think we have those? At least virgo does.

**Comment by listerla** [comment]
Polaris does not.

**Comment by Atermonera** [comment]
For reference, #4112

**Comment by Atermonera** [comment]
Staff input: Yae

**Pull request merged**
