### PR TITLE
Adds Tarot Cards + Trading Cards + Arcade Adjustments

### PR DESCRIPTION
**Pull request by Yoshax**
Ports tarot cards, trading cards and arcade changes from Baystation12/Baystation12#11445

### CODE REVIEW

**Comment by Yoshax** [comment]
Few tiny map additions to be map, but will likely do in another PR if this is merged, due to devs, or one or two of them, having issues with map PRs.

**Comment by Datraen** [comment]
I like it, gets my approval.

Spaceball Jones.

**Comment by Yoshax** [comment]
Just as a comment, I'm not sure what direction people want to go with the arcade emagging, but the Orion Trail I believe was taken straight from /tg/, and has some odd emag interactions, just like the current arcade does. You may want to add it to the topic on the forums.

**Comment by Datraen** [comment]
Juust waiting on Travis.

**Pull request closed without merging**
