### PR TITLE
Drawing blood takes time

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by Yoshax** [comment]
When used on yourself, and others, or just others?

**Comment by Anewbe** [comment]
Everyone

**Comment by Yoshax** [comment]
Inconsistent with the other behaviour. Using a syringe on yourself to inject things takes no time, hardsuit or not.

**Comment by Anewbe** [comment]
Drawing blood requires a bit more precision and focus than giving an injection, at least as far as I know.

**Comment by Yoshax** [comment]
The issue is the self vs use on others. Injecting someone else takes time, injecting yourself does not. Here, both take time. They should match in one way or the other, in my opinion. Either both on self takes time, or neither does.

**Pull request merged**
