### PR TITLE
Prevents surgery from being done while wearing a voidsuit

### PR DESCRIPTION
**Pull request by Heroman3003**
Other than hardsuit detachment one.

Ideally it should a special proc that prevents surgery from being done on an area covered by any non-medical clothing, IMO, but this is a start.

### CODE REVIEW

**Comment by Atermonera** [comment]
You could check if the target body part is covered, using the clothing flags? Though that might be too strict...

**Comment by Heroman3003** [comment]
I was thinking of leaving specific clothing subtypes with a flag to allow for it regardless should I do it for ALL clothing. For example medical scrubs/surgery caps/medical masks would still allow surgery through them, as well as survival gear for species like Vox.

**Comment by Heroman3003** [comment]
To clarify: this PR is more balancing of "surgery through voidsuit". If I'm gonna do it for all clothes it probably will be overriding this PR's changes, but it will be more of "how does it even make sense to surgery through the clothes".

**Comment by Nalarac** [comment]
How will this impact the Zaddat, who can't remove their voidsuits in normal station environments?

**Comment by Schnayy** [comment]
Zaddat were intended to not be able to get surgery through their suits w/out a special room, I believe. Working as intended.

**Comment by Heroman3003** [comment]
Split it off. The new proc can later be modified should it be updated.

**Comment by Cerebulon** [comment]
This appears to have entirely prevented surgery, voidsuit or no.

**Comment by Heroman3003** [comment]
Fix for that aspect is already up. It appears a fix to way attackby logic works for surgery broke it due to one of procs involved being entirely nonfunctional (and yet still used for some god forsaken reason).

**Pull request merged**
