### PR TITLE
Optmized Multi-Z ZAS and explosions ports

### PR DESCRIPTION
**Pull request by Leshana**
* Re-ports multi-z ZAS improvements and explosion improvements from bay from https://github.com/PolarisSS13/Polaris/pull/2998 done by @Anewbe 
  * This renames the ZLEVELS define to MULTIZAS and adds multi-z support to the all-important can_safely_remove_from_zone()
* Ports https://github.com/Baystation12/Baystation12/pull/16947 done by @Leshana to optimize multi-zas performance
* Makes the multi-z explosion strength scalar configurable, so you can disable multi-explosions, or tune the value you like at runtime.

### CODE REVIEW

**Comment by Leshana** [comment]
During testing I discovered that 0.35 is pretty anemic explosion z-scalar.  a "big" admin bomb (3,5,7) damaged only one tile on the next floor up (became a 1,2,2) so 0.5 seems better as a default.  But its configurable now, so the default value really isn't that important anyway.

**Comment by LorenLuke** [comment]
https://github.com/VOREStation/Polaris/blob/347e759b103185128e62613386d5031191e55abd/code/game/objects/explosion.dm#L77

Can you move this line to below the ex_act for each of the items?
I've had spectacularly silly stuff result from this, like a ninja deadman going off, it deleting the tile, the ninja falling through, then the explosion processing all the turf.
Same with a person on top of the ninja at time of boom.
Ex_act()'ing the turf last solves this in my experience:
https://github.com/Baystation12/Baystation12/pull/16152

**Comment by Leshana** [comment]
Ah, that explains that then.  Okay, I have cherry picked your commit https://github.com/Baystation12/Baystation12/commit/d8df8c4993ac6fc4705e0b310a2f337413ead7ed

**Comment by Anewbe** [comment]
Tested and ready to go?

**Comment by Leshana** [comment]
Yes, that's how I decided to use 0.5 as the default for the explosion coefficient.  ZAS was tested with NO2

**Pull request merged**
