### PR TITLE
Changed food sprites

### PR DESCRIPTION
**Pull request by listerla**
Ported from https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/781 and Aurora https://github.com/Aurorastation/Aurora.3

Only took the ones that don't fuck with perspective too much, pending a consensus on what perspective means in the context of Polaris.

### CODE REVIEW

**Comment by Cerebulon** [comment]
Your second link is broken, could you fix that so we can see pics?
Afaik the burgers are something we already were thinking about porting so you're probably good on that end, would just be good to see the others.

**Comment by listerla** [comment]
@Cerebulon https://github.com/PolarisSS13/Polaris/pull/6702/checks?check_run_id=451104973

It's not a link to a PR b/c I don't know which PR. I just took them from the repo. I can screenshot if needed later.

**Comment by Neerti** [comment]
The icon diff [here](https://github.com/PolarisSS13/Polaris/pull/6702/checks?check_run_id=451104973) shows most of the sprite changes.

**Comment by Atermonera** [comment]
hamburger, cheeseburger, and spellburger appear to be missing sprites / have blank ones, but it may just be on my end, uncertain. icon diff

**Comment by listerla** [comment]
@Atermonera This is in fact on your end. DMI has sprites.
image

**Pull request merged**
