### PR TITLE
Removes unused code - old turrets

### PR DESCRIPTION
**Pull request by Kelenius**
Removes /obj/machinery/turret (by the looks of if they wouldn't fire anyway)
Removes /obj/machinery/turretcover
Removes /area/turret_protected (new turrets don't use it), its associated procs, changes areas from /area/turret_protected/x to area/x

### CODE REVIEW

**Comment by Kelenius** [comment]
No actual changes to the game, just removal of unused code, c'mon.

**Comment by Techhead0** [comment]
To be fair, removing this code results in a big pile of map changes.

**Comment by PsiOmegaDelta** [comment]
To be fair, the old turret code is creaky and unmaintained, at least in comparison to the portable turret code.

**Comment by Kelenius** [comment]
>To be fair, removing this code results in a big pile of map changes.

Yeah, ``s/\/turret_protected/``

**Comment by Kelenius** [comment]
Guys.

**Comment by Kelenius** [comment]
I'd like to get approval before fixing the conflicts.

**Comment by Datraen** [comment]
:+1: pending conflicts

**Comment by Kelenius** [comment]
Resolved.

**Pull request merged**
