### PR TITLE
Changes to SMES Interface

### PR DESCRIPTION
**Pull request by Hubblenaut**
Image

 - Transition to using kilowatts and kilowatt hours
 - Adds an input load bar with value
 - SMES charge rate and coil capacities slightly adjusted for using
   kilowatt units

### CODE REVIEW

**Comment by Datraen** [comment]
Provided it handles decimals, which you said it did in dsay, :+1:.

**Comment by Hubblenaut** [comment]
To clarify, nothing has been changed to custom input other than a division by 1000. Float values are possible, but we're rounding at one digit behind the dot.

**Comment by Datraen** [comment]
Sounds good.

**Comment by mwerezak** [comment]
You may want to grab https://github.com/Baystation12/Baystation12/pull/12914

**Pull request merged**
