### PR TITLE
Tones down the Darkmatter Beam

### PR DESCRIPTION
**Pull request by Anewbe**
To 35 BRUTE, from 60

### CODE REVIEW

**Comment by Atermonera** [comment]
Darkmattergun is `boom boom, fill the room`, right?

**Comment by Anewbe** [comment]
Yeah, but this is the laser beam part that people actually use.

**Comment by Magneld** [comment]
Whats the dakka dak mode damage at, five?

**Comment by Anewbe** [comment]
20 for this one, but it'll basically never hit.

**Comment by Magneld** [comment]
Works for me.

**Pull request merged**
