### PR TITLE
Removes the old virus system

### PR DESCRIPTION
**Pull request by Kelenius**
Appendicitis moved to appendix organ

### CODE REVIEW

**Comment by Mark9013100** [comment]
rip virology

**Comment by Datraen** [comment]
Last I've heard, we don't want to remove the framework for virology until we have a non-aggressive replacement for it.

As it currently stands, it's been removed from the random events, making viruses a non-issue right now.

**Comment by Mark9013100** [comment]
*points to genetics*

**Comment by Kelenius** [comment]
Old system.

/tg/ system.

The bugged and unsupported one.

The one that has GBS, pierrot's throat and rhumba beat.

**Comment by GinjaNinja32** [comment]
@Datraen, this is the old old disease system (`/datum/disease`), not the Virology/RNG virus type system (`/datum/disease2` aka virus2).

**Comment by Datraen** [comment]
Ah. The time I spent glancing between classes wasn't enough to recognize that we have two systems, sorry.

**Comment by Zuhayr** [comment]
No objection to this assuming it has been tested. In the middle of my own branch atm so I will not be able to test it tonight, will do it tomorrow if nobody else gets it out of the way.

**Comment by Fox-McCloud** [comment]
Still better than Virus2 in a lot of ways.

Allows for multiple/differing cure types, easier to add different/new diseases, support for disease reagents, and the likes.

Improve, don't remove.

**Comment by Kelenius** [comment]
@Fox-McCloud don't comment on PRs while high please.

**Comment by Zuhayr** [comment]
I'm glad to see you're maintaining your long proud tradition of commenting uselessly on PRs for codebases you don't use, Fox.

**Comment by Zuhayr** [comment]
Looks good to me. Removed virus and virus2 completely on Europa and had no bugs. :+1:

**Pull request merged**
