### PR TITLE
Adds communicator watch (take 2)

### PR DESCRIPTION
**Pull request by BillyBangles**
(hopefully i did it right this time)

It's just a communicator that you can equip to your glove slot. That's all. Useless? Maybe. I just thought it was a nice bit of fluff. It's the 26th century, you'd think we'd have smart watches by now.

### CODE REVIEW

**Comment by Anewbe** [comment]
Can we stick the loadout part of this into a "Selection" menu? Not sure how the game will handle people with multiple comms.
Also, can we get an image?

**Comment by BillyBangles** [comment]
Here's a picture
image
And I'll get to making the selection list in a bit.

**Comment by BillyBangles** [comment]
Might do some more touch ups on that later as well. I feel a little iffy about it right now

**Comment by MisterLayne** [comment]
Is it literally just a communicator on a watch, or does it have limited abilities compared to the regular communicator?

**Comment by BillyBangles** [comment]
it's literally just a communicator on a watch. I guess the only downside is that you have to have your inventory open to see if it's ringing or anything like that.

**Comment by Belsima** [comment]
@Anewbe you can get them all over the map anyways, I think the game can handle multicomms
though a selection is still preferred

**Comment by Keekenox** [comment]
Can I make a better sprite?

**Comment by BillyBangles** [comment]
@Keekenox If you think you can do better, go for it, though I do plan on making some changes to this.

**Comment by BillyBangles** [comment]
might try to tinker with a new sprite but for now it's ready to go

**Pull request merged**
