### PR TITLE
Adds lizard, visitors and intrigue* game modes + tweaks.

### PR DESCRIPTION
**Pull request by Datraen**
Lizard is a combination of Changeling and Wizard (I forgot who mentioned the name in the Teamspeak.)

Intrigue* is a combination of Traitor and Ninja

Visitors is a combination of Ninja and Wizard. Having more antagonists might be more chaotic, or might be less chaotic.

Autotraitor is now it's a child of the traitor template, utilizing a check for allowing late spawn. This check allows for specified antagonists to late spawn in mixed game modes.

Needs Review added because it touches an existing game mode, and I want to make sure others catch anything I might miss to help prevent any interruptions in current gameplay. I had tested the modification with the two different traitor modes and it did not seem to affect either.

### CODE REVIEW

**Comment by Techhead0** [comment]
Proper spelling is "Intrigue".

**Comment by Datraen** [comment]
Renamed to the proper spelling of intrigue.

**Comment by Minijar** [comment]
Perhaps one for wizard plus cult? Something like magicians circus or something idk.

**Comment by Datraen** [comment]
@Minijar You mean conflux? https://github.com/PolarisSS13/Polaris/blob/master/code/game/gamemodes/mixed/conflux.dm

**Comment by nachomeep** [comment]
Do these modes exist in secret?

**Pull request merged**
