### PR TITLE
Clears up machine constructions

### PR DESCRIPTION
**Pull request by Kelenius**
Circuits contain paths instead of strings.
Circuit definitions moved to a single file. We don't need 100500 files with five lines in each.
Machines don't create parts inside them by default. Instead there are preset options that do; those are placed on the map. Previously, machine frame would cut the component list after creating a machine.
Telecomms are left untouched pending #965.
No functional changes to the game - pure cleanup.

### CODE REVIEW

**Comment by Neerti** [comment]
Conflicts.

**Comment by Kelenius** [comment]
Resolved.

**Comment by Kelenius** [comment]
:<

**Comment by Datraen** [comment]
Not really sure which did this in, but currently conflicts.

**Comment by Kelenius** [comment]
Please don't make me fix map conflicts three times.

**Comment by Kelenius** [comment]
Conflicts like hell, would be easier to remake.

**Pull request closed without merging**
