### PR TITLE
Removes activation sounds from glasses that have them

### PR DESCRIPTION
**Pull request by Yoshax**
It's a horrifying noise and sounds like a bloody dentist's drill or something.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
But I like it. D: It sounds like a set of night vision goggles when you turn them on.

https://www.youtube.com/watch?v=TC0KTDMPx5E

**Comment by Yoshax** [comment]
It's far more shrill, and high-pitched than that.

**Comment by SpadesNeil** [comment]
Is it? Maybe I didn't notice it. Well, let's replace the awful sound, then. Not remove it! :( I like the sound...

**Comment by Yoshax** [comment]
Finding sounds is hard.

**Comment by SpadesNeil** [comment]
Gimmie a minute! (And as usual by 'a minute' I mean _'probably like an hour just hang on I'm doing a thing'_)

**Comment by SpadesNeil** [comment]
Initial research into this states that the sound is really just a fantasy thing and RL goggles don't make that sound. Reality is it's not realistic.

But I think the sound is still cool so I demand we keep it! :U

At least if we don't, I won't feel so bad.

**Comment by Spookerton** [comment]
http://www.freesound.org/people/reg7783/sounds/321800/
While real nogs don't **usually** make noise *(splinter cell is PROBABLY the trope origin, and it's basically just an audio cue for the player)*, capacitor whine can still be a thing. Defibs are one of the better examples of the same sound that's true(r) to life.

**Comment by Hubblenaut** [comment]
And here I thought you mean drinking glasses and got all confused.

**Comment by Yoshax** [comment]
@Neerti, @EmperorJon. @Datraen.

This has been idle for some tmie.

**Comment by Datraen** [comment]
People suggested alternative sounds, which I would prefer to just removing it.

While it's not something that's realistic, it's something that's fun.

**Comment by Yoshax** [comment]
Three sounds have been proposed. One is from Splinter Cell. The other two are just as bad as what we have now. It isn't fun, it's irritating.

**Comment by Datraen** [comment]
We could tone down the sound in the second link that @SpadesNeil posted, http://www.freesound.org/people/Syna-Max/sounds/60345/ , and I think that would be a better route.

**Comment by Yoshax** [comment]
I dislike it, it's ridiculously high-pitched and irritating.

**Comment by Spookerton** [comment]
Perhaps we could just get a http://freesound.org/search/?q=switch sound. :star2:

**Comment by Hubblenaut** [comment]
We definitely need that switch sound for lighting switches, levers ect.

**Comment by Zuhayr** [comment]
Clearly toggling your glasses should trigger Shia Labeouf shouting JUST DO IT.

**Comment by Serithi** [comment]
I'm going with Zuhayr's suggestion myself. :v

**Comment by SpadesNeil** [comment]
Agreed. *nodnod*

**Pull request merged**
