### PR TITLE
Replaces [stack]/fifty atoms with atoms that spawn the normal stack

### PR DESCRIPTION
**Pull request by MagmaRam**
The stack/fifty objects were really buggy, this should fix all of that in one go.

### CODE REVIEW

**Comment by Anewbe** [comment]
Did you test this?

**Comment by Techhead0** [comment]
I'm curious how they were buggy, aside from R&D stuff that checked exact type instead of using istype.

**Comment by Anewbe** [comment]
They weren't working in a lot of cases. The carpet stacks especially were screwed up.

**Comment by MagmaRam** [comment]
let me just fuck with git for 50000 weeks trying to figure this out ok

**Comment by Techhead0** [comment]
So... having read this, if this actually fixes whatever problems you're having with carpets, I'll be impressed.

**Pull request merged**
