### PR TITLE
Adds maint tunnel between Atmos and Solars

### PR DESCRIPTION
**Pull request by SpadesNeil**
---OOC---
- Fixes lighting in Security. Again.
- Fixes lighting in Library.
- Adds a new maint tunnel between engineering solars and atmos, now
outside the blast radius of SME explosions.

Also resolves https://github.com/VOREStation/VOREStation/issues/523 but I'm adding it to my map regardless of if you guys want it or not.

----IC----
# INCOMING FAXES FROM VIRGO-ERIGONE . . .

**Subject:** Fw: atmos maint
> hav some blooprints for the new atmo access tunel I made
> 
> i also put the solar wiring through atmo so it dun go through the bit wot gets blown up if the enjin blows
> 
> -Scree

**Subject:** Regarding addition of new atmospheric maintenance tunnel
> Dear Vir Central Command,
> 
> Please forgive Scree's crude penmanship. Our Chief of Safety and Engineering recently approved this project after power was cut due to several engine accidents. He suggested we forward this adjustment to the administration of the NCS Northern Star, whose blueprints are the original template of the Virgo Orbital Research Establishment.
> 
> Attached below are the new blueprints, rather than photographs taken by Scree through a set of meson goggles. Highlights in green denote new additions. Highlights in red denote removals.
> 
> Please note that the gas tank storage area in Atmospherics had to be shifted two meters northward to accommodate this change. There should be absolutely no impact on productivity from this minor adjustment.
> 
> Have a secure day.
> 
> Sincerely,
> Victor MacDaniel,
> NanoTrasen Chief Administration Office of the Virgo-Erigone Branch

blueprint
(( Edit: Now a gif to make changes more obvious. ))

### CODE REVIEW

**Comment by Anewbe** [comment]
The new tunnel has no turnaround space; if you widen the hallway one tile right, and shift the contents of the drone room accordingly, I think we'd be cool with merging it.

**Comment by SpadesNeil** [comment]
Gimmie a minute to do just that.

**Comment by SpadesNeil** [comment]
Widened the hallway, shifted over drone fab, and added some trinkets to the hallway.

**Comment by Anewbe** [comment]
Image?

**Comment by SpadesNeil** [comment]
capture

Also as soon as Github client stops acting up there will be a properly cleaned version of the map.

**Comment by SpadesNeil** [comment]
capture

**Comment by Anewbe** [comment]
Looks fine to me, :+1: , unless someone comments otherwise will merge tomorrow.

**Comment by Ithalan** [comment]
This will be awesome for those times when the engineering staff wants to run direct nitro feeds down to the engine room, or waste feeds back to atmospherics, too.

**Comment by Screemonster** [comment]
I know, right? I used to do that on the old old old Bay map when it was still based on radiation collectors.

**Pull request merged**
