### PR TITLE
[Project] Vintage Voidsuits

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Rifling through the files the other day, I found the Rugged Zaddat shroud, and was like "man, this is a really neat design", and it's apparently based on old human voidsuits? So here we go! A set of refurbished voidsuits for use in events or space exploration POIs.

Five variants (crew, medic, marine, engineer, officer), four* species, four facings, two UI states. That makes 160 states.
*Well, four for you guys. Five for downstreams! ~~and 40 more states. RIP my wrist.~~

talonsuits_v2

- [x] Items & Cycler Entries coded
- [x] Human UI sprites imported
- [x] Human Mob sprites imported
- [x] Skrell UI sprites imported
- [x] Skrell Mob sprites imported
- [x] Tajaran UI sprites imported
- [x] Tajaran Mob sprites imported
- [x] Unathi UI sprites imported
- [x] Unathi Mob sprites imported
- [x] Final testing
- [x] Final polish & item coding

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
Doing some final tweaking/testing, but this is otherwise good to go.

**Comment by Rykka-Stormheart** [comment]
I love these, holy shit. Thank you!

Are you planning on porting early or waiting for Polarismerge?

**Comment by KillianKirilenko** [comment]
Eh, most of the sprite credit here goes to whoever sprited the original rugged zaddat shroud. My main influence was reworking the back stripe, adding tails where necessary, doing the helmet paintovers, and doing the variant markings.

I don't think I'll be earlyporting unless people *desperately* want this - importing 160 states was a tedious nightmare (only made possible in the time window I hit thanks to a web-based sprite sheet splitter that I found), even if I can just copy the files across.

**Comment by KillianKirilenko** [comment]
Did I mention I hate dmi merge conflicts?

I hate dmi merge conflicts.

Hold on whilst I fix this.

**Pull request merged**
