### PR TITLE
Adds All of the Winter Coats to the Loadout.

### PR DESCRIPTION
**Pull request by redstryker**
Does as the title says.  Nothing more.  Nothing less.  I _would_ have made it more organized with the new system, but I don't know how to do that/if it works if you want there to be job restrictions for the items.

### CODE REVIEW

**Comment by Hubblenaut** [comment]
New system is self-organizing IMO.
One question:
Why is the engineering coat available for atmospheric technicians, but the atmospheric one not available for engineers?

**Comment by Datraen** [comment]
We have to add a system that does job restrictions at some point, if it's not done by the time Xenobio2 is done, I'll take a crack at it.

**Comment by Zuhayr** [comment]
The current loadout system does do job restrictions.

**Comment by Datraen** [comment]
@Zuhayr: The current "issue" is that the implementation that allows for listed selections doesn't handle job restrictions on a item-by-item basis, it's all or nothing.

**Pull request merged**
