### PR TITLE
Ports Turbolifts from Bay.

### PR DESCRIPTION
**Pull request by Neerti**
Ports code for turbolifts, and adds them to the test map.
Pictures:
First floor
Second floor
Also fixes the %ETA% shuttle bug.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
It would be great if there was a way to sabotage the elevators..hm.. Looks great anyway

**Comment by Neerti** [comment]
You can use them to crush people.

**Comment by SilverTalismen** [comment]
I more so mean in a emag way, l,ike emag and it drops from the highest point it has avaliable to the lowest very quickly or something?

**Comment by Neerti** [comment]
Kinda against the trend of 'everything needs to be emaggable', also this is just straight port (with a bugfix too) so that's a bit outside of scope.

**Comment by SilverTalismen** [comment]
Mostly a thought I had, Not saying it has to xD

**Comment by Anewbe** [comment]
Tested?

**Comment by Neerti** [comment]
Those pictures wouldn't be possible if it wasn't tested.

**Comment by PsiOmegaDelta** [comment]
Bug fix?

**Comment by Neerti** [comment]
Just the %ETA% thing.

**Pull request merged**
