### PR TITLE
makes scrubbers filter N2O

### PR DESCRIPTION
**Pull request by Belsima**
"ai, set all scrubbers to filter N2O"
"[src] has been moved to intelligence storage."

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Did... did it not already?

**Comment by Atermonera** [comment]
Not by default, no. It has the functionality to scrub anything, but was initially set to just phoron and co2

**Comment by Anewbe** [comment]
I feel like the brig makes a fairly specific use of siphons not auto-filtering N2O...

**Comment by Atermonera** [comment]
Has that system ever actually been used? Particularly by non-antags?

**Comment by SpadesNeil** [comment]
I've never seen the N2O in the brig used in all the time I've played SS13, except by people who just wanted to see what happens. The prisoner population isn't ever enough to justify it.

**Comment by Anewbe** [comment]
I've personally used it several times. It's helpful.

**Pull request closed without merging**
