### PR TITLE
Adds Overseer and Colony Director as an Alt Title to Station Admin

### PR DESCRIPTION
**Pull request by redstryker**

### CODE REVIEW

**Comment by SpadesNeil** [comment]
I want to see Station Administrator removed entirely _but_ this is a good compromise for the time being. :+1:

**Comment by redstryker** [comment]
@SpadesNeil , post that Email from NASA plz.

**Comment by SpadesNeil** [comment]
https://github.com/PolarisSS13/Polaris/issues/2601 intends to remove Station Administrator as an alt title because it's bad for reasons I explained in the meeting.

**Comment by SpadesNeil** [comment]
Edited comment because I posted the wrong link. It is corrected now. This PR should remain separate from my own changes. Colony Director should not be an alt title, but rather, the default.

**Comment by redstryker** [comment]
Closing because removal of 'Station Administrator' is apparently going to be a thing.

**Comment by Anewbe** [comment]
May as well add Overseer, though... Nothing wrong with it as far as I can tell.

**Comment by SpadesNeil** [comment]
You can totally still add Overseer if you want, yea. I don't see an issue with it. I just wanted that awful title of Station Administrator gone.

**Comment by redstryker** [comment]
Was going to do so in a different PR.
I'll actually get to that now.

**Pull request closed without merging**
