### PR TITLE
Remove Step_delay from all mech equipment.

### PR DESCRIPTION
**Pull request by lbnesquik**
My issue is that slowdown is one of the least fun things to have to deal with in this game. To my understanding, the goal of most mech PR's lately wa make mechs more fun, so this is pretty much in direct conflict.
The info on slowdown is also very much hidden with essentially zero way for someone to know that this particular thing causes slowdown.
And if the weapon is not balanced, i'd much rather we ask ourselves if that weapon really is unbalanced and take other actions to make it so.
Not to mention with how many novelty weapons we have, there is a LOT of them which are just underpowered and situational as hell. Like the incendiary weapons which don't really affect creatures, the main target of mechs in our servers.

### CODE REVIEW

**Comment by Mechoid** [comment]
Hokay. Do you have a recording of your testing done to show what you're classifying as too extreme of slowdown? As the PRs have been intended to be both fun and maintain a measure of balance. The problem is not specifically any one weapon or armor, it is combinations of such that can cause spikes of power that aren't intended. A Durand with a ranged armor booster, scattershot, AC 2, and energy relay, is generally strong enough to hold its own against a crew, or swarm of spiders.

**Comment by lbnesquik** [comment]
Any crew member equipped with gear that takes as much effort as a Durand to get can hold its own against spiders and crew, provided they don't blindly rush forward. 

If you can get a Durand, you can get a laser canon, self recharging laser, SABER, EMP shells from R&D. 
And from cargo, you can order combat shotguns, extra armor, ion rifle, phoron bores, extra lasers and so on. 
And they can also make EMP grenades from Chemistry/R&D with the uranium. 
And there is always the whole ion rifle at the armory. 

Given it is an HRP server, we can assume that people don't just randomly start shit for the heck of it every single shift. So i can't think of many scenarios where a Durand or Gygax ends up in a firefight with crew where no one has any counter.

**Comment by lbnesquik** [comment]
Ion weapons could be made easier to receive as a compromise.

**Comment by lbnesquik** [comment]
#7620

**Comment by DerBlitzkrieg** [comment]
Hell yea, make mechs not painful to play.

**Comment by Mechoid** [comment]
Exosuits have been given an encumbrance system, which has, seemingly, solved the problem. If there's further concerns after using it, feel free to re-open this or another PR.

**Pull request closed without merging**
