### PR TITLE
[DNM] Converts HAP to HRT

### PR DESCRIPTION
**Pull request by Mark9013100**
### Changes:
* Renames (Heavy) Asset Protection to Heavy Response Team.

* Replaces the current HAP headset with an ERT headset. The old radio HAP had was just a regular headset set to the ERT frequency.

* Changes the HAP rig's color scheme to green. Previous color scheme was deathsquad red, which just reeked from grimdark.

* Removes the Nuke disk/code from the HAP leader. There's no need for it since there is no nuke on the station.

* HRT Leaders/Operators spawn with ERT tactical jumpsuits. Previously, HAP spawned with NT officer uniforms/ugly bright green jumpsuits.

* The ERT channel can now be used by :o/.o instead of the old :h method.

### Fixes:
* Previously, energy swords tried to spawn on the suit slots, which never happened because only the suit control module spawn, they now spawn in the right pocket.

### Other:
* Modifies the ERT spawn description.

Imgur link to what the HRT suit looks like ingame: http://imgur.com/a/fmVHp

### CODE REVIEW

**Comment by Yoshax** [comment]
That green is pretty appalling. I don't see how red, as you say, "reeked from grimdark."

**Comment by Yoshax** [comment]
Or just use the red, it looks good. There isn't really another good color for it.

**Comment by Mark9013100** [comment]
I'd rather it be a color that wasn't used by any of the other RIGs, it should be a neutral color IMO.

**Comment by Yoshax** [comment]
Green isn't exactly neutral, it has a lot of medical connotations, and if you really wanna get into it, green is old-school Centcom/Command.

There isn't a good colour not used by others rigs, unless you make it pink or something stupid.

**Comment by Mark9013100** [comment]
Hm, good points, but still, I heavily want to refrain from making it red, since that'd basically make it ERT-S+.

**Comment by Anewbe** [comment]
I'm not sure why the name was changed, I like them being Asset Protection rather than Heavy Response Team. Asset Protection had a nice, Protect the people/things connotation to it, HRT makes it feel (to me) like an actual Deathsquad that just gets sent in after the first one dies.
Also the burgundy/maroon HAP suit always looked good to me, it's not the same Fresh-Blood Red as the ERT-S or Sec, and it immediately marks the HAP out as something different from what we've seen.
In the actual code, I'm not sure any member of the ERT actually spawns as /The Leader/, at least from what I've seen. Could be wrong, but it always seems to be a scramble to be anyone but the ERT-C. I think the spawn announcement is a bit of leftover.
Other than those little bits, yes please?

**Comment by Mark9013100** [comment]
I think, that Zuhayr said at one point said that Leader spawning for ERTs is bugged.

**Comment by Mark9013100** [comment]
Though, I might change it back to the old colors, but I atleast feel like the naming needs changed.

**Comment by Yoshax** [comment]
Both names majorly suck, imo. To be quite honest, the whole concept of something one step higher than an ERT sucks. If things get to the point where it's necessary, the antags deserve a win and not just another, harder level.

I do think that Asset Protection, with no leading 'heavy' or anything sounds better.

**Comment by Anewbe** [comment]
Ah, bugs. That would explain it.
Anyway, if the HAP/HRT is called the station's in dead shit, I've never seen one or heard of one on Polaris, doesn't really matter what you call them, they're the last chance for shit to get under control, so I wouldn't really expect them to sound friendly. I'd expect them not to be played as a Deathsquad, yes, but that's on the players and the admins who spawn them.

**Comment by Mark9013100** [comment]
Back on Bay, the only instances I saw HAP/AP being used were for deathsquading or that during that one bug when ERTs were uncapped and some admin said fuck it and spawned HAP rigs.

**Comment by Anewbe** [comment]
Only time I've seen them was a full, Nar'Nar summoning cult, the HAP got sent, they killed like 2 hellbeasts and then Noped the fuck out. They're not really common, and they're basically the ERT for when things are truly terrible. The concept as far as I can tell is that they're sent in to salvage whatever they can from an uncontrollable situation, not Deathsquad or ERT: Take 2.

**Comment by Zuhayr** [comment]
Death commandos were added as death commandos because when I implemented the system I wanted 1:1 feature replacement where possible. This thing with them being HAP is kinda a halfassed admin-pushed idea that was never actually intended or directly supported by the code. They were never meant to be related to the ERT.

**Comment by Mark9013100** [comment]
Well, guess I'll restore the old color scheme, I'll try and find a good balance with the naming of the RIG as well.

**Comment by Mark9013100** [comment]
Aw fuck. Conflicts. I'll throw this PR up again tomorrow.

**Comment by Zuhayr** [comment]
You and a few other people really need to learn how to force push over branches so you can just update a PR instead of making 20 of them for a single change.

**Comment by Mark9013100** [comment]
Better safe than sorry.

**Comment by Zuhayr** [comment]
That isn't remotely an excuse and 'better safe than sorry' makes no sense in this context. It's literally an overwrite. All you're doing is cluttering the closed PR list.

**Comment by Mark9013100** [comment]
Yeah, I got no clue what I'm doing. It'd just be easier for me to start over.

**Comment by Zuhayr** [comment]
Force-push to this branch instead of making a new branch. That is all you need to do.

**Pull request closed without merging**
