### PR TITLE
Removes redundant baton charging from sec borg.

### PR DESCRIPTION
**Pull request by Verkister**
The borg baton uses the borg's own cell.

### CODE REVIEW

**Comment by Arokha** [comment]
I thought I was looking at our codebase and added a review. XD... why can I even add a review here?

**Comment by Atermonera** [comment]
Anyone can review, but I think approving/requesting changes won't have an effect unless you're an official dev

**Comment by Arokha** [comment]
Ah-ha. Well, just ignore it. It won't let me dismiss it, sorry. Didn't mean to be creeping on your github or anything like I have the right to review things.

**Comment by Anewbe** [comment]
*shrug?
Review's a review, looked fine to me anyway.

**Pull request merged**
