### PR TITLE
Allow admins to see say/emote near their own body while aghosted

### PR DESCRIPTION
**Pull request by Arokha**
image

yw

### CODE REVIEW

**Comment by elgeonmb** [comment]
thank you

*brushes away single tear*

**Comment by Atermonera** [comment]
How does this look if you don't use chat tags?

**Comment by Arokha** [comment]
I have never turned off chat tags. It would probably say BODY: though. I see the create_chat_tag thing accepts a string and that string for OOC is `OOC:` and I put `BODY:` for this so I assume it would say `BODY:`

**Comment by Atermonera** [comment]
I don't personally use chat tags, just a matter of preference, so it's understandably a concern when I'm uncertain if particular formatting will look fucky with something developed for chat tags. Appreciate the test

**Pull request merged**
