### PR TITLE
General uniform updates.

### PR DESCRIPTION
**Pull request by Belsima**
Adds bathrobe and changes patient gown sprite. Both from Tau Ceti.
Old gown vs new.
images
Takes heed of a comment and puts the scrubs as children of eachother.
Replaces red cross medical band with a blue cross from Aurora.
Adds new cheongsams from Aurora.
Adds two new swimsuits from Vore.

### CODE REVIEW

**Comment by Belsima** [comment]
Ah. I fucked it up.

**Comment by Belsima** [comment]
Somewhat fixed, nevermind.

**Comment by Belsima** [comment]
keeping these open now I'm a mess

**Comment by Belsima** [comment]
DNM, by the way. I reverted the commit that fixed cheongsams and need to fix that when I get home.

**Comment by Belsima** [comment]
Cheongsams fixed, bathrobes now in bathroom.

**Comment by Anewbe** [comment]
Include all the pictures, please.

**Comment by Belsima** [comment]
https://github.com/PolarisSS13/Polaris/pull/3804

**Comment by Belsima** [comment]
image
that should be the rest?

**Comment by Anewbe** [comment]
Have you tested this?

**Comment by Belsima** [comment]
I have not. I'll compile it and test it now.

**Comment by Belsima** [comment]
Fixed scrubs appearing in loadout, accessory icon states from armbands to sweaters, inhands for clothing items, and the white swimsuit covering hands.

**Pull request merged**
