### PR TITLE
Lowers standard laser damage to 30

### PR DESCRIPTION
**Pull request by Anewbe**
300 per carbine is still nothing to laugh at, but now gunfights will take ... Roughly one shot longer?

### CODE REVIEW

**Comment by Wutnold124** [comment]
only one shot? for shame, anewbe, for shame

REAL laser nerfs just make them really powerful laserpointers that hurt your eyes

**Comment by Belsima** [comment]
Won't ballistics still easily destroy in gunfights, though?

**Comment by Neerti** [comment]
It may be desirable to adjust this too.

**Comment by Belsima** [comment]
I'm just seeing repeated nerfs to lasers; it feels like at some point we may have ballistics nearly objectively outclass them if that continues.

**Comment by Anewbe** [comment]
If we need to adjust ballistics at a later date we will.

**Comment by Magneld** [comment]
With some exceptions this should make the laser carbine about even with most ballistics when rate of fire and ammo capacity is taken into account. Thats the idea anyway we'll see where we end up.

**Comment by Nalarac** [comment]
I have some issues with this change:
1.) The x-ray laser gun will be objectively better (it does 25 damage but you get armor pen and 12 shots so it does 300 damage in the end)
2.) I feel like it's a pretty big nerf to the laser carbine that emagged/unlocked security cyborgs get
3.) (not "necessarily" an issue) It will now take 1 to 2 more shots from the carbine to kill a giant spider

**Comment by Woodratt** [comment]
Maybe try 35 instead?

**Comment by Anewbe** [comment]
Closing in favor of #4415

**Pull request closed without merging**
