### PR TITLE
Allow mechs to butcher things with their drill.

### PR DESCRIPTION
**Pull request by lbnesquik**
- Vague copy of a TG feature, made difficult by their different code. Still, it works.

### CODE REVIEW

**Comment by Atermonera** [comment]
DNM on #7494

**Comment by Atermonera** [comment]
Needs documentation: Updates to the robotics wiki necessary. Extended desc of the drill is probably helpful (read: preferred), even though I doubt most people will check that.

**Comment by lbnesquik** [comment]
Merge this one after the other, it seems easier to fix the conflict going that way

**Comment by lbnesquik** [comment]
@Atermonera

**Pull request merged**
