### PR TITLE
Hair can get caught in industrial equipment.

### PR DESCRIPTION
**Pull request by Belsima**
Given we literally just made Floor Length Braid invisible in the past as a deterrence, I figured a porting of https://github.com/Aurorastation/Aurora.3/pull/15 would be appreciated as a less memey deterrence. Tested and functional.

### CODE REVIEW

**Comment by Woodratt** [comment]
Not seeing the point.

**Comment by Iamgoofball** [comment]
prevents people from using weeb hair style

**Comment by Belsima** [comment]
We used to just make their hair invisible if they picked it, I thought this was a better solution than that.

**Comment by Anewbe** [comment]
I'm with Woodrat, not seeing the point.

**Comment by Belsima** [comment]
Just ported upon request, here. Close if you want.

**Pull request closed without merging**
