### PR TITLE
Ports the translator

### PR DESCRIPTION
**Pull request by Anewbe**
Ports https://github.com/VOREStation/VOREStation/pull/1148 and the improvements

Edit: Also threw in an earpiece version, and checks for blindness and deafness.

### CODE REVIEW

**Comment by nachomeep** [comment]
I want to point out the universal translator here is literally the most expensive loadout object in the game. Is this intentional?

**Comment by Anewbe** [comment]
Yes.

**Comment by nachomeep** [comment]
Is it possible to get the translating recorder into loadout as well? I'm playing a deaf character and it would just be useful, and don't want to throw up an entire PR for it.

**Comment by Anewbe** [comment]
That'd be better for another PR.

**Comment by nachomeep** [comment]
Alrighty.

**Comment by Anewbe** [comment]
@Arokha Oi, I did a thing.

**Comment by Arokha** [comment]
Oh I seeeee :0 What sprite does it use?

**Comment by Anewbe** [comment]
Made a new one out of some other headsets.

**Pull request merged**
