### PR TITLE
Saves janitors from getting stuck

### PR DESCRIPTION
**Pull request by Belsima**
Just makes their things climbable so that they don't need admins to get them out of maint.

### CODE REVIEW

**Comment by Anewbe** [comment]
code/game/objects/structures/janicart.dm:8:error: climable: undefined var

**Comment by Belsima** [comment]
I'm a dumbass.

**Comment by Kasuobes** [comment]
Consider Baystation12/Baystation12#16622 instead, though it should be made into an extension which I have no idea how to start with right now.

Also port of Baystation12/Baystation12#16075

**Comment by Techhead0** [comment]
It's not a port if he re-did the work himself independently.

**Comment by Kasuobes** [comment]
It's hard to tell what's a port and what isn't in single line changes.

**Comment by Belsima** [comment]
...yeah, it's a one-line change. Hardly a port. I just kept getting stuck in the tunnels.

**Pull request merged**
