### PR TITLE
Replaces the adminhelp sound.

### PR DESCRIPTION
**Pull request by Belsima**
The ahelp sound has, as it is, on more than one occasion come out loud through my speakers and scared the shit out of me. I figured this was less INTIMIDATING. It's a matter of opinion, so this could get merged or closed. Either way, I wanted to basically just suggest it.

### CODE REVIEW

**Comment by Cyantime** [comment]
_No_

**Comment by Anewbe** [comment]
I personally like it the way it is. Will query the staff.

**Comment by elgeonmb** [comment]
Belsima I didn't sweat my ass off apping for moderator to not make people shit their pants whenever I speak.

**Comment by Belsima** [comment]
terror itself arrives every time an admin pings me and goes 'oops wrong person'

**Comment by Anewbe** [comment]
How often does that happen? Because I don't see it basically ever.

**Comment by Belsima** [comment]
I've had it happen a couple times, it was mostly a joke regarding the BWOINK being loud and scary when you're playing at 3 AM and somehow barely awake.

**Comment by Andromeda-K22** [comment]
If i'm to be honest, i believe this should be the admin-PM/bwoink sound.
https://www.youtube.com/watch?v=Ag1o3koTLWM

**Comment by Anewbe** [comment]
I'm getting a solid No from basically every staff member I've talked to. Going to close this.

**Pull request closed without merging**
