### PR TITLE
Ports Bay Fixes for TTV Yield

### LINKED ISSUE #457: TTV Bombs inconsistent with Baycode
Not sure if this is the intent or not, but a 250-300 deg C ~1200 kPa phoron, 20 deg C 1013 oxygen gives a 0,1,something explosion on Polaris and a 3,7,14 on current Bay master.

### PR DESCRIPTION
**Pull request by Hubblenaut**
Fixes #457

### CODE REVIEW

**Comment by Zuhayr** [comment]
... I am confused, I tried to cherrypick these and eventually looked them up in the Polaris commit history and they were already present.

**Comment by Hubblenaut** [comment]
Perhaps the change got reverted on some merge. Would have to look up.

**Comment by zekesulastin** [comment]
I pulled the branch locally; works as expected

**Comment by Neerti** [comment]
:+1:

**Pull request merged**
