### PR TITLE
Attempts to port bay's travis update attempts

### PR DESCRIPTION
**Pull request by Kelenius**
See https://github.com/Baystation12/Baystation12/pull/10096
https://github.com/Baystation12/Baystation12/pull/10231
https://github.com/Baystation12/Baystation12/pull/10421
https://github.com/Baystation12/Baystation12/pull/11642
https://github.com/Baystation12/Baystation12/pull/12218
~~Still not getting it fully, DNM until I'm confident enough~~
~~DNM until I put everything I want to in~~
Okay, seems to be working fine.

### CODE REVIEW

**Comment by Kelenius** [comment]
That's all for now.

**Comment by PsiOmegaDelta** [comment]
The tag matcher has been updated on Bay to also report the line numbers of unmatched tags.

**Comment by Kelenius** [comment]
After this is merged, I'll look into porting unit tests.

**Comment by Kelenius** [comment]
Will resolve after approval.

**Comment by Datraen** [comment]
I'm not noticing anything missing that we don't already have, and considering that Bay is currently running this, :+1:.

**Comment by Kelenius** [comment]
Resolved.

**Comment by Kelenius** [comment]
Ping.

**Pull request merged**
