### PR TITLE
Lung damage QOL

### PR DESCRIPTION
**Pull request by Anewbe**
You shouldn't get popped lungs from being choked or drowning (I don't think), and brain damage from OxyLoss only starts after having 20 Oxy.

### CODE REVIEW

**Comment by Yoshax** [comment]
You really should put the Brain Damage stuff outside of the failed breath statement. Means there's no Brain Damage from severe bloodloss or anything of the sort, which should probably happen. Would mean bad heart damage would cause it as well, like it probably should.

**Comment by Anewbe** [comment]
Good point.

**Comment by Anewbe** [comment]
Moved it into handle_regular_status_updates(), don't know if there's a specifically better one.

**Comment by Yoshax** [comment]
That seems fine. :+1:

**Pull request merged**
