### PR TITLE
Fuzzy Cuffs

### PR DESCRIPTION
**Pull request by redstryker**
Adds fuzzy cuffs, a child of handcuffs.

https://puu.sh/qXUUK/c54c6e3516.png

### CODE REVIEW

**Comment by Iamgoofball** [comment]
:-1: fetish content

**Comment by SpadesNeil** [comment]
y tho

**Comment by SkowronX** [comment]
For merc party boats of questionable content.

**Comment by redstryker** [comment]
Y'all do realize that fuzzy cuffs were already an item, right?  They were a child of cable ties.  I just provided a nicer sprite.

**Comment by SpadesNeil** [comment]
>Y'all do realize that fuzzy cuffs were already an item, right? They were a child of cable ties. I just provided a nicer sprite. 

capture

No they weren't.

**Comment by redstryker** [comment]
They must have been since removed, because I am positive they were mapped in.  Regardless, it is Dev Staff's decision.

**Comment by Anewbe** [comment]
There used to be an item called Fuzzy Cuffs somewhere in maint.
I have no opinion on this PR. If someone else wishes to close this, fine, otherwise I don't see a reason not to merge it.

**Comment by Yoshax** [comment]
There is. Locker room. Behind a Wall there's a chair, and a cable cuffs renamed to fuzzy cuffs.

**Comment by SpadesNeil** [comment]
Oh well that explains the confusion.

**Comment by Iamgoofball** [comment]
a shitty rename a mapper snuck in should not be a reason to add fetish content to the game

**Comment by SpadesNeil** [comment]
Is it ironic that the guy who runs a fetish server (me) wants to see these removed from the normal server?

**Comment by Hubblenaut** [comment]
People are making more of a fuss about this than it is. It's a lewd joke, not the harbinger of ERP.

**Comment by Iamgoofball** [comment]
slippery slope @Hubblenaut

**Comment by Hubblenaut** [comment]
This is only an issue if people make it one. Just let staff decide on it.

**Comment by SpadesNeil** [comment]
>People are making more of a fuss about this than it is. It's a lewd joke, not the harbinger of ERP.

I completely agree, but I still say the silly fuzzy cuffs should be removed. It's not worth the trouble of adding ACTUAL fuzzy handcuffs, while at the same time, the renamed cable cuffs on map look silly.

**Comment by SpadesNeil** [comment]
Neerti has forsaken us...

Oh well. These will end up in ready use on Vorestation anyway. ( ͡° ͜ʖ ͡°)

**Pull request merged**
