### PR TITLE
AI Language tweaks

### PR DESCRIPTION
**Pull request by Anewbe**
Adds Siik'Maas and Schechi to AI language list

### CODE REVIEW

**Comment by Neerti** [comment]
I'm not sure if the Taj language you're adding is still used in lore, but I could be wrong.

**Comment by Anewbe** [comment]
It's still in the code in some form or other, is why I added it.

**Comment by Zuhayr** [comment]
You should be using macros for this. See https://github.com/PolarisSS13/Polaris/blob/4456f77d751d3f19bb67c04421a8a602191fad9c/code/__defines/species_languages.dm

Additionally Siik'Maas is the wrong language. Taj speak Tajr.

**Comment by Nerezza** [comment]
It's true, however our lore page still claims Siik'Maas is the main language and Siik'Tajr is the special kitty sign language. Idk why we didn't make the spoken language, Siik'Maas, into the language used in Polaris.

**Pull request merged**
