### PR TITLE
Sleek Communicator

### PR DESCRIPTION
**Pull request by Greenjoe12345**
Ports the communicator sprites from World Server as a new communicator type
image

### CODE REVIEW

**Comment by Cerebulon** [comment]
Not sure about this. Those are just smartphones.

**Comment by Spookerton** [comment]
I'm certainly not *against* just smartphones myself. Code approval since it's tiny, adding talk tag since there's a meeting today. @Cerebulon

**Review by Spookerton — APPROVED** [review]

**Comment by Atermonera** [comment]
Staff input: Paging @Sypsoti for how well this fits our existing aesthetic.

**Comment by Spookerton** [comment]
quoth sippy cup, "i genuinely do not see an issue if they're addition"

**Review by Sypsoti — APPROVED** [review]
Why wouldn't we have smartphones? Approved.

**Comment by Spookerton** [comment]
ingo

**Pull request merged**
