### PR TITLE
Map Fixes

### PR DESCRIPTION
**Pull request by zekesulastin**
Currently Fixes:
- #7741 (Random engine selection results in doubled up doors/windows)
- Fixes miswired APC in engine_tesla submap (can't find issue # for that)
- R&D desk blocked by extinguisher (can't find issue # for that) - moved to corridor

### CODE REVIEW

**Comment by zekesulastin** [comment]
Never mind I'm dumb and panicked and didn't look closely at the diff - apparently literally everything in engine_tesla.dm was very aggressively split into separate lines, so when I edited the file and saved it the condensing of said newlines resulted in the large diff.

**Comment by Novacat** [comment]
It is supposed to be aggressively split into seperate lines, basically what you are supposed to do is run dmm2tgm in mapmerge2. This is what we are referring to when asking for things to be mapmerged.

**Comment by zekesulastin** [comment]
> Edit: Wait. This is Polaris. Why was a polaris mapfile converted to tgm?

The submaps for not-the-supermatter were ported that way by Rykka a couple of months ago.

**Comment by zekesulastin** [comment]
I'm just going to start putting more southern_cross-1.dmm fixes in here until this gets merged or I'm told to stop %)

**Comment by Shadow-Quill** [comment]
#7741 was not closed by this.
As a note, to have issues auto-close, they *must* be preceeded by one of the closing keywords (ie: Fixes #xxxx, Closes #xxxx, & whatever else)

**Pull request merged**
