### PR TITLE
Removes popups from logging in.

### PR DESCRIPTION
**Pull request by Neerti**
Removes VChat failing to start popup if it was due to player pref setting.
News popup is now opt-in instead of always happening.

### CODE REVIEW

**Comment by Neerti** [comment]
Planning to make the button to look at the ingame news get bold if there is new news, to be consistent with other things like the changelog button or the admin news button.

**Comment by MistakeNot4892** [comment]
Obviated by #8209

**Comment by MistakeNot4892** [comment]
Given that #8209 is merged, is this still desired? If so, are you likely to get around to reviving/finishing the PR?

**Comment by MistakeNot4892** [comment]
Going ahead and closing this given the lack of response. Feel free to reopen at a future date.

**Pull request closed without merging**
