### PR TITLE
Adds code to allow shoes to influence speed on snow or in water

### PR DESCRIPTION
**Pull request by Anewbe**
There's probably a better way to do this, but I'm not sure what it is.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Does that mean certain shoes are better in the snow then others?

**Comment by Anewbe** [comment]
Not yet, but eventually.

**Comment by SilverTalismen** [comment]
Aah, understood!

**Comment by SpadesNeil** [comment]
should totally add snow shoes

**Comment by Anewbe** [comment]
Actual Note to Self: Check for turf before checking for shoes.

**Comment by Belsima** [comment]
are you checking for turfs yet

**Pull request closed without merging**
