### PR TITLE
NO_POISON or IS_PLANT now grant hallucination immunity

### PR DESCRIPTION
**Pull request by Yoshax**
Also stops hallucinations from preventing passing out from halloss.

### CODE REVIEW

**Comment by Anewbe** [comment]
Not certain how this stops the halloss thing, but my bigger question is: What is the reasoning behind this change?

**Comment by Techhead0** [comment]
The halloss thing is a leftover message from when I made this commit on Bay. It doesn't apply here.

**Comment by Yoshax** [comment]
Woops, thought I had removed the holdover message, guess not. Was already fixed here/never like that.

This change is quality of life, and sensible. Mostly for Diona. They can't wear mesons, or anything of the sort that stop hallucinations from the Supermatter, and hallucinate. They don't take radiation damage, so don't need the radiation suit, but can't protect against the hallucinations that really make no sense affecting them in the first place. They live and space, around stars and all that fun, they really shouldn't be experiencing hallucinations from the Supermatter, nor at all. It's very unlikely that a species so different and incomprehensible experiences hallucinations at all, never mind the same as humans.l

**Comment by Spookerton** [comment]
Sounds fine to me.
👍

**Pull request merged**
