### PR TITLE
Removes Shellguard Noble cyborg sprites.

### PR DESCRIPTION
**Pull request by TravellingMerchant**
This PR removes my Shellguard Noble cyborg sprites.
I respectfully ask that my shellguard sprite work is removed from the polaris codebase. If any other of my non-Shellguard sprites have been ported, that's not an issue. 

I'm not sure why they were also renammed to cupcake. That's a little odd.

### CODE REVIEW

**Comment by optimumtact** [comment]
Do you understand the concept of opensource licensing?

**Comment by ThatLing** [comment]
Do you understand the concept of a friendly request?

**Comment by optimumtact** [comment]
This is an unfriendly request

**Comment by TravellingMerchant** [comment]
I had spoken to Anewbe before hand, he told me to make the PR.

It was a polite conversation and as far as I'm aware there were no issues.

**Comment by SpadesNeil** [comment]
Then it's up to the staff. Knowing Polaris, I don't think they have any reason to decline. It's other code bases who might have something else to say about it.

But that's their problem, not Polaris.

**Comment by Anewbe** [comment]
I'm going to lock this until such time as it is discussed by the Staff, who will make the final decision.

As mentioned, the author was told to make this PR, if they felt the issue was pressing, which they have done. There's no reason to flame them for that. They're doing exactly what they were told, working within our rules, in a manner that is their best option based on the fact that the law does not in fact require us to remove what they see as their intellectual property.

So let's all be excellent to each other.

**Comment by Atermonera** [comment]
Staff discussion is in favor of honoring this request.

**Pull request merged**
