### PR TITLE
Modifiers visitor rooms layout

### PR DESCRIPTION
**Pull request by Yoshax**
- 1st row of rooms are still single rooms
- 2nd row of rooms are double rooms with 2 single beds
- 3rd row of rooms are now double rooms with a double bed

See screenshot: https://i.gyazo.com/5dfa38920f47b2bbf5036fc1965486a5.png

### CODE REVIEW

**Comment by Datraen** [comment]
:+1:

**Comment by Neerti** [comment]
The right-most room with the double bed seems to be missing a bedsheet.

**Comment by Yoshax** [comment]
Does now.

**Comment by Neerti** [comment]
:+1:

**Comment by Datraen** [comment]
Sad that I missed the missing bedsheet.

**Pull request merged**
