### PR TITLE
Fixes some punctuation

### PR DESCRIPTION
**Pull request by Mark9013100**

### CODE REVIEW

**Comment by Datraen** [comment]
Not sure why you're adding "Yum," to the end of the description of the virus food dispenser, but otherwise :+1:

**Comment by Kelenius** [comment]
You just had to make something that would conflict with #1410, did you? >w>

**Comment by Datraen** [comment]
That's relevant, DNM pending #1410 merge/otherwise.

**Comment by Mark9013100** [comment]
Oh, didn't know, sorry Kelenius. I'll just wait for that to come through then.

**Comment by Kelenius** [comment]
Doesn't matter now.

**Pull request merged**
