### PR TITLE
[READY] Fixes chemistry/nanoui

### PR DESCRIPTION
**Pull request by kevinz000**
Chemistry processes instantly again
Nanoui sends stuff even after client connect

WIP because I need to test if NanoUI is still lagging/not ticking fast enough, and because I want to get rid of chemistry processing entirely (to make ALL reactions happen instantly, including subreactions from the first reaction's products, like on TGchemistry, unless people want it to be limited to 5 reactions per tick per container for whatever reason.)

### CODE REVIEW

**Comment by kevinz000** [comment]
testing today

**Comment by Novacat** [comment]
This fix currently runtimes:
[2019-04-08T15:30:58] Runtime in Chemistry-Holder.dm,95: Cannot execute null.can happen().
  proc name: handle reactions (/datum/reagents/proc/handle_reactions)

**Comment by kevinz000** [comment]
YIKES

**Comment by Novacat** [comment]
https://github.com/VOREStation/VOREStation/pull/5006

This might be helpful here.

**Comment by Novacat** [comment]
Ran some additional tests, NanoUI still has a bit of weirdness in loading templates.

**Comment by Atermonera** [comment]
Changelog aside, this no longer has the mentioned runtimes?

**Comment by Novacat** [comment]
It does, but the fixes for this PR (including runtimes) can be found in the two above PRs I linked.

**Comment by Atermonera** [comment]
@kevinz000

**Comment by Atermonera** [comment]
#6151 is merged

**Pull request closed without merging**
