### PR TITLE
Increases cell charge loss on mecha halloss hit

### PR DESCRIPTION
**Pull request by Hubblenaut**
Increases charge loss from (5 \* projectile_halloss) to (15 \* projectile_halloss).

Hitting a mecha ten times with an energy gun on stun would therefore result in a charge loss of 15\*40\*10=6000 points.
For Reference:
Normal Power Cell: 5,000
High-Capacity Power Cell: 10,000

Should make using tasers on mechs a way more viable option than it was before.

### CODE REVIEW

**Comment by Mark9013100** [comment]
Face the wrath of the golden bolt.

**Comment by Spookerton** [comment]
Using tasers on mechs should never BE a viable option. Close posthaste.

**Comment by zaredman** [comment]
>Using tasers on mechs should never BE a viable option. Close posthaste.

Exactly this.

**Comment by EmperorJon** [comment]
Now that I have been made aware of this, I very much do not like. Will note for review etc.

**Comment by Hubblenaut** [comment]
This has been a thing for .. ages

**Comment by Anewbe** [comment]
I actually wish Ions did something like this, instead of just nuking the mech,

**Comment by Spookerton** [comment]
> This has been a thing for ages. Why has every mech to be shot to crap with lethals and ions..?
Because tazing mechs is fucking stupid.

**Comment by Hubblenaut** [comment]
There should probably be another way to disable mechs without fully destroying them then. Maybe the ion rifle, as suggested above. It's definitely ridiculous that you need to go lethal and completely demolish a mech, even if it's just to get somebody out of a Ripley.

**Comment by Anewbe** [comment]
Didn't the exosuit trackers/lock consoles disappear, too?

**Comment by Dragor** [comment]
...So essentially you can take down a durand death mech with a few officers and tasers??

That's hilariously dumb. How do tasers even manage to drain the cell? How does this even make sense?

**Comment by Hubblenaut** [comment]
Ask the person that initially coded it, I guess.

**Comment by Kelenius** [comment]
On one hand, 15 shots is a lot. On the other hand, mech consumes power on its own, and tasers ignore armor.

**Comment by Hubblenaut** [comment]
I'll close this for now, as it seems to go nowhere.

**Pull request closed without merging**
