### PR TITLE
New Unathi Sprite

### PR DESCRIPTION
**Pull request by Anewbe**
Minor tweak, courtesy of SereneMelody
lizard sprites

### CODE REVIEW

**Comment by SpadesNeil** [comment]
These look good. Though I am convinced that the female Unathi should have boobs. Right now I can't tell them apart.

**Comment by serenemelody** [comment]
I'm gonna be honest, I forgot which is which.

We should just add boobs to all the female sprites.

**Comment by SpadesNeil** [comment]
Now you're talking. :D

**Comment by serenemelody** [comment]
Including Diona.


_Especially Diona._

**Comment by Hubblenaut** [comment]
Halp Serene has gone mad :c

**Comment by SpadesNeil** [comment]
But Diona reproduce asexually.

**Comment by Techhead0** [comment]
>But Diona reproduce asexually.

If robots can get boobs, why not Diona?

**Comment by Hubblenaut** [comment]
If females can get boobs, why not males?

**Comment by SpadesNeil** [comment]
>If robots can get boobs, why not Diona?

Obviously you do not understand the importance of the sexbot industry.

**Pull request merged**
