### PR TITLE
Drone permits can now be worn

### PR DESCRIPTION
**Pull request by Anewbe**
- Belt or ear slots. Ear slots because they're fairly rarely used.
- EDIT: Now works as an accessory

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Why not make them something you can clip to your uniform like a security holobadge?

**Comment by Anewbe** [comment]
Pretty sure I'd have to repath them for that to work. Might look into it tomorrow.

**Comment by SilverTalismen** [comment]
Cool! ^^
It would be way more useful to be able to just clip them onto my uniform so I don't need to take up space in a bag or something.

**Comment by Anewbe** [comment]
That was easier than expected.

**Comment by Belsima** [comment]
Do they fit in the ID slot?

**Comment by Anewbe** [comment]
No? That's where one's access lives.

**Comment by Anewbe** [comment]
Yeah, that.

**Comment by Belsima** [comment]
Can't hurt to let you store it in the ID slot, can it?

**Comment by Anewbe** [comment]
I'm gonna say yes, it can. One's a governmental thing, the other is a corporate thing, and unless you're an Assistant you won't be able to access anything.

**Pull request merged**
