### PR TITLE
5 POI's

### PR DESCRIPTION
**Pull request by Kazzc**
As the tittle, adds 5 additional POI's intended for the plains.
Nothing valuable or useful should be found on any of these, maybe a bit of story and curiosity for anyone that wants to explore these.
Or better... maybe explore the remains and restore them to its former glory and take ownership to any abandoned home.

### CODE REVIEW

**Comment by Kazzc** [comment]
Some screenshots.
image
image
image
image
image

**Comment by Kazzc** [comment]
uuhhh... unsure what I did wrong here. :x

**Comment by Kazzc** [comment]
I have no idea why the large abandoned home is making Travis angy. @.-.@

**Comment by Neerti** [comment]
Travis says
```
loading lonehome.dmm
maps/submaps/surface_submaps/plains/lonehome.dmm:13:error: bad type or variable: h_master
maps/submaps/surface_submaps/plains/lonehome.dmm:13:error: expected )
Failed to load map file /home/travis/build/PolarisSS13/Polaris/maps/submaps/surface_submaps/plains/lonehome.dmm.
```

**Comment by Kazzc** [comment]
I edited some papers by slapping info to add a bit of 'story' ?
Unsure if that caused it?
I manually edited these POI's with Polaris branch and tested them in a test server, didn't see anything wrong or out of the ordinary.
The only thing this POI has over the others is paper sheets with values changed on `name` and `info` so the paper says a story, that I tested in a test server and shows properly.

Maybe I am just talking nonsense cause I don't understand what 'h_master' means or stands for. @.-.@

**Comment by Meghan-Rossi** [comment]
h_master is the variable that some of the windows and buttons in lonehome.dmm are set to use for their id.  It doesn't seem to be defined anywhere.  Maybe it should be the string "h_master" instead?  (with the quotes).  Same for h-living and h_kitchen.

**Comment by Neerti** [comment]
Yeah, this looks like a case of accidentally forgetting to wrap the ids in quotes to make them strings, which fortunately is an easy fix.

**Comment by Kazzc** [comment]
OOOoohhh, That's what it is.

**Comment by Kazzc** [comment]
Or wait... was it that?...
I didn't wrap them with quotes, I changed `h_master` to `h-master`

**Comment by Kazzc** [comment]
whats funny is that I tested the windows, they wont work without power so you need to power the house first before you get to flick and tint the windows. Since all checks are green I guess this PR is good. :+1:

**Pull request merged**
