### PR TITLE
more gammers

### PR DESCRIPTION
**Pull request by Belsima**
i am on a crusade to fix the typos plaguing this game

### CODE REVIEW

**Comment by Anewbe** [comment]
You also appear to be on a crusade to make as many commits as possible, holy numbers Batman.

**Comment by Belsima** [comment]
@anewbe I don't know how to use the Web editor please help

**Comment by Anewbe** [comment]
I don't either?

**Comment by Atermonera** [comment]
Have you considered... y'know, actually using git? I find the web editor's really only useful for edits to PRs following reviews or to fix conflicts

**Comment by elgeonmb** [comment]
not all of us can be wizard-sages ater

**Comment by Atermonera** [comment]
Our github wiki (Found [here](https://github.com/PolarisSS13/Polaris/wiki) for those that don't see the tab to the right of code, issues, pr's, etc) has two very effective guides on how to use git. It doesn't cover some of the tricksier stuff, but you can at least make it workable

**Comment by Belsima** [comment]
@Atermonera im doing this on my phone

**Comment by Atermonera** [comment]
pls

**Comment by Belsima** [comment]
im serious.

**Pull request merged**
