### PR TITLE
Replaces intelliCards with intelliCores.

### PR DESCRIPTION
**Pull request by PrismaticGynoid**
Sprites replaced with a black box that could conceivably contain a brain, while obscuring the details. Complete with screen and convenient handle.
Certain text modified to make sense for MMIs/posibrains, instead of just drone brains (e.g. downloaded → transferred).
Description added to the new intelliCores. Made into normal-sized item, similar to MMIs/posibrains.

This is an alternative to either changing lore to allow for brain uploading, or changing code to allow for choosing multiple AI brain types.
intellicores

### CODE REVIEW

**Comment by Mechoid** [comment]
This idea saved me a very large amount of frustration, the lore-team probably a lot of headaches dealing with previously mentioned Me, and probably Anewbe's sanity. For going through AI code to make sure whatever proposed change worked because _Synthcode_.

**Comment by Anewbe** [comment]
Mind leaving the old sprites in the files, just in case? Otherwise looks fine to me.

**Comment by PrismaticGynoid** [comment]
The old intelliCard sprites are still present in pda_old.dmi for that reason - I'm fairly sure the card sprites there aren't actually used for anything ingame, so I left those ones unchanged.

**Comment by Anewbe** [comment]
Ah, alright.

**Comment by elgeonmb** [comment]
T_T

Thank you, so much.

**Comment by Anewbe** [comment]
This ready to go, Prismatic?

**Comment by PrismaticGynoid** [comment]
Pretty sure, yes. Everything seems fine from testing.

**Pull request merged**
