### PR TITLE
Adds maid bonnet, more hair pins, and adds maid uniform to locker.

### PR DESCRIPTION
**Pull request by Belsima**
Fixed https://github.com/PolarisSS13/Polaris/pull/3876.

Closes https://github.com/PolarisSS13/Polaris/issues/4372.

Ported hair pins and maid bonnets from Eros.

### CODE REVIEW

**Comment by SubberTheFabulous** [comment]
Maid bonnets, round two.

**Comment by Anewbe** [comment]
- [ ] Did you compile, test, and run this?
- [ ] Did you run the map merger before and after mapping?

**Comment by Belsima** [comment]
Yes, and yes.

**Comment by mistyLuminescence** [comment]
"+2072, -2002" tortoisegit >> git desktop

**Comment by Belsima** [comment]
youre not wrong

**Comment by Anewbe** [comment]
I'm really uncomfortable with that massive map change. Any chance you can redo that specific part?

**Comment by Belsima** [comment]
I've tried the map merger multiple times, it just seems to piss itself on my PC. Not certain I can. Though the change is just fixing items so it compiles.

**Comment by Belsima** [comment]
@Anewbe Should I just close this? I still have yet to find a fix for the map merger and it doesn't compile if I don't fix the map.

**Comment by Belsima** [comment]
@Anewbe @Neerti @Mechoid ?

Should I close this? Map merger still not fixed.

**Comment by Anewbe** [comment]
Eh, if everything is terrible we'll just revert.

**Comment by Belsima** [comment]
merci

**Pull request merged**
