### PR TITLE
Deconstructing a Technomancer Core now does Bad Things

### PR DESCRIPTION
**Pull request by Anewbe**
Currently either makes a Supermatter explosion or a smallish Tesla ball, directly on the deconstructor after a five second delay. I couldn't think of anything else suitable to have happen, so until then it's a two item switch. Sorry 'bout that.

### CODE REVIEW

**Comment by zekesulastin** [comment]
Can we like not wipe out that entire side of the station (including medical!) because someone used R&D?  What in the hell.

**Comment by elgeonmb** [comment]
I mean if you permafuck an antag (potentially the _only_ antag) by putting their Antag Box in your Science Box and you don't like, at least take the measure of putting it in a Science Box that's not right next to medical that's kind of on you

**Comment by zekesulastin** [comment]
I mean it's not like you can't just get rid of the tech levels or something to make it non deconstructable like half the other goodies in the game, no, you have to fuck everyone because "muh antags".

**Comment by elgeonmb** [comment]
man why not make the engine just vaporize engineers as a penalty for not maintaining it correctly, why does it have to fuck cargo and anyone who enjoys having power too

**Comment by drexample** [comment]
Uhh... You can deny the antag by just throwing the core into space. 
I think there needs to be a hard bomb-defusing level way to disable the core before deconstruction.

**Comment by zekesulastin** [comment]
If you're seriously going to compare the entire engine setup and warning process to this, elgeon, then I really don't know what to say to you.

**Comment by Anewbe** [comment]
If a better solution can be found, this will be discarded.

**Comment by Anewbe** [comment]
Closing this, we'll be seeking a solution that prevents Core deconstruction, rather than being horribly destructive.

**Pull request closed without merging**
