### PR TITLE
Replaces xeno sprites with cooler and darker ones.

### PR DESCRIPTION
**Pull request by Belsima**
Taken from /tg/ and Tau Ceti, edited by me. image

Old icons for reference: image

### CODE REVIEW

**Comment by Wutnold124** [comment]
ok but like

what the fr*ck is alienother supposed to be
i only see a technicolor vox

**Comment by Belsima** [comment]
i could not tell you

**Comment by Wutnold124** [comment]
pls

**Comment by Cyantime** [comment]
But why?

**Comment by Iamgoofball** [comment]
@Wutnold124 we're all adults we can say fuck

@WJohn

**Comment by Belsima** [comment]
ban goofball this profanity is not ok

**Comment by Belsima** [comment]
@Cyantime Because black aliens better serve a sense of darkness and horror, compared to the weird... bright purple??? why is it purple actually ive always wondered this does anyone have an answer as to its origin

**Comment by Cyantime** [comment]
Like many strange ss13 choices, the purple weeds are straight out of r4407.
I don't think making all the alien weeds and resins black makes them spookier, just more boring. The brighter weeds are like some sort of war of the worlds stuff, making them black just seems generic and going for some sort of grimdark realism whatever that doesn't really belong in ss13.

**Comment by Belsima** [comment]
I believe we've been taking more and more of a step from the WACKY PURPLE THINGERS like Space Carp in recent times, instead adding more reasonable features, so I figured darker night creatures made sense. Xenos are even adminabuse only as of now from what I can tell, and when they were ported the discussion was around horror events, so I figured Dark Horror Creatures worked better than Those Guys Who Make The Floor Bright Purple.

**Comment by chaoko99** [comment]
alienother is used in hallucinations.

**Comment by Anewbe** [comment]
@Belsima You've tested this right?

**Comment by Belsima** [comment]
I've tested it on Aurora code and had it work, at least; I'll compile it and test it on Polaris soon.

**Comment by Belsima** [comment]
image the sprites are happy boys

**Comment by Anewbe** [comment]
@Belsima This was discussed at the staff meeting. The following points were made:
- We would like the the weed, wall, nest, and node sprites.
- We would like the infected sprites.
- The alien sprites themselves are too dark, and we would rather not lose the detail from the purplish ones.

**Comment by Belsima** [comment]
Alright. Regarding the queen, would you prefer image or /tg/'s image?

**Comment by Belsima** [comment]
Reverted to purple ayys.

**Comment by Anewbe** [comment]
Mind updating the image(s)?

**Comment by Belsima** [comment]
image

**Comment by Anewbe** [comment]
Worse comes to worst we can revert. Merging.

**Pull request merged**
