### PR TITLE
Fixes phoron sprites.

### PR DESCRIPTION
**Pull request by nachomeep**
Adds back sprite to the vox one. Fixes assemblies.

### CODE REVIEW

**Comment by nachomeep** [comment]
oh fuck

**Comment by Arokha** [comment]
Fixed. Thanks for nothing though, git.

**Comment by nachomeep** [comment]
how the fuck do I fix those conflicts

**Comment by Arokha** [comment]
I did it!

**Comment by nachomeep** [comment]
Oh, thanks! I don't even get what the conflict was, the files were the same?

**Comment by nachomeep** [comment]
Oh, wait. The 'fix' got rid of the deletion of a line that was... the entire point of this PR? I don't get it.

**Comment by nachomeep** [comment]
I've also gone ahead and made the purple phoron canister sprites have hazard lines, because why not? Still unused.

**Pull request merged**
