### PR TITLE
Allows Robotics To Print Drone Brains

### PR DESCRIPTION
**Pull request by ParadoxSpace**
it's about time

### CODE REVIEW

**Comment by Yoshax** [comment]
Does that work? It seems to me from a cursory glance that the brain will never get a client.

**Comment by ParadoxSpace** [comment]
nh you're right
IIRC drone brains couldn't be manually activated the last time I checked??

**Comment by Yoshax** [comment]
You could make it work.

**Comment by Zuhayr** [comment]
What is the point of positronic brains if the software brains, which were explicitly intended to remove the 'pick it up and put it in a new chassis' aspect of robots, are just going to become posibrains mk2? I don't get why people have been steadily adding more functionality to them when they were intended to be a one-shot variant for the robot equivalent of playing a DNC crewmember.

**Comment by Kelenius** [comment]
>Available both in R&D and robotics
>5 minutes of research
>Only metal and glass

Are you fucking high

**Comment by ParadoxSpace** [comment]
considering that a software brain is less advanced than a pAI, and a pAI only requires metal and glass

**Pull request closed without merging**
