### PR TITLE
Fixes MCs not being rechargable

### PR DESCRIPTION
**Pull request by Heroman3003**
Allows recharging laptops, tablets and their batteries in the rechargers properly

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Wat.
`code/modules/mob/living/inventory.dm:148:error: =: conflicts with previous definition
polaris.dmb - 1 error, 0 warnings (2/22/20 1:37 am)
`

**Comment by Heroman3003** [comment]
Whatever that error is, it doesn't appear when I compile it locally.

**Comment by Atermonera** [comment]
Travis is kinda senile, frequently needs to be reminded what the heck its actually supposed to be doing.

**Comment by Neerti** [comment]
Might need to make Travis use a more recent copy of BYOND.

**Pull request merged**
