### PR TITLE
invents catgirls

### PR DESCRIPTION
**Pull request by listerla**
almach wins the war and institutes mandatory catgirls

i no-joke havent slept in literally like 2 days so this is the funniest shit in the world to me rn. im sorry.

### CODE REVIEW

**Comment by Schnayy** [comment]
... why.

**Comment by listerla** [comment]
> i no-joke havent slept in literally like 2 days so this is the funniest shit in the world to me rn. im sorry.

**Comment by Cerebulon** [comment]
If we were going to do this it wouldn't be like this

**Comment by listerla** [comment]
this was me entertaining myself
i oughtnt shitpost here sorry

**Pull request closed without merging**
