### PR TITLE
Printable Mops

### PR DESCRIPTION
**Pull request by hex37**
Adds mops to the list of things that the autolathe can print. This allows for the easy construction of ED-CLN Cleaning Robot in robotics.

### CODE REVIEW

**Comment by Cerebulon** [comment]
I think the need to ask janitorial or cargo for this specifically to make the "high end fancy nonsense" cleanbot is fine, honestly?

**Comment by Atermonera** [comment]
... But why though?
It does also make it really easy for a griefer to get access to a mop, which is probably one of the best ways to wet a large floor area. I'm inclined to agree with Cere, but I'll give it some more thought.

**Comment by hex37** [comment]
> ... But why though? It does also make it really easy for a griefer to get access to a mop, which is probably one of the best ways to wet a large floor area. I'm inclined to agree with Cere, but I'll give it some more thought.

No real reason other than the one I gave. If that isn't enough to justify it, that is fine.

**Comment by Atermonera** [comment]
Oh this has been up 3 weeks, huh.
I've discussed this with a few other members of staff, and they were also generally hesitant. There's not really a shortage of ways to get mops if you go and talk to people, designing around lowpop is not my priority, and the ED-CLN is kinda high-end.

PR is denied.

**Pull request closed without merging**
