### PR TITLE
Ports Baystation12 newest item pickup animations. Fancy!

### PR DESCRIPTION
**Pull request by drexample**
Demonstration video: https://streamable.com/z2evr

Original PR by thasc: https://github.com/Baystation12/Baystation12/pull/21092

The animation is a little faster than in video (very little, almost unnoticeably)

### CODE REVIEW

**Comment by Arokha** [comment]
So fancy!

**Comment by nerdass** [comment]
balance issue with traitor objectives. motion draws attention, this directly nerfs being able to sneakily pocket something off a table, because the object moving on the screen will make it a lot easier to notice.

**Comment by Anewbe** [comment]
I don't see that as a serious concern. If you're pocketing something worth stealing and there are other people watching, there's pretty good chance you'll get called on it, anyway.

**Comment by Atermonera** [comment]
It's also a very short animation. If there's only one thing on the table then it's considerably harder to pocket it, but if there's a ton of stuff in a pile, so long as the thing you're swiping isn't on top (Which can be done, move-to-top is a verb), there won't actually be much information about the object pocketed available to other people.
It's generally much more informative when you stow it in a bag and generate the "X stows Y in their bag"

**Comment by drexample** [comment]
I can port Pickpocket's Gloves as syndicate items with such ability, to prevent such animation happening (also with bonuses they give), if you think that's required.

**Comment by Arokha** [comment]
You could also do it more like attack animations, where it's not an object at all, just a flicked overlay, and you could use a different range to flick the overlay in, based on w_class, so that smaller items can only be seen to be picked up from closer, and larger from further (which is somewhat similar to how backpack 'X puts Y into Z' works)

**Comment by drexample** [comment]
It uses already existing effect system and can be adapted to produce that effect. Is it really needed though? Would the change be really noticeable, considering item is put in hands immedeately.

**Comment by Arokha** [comment]
I don't personally care, I think it's fine as-is. I was just mentioning that it's possible to do it with different ranges, using the existing attack animation system.

**Pull request merged**
