### PR TITLE
Buffs Back Pulse Rifles

### PR DESCRIPTION
**Pull request by ParadoxSpace**
Because it's still silly to nerf them in such a fashion.

### CODE REVIEW

**Comment by mwerezak** [comment]
I was actually planning to use the name "pulse [weapon]" for a burst laser weapon sometime...

**Comment by mwerezak** [comment]
Whoops, mistook the repo that this was opened to, my mistake.

**Comment by Datraen** [comment]
It's an admin-spawn only gun, so it's not that big of a deal, but I see no problems with this code-wise.

Balance is another issue, but again, admin-spawn only. :+1:

**Comment by Magneld** [comment]
Oh just give it burstfire already.

**Comment by Spookerton** [comment]
Why bother O.o

**Comment by Magneld** [comment]
Because var edit a pulse rifle to burst fire and tell me the noise it makes isnt awesome.

**Pull request merged**
