### PR TITLE
Removes special secret player requirements

### PR DESCRIPTION
**Pull request by Kelenius**
https://github.com/Baystation12/Baystation12/pull/11289

### CODE REVIEW

**Comment by EmperorJon** [comment]
They may need alteration but we have them for a reason, and if we're to remove them that's a discussion that needs to be had amongst the highups.

**Comment by Kelenius** [comment]
Possibilities: Extended

@EmperorJon Vote on forums or poking admins and asking them to give their input?

**Comment by Kelenius** [comment]
Okay I've put the vote on the forum if that is of any help.

**Comment by EmperorJon** [comment]
Discussed and was not wanted.

**Pull request closed without merging**
