### PR TITLE
Fixes the clusterbang grenade

### LINKED ISSUE #3447: The SOP-6 Grenade launcher issues.
#### Brief description of the issue
The SOP-6 grenade launcher (the mech one) fires clusterbangs that delete without splitting into other flashbangs.
The SOP-6 grenade launcher does not rearm after all six shots have been fired, like it's lower tech version the SG6, or the AC10 and scattershot.

#### What you expected to happen
Many many flashbangs to fly everywhere.

#### What actually happened
A clusterbang vanished doing nothing.

#### Steps to reproduce
Fire an SOP-6 grenade launcher.

#### Additional info:
Server revision: master - 2017-05-11
7502a32fd747f055e83a2e868808e8210a2cb466

### PR DESCRIPTION
**Pull request by Anewbe**
EDIT: Fixes #3447

### CODE REVIEW

**Comment by Atermonera** [comment]
Tested with the SOP-6 mech weapon? #3446 reports related issue of clusterbangs fired from that being broken

**Comment by Anewbe** [comment]
That issue doesn't seem to be related to this at all?

**Comment by Anewbe** [comment]
It fixes the clusterbang, and the station craftable mech clusterbang launcher is specifically _not_ supposed to reload, which, seeing it in action, is honestly really generous. This thing is an unholy monstrosity of Fuck You.

**Comment by Anewbe** [comment]
May God have mercy on us all.

**Pull request merged**
