### PR TITLE
Makes PDA beeps a toggable option.

### PR DESCRIPTION
**Pull request by lbnesquik**
image

I just like being a bit discrete about using my PDA sometimes.

### CODE REVIEW

**Comment by Neerti** [comment]
Isn't there already a button to turn the ringer off?

**Comment by TheFurryFeline** [comment]
There is. Wew.

**Comment by TheFurryFeline** [comment]
But this is for the other thing, not the ringer.

**Comment by lbnesquik** [comment]
@Neerti 
There is the ringer that comes when you have message, but there is also little beeps whenever you interact with the PDA's now. This allow you to disable that. #6823

**Comment by TheFurryFeline** [comment]
#6801 is actually the PR

**Comment by lbnesquik** [comment]
> 
> 
> #6801 is actually the PR

Yes thank you

**Pull request merged**
