### PR TITLE
Adds wiggles to crawling

### PR DESCRIPTION
**Pull request by Arokha**
I did this. Have I gone too far?

### CODE REVIEW

**Comment by Belsima** [comment]
this is actually horrifying

**Comment by PrismaticGynoid** [comment]
The "crawling" feature can also be used for borgs to move objects around. How does this work with that?

**Comment by Arokha** [comment]
> The "crawling" feature can also be used for borgs to move objects around. How does this work with that?

Probably does this! :D If that's not desirable, a simple `&& O == user` would make it only work on yourself.

**Comment by Anewbe** [comment]
shaq_cat

**Comment by Arokha** [comment]
Have you ever seen a borg tiptoe?

**Comment by Nerezza** [comment]
The amount of wiggle in those gifs seems rather excessive (honestly more like they're doing a weird dance) so reducing it might make it look less 'horrifying'

**Comment by Arokha** [comment]
> Also does the wiggle happen when you 'crawl' an office chair too?

Nope, this is purely in "You clicked and dragged a mob onto a turf".

I can reduce the wiggleyness.

**Comment by Wickedtemp** [comment]
I demand we merge this at least for a little while.

**Comment by Schnayy** [comment]
Strongly dislike this.

**Comment by Heroman3003** [comment]
Keep the wriggles to humanoids. Borgs dont need it.

**Comment by Belsima** [comment]
some things should not be animated

**Comment by Nerezza** [comment]
Since the community seems split on this change, I'm thinking it should be shelved for now even though I personally wouldn't mind the addition.

That's up to staff to decide of course, but my 2 cents is that crawling is already fine as-is and obviously significantly more people would be dissatisfied with its inclusion than would be dissatisfied with leaving things the way they are.

**Comment by Arokha** [comment]
Oh noooo, my 41 seconds of work. But I made it, that means you *have* to merge it! Or so I'm told by people who make PRs.

**Comment by MisterLayne** [comment]
@Arokha How much is the wiggle post-change?

**Comment by Anewbe** [comment]
Can we make the wiggle less extreme, maybe? Like, half as wiggle as it is now?

**Comment by Arokha** [comment]
I did, just haven't made another screenshot

**Comment by Anewbe** [comment]
Ah, excellent.

**Pull request merged**
