### PR TITLE
Equipment storage now requires Warden access

### PR DESCRIPTION
**Pull request by Mark9013100**
Pending staff discussion.

Screenshot: 

Also edits the vintage .45 pistol's name.

Properly tested, works fine.

### CODE REVIEW

**Comment by zaredman** [comment]
Flag this as DMN pending staff talks.

**Comment by Minijar** [comment]
Que the angry officers reporting warden when he refuses to hand over pistols.

Overall yes, I like it. If we do this, remove the rubber magazines from lockers since they serve no purpose when you can't get its gun.

**Comment by nachomeep** [comment]
I don't think this is a good change. There's no way to take down an FBP if you remove the pistols.

**Comment by Dibasic** [comment]
remove the detective gun too

**Comment by comma** [comment]
Remove all fun

**Comment by OhEmGee** [comment]
>I don't think this is a good change. There's no way to take down an FBP if you remove the pistols.

I concur.

**Comment by Kelenius** [comment]
Sounds like a reason to nerf FBPs.

**Comment by Telvayne** [comment]
FBPs should get flashed in the same way borgs do.  That'd sort things out right quickly.

**Comment by zaredman** [comment]
FBPs can get tasered.

Hi, I have tasered them before.

This is not a popular pull by staff. Current vote is 8 no, 1 yes.

**Comment by Neerti** [comment]
> I don't think this is a good change. There's no way to take down an FBP if you remove the pistols.

Could you elaborate on that? @nachomeep

**Comment by Spacemanspark** [comment]
I'd like to say that I've very easily been tasered down while playing on Polaris, as an FBP.

**Comment by Telvayne** [comment]
Right, they aren't immune to tasers.  I'm thinking of pepper spray that they're not immune to.

**Comment by Neerti** [comment]
Vote was overwhelming towards 'no' for this.

**Pull request closed without merging**
