### PR TITLE
Removed ugly blood pools from sif mobs

### PR DESCRIPTION
**Pull request by Cerebulon**
A bunch of mobs from jungle.dmi had huge ugly blood pools built into the sprite which looked terrible when dragged.
Been meaning to do this for... Since the SC.

https://i.gyazo.com/721c46cba9f4f8ea7346eaad8f3e5ca2.png
https://i.gyazo.com/0e64824ecec3d7616a51e65898699530.png
https://i.gyazo.com/bc03429569a0d1d1f18016dd257afd8a.png
https://i.gyazo.com/993d5000176eb14e2211d5cc40d96d96.png
https://i.gyazo.com/742a6aaea4781d7fec917357eaf4f273.png

(Last two are unused except for adminspawn but worth doing them all I thought)

### CODE REVIEW

**Comment by Naidh** [comment]
Pretty sure the Tindalos is used in a PoI in the mines.

**Comment by Cerebulon** [comment]
Well now they're dead.

**Comment by Naidh** [comment]
World's a shit, kill 'em all.

**Comment by Belsima** [comment]
i just glanced at the panther sprite and lost my shit

**Pull request merged**
