### PR TITLE
Adds & Upgrades a Bunch of Teshari Clothing

### PR DESCRIPTION
**Pull request by KasparoVy**
Hey folks, I hope you've been well.
As requested, this backports everything but the rad, eva, and collar assets from https://github.com/VOREStation/VOREStation/pull/9312/

Please let me know if any changes are required, happy to accommodate.

Adds blindfold & white (recolorable) blindfold to loadout-- both of which fit Teshari.
Adds orange Teshari goggles, selectable in the loadout.
Adds species-fitted Teshari ring sprites.
Fixes Teshari captain glove sprites.
Adds species-fitted Teshari hudpatches & white blindfold.
Adds some species-fitted Teshari jacket accessories (tan, charcoal, navy, burgundy, checkered).
Replaces all Teshari undercoat & cloak sprites with upgraded versions from downstream.
Adds belted Teshari cloaks.
Adds hooded Teshari cloaks.
Adds Teshari worksuits (sprites already existed?).

### CODE REVIEW

**Comment by KasparoVy** [comment]
Turns out this whole time there's been an issue with north & south dir of mining & cargo (and one other, I forgot which) undercoats being skewed 1px to the left, so that is now corrected as well

**Comment by KasparoVy** [comment]
Not sure if this is affected by PolarisSS13/Polaris#7697

**Comment by Greenjoe12345** [comment]
I wonder if the cloak sprites here can be replaced with the citRP ones, since those ones are nicer then these.
not too sure about the head of staff cloaks because teshari can't be any head of staff other then the HoP here.
the belted cloaks you're adding in the PR on virgo would be nice to have here though.

**Comment by KasparoVy** [comment]
Happy to do whatever! Just let me know and I'll change as needed. It'll result in further changes downstream we'll need to adjust for so I'd rather only adjust this PR once folks determine what they actually want (from this and https://github.com/VOREStation/VOREStation/pull/9312)

**Comment by Greenjoe12345** [comment]
uh, anotheer thing is polaris now has the ear/tail customization
can the tesh ears and tails be ported here, since we've only got a few of those, not all the ones I've seen downstream at yawn wider

**Comment by Greenjoe12345** [comment]
I also wonder about replacing the species sprites with the white versions..
since the ears/tails use the white based, it'd need a bit of color working to match it with the body...

**Comment by Greenjoe12345** [comment]
also we uh
don't actually have the white blindfold here, I think

**Comment by KasparoVy** [comment]
I (nor anyone down at Virgo) has any idea what to think of https://github.com/PolarisSS13/Polaris/pull/7697

Do I port everything?

**Comment by Greenjoe12345** [comment]
I guess everything except for the collars, spacesuit and radsuit?
as for the blending it might be better to discuss that on discord with the staff

**Comment by KasparoVy** [comment]
TBD - port everything from ^^^ & eliminate old sprites from virgo.

**Comment by KasparoVy** [comment]
Will test it all tomorrow

**Comment by KasparoVy** [comment]
Alright it's technically tomorrow. Fixed my shit

**Comment by KasparoVy** [comment]
a t m o s h

**Comment by Greenjoe12345** [comment]
guess that's all good, we'll just need someone to review it then

**Comment by Atermonera** [comment]
`icons/mob/species/seromi/deptjacket.dmi` _appears_ to have removed directional sprites for most/all of the sprites modified?

**Comment by KasparoVy** [comment]
Hey @Atermonera , those icons were straight copy-pasta and are suffixed with _s

All the other icons that aren't suffixed with _s have all their directions and render properly on mobs for all dirs

IIRC the south-dir-only _s icons are used for the object images in UI

**Comment by KasparoVy** [comment]
Ohh right, had to go thru the new CI

For the record, my suggestion is to name it CIpher ✌️👽

**Comment by KasparoVy** [comment]
Sweet, thanks.

**Pull request merged**
