### PR TITLE
Successful defibs are more damaging now

### PR DESCRIPTION
**Pull request by Anewbe**
Up to 10, from 5.
Will bring it up at the Nov 6th Staff Meeting.

### CODE REVIEW

**Comment by Wickedtemp** [comment]
Usually, burns only occur when a person is defib'd multiple times, or if the defib malfunctions, or if conductive gel isn't utilized properly. Self-adhesive defibs have gel already applied, however paddle-defibs lack it, the gel needs to be applied to the patients chest, or to the paddles, usually in the form of a pad you place on the paddle directly.

I'd support this change *if* Medical is also provided with electroconductive gel that, when used on the patient, or the paddles themselves in the form of disposable gel pads, would minimize the burns done by the defib.

**Comment by Nalarac** [comment]
The purpose of the burns is to stop people from defib spamming a patient.

**Comment by Wickedtemp** [comment]
Then have the burns kick in on the second defib, I guess. I'd be cool with that as well. I just don't want to run into "Oh, hey, we totally would've been able to defib you if the burns from the defib itself hadn't killed you again."

**Comment by Anewbe** [comment]
I have other plans, now.

**Pull request closed without merging**
