### PR TITLE
Removes the stray door from virology

### PR DESCRIPTION
**Pull request by Yoshax**
For a reason totally not involving me, there was a Chief Engineer door in virology.

### CODE REVIEW

**Comment by GinjaNinja32** [comment]
Totally not you. Bisect says https://github.com/PolarisSS13/Polaris/commit/4f623b2b9977a2cd297806f2de28ede9b0c8f671 introduced that door :P

**Comment by Hubblenaut** [comment]
Yoxhaaax that's not where the CE's Office iiiis

**Comment by Yoshax** [comment]
I blame resolving conflicts :c

**Comment by Zuhayr** [comment]
Speaking of which.

**Comment by Yoshax** [comment]
Should be good now.

**Pull request merged**
