### PR TITLE
Clothing additions, minor clothing tweaks, and undershirts

### PR DESCRIPTION
**Pull request by Kholdstare34**
Adds several feminine undershirts, tweaks the warden and HoS jumpskirt to bring them in line with the other departmental jumpskirts, and adds white short shorts and a denim skirt.

### CODE REVIEW

**Comment by Anewbe** [comment]
You committed your .gitconfig

**Comment by Kholdstare34** [comment]
Fixed, I think.

**Comment by Yoshax** [comment]
Some of the sprites are a bit grey, but I can see that's probably just from the ones you based it upon. It does impact the final saturation of the applied color though. The `shortsleeve_fem` is pretty close to perfect. But up to you whether you want to fix or not, 

For reference, with this applied to each: https://i.gyazo.com/5eaca5548e3a8429ea92d171a35ccc44.png

Darker base: https://i.gyazo.com/be382684a4b905fcfa33581910352487.png
Colored darker base: https://i.gyazo.com/8f7bf2ce5554d7cc75eed1d1bf289d3a.png

Lighter base: https://i.gyazo.com/bba71326b42ed019a0f222717fb09a2e.png
Colored lighter base: https://i.gyazo.com/26f9c2df81a14bb7cc886343bf4657a2.png

Up to you, but the darker base does impact the color and will make colors look darkers than they are.

**Comment by Kholdstare34** [comment]
@Yoshax That's not a bad idea! I don't know if I have the energy to do that at the moment but I'd certainly try to tune that in the future.

**Comment by Anewbe** [comment]
You want to do that in this PR, Khold, or is it a far-off sort of thing?

**Comment by Kholdstare34** [comment]
At the moment I don't think so, I'll probably want to play around with that in the future, though.

**Pull request merged**
