### PR TITLE
Removes checks for masks/helmets.

### PR DESCRIPTION
**Pull request by Neerti**

### CODE REVIEW

**Comment by zaredman** [comment]
Presuming that this not being merged was an oversight or pending discussion?

**Comment by Neerti** [comment]
Ala still needs to sign off on it.

**Comment by zaredman** [comment]
After a quick chat - People seem to be OK drinking food with helmets and shit on but not eating shit. That possible?

**Comment by Mark9013100** [comment]
IMO, mouth coverage just needs to go completely.

**Comment by Neerti** [comment]
Needs to go on dev2 if I ever get clearance to make this change.

**Pull request closed without merging**
