### PR TITLE
Fix health analyzer names

### PR DESCRIPTION
**Pull request by Arokha**
The one that comes out is called advanced. And there IS an enhanced one (level 3) that this is not.

Now also renames them: [nothing] -> Improved -> Advanced -> Phasic

That seems like a linear progression to me.

### CODE REVIEW

**Comment by Anewbe** [comment]
~~It would be so nice if those weren't so vaguely named.~~

**Comment by Arokha** [comment]
Yeah, I was pondering names that imply obvious improvements over the previous. I personally would have done [nothing] -> improved -> advanced -> phasic maybe. Phasic is MAGICAL and obviously the best. Improved sounds incremental, and advanced sounds 'good'

**Comment by Belsima** [comment]
We really should rename them better.

**Comment by Arokha** [comment]
Done

**Pull request merged**
