### PR TITLE
Sec gear tweaks

### PR DESCRIPTION
**Pull request by Anewbe**
HoS coats have the same protection values as normal Sec gear
Detective gear is now as protective as the Forensics coat
Armored Trenchcoat sprite was tweaked slightly

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
Sounds controversial.

**Comment by Anewbe** [comment]
It's sensible and I can't remember why I didn't already do this.

**Comment by SpadesNeil** [comment]
Considering how big of a target the HoS is, are you sure that's a good idea to change the HoS coat? Maybe nerf it a bit but not make it as whimpy as regular security armor. I feel like that might cause balance issues.

The rest sounds fine though.

**Comment by Anewbe** [comment]
The HoS really, really should not be on the front, they should be commanding their Officers, who should be on the front. Having that gear with that level of protection encourages being overaggressive, which in turn makes them a bigger/easier target.

**Comment by ParadoxSpace** [comment]
Yes, but at some point they're going to be at the front. I'd personally leave it up to the forums or something.

**Comment by SpadesNeil** [comment]
A fair point, @Anewbe ! I withdraw the statement.

**Pull request merged**
