### PR TITLE
Adds a white stripe to the emergency oxytank.

### PR DESCRIPTION
**Pull request by Belsima**
Not a big change, simply more consistent.
image

### CODE REVIEW

**Comment by Anewbe** [comment]
Where does the gauge go?

**Comment by Belsima** [comment]
I *knew* there was something I missed.

**Comment by Belsima** [comment]
Wait, no. I don't think I need to put anywhere- it adds itself.

**Comment by Belsima** [comment]
image

current sprite for reference

**Comment by Anewbe** [comment]
Can you get an image with the gauge on it, then?

**Pull request closed without merging**
