### PR TITLE
Adds Vey-Med prosthetic limbs.

### PR DESCRIPTION
**Pull request by Anewbe**
Adds human-like Vey-Med prosthetics.

### CODE REVIEW

**Comment by martin509** [comment]
Don't we already have Zeng-Hu to fill that niche? Or is this more human-like than ZH?

**Comment by Anewbe** [comment]
It is more human than ZH, yes.

**Comment by Datraen** [comment]
Pictures?

**Comment by Hubblenaut** [comment]
Zeng-Hu doesn't look much human-like to me at all? It's a mix of black amd yellow.

**Comment by EmperorJon** [comment]
Definitely going to want pictures here.

**Comment by Anewbe** [comment]
veymed

**Comment by EmperorJon** [comment]
I like them, although I feel they somewhat invalidate the existence of the ZH ones?

**Comment by Anewbe** [comment]
I would have made these the default ZH sprites, but I decided (with some prompting) that it was probably better to keep something similar to the old sprites, which I did, the results of which have already been merged.

**Pull request merged**
