### PR TITLE
Ports over the Eris Human sprites, and Bay's Vey-Med sprites.

### PR DESCRIPTION
**Pull request by ElectricB1ue**
No longer will the entirety of the Human crew either look like they have liver failure, or have been charbroiled alive. Comparison shots (No Polaris Female shots are available, current char setup is not working):
The Eris Baldie (35 skin tone)
https://gyazo.com/75866e25a2ef427c49f32b50cb0b7194
The Polaris Baldie (35 skin tone)
https://gyazo.com/ba0c87e3955a37618de74b20c68ceeff
Eris Space Icelander (1 skin tone)
https://gyazo.com/e70dd5bf5e682512a6b63fb3fce63222
Polaris Space Icelander (1 skin tone)
https://gyazo.com/c6007832d2038d9826444d00cb550a90
Eris (50 skin tone)
https://gyazo.com/a5cd4ae507e17c56b839334b5ab68d73
Polaris (50 skin tone)
https://gyazo.com/7babfd170bd9d66960b65df8fa73f37d
Eris (100 skin tone)
https://gyazo.com/25bc29a1d732043408bc887dda635652
Polaris (100 skin tone)
https://gyazo.com/f2ebc170e87c038eecc899ba80b71227
Eris (150 skin tone)
https://gyazo.com/095d9debc495fa92f5eb96b64cfa982a
Polaris (150 skin tone)
https://gyazo.com/4d938fc5aa9d20aa66b94da27ce2c342
Eris (200 skin tone)
https://gyazo.com/cfacf672e6e74311a5d4ed7b67fb715e
Polaris (200 skin tone)
https://gyazo.com/d5a88afd43e15e55fea8c3e88b142c0f
Eris (220 skin tone)
https://gyazo.com/d0df03159ce9689691c547411604c7fa
Polaris (220 skin tone)
https://gyazo.com/e70574c588784a21b67786b1f8a4b29e

Update: Female sprites have been made up to date with Bay. https://gyazo.com/9b08d4444858e6a153d9e62735f12e91 https://gyazo.com/6254956263424d0eff546627b3a564a5
https://gyazo.com/044efe4203d3bf6ea33c3d6b74fba70e

### CODE REVIEW

**Comment by Belsima** [comment]
the black polaris sprites hurt

**Comment by ElectricB1ue** [comment]
To quote #suggestions
"oh my god that's awful
he looks charbroiled alive"
"that's like
how somebody looks when taken out of the deep frier on goon"
Yes. They're bad.

**Comment by Atermonera** [comment]
It's also kinda hard to compare sprites set against contrasting backgrounds. The polaris 220 is perceived as significantly lighter than the eris 220 because the polaris 220's background is significantly darker

**Comment by ElectricB1ue** [comment]
@Atermonera ultimately this issue is a bit difficult to solve. If you believe it's necessary I'll try to fix it.

**Comment by elgeonmb** [comment]
@ElectricB1ue compile a Polaris server with this PR in it and get the comparisons there

**Comment by GMR25** [comment]
Whilst the skintones certainly look better, in a few ways the new sprites themselves look a bit.. Egh.

The side-view of the females looks completely different in style from the front/back view, and both genders seem to have an oddly pale ass compared to the rest of their skin/back, which doesn't make too much sense unless everyone goes to the beach on their Saturdays.

**Comment by ElectricB1ue** [comment]
Updated with some additional female screenshots.

**Comment by Belsima** [comment]
you forgot to include dong

**Comment by Belsima** [comment]
tyranny

**Comment by ElectricB1ue** [comment]
*twiddles thumbs*

**Comment by Anewbe** [comment]
@ElectricB1ue You seem to have a spare file, veymed_main should be in the veymed folder, not the cyberlimbs folder.

**Comment by ElectricB1ue** [comment]
@Anewbe Good catch, let me fix it

**Pull request merged**
