### PR TITLE
Changes tape coloring + slight rework

### PR DESCRIPTION
**Pull request by Yoshax**
Steals Bay's generalised tape that uses colouring rather than sprites.
Also changes colours:
Tape

Engineering
Atmos
Security

I've seen some people saying some places that Engineering + Security can get confused together, so I propose this. Also means new tape things are trivial to add, you just need to define and add the colour.

### CODE REVIEW

**Comment by Anewbe** [comment]
Did you test this on doors, too?

**Comment by Yoshax** [comment]
doors

Yup.

**Comment by Arokha** [comment]
Pretty!

**Comment by Yoshax** [comment]
Hi.

**Pull request merged**
