### PR TITLE
Adds a new verb/preference to toggle requirting help intent to fire weapons

### PR DESCRIPTION
**Pull request by Yoshax**
- Toggles between 'safe' and 'dangerous'
- Safe is the status quo and the default
- Dangerous allows the user to fire weapons when on help intent
- Nothing changes unless the user changes their preference

### CODE REVIEW

**Comment by Kelenius** [comment]
Help intent IS the preference.

**Comment by Yoshax** [comment]
Nothing changes for you unless you want it to. This doesn't affect you at all unless you wish to change it.

**Comment by Kelenius** [comment]
Except it adds to verb clutter.

**Comment by Yoshax** [comment]
Then go speak to the person/people who wanted verbs for preferences. That's not my problem. I removed all the verbs when I ported Psi's stuff, but they were readded.

**Pull request merged**
