### PR TITLE
Ports Stasis Cages from Baystation

### PR DESCRIPTION
**Pull request by Novacat**
The idea behind this is that these can be used by explorers to 'trap' mobs that have been netted, and brought back for Xenobiology to have fun with.

Edit: Stasis cages now mostly finished and operational!

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
[insert Simaris quote here]

**Comment by Mechoid** [comment]
I assume this has been tested properly?

**Comment by Novacat** [comment]
So far, I just tested basic functionality. I stuffed a mob in, took a mob out. The only thing I have not tested was to see if the mob took atmos damage while inside the cage.

**Comment by Mechoid** [comment]
Please do so, if you would.

**Comment by Novacat** [comment]
Tested. Went out into vacuum with a cat in a stasis cage. After spending 10 minutes outside, cycled back in. Cat was completely unharmed.

**Pull request merged**
