### PR TITLE
Adds ling claw power

### PR DESCRIPTION
**Pull request by Anewbe**
It's basically a hatchet for 1 point and 15 chems.

The rest of the code adds a generic obj/item/weapon/melee/changeling that is the base for the claws and the arm blade, to save on code.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Do the claws look like anything? Otherwise it looks great

**Comment by Anewbe** [comment]
They look like a claw version of the armblade, sprites c/o Mechoid, I think. I still don't know how to make images in Git.

**Comment by Yoshax** [comment]
```image title```

**Comment by LorenLuke** [comment]
@Anewbe @Neerti 
Could they be made as a non-removable glove item, and the damage be done through 'Touch()' instead?

**Comment by Mechoid** [comment]
Unless Anewbe's modified the sprites,
Claws

**Comment by Anewbe** [comment]
Nope, that looks about right.

**Comment by SilverTalismen** [comment]
Those claws are amazing.

**Comment by SubberTheFabulous** [comment]
Those claws look far more dangerous, than blades.

**Comment by SilverTalismen** [comment]
That's be*Claws* blades change the whole arm, claws affect hands and fingers

**Comment by Anewbe** [comment]
Gave the armblade some AP following feedback.

**Pull request merged**
