### PR TITLE
Mob inventory cleanup, part 2

### PR DESCRIPTION
**Pull request by Kelenius**
Replaces three item removal procs with one
Adds a proc to delete an item on the mob

### CODE REVIEW

**Comment by Hubblenaut** [comment]
Since you handle the removal of items as removal of equipped items, this makes it unable to drop items from your inventory that have canremove=0 set.

**Comment by Kelenius** [comment]
Setting force to 1 will make it ignore canremove.

**Comment by Kelenius** [comment]
Will resolve after approval.

**Comment by Kelenius** [comment]
Why does a simple cleanup take two weeks to merge :V

**Comment by Hubblenaut** [comment]
This will still handle hand- and pocket slots as equipment slots and make you unable to remove items from there that have 'canremove = 0' set.

**Comment by Datraen** [comment]
The reason why this takes so long is because of the volume of files that have to be checked.
I've been personally too busy to take the time to review, I'll try to review this by Sunday.

**Comment by Datraen** [comment]
Can't review, life got in the way, will be a week or two until I'm free enough to do this.

**Comment by Datraen** [comment]
No glaring errors, :+1:

**Comment by Kelenius** [comment]
Done.

**Pull request merged**
