### PR TITLE
Adds striped undergarments

### PR DESCRIPTION
**Pull request by PapaDrow**
Adds striped underpants in the same pattern as the striped socks, as it says on the tin. Should support recolouring.

### CODE REVIEW

**Comment by PapaDrow** [comment]
I am but a lowly spriteslave, be gentle

**Comment by SilverTalismen** [comment]
*Whips* Moar

**Comment by Anewbe** [comment]
This good to go?

**Comment by PapaDrow** [comment]
Aye sir, as good as I know how to make it with my limited knowledge.

**Pull request merged**
