### PR TITLE
Finishes Porting /tg/ Lighting + Eris Directional Lighting + Openspace refactor

### PR DESCRIPTION
**Pull request by Cerebulon**
Since the original PR creator went to space in real life before finishing it I guess. Details are in the relevant PRs since it seemed silly to just rewrite it all. Basically:
Fancy glowier lighting which is supposed to perform better.
Openspace system actually fully based on what's on the tiles below.
Removes right-click dummy darkness
~~Most of the file changes are just SSOverlay utilisation.~~ moved to own PR for readability

Primary PR:
tg lighting: https://github.com/VOREStation/VOREStation/pull/10662
with minor adjustments based on https://github.com/PolarisSS13/Polaris/pull/8142

Also incorporates:
Aimable flashlights: https://github.com/VOREStation/VOREStation/pull/10752
vis_contents openspace: https://github.com/VOREStation/VOREStation/pull/10764

Less major inclusions and bugfixes/tweaks:
Light bleeding: https://github.com/VOREStation/VOREStation/pull/10961
Light bleeding tweaks: https://github.com/VOREStation/VOREStation/pull/10969
VV-able newlights: https://github.com/VOREStation/VOREStation/pull/10759
More emissive light inclusions: https://github.com/VOREStation/VOREStation/pull/10842
Sun tweaks: https://github.com/VOREStation/VOREStation/pull/10962/files

Bugfixes included (Plus some more I may have closed the tabs of)
Planes tweaks: https://github.com/VOREStation/VOREStation/pull/10937
Openspace fixes: https://github.com/VOREStation/VOREStation/pull/10828
More: https://github.com/VOREStation/VOREStation/pull/10877
Openspace emissive light tweaks: https://github.com/VOREStation/VOREStation/pull/10894
Plus adjustments for new outdoor turf checks.

**CURRENT ISSUES:** (Prevening non-draft)
Outdoor turfs are... Completely black unless you shine a flashlight on them.
Human and simple mobs cannot see outdoor turfs (surface OR outside windows on the station e.g. roofs) normally.
AI CAN see surface outdoor turfs, but not outside the station windows.
Ghosts can see all of these fine, even with darkness on.

Any ideas where the fuck this code lives, pls help.

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
This is an effectively unreviewable monolith. You've bundled tons of conceptually distinct changes into these commits.

**Comment by MistakeNot4892** [comment]
Bit more constructively - it would be preferable for you to separate this out into several PRs, particularly things like the add_overlay/cut_overlay changes that aren't actually directly relevant to the functional lighting or zmimic changes. Following that, PRing the lighting and zmimic changes as a unified PR is probably alright given how meshed they are, but separating the additional random feature stuff like aimable flashlights out into a third (or fourth or fifth) PR would be much easier to review.

**Comment by Cerebulon** [comment]
Yeah the SSOverlay stuff being included in the original PR downstream was a huge pain if I'm honest, made it impossible to quickly see the ACTUAL changes which I suspect is why its so hard to track down the last bug.
Will cut up into bits whenever I have time again (Possibly next weekend at this rate)

**Comment by Cerebulon** [comment]
Absolutely no chance of having the time to tackle this again within the next several months.

**Pull request closed without merging**
