### PR TITLE
Adds new organization-specific locations in the tracon module

### PR DESCRIPTION
**Pull request by elgeonmb**
and misc tweaks.

1)Adds systems with lore and trade with SCG to the generic destinations list

2)Gives Vey-Med some Skrell-focused destinations

3)Gives Heph some millitary destinations

4)Gives Morpheus trade with Shelf

5)Strips out the "Icarus" generic ship name and the NDV Icarus Nanotrasen destination. Suddenly this word has a lot of history and I somehow don't see NT naming a ship after the political party they're bitterly opposed to

There's a syncing commit in this because I just now learned how to update my fork without doing that. Sorry.

### CODE REVIEW

**Comment by elgeonmb** [comment]
you cruel metal god

**Comment by elgeonmb** [comment]
Eugh I left something unmatched I guess?

**Comment by Anewbe** [comment]
@elgeonmb Do you compile your code before you commit it?

**Comment by elgeonmb** [comment]
@Anewbe that would make my craptop scream in pain but I'm gonna figure out how to do so anyway?

**Pull request closed without merging**
