### PR TITLE
Removes RNG from emagging APCs and robots.

### PR DESCRIPTION
**Pull request by Belsima**
>get emag
>have a drone captured in your cave
>swipe your emag once
>it fails
>swipe it again
>it fails
>try three more times
>you're out of charge
>the drone has PDA'd the HoS in this time
>the HoS kicks down the door and throws in a flashbang
>you shut down your PC

### CODE REVIEW

**Comment by Anewbe** [comment]
I don't care about the APC thing, robots... Might require some discussion.

**Comment by Belsima** [comment]
In my experience they're frustrating for little gain in gameplay other than potentially fucking over an antag for no reason.

**Comment by Anewbe** [comment]
It will require discussion.

**Comment by Belsima** [comment]
Of course- just giving reasoning.

**Pull request closed without merging**
