### PR TITLE
Revert "Tajaran sprite change -April Fool-"

### PR DESCRIPTION
**Pull request by ParadoxSpace**
god why is that still in

### CODE REVIEW

**Comment by zekesulastin** [comment]
Because the silhouette looks much better than before and aside from stupid memers nobody actually /cares/ (and it's the stupid memers that made it into a yearslong meme in the first place)

**Comment by Serithi** [comment]
I gotta agree with Zeke here. It's only a "thing" because people make a thing out of it. Just man the fuck up and deal with its existence :v.

**Comment by Mark9013100** [comment]
cat tats go home

**Comment by ParadoxSpace** [comment]
yes but my main complaint was it's an april 1st joke, and it's now april 4

**Comment by Anewbe** [comment]
Yeah, see, just because it was added on April 1st doesn't mean it's not fine to stay. I'd argue that the sprite is nicer, and is a pleasant contrast to the original (male) sprites.
In the end it's Serena's decision whether they stay or go, but I personally think it's fine.
:-1: On this business, and good day to you sirs.

**Comment by zekesulastin** [comment]
((to be completely fair, -April Fool's- is kind of in the original PR title, but))

**Comment by RenScorch** [comment]
I would like to point out, that while they may have added in April fools things, doesn't mean you can't also include non-April fools like things because well you know.... Merging and updating the server thing. :V

**Comment by Iamgoofball** [comment]
jesus christ

**Comment by Neerti** [comment]
This is ultimately Serena's decision.

**Comment by SparklySheep** [comment]
This community never ceases to entertain me.

**Comment by headswe** [comment]
TOPKEK :+1:

**Comment by Magneld** [comment]
Why is this such a big deal again?

**Comment by optimumtact** [comment]
Hi, Catboobs make it way way easier for me to really enjoy ERP, so I think you should keep them in.

I'll invite my furry friends over and we can have a big polaris party

**Comment by Sligneris** [comment]
Because catboobs discourse is a meme.

**Comment by Kelenius** [comment]
https://i.imgur.com/CBlJw58.png

**Comment by collinxchu** [comment]
When they add cat tits as a joke and people want it to stick around.

I didn't want to hold my lunch down anyway.

**Comment by Serithi** [comment]
Jesus H. Christ i think half of r/ss13 just ran through here to thumbs up/down people.

**Comment by EmperorJon** [comment]
Remove Katboob, Polaris Strong.

**Comment by Sabess** [comment]
jon is the hero we need

**Comment by Sligneris** [comment]
I, for one, didn't actually mind catboobs much.

**Pull request merged**
