### PR TITLE
Adds the ability to choose nicknames

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by Belsima** [comment]
Mechanically, what does this do?

**Comment by SubberTheFabulous** [comment]
Probably, if your nickname is mentioned, name emphasis thing happens.

**Comment by Anewbe** [comment]
Exactly that, yes. It's part of the name emphasis system.

**Comment by PrismaticGynoid** [comment]
Will this work for silicon mobs?

**Comment by Anewbe** [comment]
No, because of the way Silicon mobs are spawned in they don't get nicknames.

**Comment by PrismaticGynoid** [comment]
It would be incredibly helpful if that were added in in some way. Have it so they can be set in-round, maybe?

**Comment by Anewbe** [comment]
Some day, maybe.

**Comment by Yoshax** [comment]
Liked it so much you couldn't wait for lazybutt Ace? :P

**Comment by Anewbe** [comment]
It was like finding a hole in my spirit that I'd never been able to see before, yes.

**Comment by SpadesNeil** [comment]
Well I am indeed quite lazy.

**Pull request merged**
