### PR TITLE
Scrubbers no longer automatically scrub phoron

### PR DESCRIPTION
**Pull request by Anewbe**
Let Darwin claim his bounties.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Why would you do this? :(

**Comment by Neerti** [comment]
I worry this will add more tedium for the AI.

**Comment by Andromeda-K22** [comment]
How to encourage phoron griefing 101.

**Comment by Anewbe** [comment]
In order:
- This is a partial revert of a PR made in April of 2017, which I see as mollycoddling. On the Southern Cross, there are roughly six rooms where phoron might be in the air in any sane context. If your concern is Virgo, or any other server that uses phoron as an atmospheric gas, I will note that this is a one line change, and based on the fact that Virgo uses a bot to pull our merged PRs, you may close said automatic Pull Request as it suits you.
- I don't see this adding any real workload to AIs. As mentioned, there aren't all that many rooms that have reason to encounter phoron, and in my experience, especially recently, the first response to any room having a phoron leak is to tell the AI to panic siphon the room, which hasn't really changed since I started playing, I don't think.
- In the interest of treating the comment about phoron grief as a serious concern, I'm going to note that said grief is handled the same way all grief is handled, this won't particularly enable the type of person who would decide to grief, anyway. Most of them go straight for bar fights or welding tanks.

**Comment by Mechoid** [comment]
Phoron grief is relatively easily fixable atmos-wise with the power of planetary walls, I should note.

**Comment by SpadesNeil** [comment]
I mean Virgo can literally just _not change this_ and we're good.

**Comment by Anewbe** [comment]
Exactly.

**Comment by Anewbe** [comment]
The NLS Southern Cross wasn't made with the purpose of gathering Phoron, it just does so because of gameplay necessities, seeing as damn near everything interesting is tied to said rock. If we go by the logic that immersion is the absolute end-all-be-all of what needs to be in the code, the NLS Southern Cross wouldn't have half the roles it does, and most everyone would be some sort of communications technician.

And in the off chance you haven't noticed, there's a **ton** of immersion breaking nonsense that people just roll with and accept as part of playing SS13. Our engine is a magical glowing rock that doesn't start in the "On" state and explodes if you fuck with it, rather than having the station run on something reliable and safe, like solar power. Our medical bay doesn't start with a full loadout of pharmaceutical drugs for every eventuality, despite the fact that it's nearly a hospital in its own right. Science magically melts things down to learn how to make new things, every single shift.

All of these immersion breaking things exist because it's _something to do._

This is one of those cases. Adding Phoron to the list of gases that's _automatically_ removed from every single part of the station, constantly, removed it as an actual workplace hazard, which, as mentioned, is basically a non-issue anyway. As a former long-term Engineering player, perfect job safety is incredibly boring for the role. Having things be in a perfect setup for homeostasis before the map is even done loading basically obviates the purpose of that entire department, until meteors strike and everyone abandons the round anyway.

Space Station 13 as a whole runs on chaos and unpredictability, that's what made it a cult classic in the first place. Despite the fact that Polaris is roleplay focused, the base game still needs to have a draw, or it devolves into a chat room with pretty colors.

**Comment by Andromeda-K22** [comment]
Disabling roundstart phoron filtering won't add 'chaos and unpredictability'.

It'll just be a pain in the ass for the few engineering players remaining.

**Comment by Belsima** [comment]
Toggling scrubbers is perhaps the most boring thing one can do. This is just adding a monotonous task to click the same button over, and over, and over (gas spreads a lot if the crew fucks up or if things explode (things often explode when Phoron is involved)) rather than a task that defines a job like the supermatter, chemistry, and such. 

Repairing explosions is at least somewhat engaging, walking to console after console to repeat the same clicks in the same order is absolutely not.

**Comment by StarSmasher44** [comment]
Remember having to actually get back into your fucked up phoron flooded room just so you can configure those "fucking misbehaving Air Alarms" to actually FILTER YOUR FLOODED ROOM, rather than assuming it already does and sit there for 2 hours looking stupid..

(Phoron research station, toxic gas... Confined spaces, who wouldn't filter that shit?)

**Comment by StarSmasher44** [comment]
So either that or just make phoron more toxic, allow it to be filtered but make the consequences of being in contact with it serious enough to make people to "Oh fuck"

**Comment by Poojawa** [comment]
You have Atmosia RCON, why would you enter any room to manually set an air alarm, when it gets automatically unlocked there and fixed at the touch of a button.

**Comment by zekesulastin** [comment]
I really don't understand what this is supposed to accomplish gameplay-wise aside from having an _appearance_ of "reducing safety" on the station.  That said, given the comments on the [atmos leak event](https://github.com/PolarisSS13/Polaris/blob/3a709c12d6d80e26df5cdbedfc6982b133d5798f/code/modules/events/atmos_leak.dm) (that currently does not fire off) that put phoron as the mid-level event because of the default filtering, if this goes through please re-examine those severity levels.

**Comment by Wickedtemp** [comment]
Yeah, this... kinda seems like something without a point aside from "increasing inconvenience and annoyance".

The entire argument for this change can be boiled down to "Well I personally don't see why it's a big deal", which is irrelevant, and "It adds chaos and unpredictability", which is pretty much false. 

Antagonists add chaos and unpredictability. Spider events, a slime outbreak, someone taking a hostage or attempting to kill another crew member, a bar-fight, etc, all add chaos and unpredictability. Making engineers run around and click a few buttons to have all of the scrubbers filter phoron again? Doesn't add anything but tedium and from the commenters here, doesn't really sound like a change they want to deal with.

**Comment by Mechoid** [comment]
Before I merge this, I'm going to point out here. This was discussed in the staff meeting, and some of the people who saw it as just "increasing inconvenience" saw that it really did touch nothing in the vast majority of rounds. In the future, this may change yet again pending Future Things TM. Chemists need to be careful, toxins scientists need to be careful, the latter of which can just pre-emptively ask 'Hey can you set this to filter'.
If you want an example: If an engineer is asked to do it instead of say, the AI, they suddenly have an opening for things they can do while inside Science, if they're an antag. Which is good.

**Pull request merged**
