### PR TITLE
Updated scrubber & Vent icons

### PR DESCRIPTION
**Pull request by Cameron653**
Sprited by Keekenox

- Updates Vent icons
- Updates Scrubber icons

OLD VENT PUMPS: https://i.imgur.com/gK6fSSa.png
NEW VENT PUMPS: https://i.imgur.com/I0jR9PD.png

OLD SCRUBBERS: https://i.imgur.com/wGm4waT.png
NEW SCRUBBERS: https://i.imgur.com/x21B26W.png

The ones which need to be animated are animated.
I could make gifs of them, but it's simpler for someone to just download the file & open it up in dream maker.

### CODE REVIEW

**Comment by Belsima** [comment]
How do the new scrubbers look on tiles like carpet or others?

**Comment by Cameron653** [comment]
They'd be in the same position as the old ones, just a bit smaller, I'd imagine. All this PR does is change their sprite.
New scrubbers: https://i.imgur.com/TQXNaJN.png
Old scrubbers: https://i.imgur.com/cG661pU.png
I could take some photos of how it looks on carpet and other various tiles in game if you wanted.

**Comment by Belsima** [comment]
I was more asking about how it looks, yeah.

**Comment by Cameron653** [comment]
On gray tile: https://i.imgur.com/yXoXxgv.png
On wood: https://i.imgur.com/oeWu9yy.png
On carpet: https://i.imgur.com/hpTcoVk.png
Bathroom: https://i.imgur.com/Ez9sMHK.png
Medical: https://i.imgur.com/7ytqs5q.png
Plating: https://i.imgur.com/sbGSJCP.png
Bedrooms W/ carpet: https://i.imgur.com/RDlDxdm.png

**Comment by Belsima** [comment]
Yeah, personally I think it looks good on regular tile and the vent is a direct upgrade, but the scrubber feels.. off on other flooring. I don't get what it's meant to be, which I suppose is true of the old one too, but something doesn't feel right seeing it on carpet.

**Comment by Cyantime** [comment]
Does this also effect passive vents?

**Comment by Cameron653** [comment]
I'm not sure what the passive vents are.

If they use vent_pump.dmi, then they'll also be changed.

**Comment by Cyantime** [comment]
https://github.com/PolarisSS13/Polaris/blob/master/code/ATMOSPHERICS/pipes.dm#L1259

**Comment by Cameron653** [comment]
Alrighty, done.

**Comment by Cameron653** [comment]
This should be ready to merge.

**Pull request merged**
