### PR TITLE
Adds NT brand prosthetics

### PR DESCRIPTION
**Pull request by Anewbe**
Adds in some spiffy new NanoTrasen brand prosthetics. You can show up with 'em or you can build 'em (don't need a disk, either).

Moves the Morpheus torso back to the old ways, where the limbs actually match the body. The current Morpheus torso is the base for the NT set.

### CODE REVIEW

**Comment by Datraen** [comment]
Pictures of these changes/additions?

**Comment by Anewbe** [comment]
nanotrasen


Morpheus is on top, NanoTrasen is on the bottom.

**Comment by Datraen** [comment]
I don't see a problem with them as they are currently presented, so :+1:.

**Comment by Spacemanspark** [comment]
Reminds me of Worker Joes

**Pull request merged**
