### PR TITLE
Porting forensics from Aurora.

### PR DESCRIPTION
**Pull request by Zuhayr**
Port of Bay's commit. Haven't actively tested it yet on this codebase, porting it over by request of Minijar.

### CODE REVIEW

**Comment by Datraen** [comment]
I'd love to see some testing prior to just porting.

**Comment by Zuhayr** [comment]
It will be a few days in that case as I am moving house tomorrow and may not have my PC set up again for awhile.

**Comment by zaredman** [comment]
Oh fuck yes fuck yes.

But yea, seconding what @Datraen said.

**Comment by Zuhayr** [comment]
If someone feels like pulling/testing/posting issues you will give me a head start on fixes when I am back on a PC with Dream Maker on it.

**Comment by zaredman** [comment]
For record:

"These changes replace the current scanner/forensics computer setup.

    Gunshot residue: Palms and clothing keep track of the last caliber of ballistic weapon fired by the owner until washed.
    Swabs: Can be used to obtain DNA samples from blood on objects or saliva from mobs. Can also be used to obtain gunshot residue from the palms of mobs or from clothing.
    Fiber kit: Recovers fibers from objects.
    Fingerprint powder/cards: Recover prints from objects or mobs. They can be merged to turn partial prints into full prints.
    Luminol/UV light: When luminol is sprayed over blood that has been cleaned up but not sterilized (with sterilizine), it produces white marks when exposed to UV light.
    Microscope: converts evidence from gunshot residue swabs, fiber kits or fingerprints into a readable report.
    DNA scanner: converts DNA from swabs into a readable report."


What I have so far, @Zuhayr:

Found issues:
-Cleaning blood with non-steralizine spray and then walking on said tile still tracks blood as if it were never cleaned. Had that happen twice out of three attempts.
-Unable to remove anything from microscopes.
-DNA scanner refusing to accept blood swabs


What works:
-Luminol + UV works; shows the blood locations after cleaning.
-Fingerprint powder kits spit back prints.
-Fingerprint cards spit back prints
-DNA analyzer does analyze saliva for proper DNA
-GSR > Slide > Microscope reads properly

**Comment by NortonDK** [comment]
Need a way to get more luminol

**Comment by Zuhayr** [comment]
@zaredman Cheers.

@NortonDK You can make it in chemistry.

**Comment by zaredman** [comment]
What about microscope slides? Autolathe or order?
Same goes for the swab kits/dust kits/print cards.

**Comment by Zuhayr** [comment]
Slides could stand to be made at a lathe, but currently all the forensics gear can be ordered in the auxillary forensics crate from Cargo.

**Comment by Zuhayr** [comment]
Re: map changes, @Minijar was going to do them himself I believe.

**Comment by Minijar** [comment]
Yep, as soon as I this gets merged I'll pop it in.

**Comment by Datraen** [comment]
Could attempt to set blood that was sprayed with non-sterilizine as dried blood. Doesn't track blood that way, and we could remove the icon when that happens.

**Comment by zaredman** [comment]
Oh. @Zuhayr - Another issue I found, let it be a bug or my own stupidity?

Couldn't get fiber kits working.

**Comment by Zuhayr** [comment]
clean_blood() actually does set the blood to amount=0, I just bypassed it for some reason. Will have a general fix PR up after I finish testing.

**Comment by Zuhayr** [comment]
Glad someone called this out for testing, there were several niche runtime errors.

**Comment by Zuhayr** [comment]
Updated and rebased, tested, no immediately evident bugs.

**Comment by Minijar** [comment]
If someone wants to merge this, I can go ahead and fix my thing and we'll have shiny new CSI.

**Comment by zaredman** [comment]
I'll run through a test one last time and merge after.

**Comment by zaredman** [comment]
@Zuhayr unless I am doing something wrong, still two issues:

1) Can not remove slides from microscope
2) Microscope has no 'cooldown' timer - aka I can click it rapidly five times and it just spits out results five times in the blink of an eye.

**Comment by zaredman** [comment]
Just got brought up that I didn't check evidence bags.

Staaaaaaaaand by.

**Comment by zaredman** [comment]
So evidence bag box is porked.

runtime error: Cannot modify null.screen_loc.
proc name: standard orient objs (/obj/item/weapon/storage/proc/standard_orient_objs)
  source file: storage.dm,161
  usr: Leila Berkheimer (/mob/living/carbon/human)
  src: the evidence bag box (/obj/item/weapon/storage/box/evidence)
  call stack:
the evidence bag box (/obj/item/weapon/storage/box/evidence): standard orient objs(0, 5, null)
the evidence bag box (/obj/item/weapon/storage/box/evidence): orient2hud(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): open(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): MouseDrop(Leila Berkheimer (/mob/living/carbon/human), the floor (148,214,1) (/turf/simulated/floor/tiled/white), the floor (148,213,1) (/turf/simulated/floor/tiled/white), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=21;left=1;scr...")
runtime error: wrong type of value for list
proc name: show to (/obj/item/weapon/storage/proc/show_to)
  source file: storage.dm,95
  usr: Leila Berkheimer (/mob/living/carbon/human)
  src: the evidence bag box (/obj/item/weapon/storage/box/evidence)
  call stack:
the evidence bag box (/obj/item/weapon/storage/box/evidence): show to(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): open(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): MouseDrop(Leila Berkheimer (/mob/living/carbon/human), the floor (148,214,1) (/turf/simulated/floor/tiled/white), the floor (148,213,1) (/turf/simulated/floor/tiled/white), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=21;left=1;scr...")

**Comment by Zuhayr** [comment]
This PR doesn't touch evidence bags, that isn't a bug with the port.

**Comment by Zuhayr** [comment]
Microscopes also use alt-click for removing slides, ftr.

**Comment by Neerti** [comment]
Clickdelay issue is fairly minor and can be fixed later.

**Pull request merged**
