### PR TITLE
Adds a bunch of new hair styles.

### PR DESCRIPTION
**Pull request by Belsima**
Ported from /vg/ and the Eris. All tested and working.

imageimage

### CODE REVIEW

**Comment by Anewbe** [comment]
As a note, if you change your branch to Master, then pull from the upstream master, then make your branch, it won't have that first commit. It's also good practice in general.

**Comment by Belsima** [comment]
Ah. I was wondering why that was a thing, thanks.

**Comment by Belsima** [comment]
I did the thing and it still has commits in other branches for some reason.

**Comment by SilverTalismen** [comment]
Looks like good hairstyles to me atleast.

**Pull request merged**
