### PR TITLE
Removes xenormorphs.

### PR DESCRIPTION
**Pull request by Zuhayr**
DNM until #1014 is merged.

I raised this idly in the TS while I was removing Vox and had several high-up admin shout YES at me so here it is.

### CODE REVIEW

**Comment by Serithi** [comment]
rip

**Comment by Mark9013100** [comment]
How the fuck am I supposed to reenact the lusty xenomorph maid now?

**Comment by Serithi** [comment]
@Mark9013100 Horny Unathi Janitor time.

**Comment by Mark9013100** [comment]
Well shit.

**Comment by Telvayne** [comment]
"Give to CM what is CM's."

**Comment by Neerti** [comment]
Vox removal got merged, so I think this is good to merge too.

**Pull request merged**
