### PR TITLE
New Limb HUD System, from Bay

### PR DESCRIPTION
**Pull request by Neerti**
Manually ports https://github.com/Baystation12/Baystation12/pull/13530, and https://github.com/Baystation12/Baystation12/pull/13561 from bay.
Adjusts the scaling on the coloration, since it seems Bay has different shading than us for species, otherwise some species would be dark, and others would be superbright.
Credit goes to Zuhayr for the code.

### CODE REVIEW

**Comment by EmperorJon** [comment]
Should probably have a changelog, especially for credit purposes. (We need to get into the habit of changelogging basically every addition)

**Comment by Neerti** [comment]
My brain is dumb and titled the commit 'changeling', woo.

**Comment by EmperorJon** [comment]
Nah leave people confused. :p

**Comment by Yoshax** [comment]
Are those left-in world messages deliberate?

**Comment by Neerti** [comment]
I really need to sleep.

**Pull request merged**
