### PR TITLE
Defibs should revive people now.

### PR DESCRIPTION
**Pull request by MagmaRam**
This might be an unnecessary fix, I might just have the worst luck. But I couldn't get a defib to res in 10 tries before this, got it on the second after.

### CODE REVIEW

**Comment by Anewbe** [comment]
It was working fine for me when I tested it.

**Comment by MagmaRam** [comment]
It might be down to my own cruddy luck, then. I also haven't seen defibs work on the live server, though. If they've worked on live, then I'll close this one.

**Comment by Anewbe** [comment]
I'll test it live sometime today.

**Comment by Nerezza** [comment]
How does time of death track? Is it a timer counting down or the round time that death occurred? I'm still in vacation so I can't check

**Pull request merged**
