### PR TITLE
Adds Flannels

### PR DESCRIPTION
**Pull request by redstryker**
Adds flannels as an item worn in the suit slot.  They are also in the loadout.
All of them can have their sleeves rolled up, their buttons buttoned, and be tucked in and any combination thereof.

Sprites (Only showing the three base ones since there are /way/ too many of them):
http://puu.sh/pV2C4/fa8020ab33.png
http://puu.sh/pV2Ej/519d23b136.png
http://puu.sh/pV2Gz/e2f97c03d5.png

### CODE REVIEW

**Comment by Anewbe** [comment]
Oh hey, how'd you fix the indentation errors?

**Comment by redstryker** [comment]
@Anewbe , somewhere in our clusterfuck of shared code, the indentation errors turned into different ones,  I turned some '=' into '==', and then Neerti re-wrote one of the functions.

**Comment by Anewbe** [comment]
Sounds about right.

**Comment by Yoshax** [comment]
Much icon states.

**Pull request merged**
