### PR TITLE
Zheng Hu Improvements

### PR DESCRIPTION
**Pull request by Anewbe**
- Makes the ZH robolimb sprites a bit closer to the human default, C/O BattlefieldCommander.
- Separates the ability for robolimbs to apply skin tone from their lifelike var, adds a skin_tone var to control that function

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Any screenshots of the new/tweaked sprites? :o

**Comment by Atermonera** [comment]
From discord spriting channel:
[I think this url should work?](https://cdn.discordapp.com/attachments/412152289219051521/415695290277036033/zenghu_example.png)

**Comment by elgeonmb** [comment]
how does zh look w/ 0 and 255 skin tones?

**Comment by elgeonmb** [comment]
(or you know fuck it min/max)

**Comment by BillyBangles** [comment]
another pic if ur too lazy to click links
the new 'hu

**Comment by Anewbe** [comment]
'bout the same as a human or Vey-Med. The greyish lines don't really pick up a lot of color.

**Comment by SilverTalismen** [comment]
Looks really nice, Great work.

**Pull request merged**
