### PR TITLE
IAA Upgrade & First Aid Stations Boogaloo

### PR DESCRIPTION
**Pull request by Minijar**
Exactly the same as my previous pr's except this now contains both commits in one. Best to merge asap before something else is merged to break this again.

### CODE REVIEW

**Comment by Spookerton** [comment]
Split this into two separate pull requests. Your IA changes are contentious.

**Comment by Minijar** [comment]
And how exactly do I do that?

**Comment by Spookerton** [comment]
Heck if I know!

**Comment by Minijar** [comment]
I give up with this due to the constant conflicts from other things being merged first.

**Pull request closed without merging**
