### PR TITLE
Removes the leg trim on the corporate uniforms

### PR DESCRIPTION
**Pull request by Mark9013100**
* Removes the leg trim on the Corporate Security jumpsuits.

* Allows the sleeves of the Corporate Security jumpsuits to be rolled up/down.

* Gives the Corporate Security jumpsuits rolled down sprites. Very basic though.

Officer:

Warden:

Head of Security:

Detective:

### CODE REVIEW

**Comment by Datraen** [comment]
I'm interested in the "simple" rolled down sprites to be visible on the PR as well.

**Comment by Mark9013100** [comment]
Alright, screenshots inbound.

**Comment by Datraen** [comment]
:+1:

**Comment by Verarch** [comment]
Why hasn't this been merged yet? I need this in my life.

**Comment by Mark9013100** [comment]
I'll fix it by the end of this week.

**Comment by Mark9013100** [comment]
Closing, will re-open when done bringing this up to pace.

**Pull request closed without merging**
