### PR TITLE
Adds the medical webbing

### PR DESCRIPTION
**Pull request by Mark9013100**
* Adds the white webbing, an edit of the brown webbing with a medical cross on the back. Available in the EMT closets and their relevant cargo crate.

* Paramedics, Medical Doctors, and the Chief Medical Officer can select white webbings from custom loadout.

* Adds white webbings to the Mercenary base and ERT Medical Prep.

Re-done because I'm shit at fixing merge conflicts.
Previous attempt: https://github.com/PolarisSS13/Polaris/pull/1297

### CODE REVIEW

**Comment by Yoshax** [comment]
Add it to the webbing crate: https://github.com/PolarisSS13/Polaris/blob/master/code/datums/supplypacks.dm#L1633

I still think it's unfair that not everyone in medical is allowed the same chance to have a fancy webbing.

And also, making a new PR seems pretty poor because the previous discussion, issues raised in such, etc, are lost unless someone goes to find the old PR.

**Comment by Mark9013100** [comment]
The reason why the medical webbing isn't in the main webbing crate is because it's for medical personnel use only, and any Urist McCargotech can order it.
And I'm not really sure if everyone in medical having 5 extra slots would be okay'd staffside. Though, I'll let MDs have the chance to get it from loadout as well.

**Comment by Datraen** [comment]
What Yoshax said, add it to the webbing crate. If Urist McCargotech can order engineering and security webbings, then they can have medical webbings too.

**Comment by Mark9013100** [comment]
Alright.

**Comment by Datraen** [comment]
:+1:

**Comment by mwerezak** [comment]
> The reason why the medical webbing isn't in the main webbing crate is because it's for medical personnel use only, and any Urist McCargotech can order it.

Not sure if you guys changed up the cargo crates but I'm pretty sure the webbing crate is meant to contain webbings from every department.

**Comment by Yoshax** [comment]
Much better. And as above yeh, cargo should be able to order supplies for everyone, which is fixed now and better.

Also, many people on IRC or whatnot will be willing to help you learn to resolve conflicts and whatnot. It's a pain, but not that hard.

**Pull request merged**
