### PR TITLE
Replaces organ sprites.

### PR DESCRIPTION
**Pull request by Belsima**
image

From /tg/.

I'm not sure on the eyes, so I'd want input on those.

### CODE REVIEW

**Comment by MisterLayne** [comment]
The eyes are beautiful.

**Comment by Anewbe** [comment]
Eyes I like, kidneys I dunno. Will think about it.

**Comment by Belsima** [comment]
Aight.

**Comment by Anewbe** [comment]
We like to save our old sprites, for rainy days. Please include those too.

**Comment by Belsima** [comment]
Done.

**Pull request merged**
