### PR TITLE
[DNM] Merges Modular Computers

### PR DESCRIPTION
**Pull request by Lorwp**
Merges modular computers (and commits required for them)

## TODO ##
- [ ] Merge Baystation12/Baystation12#11851 into master, and resolve merge conflicts
- [ ] Merge any other applicable PRs or commits
  - [ ] Merge Baystation12/Baystation12#10484
  - [ ] Merge Baystation12/Baystation12#12036
  - [ ] Merge Baystation12/Baystation12#12040
- [ ] Map in Computers and equipment needed to use computers
- [ ] ??? (Test it)
- [ ] Profit

### CODE REVIEW

**Comment by Lorwp** [comment]
Seems like some of the merge markers were not removed by my mergetool, going to fix them later.

**Comment by Mark9013100** [comment]
420 files changed
:leaves:

**Comment by Zuhayr** [comment]
You've pulled most of the Dev branch, looks like.

**Comment by Lorwp** [comment]
At this point i'm going to close this. It would be better to just get this with a merge of the Dev branch. Also there is [the compile logs that don't really give me confidence that this is going to work at all without introducing quite a lot of bugs indeed](https://gist.github.com/Lorwp/7a469023d283d92db0ba)

**Pull request closed without merging**
