### PR TITLE
Makes Communicators free

### PR DESCRIPTION
**Pull request by Anewbe**
Concept is to give anyone who wants a cellphone their cellphone, for free.

~~Current issues: 
Doesn't save the selected pref properly when you save slot: Goes back to a blank state every time
Doesn't actually give anyone a comm yet: I'm looking for a way to make one bit of blanket code instead of having to put it in every single job
Worded poorly: I plan on adding at least one other color of Communicator and redoing the wording, but I want to make the code work before I start adding in the shiny bits.~~

### CODE REVIEW

**Comment by Nerezza** [comment]
Is it possible to make it cost 0 loadout points?

**Comment by Anewbe** [comment]
Tried that, seems to just remove the option, instead of making it free.

**Comment by Yoshax** [comment]
This a hugely unnecessary solution for a problem that isn't a problem. The code presented here is worse than the current solution in almost all ways. It adds more of its own snowflake code in a manner that is worse than what is currently in place. The current solution ties into an already existing system and is very simple, building upon a system that handles all of the stuff, including the presenting of the thing in the loadout, the spawning of the item, etc. This, does not. It adds new things to read and write to and from the sav files, it adds more unecessary logic to various places, adds its own HTML for presenting it and further touches preferences.

Solely from a perspective of code quality I give this a large :-1: Even then, the issue is not solely the code itself, but the fact it exists at all and bloating the other things more. Character setup is already fairly bloated and poor, adding more vars, lists and logic to it does no favours.

**Comment by Anewbe** [comment]
How would you do it, then?

**Comment by Techhead0** [comment]
[Change this line](https://github.com/PolarisSS13/Polaris/blob/0bb15b27324a371804f8f625708cbe8bb03b00e0/code/modules/client/preference_setup/loadout/loadout.dm#L24) to `if(isnull(initial(G.cost)))` and 0-cost things should work.

**Comment by Anewbe** [comment]
Travis doesn't like that.

**Comment by Techhead0** [comment]
[Same problem, different place.](https://github.com/PolarisSS13/Polaris/blob/0bb15b27324a371804f8f625708cbe8bb03b00e0/code/unit_tests/loadout_tests.dm#L12)

**Comment by Anewbe** [comment]
Thank you for the help.

**Pull request merged**
