### PR TITLE
Metamorphic Pint Glass

### PR DESCRIPTION
**Pull request by Darlantanis**
So you don't need to choose between aesthetics and volume.
-Adds a metamorphic pint glass, a 60 unit version of the metamorphic glass.
-Adds 10 metamorphic pint glasses to the booze-o-mat.
-Adds an icon for the metamorphic pint glass to drinks.dmi
-Fixes metaglass sprites for mojitos and goldschlager.

### CODE REVIEW

**Comment by Atermonera** [comment]
How does... an icon file get smaller... by adding a sprite...?

**Comment by Darlantanis** [comment]
I have no idea. I was certain I made a mistake when I saw the file size drop but upon downloading the file I submitted it and comparing it side-by-side with drinks.dmi from Polaris live the only difference I could find was the sprite I added. Doing so again just now shows me no change but the sprite addition.

I also don't see icon diffs showing any changes other than my addition.

**Comment by Darlantanis** [comment]
It's been around two weeks. Is there anything I can do/change to get a yes or no on this PR?

**Comment by Atermonera** [comment]
Commenting on the PR so that I see it exists, nestled against all the ancient dnm/cnm stuff, is exactly what you should do.

**Pull request merged**
