### PR TITLE
Adds Multiple New Clothing Items

### PR DESCRIPTION
**Pull request by redstryker**
Adds the following:
- Brown and Black Chaps: accessories to be worn over pants.  Available on the loadout.
- Sexy Brown and Black Chaps: pants.  Identical to the other variety, but cannot be worn over anything.  Not on the loadout.
- Flip flops: Colorable sandals that are available on the loadout.
- Loincloth: Clothing item on the loadout.

Also allows you to 'roll down' the kilt.  Rolling it down removes the shirt from the sprite, but leaves everything else on.  Also removed the shoes from the kilt, but kept the socks because the socks are fancy.

Sprites:
Black Chaps: http://puu.sh/qIgLR/bf25a2c0f2.png
http://puu.sh/qIgN1/4dad6ef86f.png

Brown Chaps: http://puu.sh/qIgPO/d9383c39c1.png
http://puu.sh/qIgOT/1cbf3e3f7e.png

Flip Flops and Loincloth: http://puu.sh/qIgIu/04b48fd0e0.png

### CODE REVIEW

**Comment by EmperorJon** [comment]
... are we really adding fucking assless chaps.

**Comment by Anewbe** [comment]
I think most if not all chaps are assless, no?

**Comment by redstryker** [comment]
I mean... we have a mankini and stripper outfits, so *shrugs*.  The normal ones only attach to clothing.

**Comment by serenemelody** [comment]
Could the same effect as the clothing item version of the chaps be gotten from using the gear harness in tandem with the accessory chaps?

**Comment by redstryker** [comment]
....Fuck.
Well, I guess if someone abuses it, we can always bwoink 'em for it?

**Comment by Woodratt** [comment]
A loincloth...

Really... even better as a loadout item.

Really?

**Comment by redstryker** [comment]
If you don't like something on the PR, you can just up and say it.  Please refrain from rhetorical questions or sarcasm. 
In regards to the loincloth, there is a reason I put it in the 'Xenowear' category.  Tajaran and Unathi would have it as a cultural garment.  Regarding Tajaran, they have areas where they have a heavily maritime based culture, so there would be those who would wear a loincloth for practical reasons, since they would already be hot with their fur.  Unathi would have it due to the harsh environment of their home planet.  It would be cool and practical in the hot sun (if they did not mind the rays of the sun).

**Comment by redstryker** [comment]
Actually, I will add a species restriction/restriction label when I get back to my computer.

**Comment by ParadoxSpace** [comment]
I really don't think it's such a stretch for a human to wear a loincloth. It's not more revealing than short shorts.

**Comment by Yoshax** [comment]
Species restrictions are fucked.

**Comment by redstryker** [comment]
Goddamnit..

**Pull request merged**
