### PR TITLE
Added washing machine working sound

### PR DESCRIPTION
**Pull request by Heroman3003**
A small noise for washing machine working.

### CODE REVIEW

**Comment by Atermonera** [comment]
Obligatory question re: sound file source and licensing

**Comment by Atermonera** [comment]
@Heroman3003 bumping, you still need to provide a source and licensing information for this, so that we know it's compliant with our license.

**Comment by Atermonera** [comment]
If it was on an ss13 build, that should have licensing info somewhere.

**Comment by Heroman3003** [comment]
I admittedly do not understand much in terms of coding licenses, but I did find GPL3 and AGPL3 license text files in main directory.

**Comment by Atermonera** [comment]
Does README.MD, in the root directory, include a line regarding assets, icons, or sounds?
The reference line from our own readme" `All assets including icons and sound are under a CC BY-SA 3.0 license unless otherwise indicated.`

**Comment by Heroman3003** [comment]
Nothing regarding assets themselves is mentioned in readme file.

**Pull request merged**
