### PR TITLE
Porting various QOL from Bay.

### PR DESCRIPTION
**Pull request by Zuhayr**

### CODE REVIEW

**Comment by Datraen** [comment]
Boot knives already exist, AFAIK.

**Comment by Hubblenaut** [comment]
POCKET SAND

**Comment by EmperorJon** [comment]
Holster nymphs. Wow.

**Comment by zaredman** [comment]
ORANGE YOU GLAD I DIDNT SAY BANANA GUN?

**Comment by Neerti** [comment]
Looked over it, nothing glaringly obvious wrong, and I'm told that Zuhayr's bootknives shouldn't conflict with ours, so later on we can phase ours out.

**Pull request merged**
