### PR TITLE
Switch places of No and Yes in give verb to Yes and No

### PR DESCRIPTION
**Pull request by Lorwp**
I fixed it boys (i hope).

### CODE REVIEW

**Comment by Neerti** [comment]
:+1: && Travis

**Comment by Lorwp** [comment]
Welp, let me try and fix it (again)

**Comment by Zuhayr** [comment]
Why? It was changed so that you can't accidentally accept something.

**Comment by Zuhayr** [comment]
Keep in mind that this includes things like grenades, things that people might want your prints on, contaminated shit...

**Comment by Lorwp** [comment]
@Zuhayr Yeah, probably worth quickly polling the forums about this

**Comment by Neerti** [comment]
The situations where you're being given a live grenade or other malicious items by baddies is very much in the minority compared to normal people giving normal things and having to do it twice or three times because the button positions were swapped.

Also, given time, people will accept being handed live grenades once they get used to moving their mouse to the other side, so changing the positions is really not that helpful overall imo.

**Comment by Lorwp** [comment]
Yeah, i'm going to close  this. Unless we suddenly get outrage about people  not wanting to move their mouse, this probably will work out better anyway.

**Comment by Zuhayr** [comment]
@Neerti the point is that if you are typing and hit space when the prompt pops up, it will default to 'Yes' before you even see the window, like what happened with positronic brains before they were changed in the same way.

**Pull request closed without merging**
