### PR TITLE
plushie love

### PR DESCRIPTION
**Pull request by Belsima**
Port from https://github.com/tgstation/tgstation/pull/32918, you can now make little plushes kiss.

Yes, I know, high priority feature. Drown me in praise.

inb4 it dont travis

### CODE REVIEW

**Comment by BillyBangles** [comment]
you're doing God's work bels

**Comment by Belsima** [comment]
The severed heads should be allowed to kiss, now.

And @Anewbe what's that mean?

**Comment by Anewbe** [comment]
Wow, phone GitHub is wildly unhelpful. I would have the attacking item be mentioned first in the attackby, rather than the src.

**Comment by Belsima** [comment]
Ah, alright. That makes sense.

**Comment by Belsima** [comment]
the web editor is impressively shitty its as if they tried to make the worst thing feasible

**Comment by Arokha** [comment]
The web editor is intended for editing text files and desperation mostly. You're supposed to use a git client.

Have you considered porting Paradise's plushes? They have a lot. Not in this PR, I don't mean.

**Comment by Belsima** [comment]
Yeah, planning on it.

**Comment by Arokha** [comment]
Not that I want like 10 different fox plushes. Or anything.

**Comment by Arokha** [comment]
I'm looking at Paradise's toys...
```
/obj/item/toy/plushie/attack(mob/M as mob, mob/user as mob)
	playsound(loc, poof_sound, 20, 1)	// Play the whoosh sound in local area
	if(iscarbon(M))
		if(prob(10))
			M.reagents.add_reagent("hugs", 10)
	return ..()
```
🤔

**Comment by Arokha** [comment]
I doubt https://github.com/PolarisSS13/Polaris/pull/4974 will conflict with yours, because I avoided touching those lines.

**Comment by Belsima** [comment]
i dont know how to fix conflicts and i know it will because github hates me

**Comment by Arokha** [comment]
Just merge yours first then! :P

**Comment by Belsima** [comment]
I'll just do my usual ~remake and hope I know what I'm doing the second time~ magic.

**Pull request merged**
