### PR TITLE
Adds a fuckton of robot sprites.

### PR DESCRIPTION
**Pull request by nachomeep**
~~Stolen~~ Borrowed from: 
https://github.com/Baystation12/Baystation12/
https://github.com/Aurorastation/Aurora.3
https://github.com/ParadiseSS13/Paradise
https://github.com/tgstation/tgstation

Standard: http://i.imgur.com/Zp1TkBf.png
Engineering: http://i.imgur.com/u8JPyMb.png
Medical: http://i.imgur.com/VkMA95v.png
Mining: http://i.imgur.com/0MlrV0l.png
Janitorial: http://i.imgur.com/PHj3ix5.png
Service: http://i.imgur.com/5iIPdG7.png (The green ones are hydroponics. They have service counterparts that simply use the 'standard' sprites because the color scheme for that is grey.)
Clerical: http://i.imgur.com/YHKGtl4.png (I have since fixed the eyes on the bottom left and top right.)
Security: http://i.imgur.com/CLLSY0P.png
Research: http://i.imgur.com/6VdE8gZ.png

### CODE REVIEW

**Comment by Anewbe** [comment]
Any chance you can include images?

**Comment by nachomeep** [comment]
Working on that now. Incredibly tedious.

**Comment by nachomeep** [comment]
Standard: http://i.imgur.com/Zp1TkBf.png
Engineering: http://i.imgur.com/u8JPyMb.png
Medical: http://i.imgur.com/VkMA95v.png
Mining: http://i.imgur.com/0MlrV0l.png
Janitorial: http://i.imgur.com/PHj3ix5.png
Service: http://i.imgur.com/5iIPdG7.png (The green ones are hydroponics. They have service counterparts that simply use the 'standard' sprites because the color scheme for that is grey.)
Clerical: Clerical: http://i.imgur.com/YHKGtl4.png (I have since fixed the eyes on the bottom left and top right.)
Security: http://i.imgur.com/CLLSY0P.png
Research: http://i.imgur.com/6VdE8gZ.png

I'm also considering making the Janitorial Default also cross over to Research, since every department should probably have the Default skin, and they share color schemes.

**Comment by nachomeep** [comment]
oh fuck me i hate commas

**Comment by nachomeep** [comment]
shit me everything's gone down the fuckhole

**Comment by nachomeep** [comment]
Closing until I fix this. I fucked up _**everything**_ somehow.

**Comment by nachomeep** [comment]
I'm a real moron. I didn't break anything.

**Comment by nachomeep** [comment]
I really need to commit less. Gonna need to learn to squash too.

**Comment by Arokha** [comment]
My advice, take it or leave it:
Feel free to squash in your own branches (or git reset mixed and recommit and push -f to your development branch, or amend commits). But don't use the git**hub** squash merge button because it destroys important history and fucks you later.

**Comment by nachomeep** [comment]
...I'll just try to commit less in that case.

**Comment by Arokha** [comment]
I mean, if you have a branch, and you're pissed off at the number of commits, do `git reset --mixed $hash` where $hash is the one that the branch started on, as in, the one that was there when you created the branch (easy to see in GUIs that provide the little tree graph, or you can use `git reflog --date=local --all | grep branch` in git bash or some other CLI). 

`git reset --mixed $hash` will roll back your branch to that commit, but leave all your changes in all the files you've changed. You can then re-stage them all (or `git commit -a` if you want all of them) into one commit without getting insane history.

My only 'warning' about this is that you:
a) Have to `git push --force` when you push to your remote next because the history will be different, and
b) Never do this on a branch that is going to stay around. You can do it on development branches though if you're just going to delete them when your stuff is merged.

**Comment by Spacemanspark** [comment]
Oh shit, the standard module sprite.
My favorite.

**Comment by nachomeep** [comment]
DNM. Updating later with input from Mistress @elgeonmb

**Comment by nachomeep** [comment]
Basically just cut out a few shitty sprites, renamed with LORE.
NanoTrasen M-USE is this line: http://i.imgur.com/sBmJuJS.png
Ward-Takahashi Operator is this line: http://i.imgur.com/tXxQj6u.png
Morpheus CUPCAKE is this: http://i.imgur.com/HTP9ytO.png
Xion Industrial GUS is this: http://i.imgur.com/JSzsQjb.png
Xion Industrial ALP is this: http://i.imgur.com/NR8wuBl.png
Hephaestus Industries Cabeiri is this: http://i.imgur.com/yTm9tkl.png

**Comment by Anewbe** [comment]
@nachomeep The delay on this is because it takes a fair amount of time and energy to properly review sprite changes. For the most part them sprites are nice, but we just need to double-check and make sure everything is done properly.

**Comment by nachomeep** [comment]
It's just been closed because I'm entirely re-doing it since right now its a clusterfuck of files and names, and I've found more sprites.

**Pull request closed without merging**
