### PR TITLE
Refactor of admin fax handling 

### PR DESCRIPTION
**Pull request by Yoshax**
Ports Baystation12/Baystation12#13795

Ontop of that, adds the ability to select between the Nanotrasen and SolGov logo for the fax header.

### CODE REVIEW

**Comment by Anewbe** [comment]
Tested and functional?

**Comment by Yoshax** [comment]
Tested and functional.

**Comment by Yoshax** [comment]
The only withstanding issue is that the logo insertion is not primed for future expansion due to it being an alert and that you only get one chance to select the logotype. But, I'm happy enough with at as is and those problems can be resolved when we actually have a 3rd logo.

**Comment by Hubblenaut** [comment]
Long live the fax queen

**Pull request merged**
