### PR TITLE
Replaces the .45 pistol with the detective's.

### PR DESCRIPTION
**Pull request by Mark9013100**
Link to previous PR: https://github.com/PolarisSS13/Polaris/pull/615

### CODE REVIEW

**Comment by Hubblenaut** [comment]
Why is the window on that spot on one million health points..?

**Comment by GinjaNinja32** [comment]
Someone probably copied a centcom window without realising.

**Comment by Mark9013100** [comment]
Just tested that specific window, broke normally when I shot it with a energy gun, since I'm sure windows rely on the maxhealth var instead of the health var.

**Comment by Sabess** [comment]
Question. Would this replace them in cargo crates as well? Might as well do so if not. Pretty easy to do.

**Comment by Mark9013100** [comment]
Yes, it does the replace the standard pistols in cargo.

**Comment by Datraen** [comment]
What's up with the map changes? I'm fine with line 1594, but the others?
Keep in mind, this is a question coming from someone who's unfamiliar with map related things in BYOND.

**Comment by GinjaNinja32** [comment]
Looks like whoever added those particular turfs missed the starting `/`, which DM *always* saves.

**Comment by Mark9013100** [comment]
Welp, merge conflicts, closing and reopening soon-ish.

**Pull request closed without merging**
