### PR TITLE
Adds an alt-title for the HoP

### PR DESCRIPTION
**Pull request by Mark9013100**
<s>* Adds the 'Detention Officer' alt-title for the Warden.</s>

<s>* Adds the 'Crew Services Officer' alt-title for the Chaplain.</s>

* Adds the 'Crew Resources Officer' alt-title for the Head of Personnel.

### CODE REVIEW

**Comment by Yoshax** [comment]
Not a fan of the Warden title myself.

**Comment by nachomeep** [comment]
I don't like the warden title either, personally.

**Comment by Datraen** [comment]
Neither do I.

**Comment by SpadesNeil** [comment]
I like the Warden title! But, more options are always good, and these options look very good.

**Comment by sabiram** [comment]
Is the station an airline now?

**Comment by SkowronX** [comment]
Master-at-Arms works too.

**Comment by Minijar** [comment]
Two all the people who don't like the title, there's an amazing thing called just don't use them.

**Comment by sabiram** [comment]
Huh, I guess we should just have a text field to let people type whatever they want. After all, they're using it, and not us.

**Comment by Yoshax** [comment]
@Minijar Perhaps you see where two of the people who don't like them have that little 'Polaris Member' beside their names. That means something.

**Comment by Datraen** [comment]
My issue with the title "Detention Officer" is the fact that the warden does more than that, they are also in charge of the armory. Having the title "Detention Officer" kind of strips that away fluff-wise.

**Comment by nachomeep** [comment]
@sabiram I see the 'just ignore it' or 'don't use it' argument constantly- You people only opposed it in this case as far as I have seen. @Minijar 's argument is fair in this case, considering past cases where the same argument has been used successfully.

**Comment by Spookerton** [comment]
Sheriff and deputy when

**Comment by Hubblenaut** [comment]
Alt titles should be well defined and have disjoint role meanings to not conflict with each other. These new alt titles however seem very arbitrary names for what is basically the same thing - also looking at the 'Investigator' title here, which is basically a broader term for anyone doing detective-work.
I'm really not in favor of these.

**Comment by SpadesNeil** [comment]
I misunderstood the original comments up there and deleted my post. "Not a fan of the Warden title myself," everyone says.

I thought you meant you disliked Warden as a name and preferred detention officer. I was like, "But I like the title Warden!"

That isn't what I meant.

No, Detention Officer is not a good name.

I initially said The HoP's alt title of Crew Resources Officers is _okay_ but now that I think about it, that doesn't sound like a manager's role. That sounds like an alt title for either the psychiatrist or internal affairs agent.

**Comment by Datraen** [comment]
I'm fine with CRO myself, since it doesn't detract from the role.

**Comment by Mark9013100** [comment]
@Hubblenaut: The Detective role had the 'Investigator' alt-title very long ago on Baycode, I just thought it was neat and readded it.

**Comment by Anewbe** [comment]
HoP title's not bad. 

Warden, Idunno. Technically Detention Officer is an alternative name for Wardens in the US, but personally, I don't consider the (SPACE) Warden to be an Officer of any sort. I don't expect him to go out and arrest anyone, and I don't expect him to fight much. Barring abnormal circumstances, he's just the guy who sits around in the Brig, watches prisoners ~~go into cryo~~, and hands out weapons...

Couldn't think of any great alternatives, but you could possibly go with:
Brig Master, Jailer, Brig Guard, Prison Guard, or some other title that says "This guy is in charge of the station's Brig".

**Comment by SpadesNeil** [comment]
Brig Master I like actually.

**Comment by Mark9013100** [comment]
Removed the 'Detention Officer' alt-title, added the 'Crew Services Officer' alt-title for Chaplain.

**Comment by SpadesNeil** [comment]
Not a fan of the Chaplain title either. Too long, and it seems like a title suited for several other jobs so it's also too vague.

**Comment by Datraen** [comment]
Crew services officer is vague, but I don't have any problems with it I can properly present.

**Comment by Anewbe** [comment]
How 'bout Spiritual Adivisor?

We're starting to tally up the Officer ending and I don't want to hit Sanitation Engineer levels.

**Comment by SpadesNeil** [comment]
Spiritual Advisor, I like.

**Comment by Yoshax** [comment]
Is this good to merge? Does anyone have any problems?

**Comment by Anewbe** [comment]
Still not a huge fan of Crew Services Officer.

**Comment by SpadesNeil** [comment]
Neither am I. No "officer" things. It's bad.

**Comment by Spookerton** [comment]
Crew services officer doesn't fit the job description at all, sorry.

**Comment by SpadesNeil** [comment]
I **still** don't like the alt-title for HoP. :\

It just needlessly confuses people as to who the HoP is. Crew Resources Officer doesn't sound like what the HoP does. He's not a Resources Officer. He's a Manager. He's not some guy you go to when you're dealing with sexual harassment in the workplace. You talk to Internal Affairs about that.

Why are we hammering in these alt-titles anyway? None of them have been good so far and we're just abusing the word "Officer" on anything we want. If this is the route we're going we may as well slap in Sanitation Officer for janitor while we're at it. I really don't like these changes.

If we're going to have alt titles, do it without abusing the word "Officer."

**Pull request merged**
