### PR TITLE
Adds new AI cores and holograms.

### PR DESCRIPTION
**Pull request by Belsima**
Allows you to use some 'borg sprites as holograms, and adds the following cores, all animated. image

From /vg/.

### CODE REVIEW

**Comment by Anewbe** [comment]
Images.

**Comment by Belsima** [comment]
I make the PRs first as to be able to copy paste the DMI directly.

**Comment by Anewbe** [comment]
What're those from?

**Comment by Belsima** [comment]
/vg/.

**Comment by Anewbe** [comment]
The two on the right definitely look like they were taken from something with copyrights.

**Comment by Belsima** [comment]
The two on the right were taken from /vg/. image

**Comment by Belsima** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/icons/mob/AI.dmi

**Comment by Anewbe** [comment]
That it may be, but the icons themselves look like someone on /vg/ took them from something else, idea wise.

**Comment by Belsima** [comment]
we have xenomorphs and astromech custom robot sprites, anewbe

**Comment by Anewbe** [comment]
And I'd rather not add more to that.

**Comment by Belsima** [comment]
https://github.com/PolarisSS13/Polaris/pull/3654
image

These are literally direct rips off of fallout- the /vg/ one is just a generic anime face.

**Comment by Anewbe** [comment]
I am opposed to adding those sprites. Please remove them.

**Comment by Belsima** [comment]
I made the PR mainly to get them in, so no point then.

**Comment by Belsima** [comment]
Given you merged the fallout sprites, merged the xenomorphs, and approved the astromech (one of which was 2 weeks ago), when did this policy start? Especially since these are all things that directly reference things in sprite and code, and in the titles of the PRs and commits, yet these are just generic faces that you can't pinpoint any infringement from.

**Comment by Belsima** [comment]
https://github.com/PolarisSS13/Polaris/pull/3762
For reference, this is the PR where you merge xenomorph sprites that are called 'Xenomorphs' in the code.

**Comment by Anewbe** [comment]
The xenomorphs were specifically readded at the request of staff. I didn't have the time to replace them with something else.

**Comment by Belsima** [comment]
Could you elaborate on the Fallout sprites you merged, then? Given the title even says it's from Fallout, I'm not sure I understand when this policy started or where it's listed, or- still- how the AI core sprites fit into this and the Fallout cyborg doesn't.

**Comment by Wutnold124** [comment]
is bcuz anewbe donut want animAI

**Comment by Belsima** [comment]
Even if it was inspired by starbound, it's not very close. image

I hadn't even noticed Terminal's similarity to Discord, though.

**Comment by Mechoid** [comment]
I meant the older AIs that were differentiated by species, but, yes, if you want to reopen this as a new PR I have no issue. I would personally wait until the currently open AI sprite PR is resolved however.

**Comment by Belsima** [comment]
That _is_ the old human one.

**Pull request closed without merging**
