### PR TITLE
Removes RNG from emag

### PR DESCRIPTION
**Pull request by Belsima**
Not expecting this to get immediately merged; Anewbe had prior stated this would require discussion, so I'm putting this up for potential discussion. Will also make forum thread.

EDIT: https://forum.ss13polaris.com/viewtopic.php?f=14&t=493

### CODE REVIEW

**Comment by Arokha** [comment]
Makes sense, considering the emag already has an RNG in it for uses. Sort of silly to have an RNG on top of an already player-opposed RNG.

**Comment by Belsima** [comment]
Agreed.

**Comment by Belsima** [comment]
So far, literally nobody against.

**Comment by Belsima** [comment]
Closing because a direct buff isn't the answer. Will be looking for alternatives to 'theres a 50% chance you get fucked'.

**Pull request closed without merging**
