### PR TITLE
Made ./github

### PR DESCRIPTION
**Pull request by Lorwp**
- Made [./github](https://github.com/blog/2111-issue-and-pull-request-templates) Folder
  - Made [ISSUE_TEMPLATE.md](https://github.com/Lorwp/Polaris/blob/4c368be712780e0d84d7e0e48e09300aec78fb08/.github/ISSUE_TEMPLATE.md)
  - Moved CONTRIBUTING.md to ./github

Profit

(And if Travis Fails on this, i'm eating a shoe)
(pinging @Neerti also, as they partly own the repo)

### CODE REVIEW

**Comment by Lorwp** [comment]
:mans_shoe:

**Comment by Neerti** [comment]
For the dummies here (like me), what exactly does this do?

**Comment by Neerti** [comment]
Zuhayr told me what this does, gets a :100: :+1: from me.

**Comment by PsiOmegaDelta** [comment]
For everyone else, what this file is used for is a template for issues tickets and the contents is automatically added when opens a new one.

**Pull request merged**
