### PR TITLE
1.5.2 Woodrat Breaks the map

### PR DESCRIPTION
**Pull request by Woodratt**
- Major changes to the civilian areas. Rooms such as the vault have been moved elsewhere on station.
- Communal Dorm near cryo removed as they were never used.
- Fixed Space tiles in windows next to robotics.
- Fixed Chargers in Robotics.
- Small bug fixes such as camera in the CE office name. Fixed https://github.com/PolarisSS13/Polaris/issues/1579
-  Cash Register Issue, at least for the kitchen. Fixed https://github.com/PolarisSS13/Polaris/issues/1452
-  Missing Patient Window Fixed https://github.com/PolarisSS13/Polaris/issues/1748
- Engineering Pump Station Access Fixed https://github.com/PolarisSS13/Polaris/issues/1735

This should mean the map hold will be no longer in effect when merged.

Image links.

Civilian area [Link](http://i.imgur.com/gYkQT14.png)

Vault [Link](http://i.imgur.com/hIlDY8J.png)

Locker Room[Link](http://i.imgur.com/1S3l0BC.png)

Secondary Tool Storage [Link](http://i.imgur.com/LFRXH0g.png)

Primary Tool Storage [Link](http://i.imgur.com/1pe1wo2.png)

### CODE REVIEW

**Comment by EmperorJon** [comment]
## UNIT_TEST: --------------- Vacant Site(/area/vacant/vacant_site) lacks an Air scrubber.
## UNIT_TEST: --------------- Vacant Site(/area/vacant/vacant_site) lacks an Air vent.
## UNIT_TEST: !! FAILURE !! [MAP: Area Test APC / Scrubbers / Vents Z level 1]: [1/203]Some areas lacked APCs, Air Scrubbers, or Air vents.

**Comment by Yoshax** [comment]
Is that the vacant bar?

**Comment by Woodratt** [comment]
That, would be the vacant bar. I didn't add a scrubber or vent this time. Odd.

**Comment by Mark9013100** [comment]
Cyro shuttle: We are clear to go, let's get the fuck outta' here!

**Comment by EmperorJon** [comment]
I'm going to download this myself in ~12 hours and update the NanoUI map so that we can get that merged at the same time as this, if nobody beats me.

**Comment by Yoshax** [comment]
:+1: From a 'it works' perspective. I see no issues. Areas are good, wires, pipes, etc.

I have a few issues and reservations with some of the changes, but that's more opinionated. 

However, as one thing, it may be nice to have the locker room showers split into seperate cubicles and expanded, or something along those lines. There's a lot of space to use down there. There's also a space for another vendor right there in the locker room, fitness vendor pls.

**Pull request merged**
