### PR TITLE
O2 to O2. With lower 2. Because I give up.

### PR DESCRIPTION
**Pull request by Belsima**
Rather than O², it's now O<sub>2</sub>.
image from image

Partially ported from https://github.com/vgstation-coders/vgstation13/pull/9193. I did most HUDs on my own.

### CODE REVIEW

**Comment by PJB3005** [comment]
> He didn't even use Unicode to make the title correct.

Also, `O<sub>2</sub>` and `O<sup>2</sup>` for markdown signs.

**Comment by Belsima** [comment]
I'm a pitiful human being

**Comment by Arokha** [comment]
Muh immershuns.

**Comment by Belsima** [comment]
This was a high priority change, I'll have you know.

**Comment by Arokha** [comment]
Merge ASAP

**Comment by Anewbe** [comment]
If you review the sprite changes, then sure?

**Comment by Arokha** [comment]
I was meme'ing, sorry. 😄

**Comment by Anewbe** [comment]
Seeeeeems fine, worse comes to worst, will revert.

**Pull request merged**
