### PR TITLE
Fixes some unseen combat ai jank

### PR DESCRIPTION
**Pull request by Verkister**
haha lack of exit condition go brrrr

kuva

### CODE REVIEW

**Comment by Neerti** [comment]
Does this conflict with #8112?

**Comment by Verkister** [comment]
Should be fine on the same spot with just adjusting the tabbing. Aro might probably still slap a small fix in that PR considering there's a > facing wrong way that they spotted. Basically it works with the current code, but Aro might have their own approach planned to replace this part for their PR.

**Comment by Atermonera** [comment]
Was this addressed by aro's PR?

**Comment by Verkister** [comment]
Wasn't addressed, just mitigated by the timeout part there. The spam would still happen for the timeout wait period. This PR makes the spam not happen in the first place.

**Pull request merged**
