### PR TITLE
Fixes two bar recipes

### PR DESCRIPTION
**Pull request by Hubblenaut**
Changes iced tea and iced coffee recipes to make sense again and easily fill a 30 unit container.

### CODE REVIEW

**Comment by Kelenius** [comment]
Mix ice and tea 1:2?..

**Comment by Hubblenaut** [comment]
The other choice is 1:5

**Comment by Kelenius** [comment]
I think that filling 1/6 of the glass with ice makes more sense than 1/3. But that's just my opinion.

**Comment by Hubblenaut** [comment]
It both equally doesn't make much sense.
Yet another alternative: 1 part coffee, 1 part ice, 1 part cream

**Comment by Spookerton** [comment]
:+1:

**Pull request merged**
