### PR TITLE
Touches up Skrell sprites

### PR DESCRIPTION
**Pull request by Anewbe**
All of their pixels are in the right place now.

### CODE REVIEW

**Comment by Belsima** [comment]
I thought I already did that- were there More clippings?

**Comment by Anewbe** [comment]
Yes. Test your code, please.

**Comment by Belsima** [comment]
I did- the legs no longer clipped on the side states in my tests. What else was the issue?

**Comment by Belsima** [comment]
Ah. I fixed htem clipping out the front, since that was all I got reported. My bad.

**Pull request merged**
