### PR TITLE
Replaces xenoarch sprites + inhands.

### PR DESCRIPTION
**Pull request by Belsima**
Taken from: https://github.com/vgstation-coders/vgstation13, https://github.com/VOREStation/VOREStation, https://github.com/Endless-Horizon/CEV-Eris and https://github.com/tgstation/tgstation.

### CODE REVIEW

**Comment by Anewbe** [comment]
If I remember correctly, you don't need the item_state if the icon_state is the same thing.

**Comment by Belsima** [comment]
Oh. That makes things easier.

**Comment by Anewbe** [comment]
Alright, can you make previews for the things you've changed? Because I can see already that you've changed and replaced sprites.

**Comment by Belsima** [comment]
Ooh boy. This'll be a long one.

**Comment by Belsima** [comment]
Anomaly Scanner: image
Depth Scanner: image
Guns: image
Artifacts (old sprites were literally like 6 pixels per sprite): image
Replacement anomalies: image
Replaced anomalies were of this quality: image
Container: image
New measuring tape (old one was literally a ball of brown pixels): image
New rock: image
New location scanner: image
New EFTPOS: image
Do you want previews of inhands too?

**Comment by Anewbe** [comment]
Looking at the sprites, I see you changed the anomaly scanner to a different sprite, and in the preview you've got the old one. Please don't do that.

Some other thoughts:

- The gun sprites you have there seem sort of massive.
- Also, the old measuring tape sprite is in front of the 'new' one, that'll probably end up as the sprite that shows up in game.

As another note, please don't remove old sprites. Coders are lazy and sometimes the only thing stopping someone from making a new feature is lack of sprites, which leads to code diving, which leads to old sprites getting reused.

**Comment by Belsima** [comment]
Sorry, I used the wrong link on the anomscanner. I was actually about to commit a fix for the tape and then my oven dinged so I went, I'll fix that now.

**Comment by Belsima** [comment]
Replaced big guns with some older sprites: image

**Pull request closed without merging**
