### PR TITLE
Removes a frequent runtime

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by Nerezza** [comment]
That one's super noisy when someone's not breathing, huh? :P

**Comment by Yoshax** [comment]
You have,

`if(!breath...)`

then `if(breath...)`

**Comment by Anewbe** [comment]
The first line is `if(!breath || (breath.total_moles == 0) || suiciding)`, so if the others happen it run-times.

**Comment by Yoshax** [comment]
350-351 never executes with the changes, making lung rupturing never happens.

**Comment by Nerezza** [comment]
I could be reading it wrong, but that might be why 353 is there.

**Comment by Yoshax** [comment]
My professional has suggested you remove 349-352, delete the else, then put 350-351 below 374.

**Comment by Anewbe** [comment]
Why?

**Comment by Yoshax** [comment]
So lung rupturing can still occur in circumstances where `if(breath && breath.total_moles)` is not true, such as where total_moles = 0.

**Comment by Anewbe** [comment]
That's what the else is for?

**Pull request closed without merging**
