### PR TITLE
Makes phoron very purple.

### PR DESCRIPTION
**Pull request by nachomeep**
image
image

### CODE REVIEW

**Comment by Anewbe** [comment]
Do like the idea of purple phoron, will need to pass this PR around to see if anyone has thoughts on it.

**Comment by nachomeep** [comment]
Even if the gassy sprites aren't wanted, there's a purple version of our current Phoron sprite in the files.

**Comment by Anewbe** [comment]
Probably best to just use the purple version of our current sprite, it works well for what we need it to do, and the square edges on the new sprites raise concerns.

**Comment by nachomeep** [comment]
Fair enough, then.

**Comment by Anewbe** [comment]
This will need to be passed back up to the staff, there were some reservations when I floated the idea of everything being purple.

**Comment by nachomeep** [comment]
Alright. I just figured that if things were going purple, might as well be consistent.

**Comment by Screemonster** [comment]
Even if the gas is purple, I'm not sure why an engineering department would store it in a purple container. Things are BRIGHT DANGER SAFETY ORANGE for reasons other than the colour of the contents.

**Comment by nachomeep** [comment]
Fair enough. I'll gladly change it back if wanted, but I like the purple sprites.

**Comment by nachomeep** [comment]
Now that I think about it, it does make more sense, but still gonna wait for Anewbe to get back to me.

**Comment by Serithi** [comment]
Maybe orange with purple stripes?

**Comment by nachomeep** [comment]
That makes sense. Like N2O.

**Comment by Yoshax** [comment]
Hope you realise this had the undocumented and unmentioned change of change the tank along with the canister + gas sprites. 

![Phoron Tank(https://cdn.discordapp.com/attachments/187013248309002240/289091711840550922/phoron_-_Copy.png)

**Comment by Anewbe** [comment]
I missed that, but I can still find use for that sprite.

**Comment by nachomeep** [comment]
Shit, sorry. I literally did all that right after waking up and in the 20 mins I had before school started. Should've double checked my edits to the github went through.

**Pull request merged**
