### PR TITLE
Meatspike fixes.

### PR DESCRIPTION
**Pull request by Belsima**
Grammar and standardization, as well as ensuring only the intended mobs get spiked (NO TESHARI GOD DAMN IT).

### CODE REVIEW

**Comment by Belsima** [comment]
eat my ass travis

**Comment by Belsima** [comment]
i assume im using this helper wrong im a moron i'll use actual git to fix this instead of this web shit

**Comment by Belsima** [comment]
When you do merge, squash, please. I dunno how because I'm a moron. :D

**Comment by Belsima** [comment]
oh you're a FUCKER travis

**Comment by mistyLuminescence** [comment]
you know you can avoid all this if you write "fight me travis" in the PR when you open it right

**Comment by Belsima** [comment]
i choose to instead engage in mud-wrestling

**Comment by Atermonera** [comment]
Or, y'know, compile and test your code

**Comment by Belsima** [comment]
compiling is a cheap tactic to make weak coders stronger

**Pull request merged**
