### PR TITLE
Makes the clotting cargo crate more expensive

### PR DESCRIPTION
**Pull request by Anewbe**
As per the last Staff Meeting, cargo's supply of clotting agent is more expensive.

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
100 points is ridiculously excessive for clotting medicine. 40 is pretty high on its own.

**Comment by Anewbe** [comment]
Staffed discussed it, and this was the compromise.

**Comment by mistyLuminescence** [comment]
100 points is a 'compromise' in the same way that "how about I don't kill you, I just stab you in the chest a few times?" is a compromise. If you want to make each individual injector more expensive, why not just have less per crate? 4 clotting injectors and 3 empty injectors, maybe.

**Comment by Anewbe** [comment]
Your other option is having the crate removed entirely. I'm tired of having to fight tooth and nail over every change that affects Medical.

**Pull request merged**
