### PR TITLE
Waistcoats are accessories

### PR DESCRIPTION
**Pull request by Anewbe**
Additionally, split a few ensemble uniforms into parts, a la the suit_jacket items. These are the detective outfits with waistcoats, and the gentleman's suit.

### CODE REVIEW

**Comment by Yoshax** [comment]
You could make them both and retain the current features, whilst adding more.

**Comment by Yoshax** [comment]
Also messes with chameleon kits which cannot into accessories.

**Comment by Anewbe** [comment]
Would that work with the starting_accessories list?

**Comment by Yoshax** [comment]
Not entirely sure. You could make the accessories wearable on the outer suit slot but have them defined as accessories by type, much like ponchos. As for the chameleon kit stuff, a chameleon tie or whatever would be trivial.

**Pull request merged**
