### PR TITLE
Speeds up toxin

### PR DESCRIPTION
**Pull request by Anewbe**
Ups the speed at which toxin based reagents work by a factor of 5.

### CODE REVIEW

**Comment by Yoshax** [comment]
Seems like a very large jump. Can we get some number comparisons on times it would take to die, etc?

**Comment by Anewbe** [comment]
Totes.
Damage formula is (strength*removed), so the base toxin takes 50 units to kill, ignoring hardcrit. This remains constant.
Current toxin metabolism = REM *

**Comment by Anewbe** [comment]
On my phone, can't edit last post, continuing here
Metabolism = REM*0.05, or 0.01. This means the aforementioned 50 units toxin does ~0.04 tox damage per check, and it takes 5000 ticks to process out.
With this PR, metabolism = REM*0.25, or 0.05. You will take ~0.2 tox per tick, and it'll take 1000 ticks to process out. It'll still take basically a whole bottle of toxin to kill you, but now it won't linger for ages.

**Comment by Anewbe** [comment]
Put a little multiplication sign after those REMs, formatting ate them.

**Comment by Yoshax** [comment]
Works for me.

**Pull request merged**
