### PR TITLE
Make it so you can FINALLY export other things but platinum and phoron.

### PR DESCRIPTION
**Pull request by lbnesquik**
Man, that thing is a LONG time coming and it was surprisingly easy.
Prices are as follow:

- Silver 2
- Marble 2
- Gold 2
- Uranium 2
- Lead 2
- Platinum 5
- Phoron 5
- Titanium 6
- Plasteel 6
- Osmium 6
- mhydrogen 6
- Verdantium 8
- Diamond 8
- Durasteel 9
- Morphium 13 _spooky_

### CODE REVIEW

**Comment by MistakeNot4892** [comment]
You would be better served by making sale cost a variable on the material datum.

**Comment by lbnesquik** [comment]
> 
> 
> You would be better served by making sale cost a variable on the material datum.

I have no real idea how to make that system, so i'll leave that to someone who actually knows what they are doing.

**Comment by MistakeNot4892** [comment]
https://github.com/MistakeNot4892/Polaris/commit/046074a6f3850a2c34fc3f923e3c55d3cde01c28

**Comment by lbnesquik** [comment]
> 
> 
> [MistakeNot4892@046074a](https://github.com/MistakeNot4892/Polaris/commit/046074a6f3850a2c34fc3f923e3c55d3cde01c28)

Do you want me to redo that or wait for you to make a PR, pull and then do it? @MistakeNot4892

**Comment by MistakeNot4892** [comment]
Whichever you would prefer.

**Comment by lbnesquik** [comment]
I'll wait for a merge, it seems the least 'risky' way

**Comment by MistakeNot4892** [comment]
https://github.com/PolarisSS13/Polaris/pull/7283

**Comment by KasparoVy** [comment]
Fantastic, thanks @lbnesquik & @MistakeNot4892

**Pull request merged**
