### PR TITLE
Uplink cost tweaks

### PR DESCRIPTION
**Pull request by Yoshax**
I'm going to explain this PR in a diferrent manner than I normally do due to the nature of it. First I will detail my intentions and goals, second I will do a comparison.

Firstly, to put my biggest goal on paper, in general, this is a buff, many items are less expensive. To further explain, the cost of many lesser uses items, or ones seen as useless or less expensive have been reduced in cost, while some of the most useful and dangerous & deadly have been reduced in cost. I would like to see more variation in the items both traitors and mercenaries buy, and so, this is why I have done what I have.

Now for comparisons. I will now list each item with the previous price, and new price, along with the difference.

**Announcements**

Fake Centcom: 60 -> 40 (-33%)
Fake Crew Arrival: 40 -> 30 (-25%)
Fake Radiation Storm: 30 -> 15 (-50%)

**Armor**
Combat Armor Set: 50 -> 60 (20%)

**Badassery**

To now before I list the items, I have reworked the costs of these random crates to make them more appealing. As such, for the ones that exist currently I will list the current cost and current item worth (which determines how much you get.)

Surplus Crate:
- Item Cost: 400 -> 120
- Item Worth: 600 -> 240

Now for the new surplus crates:

Surplus Crate 2:
- Item Cost: 240
- Item Worth: 360

Surplus Crate 3:
- Item Cost: 480
- Item Worth: 720

Surplus Crate 4:
- Item Cost: 720
- Item Worth: 1440

The ones above the one costing 120 are designed for mercenary teams, or traitor perhaps working together. The more you spend on your surplus crate, the more you get. Each tier has an increase on the previous and you gain a higher percent of the base TC amount when compared.

**Grenades**

Note: Singular grenade purchases have been added, furthermore the previous boxes of 5 have became 7.

Photon Disruption Grenades: 20 -> 10 (-50%)
Cost Per Grenade: 4-> 1.43 (-64.25%)
Singular Cost: 2

Metal Foam Grenades: 30 -> 100 (-66%)
Cost Per Grenade: 4.29 -> 1.43 (-66%)
Singular Cost: 2

Smoke Grenades: 20 -> 10 (-50%)
Cost Per Grenade: 2.86 -> 1.43 (-50%)
Singular Cost: 2

EMP Grenades: 30 -> 50 (66%)
Cost Per Grenade: 6 -> 7.14 (19%)
Singular Cost: 10

Flashbangs: 40 -> 40 (0%)
Cost Per Grenade: 5.7 -> 5.7
Singular Cost: 8

Frag Grenades: 
Note: Frag Grenades have a "half box" that holds 4.

Full Box: 60 -> 80 (33%)
Cost Per Grenade: 12 -> 11.42 (-4.83%)

Half Box: NaN -> 50
Cost Per Grenade: NaN -> 12.5

Singular Cost: 15

**Hardsuit Modules**

Thermal Scanner: 20 -> 15 (-25%)
Net Projector: 30 -> 20 (-33%)
Electrowarfare Suite and Voice Synthesiser: 40 -> 30 (-25%)
Manoeuvring Jets: 40 -> 30 (-25%)
Power Sink: 60 -> 45 (-25%)

**Implants**

Compressed Matter Implant: 40 -> 30 (-25)%

**Medical**

Sin Pockets: 10 -> 5 (-50%)
Surgery Kit: 60 -> 45 (-25%)
Portable Freezer: 20 -> 10 (-50%)
Ambrosia Seeds: 10 -> 5 (-50%)
Ambrosia Deus Seeds: 20 -> 10 (-50%)

**Stealth Items**

Agent ID: 20 -> 10 (-50%)
No-Slip Shoes: 20 -> 10 (-50%)
Bug Kit: 20 -> 10 (-50%)
Chameleon Kit: 30 -> 15 (-50%)
Chameleon Projector: 40 -> 30 (-25%)
Voice Changer: 40 -> 30 (-25%)
Camera Network Access: 60 -> 30 (-50%)

**Stealth Weapons**

Subversive Soap: 10 -> 5 (-50%)
Paralysis Pen: 30 -> 40 (33%)
Cigarette Kit: 30 -> 15% (-50%)
Random Toxin - Beaker: 30 -> 15% (-50%)

**Tools**

Binary Translator Key: 30 -> 20 (-33%)
Morhic Clerical Kit: 30 -> 15% (-50%)
Operations Funding: 30 -> 15% (-50%)
Space Suit: 30 -> 15% (-50%)
Hacked AI Upload Module: 70 -> 60 (-14.2%)
Hacked Supply Beacon: 70 -> 60 (-14.2%)
Teleporter Circuit Board: 200 -> 180 (-10%)

**Visible Weapons**

Dart Gun: 50 -> 30 (-40%)
Energy Crossbow: 50 -> 40 (-20%)
Silenced .45: 50 -> 40 (-20%)
Revolver: 60 -> 70 (16%)
.357 Derringer Pistol: 50 -> 40 (-20%)
Tommygun: 70 -> 60 (-14%)
Assault Rifle: 70 -> 75 (7%)
Combat Shotgun: 70 -> 75 (7%)
Energy Gun: 50 -> 60 (20%)
Laser Carbine: 70 -> 75 (7%)
Ion Rifle: 50 -> 40% (-20%)
Xray Gun: 70 -> 85 (21%)

If you've gotten this far, thank you for taking the time to read this large list, it took quite some time to write it all. I would again like to close by stating my intentions, I wish to see a different play style from these antagonists, and I have done so here by reducing the cost of many potentially useful items while slightly increasing the cost of the most dangerous weapons. Again, thank you for reading.

### CODE REVIEW

**Comment by serenemelody** [comment]
I can't see any issues with it, personally. I like it.

**Comment by EmperorJon** [comment]
I see a lot of things which aren't guns are getting significantly cheaper. Good work on the revolver getting more expensive!

**Comment by Yoshax** [comment]
I spoke with some people, and my intentions are really to get people to do new things. Right now, you want to kill someone? You buy a revolver. Etc, there's too much of a formula and it's boring. It's hard to justify paying the current costs. "I could get a toxin to try and poison someone, or I could get a revolver for only 30 more." It's absurd. I'd like to see some of them potentially even lower, but this is good for now. I'm hoping it will encourage people to be more interesting, because now you can get much, much more when you're trying to be interesting.

For example, now you could get:
Clerical Kit: 15
Bug Kit: 10
Funds: 15
Chameleon Kit: 15

You can be super, infiltrating spy dude. And that's only 45% of your budget. To do that right now would cost, 110, or 90% of your budget. I feel as though this will encourage more interesting and varied ideas.

**Comment by Anewbe** [comment]
Looks good to me, will merge later if no one has complaints.

**Comment by Woodratt** [comment]
I like it, fund it.

**Pull request merged**
