### PR TITLE
Removes violations of the geneva conventions.

### PR DESCRIPTION
**Pull request by Belsima**
Turns red crosses into green ones. Merge ASAP, I modded a lot of files and don't want to go around and fix shit this was tedious and I don't know how to Git.

Also recolors a lot of medical equipment to be green rather than blue, for a consistent color scheme.

### CODE REVIEW

**Comment by Belsima** [comment]
Now also turns a bunch of blue items green, to fit in with the color scheme better.

**Comment by Belsima** [comment]
Redoing this at a later point.

**Comment by Neerti** [comment]
I'd prefer if the green items be made blue since iirc blue is what is used in medbay besides white.

**Comment by Belsima** [comment]
The airlock was also green and plenty of green crosses already existed so I assumed that was the intended color scheme; I'll make a blue version tomorrow.

**Comment by Neerti** [comment]
Upon feedback with some other stuff, we'd prefer if you just changed the cross to a green or blue version, since changing other stuff will probably cause similar issues to other PRs that changed a load of icons at once taking forever to be reviewed.

**Comment by Belsima** [comment]
Alright.

**Pull request closed without merging**
