### PR TITLE
Splits underwear into top underwear and bottom underwear

### PR DESCRIPTION
**Pull request by Yoshax**
-Splits underwear into top and bottom
-Removes gender split

### CODE REVIEW

**Comment by Yoshax** [comment]
Should be good now, lest I've forgot anything.

**Comment by Mark9013100** [comment]
Now I can cover my moobs, best PR of the year

**Comment by Datraen** [comment]
:+1:

**Comment by Dragor** [comment]
Yes.

**Comment by Neerti** [comment]
Look a quick look at this, it appears you didn't change the underwear wardrobe or whatever it's called that you click on to change your socks/underwear/undershirt/etc.

**Comment by Yoshax** [comment]
I did. See: d64bfb323516d8e3315ecd82e521200a905ff855

**Comment by Neerti** [comment]
I'm blind, wooo.

An alternate to alert is to use input(), and supply a list of options, however this implementation (of the underwear wardrobe) should work just fine.

**Comment by Datraen** [comment]
I'd honestly prefer another pick, rather than abusing the fact that you can close it.
It's more clear to the player when that is done.

**Comment by Yoshax** [comment]
I think it works good as is, it remains basically the same as it is now, except it has top/bottom instead of male/female.

**Comment by Datraen** [comment]
Apparently I misread something, never mind!
Back to :+1: from me.

**Pull request merged**
