### PR TITLE
Polaris fixes

### LINKED ISSUE #501: Ninja can teleport to turfs visible on camera console
Not tested with laptops. Massive oversight that allows a ninja to use their "within vision" turf jumping ability to jump even between Z-levels if necessary. Discovered when a ninja teleported from security to the mining outpost.

### PR DESCRIPTION
**Pull request by GinjaNinja32**
fix #501, #477, #424, #389, #482, #447

### CODE REVIEW

**Comment by GinjaNinja32** [comment]
noone offered sprites so i made some bad ones

**Comment by Earthcrusher** [comment]
Those sleeper sprites are actually pretty decent!

**Comment by GinjaNinja32** [comment]
@Earthcrusher, the sleeper sprites were from /tg/ when I fixed them on Bay, the console sprites are the ones I made.

**Pull request merged**
