### PR TITLE
Merc changes

### PR DESCRIPTION
**Pull request by Yoshax**
Adds to merc base:
-Megaphones
-Flares
-Maglights
-Binoculars
-Station bounced radios
-Cameras + film

Ship adjustments:
-Adjusts surgery room
-Gives rollerbeds
-Removes blast door computer, adds buttons

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
9.5/10 it's ok

**Comment by Datraen** [comment]
Can we have pictures?

**Comment by Yoshax** [comment]
Merc ship: https://i.gyazo.com/acf0dc650229ccda8dda0c02d17cbb92.png
The two buttons for the blastdoors are one in the airlock, and one in the main hallway.
The surgical tools have been shifted around because in the current setup you cannot reach the items on the table that are in the corner under the sink.

Merc armory: https://i.gyazo.com/cb760ff6338f6ec76cf3ae91b49750d8.png
Room was expanded for extra racks.
6 of each item I added, barring flares, which there is 12 of.

**Comment by Datraen** [comment]
:+1: Even though mercs could use more drills.

**Comment by Yoshax** [comment]
I wanted to remap their whole base, but couldn't decide on how I want to. So might do that in the future and add drills and stuff.

**Pull request merged**
