### PR TITLE
Port Bay's vendor/smartfridge sprites

### PR DESCRIPTION
**Pull request by Arokha**
3:4 style, and they all have deny and vend icons unlike the random mishmash that have them currently.

dreammaker_2020-03-16_18-53-41

They also have all 4 directions, woo.

dreammaker_2020-03-16_18-56-22

The fridges also have various overlays that show drinks/meds/food inside them as they get more and more stocked.

### CODE REVIEW

**Comment by zekesulastin** [comment]
The only thing I question at all are the side view trapezoid sprites for the fridges, since we don't use trapezoid walls.  Everything else looks great!

**Comment by Arokha** [comment]
> The only thing I question at all are the side view trapezoid sprites for the fridges, since we don't use trapezoid walls. Everything else looks great!

Indeed, but just don't rotate them and you get much the same as you do now, with added benefit of having a few varieties of them, plus the overlay sprites for contents!

**Comment by Arokha** [comment]
Also, sidenote, if you did want those walls I already ported them to this codebase on a branch for a map I'm working on for downstream, plus the half-wall stuff and windows and whatnot.
dreamseeker_2020-03-04_17-01-36

**Comment by Schnayy** [comment]
Vending machines are fine by me. Very against those walls.

**Comment by Arokha** [comment]
Just an offer! You do you!

**Comment by Arokha** [comment]
Sooooooooo

**Comment by Atermonera** [comment]
It's staff input so this is unfortunately stuck for a week until the next staff meeting (biweekly on sundays)

**Pull request merged**
