### PR TITLE
Adds skrellian labcoat.

### PR DESCRIPTION
**Pull request by Belsima**
Sprited by @Schnayy, concept art by @Paradoxon.

Also adds gloves to departmental biosuit sprites [the generic one already had them], ported from. https://github.com/Baystation12/Baystation12/pull/15409.

Also also fixes the Skrellian preview sprite's eyes.

### CODE REVIEW

**Comment by Anewbe** [comment]
Images, please.

**Comment by Belsima** [comment]
image

**Comment by Anewbe** [comment]
Darken the inner lines a tad, please?

**Comment by Anewbe** [comment]
Also I'd like sprites for the biosuits, too.

**Comment by Belsima** [comment]
https://puu.sh/tc2WK/bbf6deb742.png

I'll fix the labcoat some time in the next two days.

**Comment by Anewbe** [comment]
Change the boots on the orange one to be orange, and the ones on the second-to-last sprite to match the rest of the sprite, please.

**Comment by Belsima** [comment]
The orange one is actually what we have now, but sure.

**Comment by Belsima** [comment]
I never learned how to fix conflicts.

**Pull request closed without merging**
