### PR TITLE
Borgs should no longer be shocked by wires

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by SilverTalismen** [comment]
*Thank you!!*

**Comment by zaredman** [comment]
So uh I'm not totally gifted in the arcane art of coding but this strikes me as a case of "title is not completely reflective of the changes."

Clarification is appreciated.

**Comment by zaredman** [comment]
Also how the fuck am I a "Polaris contributor" when all I do is just post

**Comment by Anewbe** [comment]
Stumbled into a better way to do this, closing this PR.

**Pull request closed without merging**
