### PR TITLE
Adds even more underwear

### PR DESCRIPTION
**Pull request by Yoshax**
Sprites courtesy of Serithi

### CODE REVIEW

**Comment by Serithi** [comment]
Pics for those curious.
Front, back and side (slightly older version of it, but it's only off by a couple pixels) http://i.imgur.com/5bIQ0mY.png
Colors http://i.imgur.com/a6NA0xq.png

**Comment by Hubblenaut** [comment]
..giant bald ladies.
(Also not in favor of that sprite Serithi)

**Comment by sabiram** [comment]
That's a swimsuit

**Comment by Zuhayr** [comment]
Why.

**Comment by Neerti** [comment]
Not a fan of this myself, since it looks a bit too.. suggestive, let's say.

**Comment by Datraen** [comment]
I feel the same way as Neerti on this one.

**Comment by Serithi** [comment]
@Neerti You _have_ seen the "thong" underwear sprite we have, right :v. This technically covers stuff that thong _doesn't_.

@sabiram This is a type of halterneck bra. Felt like doing something a little more different than the generic designs we have right now. And bear in mind that swimsuits aren't exactly that much different to underwear anyway.

**Comment by sabiram** [comment]
I'm fairly well educated when it comes to ladies' undergarments

I think this sprite would be better as a swimsuit, that's all~

**Comment by Earthcrusher** [comment]
I like it. It's surprising the shape came out so well for how little space you had to work with.

**Comment by zaredman** [comment]
#underweargate2560

Completely un-shockingly, I really couldn't care about what people wear. So I'm :+1:

**Comment by Serithi** [comment]
@zaredman If it works for both, go ahead and pop it in swimwear too :v.

**Comment by Spookerton** [comment]
Just adding another :+1: from the general staff side, since pixel nipple covers are scary.

**Comment by Yoshax** [comment]
If anyone wants anything done or whatnot, it's basically Serithi's PR, I just made it because he can't into git.

**Pull request merged**
