### PR TITLE
Mech noises update.

### PR DESCRIPTION
**Pull request by lbnesquik**
This add more noise feedback for mechs:
-Light on and off
-Gygax overload
-Durand defence mode.

### CODE REVIEW

**Comment by Anewbe** [comment]
Where did those sounds come from?

**Comment by lbnesquik** [comment]
I think they mostly come from freesound.com

**Comment by lbnesquik** [comment]
All noises have been confirmed as creative commons or remplaced by others.

**Comment by Neerti** [comment]
If its not too much trouble could you link to them directly?

**Comment by lbnesquik** [comment]
I didn't bookmark the links so it would be tedious

**Pull request merged**
