### PR TITLE
Anti-materiel ammo in hacked autolathes

### PR DESCRIPTION
**Pull request by MagmaRam**
go go sniper ranger

### CODE REVIEW

**Comment by Anewbe** [comment]
How many metal monies does it cost?

**Comment by MagmaRam** [comment]
It's defined in bullets.dm - the amount of matter is 1250 steel. Autolathe costs are 1.25 times the matter, so it's 1562.5. I might change that to 1000 and 1250 because how weird that number is bothers me now.

**Comment by LorenLuke** [comment]
I don't think this should be a thing. If anything lower the AM rifle cost, because otherwise Mercs can have ammo for days. Without this, the big bad bullet is something they have to spend TC on, and it becomes a choice they have to weigh.

**Comment by MagmaRam** [comment]
1 sheet of steel is 2000 metal, one bullet costs 1250. You'd have to spend a lot of metal, and they have to be manufactured individually, which takes a lot of time.

And given that RNG can screw you on shooting, having ammo be rationed by the bullet can be incredibly frustrating. I'd rather have RNG-dependent mechanics be a little more forgiving for players who come prepared (those who come unprepared, of course, will be up shit creek with no paddle).

**Comment by LorenLuke** [comment]
@MagmaRam 
On Bay, ordering it yields a very fancy secure briefcase that can fit the rifle, and a box of ammo, allowing for eight total shots, rather than one. You get screwed by RNG, that's going to happen. Point is, you have more ammunition at your bevy just for ordering the damn thing. If you need more than eight _**Anti-mech**_ bullets, it should cost you TC rather than just being able to plop in five steel sheets for eight more bullets, IMO.

**Comment by SpadesNeil** [comment]
For something so immensely powerful, I say it should cost a lot of metal. Or buy the damn ammo for sake of convenience.

**Comment by Anewbe** [comment]
This still needs discussion and it has conflicts, so I'm going to close it for now.

**Pull request closed without merging**
