### PR TITLE
Tweaks bodybag relaymove(). Allows exit from morgue trays while in bodybags.

### PR DESCRIPTION
**Pull request by LorenLuke**

### CODE REVIEW

**Comment by Anewbe** [comment]
Did you test this?

**Comment by Yoshax** [comment]
Src is implicit.

**Comment by SilverTalismen** [comment]
As far as I know, you can escape morgue trays by clicking the tray while inside of it

**Comment by LorenLuke** [comment]
@SilverTalismen It doesn't work from inside a bodybag.

Noticed had forgot to commit the changes to the morgue tray itself. Current version has been tested and works, but will _**not**_ work if you're resting or unable to move while doing so.

**Pull request merged**
