### PR TITLE
Adds M1 Garand

### PR DESCRIPTION
**Pull request by SpadesNeil**
OKAY WAIT, I KNOW WHAT YOU'RE THINKING!

# "Spades, why the _fuck_ have you added _another_ vintage gun to my spacemens?!"

Just... hear me out on this.
https://github.com/SpadesNeil/Polaris/blob/13a83743a38324a1cc148fc807a0ae865c9cb37d/sound/weapons/garand_ping.ogg?raw=true

:-)

Jokes aside, I was **attempting** to make a gun that could handle speed reloading _and_ magazines _at the same time_. This was the gun I used for the example. I was not successful but I didn't want the sprite to go to waste. I plan to work on this more at a later date. I know where in the code I need to fix this but it's 3AM and my brain is mush. What I need to edit is in `projectile.dm` to make this work.

Sprite is pilfered from Fallout 13 server. The Garand ping sound was supplied by my good pal WankerSonOfJerkin from his actual M1 Garand.

The gun is currently admin spawnable only. So is the ammo.

### CODE REVIEW

**Comment by Ketrai** [comment]
*SQUINTS*

**Comment by Anewbe** [comment]
What's the license on that server, do you know?

**Comment by SpadesNeil** [comment]
https://github.com/animusdev/Fallout-13/

"All source code of /tg/ Station 13 after commit 333c566b88108de218d882840e61928a9b759d8f on 2014/31/12 at 4:38 PM PST (https://github.com/tgstation/tgstation/commit/333c566b88108de218d882840e61928a9b759d8f) is licensed under GNU AGPL v3."

**Comment by MagmaRam** [comment]
Well, I like it.

**Comment by Anewbe** [comment]
Spades, why the fuck do you keep adding vintage guns to my space-escapism?

**Comment by SpadesNeil** [comment]
You know damn well why.

https://www.youtube.com/watch?v=HlW4ELd8s7w

:D

**Comment by Iamgoofball** [comment]
👮 📧 ➡️

**Comment by SpadesNeil** [comment]
oh shit merge conflict

**Comment by Anewbe** [comment]
Conflicts.

**Comment by SpadesNeil** [comment]
That should fix it.

**Comment by SpadesNeil** [comment]
_merg dis_

**Comment by Anewbe** [comment]
**Full Disclosure:**
I was about to close this. That gun doesn't fill a niche other than "Crappier Z8" and I'm still not a fan of adding guns that are _already antique_ to my fucking **SPACE** game set five and _half centuries in the future_. But that comment made me laugh loud enough at 1 AM that I woke up my family, so yeah, merging. You win this time.

**Comment by SpadesNeil** [comment]
love you too Anewbe

**Pull request merged**
