### PR TITLE
The Great Storage Wars

### PR DESCRIPTION
**Pull request by Yoshax**
Hello, and welcome to my PR. This PR proposes large changes to storage.

This PR does the following:
- Storage items can no longer hold items of the same size.
- Many storage items are slightly smaller in capacity.
- Many items are now larger.
  - This includes but is not limited to: Guns, other weapons, suits, armor, tanks.

### CODE REVIEW

**Comment by MagmaRam** [comment]
Isn't this the sort of thing that should be discussed on the forums, or at least somewhere, before it's done up?

**Comment by Yoshax** [comment]
Forum is a barren wasteland.

**Comment by ThoughtSynapsis** [comment]
Actually a lot of people browse the forms, And if not we can direct them to it. This is a /really/ big change and it would be better to get peoples opinions on it before putting it in.

**Comment by MagmaRam** [comment]
Alright, then. This is a change that serves just to make things more inconvenient. It also messes with some things that were changed for a specific reason (gun sizes) as part of a larger change. It is, all around, a change that will do nothing but make everyone's life harder for no good reason. Never has "backpacks hold too many things" been a major balance problem.

I have a very hard time believing this PR is even proposed seriously, or in good faith.

**Comment by serenemelody** [comment]
To be fair (and it might be personal bias) forum discussions before a pull is made rarely end up with anything other than two parties getting angry at each other and nothing being agreed upon.

Also for my own curiosity, when and why was gun sizes changed?

**Comment by Yoshax** [comment]
Why else would a PR would be proposed? It's a positive change that moves away from people being able to carry enough weapons to arm a whole army plus enough materials to build a station. Also, @MagmaRam I do not appreciate you accusing me of making a PR not in good faith.

Forum discussions never go anywhere, look at recent ones. They get like two or three comments.

**Comment by redstryker** [comment]
Being able to hold a rifle in a bag as well as enough metal for ten girders is dumb.

**Comment by redstryker** [comment]
If you want to fix something, bring a bloody crate.

**Comment by FenodyreeAv** [comment]
Gameplay > Realism in this case.
Engineering would be impossible with restrictions on carrying large quantities of materials.

**Comment by MagmaRam** [comment]
The day engineering has to carry crates through what are often single-tile hallways in order to bring any sort of materials to the repair site is the day when nothing, save nothing, gets fixed. It's hard enough to get people to take the pipe dispensers places.

And, for reference, a gun takes up 2/7 of the space in a backpack. A stack of materials (and one stack of metal will not be enough to do any real repairs) takes 1/7. You can carry, if you go to the trouble, three backpacks at once (two in each hand, one on the back), but you very rarely see someone with more than one unless they're bringing someone else a bag. If someone can carry "enough weapons to arm a whole army plus enough materials to build a station", they're either using a bag of holding full of backpacks or they're making shit up.

**Comment by Yoshax** [comment]
That's not true information. See: https://i.gyazo.com/a2fc5554c041cd4e08cfe161e9ecb6f6.png
That is seven guns. Each taking up 1/7 of the space.
Here is another: https://i.gyazo.com/400e4e849cbe08b4c37b4ad63ad04c6e.png
Yet another: https://i.gyazo.com/7f75b241f7af48a722f15b1dcc222d88.png
And another:  https://i.gyazo.com/b5f953910d949db312d48965af0bedb8.png

Or how about the one where I can have a gun on my suit storage, seven in my belt, one in a holster, and then 350 sheets of steel in my bag?

**Comment by MagmaRam** [comment]
Alright then, pistols and submachine guns take up 1/7 of the space. X-ray lasers taking up 1/7 is almost certainly an oversight, since the laser carbine (which has a very similar function and sprite) was recently changed to be larger. The only belt that holds guns is the security belt, and the only lethal guns that holds are security .45s, detective Colts, and eguns. A holster prevents you from carrying ammunition in webbing (which you'll certainly need if you intend to do that much shooting). Wearing a secbelt prevents you from wearing a toolbelt, as well, which you'd like to have if you're doing to be using 350 metal sheets. If you're wearing a gun on your suit storage, you're not wearing an oxygen tank on it, which means you're not going to be doing very much repair work unless it's entirely internal.

But at the end of the day, all of that is splitting hairs, because my main issue with this PR is this: **This is a change that will not make the game more fun, nor more interesting.** I doubt you could find two examples in a month of a situation being ruined because someone carried too many things in their backpack. There is no interesting decision to be had from this, engineering just has more hassle and Security is not carrying that many guns in the first place, a few powergamers excepted. Hell, neither is Medical or Cargo or anyone else. **This is a change that serves only to make the game more frustrating to play, which is by any measure a bad change.**

**Comment by Neerti** [comment]
So, this PR is quite big, at nearly 90 files changed, and approximately 2.8k lines edited.  Reviewing it took quite awhile, so sorry for this somewhat slow response, but anyways.

I'm not in favor for most of these changes.  There's a few things I like, like the jetpacks, but most of this is quite bad in my opinion, and seems really unnessecary.  Some of the changes are also not very obvious to someone just reading the top comment.

I'll list some of the stuff I have issues with, and which some others would likely to know what this PR actually does.

- **Makes backpacks contain 21 space instead of 28, and reduces the max w_class to 3.  This makes the normal bag have room for 5.25 medium (w_class 3) items instead of 7, as it does now.  Since most people will have the atmos box in their bag, that's down to four medium items, which is quite tight.**
- Dufflebags bizzarely remain unchanged in the space department.
- **Makes stacks/rods/floor tiles w_class 4.  This makes them unable to be put in a backpack.**
- Fire extingushers increased to w_class 4.
- C4 now w_class 3.
- Hatchets now w_class 3.
- Briefcases maximum storage reduced by 1, making it unable to store four medium items, as it is 15 on the PR vs 16 today.
- Secure briefcases max storage reduced by 2 for no apparent reason.
- Binoculars increased to w_class 3, making inventory more scarce with the above change to bags.
- Flashlights now w_class 3, making inventory space tighter and disabling pocket storage.
- **Mining bags increased to w_class 4.**
- Plant bags increased to w_class 4.
- Plastic bags that the janitor uses increased to w_class 4.
- The emergency oxygen tank cannot fit in a pocket.
- The normal tanks cannot fit in a backpack.
- Bear traps increased to w_class 4, which makes their rare use by baddies even more rare.
- Single tank bombs are increased to w_class 4.  See above.
- Rad suit and fire suit increased to w_class 4.  Seems unnessecary, as holding one in your backpack currently takes about a third of your storage.  The accompnying helmet also takes up more room.
- All wedding slots reduced by 1.
- Cable stack increased to w_class 3, for some reason.
- Retro, Captain's laser increased to w_class 4, when they look like a pistol, and a sleek one at that.
- Lasertag also fits that profile but I don't care too heavily about this one.
- Most if not all the SMGs are now too big to fit in a backpack, even tho based on the sprite you'd think they would fit, just poorly.  The Uzi is also increased to w_class 4.
- In general, the massive increase of w_class on weapons makes it harder for antags to hide their weapons.

Remember, anything w_class 4 will be unable to fit in a backpack after this change.
w_class 3 means that it takes one of five of your imaginary slots, which is generally cut to one out of four due to your internals box existing.

All in all, this PR is just badness all around, especially for engineering.  I don't want this, and most staff I talked to about this don't really want this.  I'm sure a lot of players also feel the same way.  This creates what I see as unnecessary conflict with a lot of people to an issue that doesn't really exist or is pressing.

Do not want.

**Pull request closed without merging**
