### PR TITLE
adds a bunch of pins

### PR DESCRIPTION
**Pull request by Belsima**
i dont know how to map but the compiler told me to touch it

elgeon wanted pins please don't hurt me

all taken from eros

### CODE REVIEW

**Comment by Belsima** [comment]
what the fuck did i do to the map file

**Comment by Atermonera** [comment]
Presumably, you didn't use the map merger

**Comment by Belsima** [comment]
what the fuck is a map merger

**Comment by Atermonera** [comment]
[https://tgstation13.org/wiki/Map_Merger](https://tgstation13.org/wiki/Map_Merger)
It can be finicky to use, and sometimes eats your changes, but that's how you should be editing any maps

**Comment by Belsima** [comment]
Closing this; I actually learned a lot from this set of PRs. I'll make good ones next time.

**Pull request closed without merging**
