### PR TITLE
Asset Cache Update, NanoUI Overhaul, and tgui

### PR DESCRIPTION
**Pull request by SinTwo**
Ported from Paradise and Baystation and adapted for our code base.

## What does it do?:
Adjusts how assets are sent to the client and should eliminate the interface lag when you first join as well as changing over to a new form of NanoUI that is very similar to tgui.

Also ported in this is tgui with a few UI's accompanying.

## Images:
http://imgur.com/a/7lrB8

### Asset Cache
ParadiseSS13/Paradise#1807
ParadiseSS13/Paradise#2824
Baystation12/Baystation12#12117  -  Newscaster

### NanoUI
ParadiseSS13/Paradise#3013
ParadiseSS13/Paradise#3030
ParadiseSS13/Paradise#3079
ParadiseSS13/Paradise#3121
ParadiseSS13/Paradise#3173
ParadiseSS13/Paradise#3230
ParadiseSS13/Paradise#3280
ParadiseSS13/Paradise#3322
ParadiseSS13/Paradise#3329
ParadiseSS13/Paradise#3363
ParadiseSS13/Paradise#3412
ParadiseSS13/Paradise#4626

### Animated UI
ParadiseSS13/Paradise#4509
ParadiseSS13/Paradise#4602

### tgui
Baystation12/Baystation12#12344
Baystation12/Baystation12#13689
Baystation12/Baystation12#13721

### datum fix
Baystation12/Baystation12#12464
tgui port broke datums in some capacity, above fixed it.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
Yay.

**Comment by PJB3005** [comment]
👎 we don't need more code bases being overtaken by the false promise that I'd tgui.

**Comment by Chnkr** [comment]
@PJB3005 TGUI is fine, unless you have a twelve year old windows XP machine.

**Comment by PJB3005** [comment]
@Chnkr That's a blatant lie.

I've experienced unacceptable performance on Windows 10 with a machine that should be more than fast enough. Want to know how bad it is? Opening a SINGLE INTERFACE more than DOUBLED Dream Seeker's CPU usage. And that wasn't even that complex of an interface. I could rant on about how slow it is for ages. 

Even if we just tell everybody with even a remotely old computer to suck it up and buy a new computer it stills runs like complete ass when you compare it to Nano UI.

Not to mention that it's poorly documented, @neersighted disappeared, and he's the only person who has even a vague understanding of the complete Web 2.0 mess that it is.

And worst of all it doesn't even SOLVE the primary issues with Nano.

Oh and the server side code is something I'd have a field day on. 

Literally the only good thing about it is, IMO, the CSS.

**Comment by PJB3005** [comment]
Another code base bites the dust...

**Comment by StrikS** [comment]
Great work!

**Pull request merged**
