### PR TITLE
Communicator Glasses

### PR DESCRIPTION
**Pull request by MisterLayne**
The future is **now**.

### CODE REVIEW

**Comment by Anewbe** [comment]
I'm hesitant to merge this, because it's contrary to our long-standing plans to make communicators entirely replace PDAs, including the slots they can occupy. Communicator watches can be easily made to fit into this plan, but an eyepiece is a bit much.

**Comment by MisterLayne** [comment]
Is that a definite 'no', then?

**Comment by Anewbe** [comment]
I'll let @Atermonera give you a final verdict on that, but from what I can tell it leans that way.

**Comment by Atermonera** [comment]
How can you do messaging with commglasses? You can't say speaking unless you code it to act as such, like how radios do it.
How do you fit an ID card into it? (planned feature that's part of my ongoing project)
Where do cartridges attach to to not be big bulky awkward things? 
How do you use something like a medical scanner , which gives a readout, with a pair of glasses?
(Possibly more questions to come, I have to get back to work. Unless you can provide a satisfactory answer to all of them this will be denied)

**Comment by MisterLayne** [comment]
Rest in peace, Google Glass.

**Pull request closed without merging**
