### PR TITLE
BYOND 512 Compiling Errors Fix

### PR DESCRIPTION
**Pull request by Cameron653**
With 512, they added "filter" and "filters" vars.
Upon attempting to compile the code in 512, you're met with a variety of errors due to this.
This PR goes in and changes everything that has "filter" and "filters" and gives them more appropriate var names, such as changing "filters" to "atmos_filters." and changing the filters path from /obj/machinery/atmospherics/omni/filter to /obj/machinery/atmospherics/omni/atmos_filter, among other things.

Code compiles fine and, as far as I can see, there's no issues. https://i.imgur.com/Yb6CUWS.png

With this, the server is able to be upgraded to BYOND 512 without errors.

### CODE REVIEW

**Comment by Cameron653** [comment]
Edit:
As a side note, the reason the map was changed was due to the omni/filter being changed to omni/atmos_filter, the subspace crystals being changed from subspace/filter to subspace/sub_filter, etc.

Additionally, the changeling menu code uses "var filter" but it's in javascript and seems to not be affected by the new BYOND filter and filters changes, so I went ahead and left it.

**Comment by Anewbe** [comment]
You committed a number of backup files, I'm not sure we're supposed to have those.

**Comment by Cameron653** [comment]
Oh. Euugh, let me remove those. BYOND add those in every time I edit a map file whatsoever.

**Comment by Anewbe** [comment]
Yeah, whenever I do map changes, the first thing I do after running the merger tool is revert and delete everything I know I didn't touch.

**Comment by Cameron653** [comment]
Theeere we go. All the backup files removed.

**Comment by Cameron653** [comment]
~~Please merge whenever possible before there's a conflict in one of the 33 files edited~~

**Comment by Neerti** [comment]
Will need to go through all of our current map files but I can do that later in a separate PR.

**Pull request merged**
