### PR TITLE
Updates Preference Permissions, Re-adds Verbs

### PR DESCRIPTION
**Pull request by Datraen**
Also ports Baystation12/Baystation12#12526

### CODE REVIEW

**Comment by Yoshax** [comment]
Why re-add all the verbs?

**Comment by Neerti** [comment]
Because removing them made a lot of people very unhappy.

**Comment by Yoshax** [comment]
Yes, I'm incredibly dumb and didn't realise it was the admin verbs before commenting. Yay for assumptions.

**Comment by Datraen** [comment]
I did re-add all of the verbs, because I got more than a couple "Where did the verbs go?"

**Comment by Yoshax** [comment]
Change isn't in itself bad, people just need time to get used to change. I only really saw 1 person actually complain about the lack of verbs.

**Comment by Datraen** [comment]
I started to feel that it was more of an inconvenience than an improvement when I was doing things on the server, as well.

**Comment by Kelenius** [comment]
Verbs are bad :<

**Comment by Datraen** [comment]
Verbs are nice. I'm not removing the alternatives, but being able to select a verb rather than constantly switching to global before joining or having to navigate in game is less convenient.

**Comment by Nerezza** [comment]
My 2 cents is that it's strange to open a window to toggle OOC when it's drowning out everything else. For a user, what's been done is an inconvenience and not a convenience.

However, I do wanna note someone complained about the toggle prefix on a bunch of these verbs hijacking auto complete for toggle lock and toggle open or something.

**Comment by Datraen** [comment]
For clarification: Bugfix tag is because the mods/developers didn't have access to attack/debug logs respectively, feature tag is the readdition of the verbs.

**Pull request merged**
