### PR TITLE
Adds New Fallout-ish style "Handy" Cyborg Sprites

### PR DESCRIPTION
**Pull request by Cameron653**
----------------------------------------**Handy Style Cyborg Sprites**------------------------------------------
- Adds new cyborg sprites for: Medical, Science, and engineering.
- Sprites made by Keekenox.
- Adds an indent to 2 places where it had 1 indent too few because it was driving me mad.

Photos:
Medical: http://i.imgur.com/MViPivE.gifv
Science: http://i.imgur.com/nJP4rfX.gifv
Engineering: http://i.imgur.com/ttFXcbn.gifv
Eyes: http://i.imgur.com/tQCz0jD.png

### CODE REVIEW

**Comment by Anewbe** [comment]
Where did these come from?

**Comment by Cameron653** [comment]
As mentioned, they were created by Keekenox.

**Comment by Anewbe** [comment]
For what server? What license do they use?

**Comment by Cameron653** [comment]
They were never added to a server. He sent them privately to me over discord.

**Pull request merged**
