### PR TITLE
Scheduler now uses btime, and other improvements

### PR DESCRIPTION
**Pull request by Yoshax**
Port of Baystation12/Baystation12#11364

This is in preperation of porting other things, and was one of the reasons why I had so much difficulty with #1793 

This seems functional alone, but only includes the original PR by Psi. Other modifications and additions will come in additional PRs along with their accompanying things.

### CODE REVIEW

**Comment by Yoshax** [comment]
There's a diff difference between this and Psi's PR because of Github just figuring stuff out differently.

**Comment by PsiOmegaDelta** [comment]
And here I'm about to remove the use of btime as 510 has been officially released :P

**Comment by Yoshax** [comment]
AAAAAAAAAAAAAAH. PSI. WHY YOU DO THIS. HOW AM I EVER MEANT TO PORT ALL YOUR STUFF.

But really. This'll do for now, until I can port all the rest of the stuff, and Psi's done whatever he's doing then I can port that.

**Comment by Datraen** [comment]
For right now, let's use btime until we're 510 ready.

**Pull request merged**
