### PR TITLE
Removes the "Subversive Elements" Cent. Com. report at roundstart

### PR DESCRIPTION
**Pull request by silveryferret**
As title. It's horribly inaccurate, no one treats it seriously ICly, even all of command treats it as a joke. 

( Let's hope this PR looks tidier than my last one. )

### CODE REVIEW

**Comment by EmperorJon** [comment]
I support this. People may have reasons for opposing. We'll see where it goes.

**Comment by martin509** [comment]
I never saw this used once by any command staff, but it does give a little flavour for what it's worth.
It doesn't hurt anyone by staying there, nor does anything change if it's gone, so shrug.

**Comment by PsiOmegaDelta** [comment]
If you're talking about the loyal/oppressive/supportive relationship with NT it's what NT thinks your character's stance towards them is, not the character's actual stance.

**Comment by silveryferret** [comment]
Omega.. I'm not entirely sure what you're trying to say? All this PR does is removes this from happening when the round starts up: 

http://puu.sh/oLM52/94dda084fb.jpg

**Comment by Neerti** [comment]
I also support this change.

**Comment by Yoshax** [comment]
Fun fact, the loyalty stuff also affects how much money you start with.

**Comment by PsiOmegaDelta** [comment]
@silveryferret It was a response to @EmperorJon as I read his comment as "People have a reason to be opposing NT". I now realize I read it wrong.
@Yoshax Indeed, it was made that way as loyalty is supposed to be NT's perception of you (as opposed to your actual stance).

**Comment by Kelenius** [comment]
It's actually broken ATM. It ONLY shows non-antagonists due to a reverse ANTAG_SUSPICIOUS check.

**Comment by Spookerton** [comment]
:+1: Removes ancient goofy game feature that 95% of people ignore because it's out of place. Merge posthaste.

**Comment by emmanuelbassil** [comment]
RIP.

**Pull request merged**
