### PR TITLE
Simple Animal Tweaks

### PR DESCRIPTION
**Pull request by Arokha**
They can resist out of closets, buckles, and when calling for help, if the helpers can see the issue, they don't just follow the caller, they attack the issue. This means that retaliate class mobs properly assist in fights for the mob who is retaliating.

### CODE REVIEW

**Comment by Arokha** [comment]
Making a change.

**Comment by Anewbe** [comment]
Alrighty.

**Comment by Arokha** [comment]
Sorry, was just in a huge hurry and didn't want you to merge at the time.

**Comment by Anewbe** [comment]
No worries, I have a tag called "Work In Progress" that I tend to stick on PRs that aren't quite polished, feel free to ask for it.

**Comment by Anewbe** [comment]
What did you change?

**Comment by Arokha** [comment]
Leshana pointed out that cats and stuff would unbuckle themselves which would be annoying. So only mobs that think they have something to attack unbuckle themselves.

**Comment by Anewbe** [comment]
Ah, delicious. Did you test this?

**Comment by Arokha** [comment]
Yarp. With a spacecarp anyway. WILEY THINGS.

**Pull request merged**
