### PR TITLE
Condensation can now freeze floors, if you have the scepter.

### PR DESCRIPTION
**Pull request by Anewbe**
Also made it impossible to mop up ice.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Would be kind of neat if Condensation soaked people too, and maybe make you able to freeze them immobile for awhile or something

**Comment by Anewbe** [comment]
It already can soak them, pretty sure.

**Comment by SilverTalismen** [comment]
Would be nice to be able to freeze people temporarily then if they are soaked, although I understand why that may be difficult to code.

**Comment by Neerti** [comment]
Remember to change the ``enhancement_desc`` in the spell datum at the top of the file to tell people looking in the catalog that the scepter has an effect.

**Comment by Anewbe** [comment]
Oh, thank you.

**Pull request merged**
