### PR TITLE
Revert the material price increase for durand boards

### PR DESCRIPTION
**Pull request by lbnesquik**
Forgot to make this one too.

### CODE REVIEW

**Comment by Mechoid** [comment]
Before I modified the Durand, it had already been significantly buffed in armor resistance, to the point that standard equipment barring EMP is nearly useless against it. I have compensated for this in material cost, though as on my PR I have already reverted the time cost.

**Comment by Mechoid** [comment]
https://github.com/PolarisSS13/Polaris/pull/7473

**Comment by Cerebulon** [comment]
(and polyacid)

**Comment by lbnesquik** [comment]
All of my changes up to this were to increase mech usage, fancy extra costs aren't really helping with this goal. 
Did anyone give feedback on the durand from actual rounds?

**Comment by Atermonera** [comment]
Staff input: going with mechoid's tweaks, then evaluating the results.

**Pull request closed without merging**
