### PR TITLE
Adds Squid plushies to the arcade prize pool

### PR DESCRIPTION
**Pull request by H-Baguette**
Adds the squid plushies I made a while back to the arcade prize pool, giving you even more ways to get a squid friend :)

(also makes some changes to the squid plushies in the toy file)

### CODE REVIEW

**Comment by H-Baguette** [comment]
I genuinely have no idea why this is set to 'cannot merge'. I didn't change any files that would be too difficult to resolve in the web editor, either, so I don't know why Github's throwing a fit over it.

**Comment by Atermonera** [comment]
The conflicts were caused by another PR, in this case #7469, which touched the same file. Since the base file that your changes are supposed to be applied to, there's a conflict. Because that PR renamed the base file, github doesn't know where the file these changes are supposed to be applied to is, so it doesn't even know how to try and help resolve the conflict.
The simplest solution would be to simply remake the changes on the new file.

**Comment by H-Baguette** [comment]
ill do this when i have the energy

**Comment by Atermonera** [comment]
@H-Baguette this still has merge conflicts, any plans on fixing those?

**Comment by H-Baguette** [comment]
Yeah, I'll fix them over the weekend. Dealing with Uni shit right now.

**Comment by H-Baguette** [comment]
Gonna close this and re-open it when I've got more free time to do it properly. Blegch.

**Pull request closed without merging**
