### PR TITLE
Adds Jukebox hacking!

### PR DESCRIPTION
**Pull request by SpadesNeil**
https://github.com/PolarisSS13/Polaris/pull/1718 Doing this over again.

Just a fun completely unimportant feature I thought you would all appreciate. Ported from Vorestation.

- Jukeboxes can now be hacked.
- Some wires can remove parental controls to unlock **FUN**™ songs.
- You can speed songs up.
- You can slow songs down.
- You can play songs in reverse.
- Adds a new song that I like to call Russian Rap Disco. Yes, it's fair use in copyright. I checked. It's a remixed version of "Song About Hares" from a Soviet comedy film, "The Diamond Arm." Covered by fair use as a blatant parody: http://fairuse.stanford.edu/overview/fair-use/what-is-fair-use/
- GSC World (owners of STALKER and bandit_radio.ogg) don't care if we use assets from their game so long as we're not selling it. Source: http://gsc-game.com/index.php?t=community&s=forums&s_game_type=xr&thm_page=1&thm_id=20587&sec_id=16&offset=240

Looks like someone already made jukeboxes constructable, so I don't need to do that anymore.

### CODE REVIEW

**Comment by Anewbe** [comment]
Are any of those songs copyrighted or trademarked, or whatever?

**Comment by SpadesNeil** [comment]
Russian Rap Disco, no. It's from an obscure movie developed in Russia called the Diamond Arm. The Soviet Union was still around, and this is a parody of the original song, and therefore, perfectly within fair use. I checked this.

Bandit Radio, like I said, GSC World is okay with their assets from STALKER being used in mods, other games, etc, as long as those games aren't being sold for profit. This is also fine.

The rest of the songs were already in your code.

**Comment by SpadesNeil** [comment]
Accidentally deleted the branch. <_>

**Comment by Anewbe** [comment]
Rest of the code is fine, but we **will not** merge this with those songs, they're not going to work with our licensing.

**Comment by SpadesNeil** [comment]
http://gsc-game.com/index.php?t=community&s=forums&s_game_type=xr&thm_page=1&thm_id=20587&sec_id=16&offset=240

**Comment by SpadesNeil** [comment]
@Anewbe is this better?

**Pull request closed without merging**
