### PR TITLE
Silly admins can't blindly break movement irreparably

### LINKED ISSUE #6759: It is still possible to var-edit bound_x/y
#### Brief description of the issue
An event manager var-edited `bound_x` on a mob, and this broke the movement animation byond does.

#### What you expected to happen
For unsafe variables like `bound_x` to not be visible, or at least be read-only, in VV, as we now have the ability to do that.

#### What actually happened
VV allowed someone to break movement for the whole round by modifying an unsafe variable. Because of BYOND, the movement breakage is not able to be fixed without a restart.

#### Steps to reproduce
Spawn any atom of your choice.
Open VV on it.
Look for bound_x/y.
Edit it.
Observe movement breaking because byond thinks the server is using pixel movement.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2020-02-25
d079fc6329e15f205e4574b562d01d5193380e2f 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
I'm not sure if `step_x/y` edits are blocked or not, but they will also break movement.

### PR DESCRIPTION
**Pull request by Atermonera**
Fixes #6759 
[tested](https://puu.sh/Fotkg/dd3631ab4e.mp4)

The code was copied from the mass-edit protections

### CODE REVIEW

**Comment by Arokha** [comment]
You should probably just add this to the list of vars that admins can't edit, like step_x and step_y and bound_x and bound_y etc etc

**Comment by Atermonera** [comment]
`GLOBAL_LIST_INIT(VVpixelmovement, list("bound_x", "bound_y", "step_x", "step_y", "step_size", "bound_height", "bound_width", "bounds"))`

**Comment by Arokha** [comment]
Oh wait, I see what you did. Whyyyyy?

**Comment by Atermonera** [comment]
Apparently the protections have been deprecated or otherwise never existed for regular vv edit and change, and only existed for mass-vv, even though I have yet in all my years of being around polaris staff to even so much as hear of anyone using the mass-edit. One of our admins may have mistakenly clicked on it instead of a var that was presumably close to it, and in doing so unwittingly broken everything.

**Comment by Neerti** [comment]
Actually I think it was a case of them mistaking `step_x` for `pixel_x`.

**Comment by Leshana** [comment]
Hello @Atermonera ! The protections do exist for regular vv change also, but they are broken.

In *atoms_movable.dm:47* change
`if(GLOB.VVpixelmovement[var_name])` to `if(var_name in GLOB.VVpixelmovement)`

**Comment by Atermonera** [comment]
Probably best to leave this warning in in case the hard protections should break again

**Pull request merged**
