### PR TITLE
Buffs the mop bucket by the same amount as the janicart.

### PR DESCRIPTION
**Pull request by Belsima**

### CODE REVIEW

**Comment by Neerti** [comment]
300 seems a bit much when the janicart has to be dragged where as buckets don't.

**Comment by Atermonera** [comment]
You can pick up the yellow mop buckets?

**Comment by Neerti** [comment]
I'm a dummy and thought this was being applied to the blue buckets.

**Comment by Belsima** [comment]
Yeah, it's still strictly inferior to the janicart, even. I don't think it has any advantage.

**Pull request merged**
