### PR TITLE
Adds player age req to Chemist and Atmos

### PR DESCRIPTION
**Pull request by Anewbe**
3 days each
Surprised this wasn't already a thing

### CODE REVIEW

**Comment by Yoshax** [comment]
Probably because the other jobs aren't. If you're playing Station Engineer or Medical Doctor, you're basically playing Atmos Technician and Chemist.

**Comment by Anewbe** [comment]
It's more I'm surprised that no one has added a time-block for these two jobs, which have easy access to phoron and other grieftastic things.

**Comment by Yoshax** [comment]
You can't really phoron grief without at least a little atmos knowledge anymore. It's not just two pumps and fill the station.

**Comment by Anewbe** [comment]
Griefers aren't always dumb, though.

**Pull request merged**
