### PR TITLE
----- HOLD MAP CHANGES ----- NO MAP CHANGES ABOVE THIS LINE -----

### PR DESCRIPTION
**Pull request by EmperorJon**
A large map change will be incoming. Due to map merging issues, we're not going to accept map changes for some time.

### CODE REVIEW

**Comment by Yoshax** [comment]
What kinda change?

**Comment by EmperorJon** [comment]
A reconfiguration of the civilian sector.

**Comment by Yoshax** [comment]
Are currently open map PRs going to be merged first, or are they going to have to wait until this is done?

And does it only affect map1?
And what about any bugs that around found on the map, are they just not allowed to be fixed?

**Comment by EmperorJon** [comment]
We are going to attempt to process map changes that are currently open first.
It should only by the main z-level, yes.
As for bugs, we don't know of any large outstanding map issues and hopefully no large issues will found. If they are they'll be dealt with as we see fit.

**Comment by Yoshax** [comment]
How long is 'some time'?

**Pull request closed without merging**
