### PR TITLE
Changes the changelogs

### PR DESCRIPTION
**Pull request by Anewbe**
The example changelog now cites Unknown as the default author.

Also properly renamed an unmerged changelog.

### CODE REVIEW

**Comment by Anewbe** [comment]
Apparently Travis is having an issue with build logs.

**Comment by PsiOmegaDelta** [comment]
Travis checks the checksum of example.yml to prevent accidental changes.
If you're either running Linux or git bash on Windows you should be able to do ```md5sum *html/changelogs/example.yml"``` to get the new checksum.

**Comment by Anewbe** [comment]
Will attempt to do so, thanks.

**Comment by Anewbe** [comment]
Will redo later.

**Pull request closed without merging**
