### PR TITLE
Nalarac's Farmbot Tweak

### LINKED ISSUE #6296: Xenobotanists Lack Access to Farmbots
#### Brief description of the issue
Farmbots requires **access_xenobiology** so xenobotanists can unlock them
#### What you expected to happen
To be able to unlock a farmbot as xenobotanist.
#### What actually happened
You are unable you
#### Steps to reproduce
1.) Spawn farmbot
2.) Be Xenobiologist / Xenobotanist
3.) Swipe ID on farmbot
#### Additional info:
 - **Server Revision**: master - 2019-07-05 438e113621ce62899e9d7cb60bb187b30b6fc582 
 - **Anything else you may wish to add** I tried doing this simple fix twice (#6291 & #6288) but Travis hates me for some reason and screams about a completely random file.

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Adding access_xenobiology to the permission levels for Farmbots so xenobotanists can make use of the bugger. Doing this on behalf of Nalarac, using work from  https://github.com/PolarisSS13/Polaris/pull/6288

Resolves #6296

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Wot. Travis passed on my fork, though.... Why is it screwing me over **here**????

**Comment by Woodratt** [comment]
Its cursed.

**Comment by TheFurryFeline** [comment]
Gonna.... Paste that snippet that Ater posted in the referenced PR.

> code/modules/mob/living/silicon/robot/robot.dm:959:error: =: conflicts with previous definition

`/mob/living/silicon/robot/mode()

set name = "Activate Held Object" << 959
set category = "IC"
set src = usr`

**Comment by Anewbe** [comment]
Could you possibly undo your change, then put a comment on the line below, just so we can see if the build fails Travis if the file is touched at all?

**Comment by TheFurryFeline** [comment]
...... Well, then.... It actually passed.

**Comment by TheFurryFeline** [comment]
Hmm.... I wonder if the same issue pops up downstream on VoreStation. Going to do a test PR there, see if Travis also screeches.

**Comment by TheFurryFeline** [comment]
Late, I know, but looks like it should be working here as well.... Not running into an issue with Travis about silicon/robot/robot.dm 959.... >_>Even the code for that section is the exact darn same. 🤦‍♂

**Comment by TheFurryFeline** [comment]
Well, then. Passes here at long last. <_< @Nalarac here we go with this silly thing after all. Yay.

**Pull request merged**
