### PR TITLE
Fixes some lost drone laws not ever applying

### PR DESCRIPTION
**Pull request by Heroman3003**
P much.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
This the thing that made the end of rounds with a Lost Drone fail to display a list of the random events that happened in a shift? That's an issue downstream at Chompers.

**Comment by Heroman3003** [comment]
No idea about that, but I do believe this made the drone have missing lawsets outside specifically option for "empty lawset" diceroll

**Comment by TheFurryFeline** [comment]
Lost Drone-547 (Played by: ) was unable to survive the rigors of being a stationbound synthetic without an AI. Its laws were:
DEBUG: Runtime in gameticker.dm,438: Cannot execute null.show laws(). [view] 
[2019-09-07T00:07:01] Runtime in gameticker.dm,438: Cannot execute null.show laws().
Just for reference since it happened again at the end of a shift, preventing the event list from displaying.

**Comment by Heroman3003** [comment]
Then it might be that, yeah, since if laws failed to apply, they remained as null, which would be the cause of the runtime

**Comment by TheFurryFeline** [comment]
Hmm, just tried it and it didn't fix the runtime there, ugh... Still got the same gameticker issue.

**Pull request merged**
