### PR TITLE
Adds a new hud & removes red crosses from huds.

### PR DESCRIPTION
**Pull request by Belsima**
From the Eris
images

Anti-Red Cross sprites
image
image
image

### CODE REVIEW

**Comment by Anewbe** [comment]
What exactly is that top image supposed to show?

**Comment by Belsima** [comment]
The top image is the hud from the Eris.

**Comment by Anewbe** [comment]
Ah, HUD meaning the actual icons and stuff, rather than the thing the MedHUDs show?

**Comment by Belsima** [comment]
Precisely.

**Pull request merged**
