### PR TITLE
Fixes Chapel Solar Airlock + Makes Solar Airlocks Bigger

### PR DESCRIPTION
**Pull request by SpadesNeil**
Solar Chapel Airlock was broken because the pump was incorrectly named.

The airlock size was extended for all airlocks because it's too small to drag a solar crate in with you. Climbing onto the box for extra room also doesn't work for borgs. It's just one tile longer.

### CODE REVIEW

**Comment by Anewbe** [comment]
Any chance we can get some images of those airlocks?

**Comment by SpadesNeil** [comment]
Oh come on it's just one tile bigger! ;-; Fiiiiine. One sec.
capture

I'm not screenshoting all for on the grounds of damn it I'm lazy.

**Comment by Hubblenaut** [comment]
Keep in mind that without a second vent, they will take twice as long to cycle.

**Comment by SpadesNeil** [comment]
Oh shit I hope I didn't accidentally remove the exterior button. Let me go make sure.

**Comment by SpadesNeil** [comment]
Nope. Didn't forget the cycling buttons. Nuh-uh. They're there. See? They were just... they were hiding. Yea, that's it.

**Comment by Anewbe** [comment]
Seriously though, is there a button for that or is there not?
I don't have any sort of opposition to this, personally, but neither do I support it strongly.

**Comment by SpadesNeil** [comment]
>Put cycling buttons back.

**Comment by Anewbe** [comment]
Gonna throw this at people who might have opinions, we'll see what they say.

**Pull request merged**
