### PR TITLE
Makes the hacker rig spaceproof, edits sprite to reflect this

### PR DESCRIPTION
**Pull request by Anewbe**
Been talked about multiple times, might make it useful for heisters

### CODE REVIEW

**Comment by Yoshax** [comment]
Screen shot of the sprite?

**Comment by Anewbe** [comment]
Right, duh, just a tick

**Comment by Anewbe** [comment]
Unsealed -> Sealed
cyber_unsealed cyber_sealed
Back of the unsealed doesn't have that blue light, missed that in the first pass.

**Comment by Neerti** [comment]
Could you make the glass part for sealed by a bit more opaque, since I can barely tell otherwise?

**Comment by Anewbe** [comment]
Gonna swap the color, started with a grey, doesn't look all that different with higher opacity.

**Comment by Anewbe** [comment]
blueface
Opinions?

**Comment by ParadoxSpace** [comment]
That's too opaque.

**Comment by SilverTalismen** [comment]
Why not look at what the medical hardsuit has going on visor wise?

**Comment by Anewbe** [comment]
Medical hardsuit's not opaque, and I'm not a tremendous fan of that sprite anyway.

**Comment by Anewbe** [comment]
Closing for now, will redo later.

**Pull request closed without merging**
