### PR TITLE
Changes blast doors to shut top to bottom.

### PR DESCRIPTION
**Pull request by Belsima**
image

All sprites rotated to be sideways- this increases the feeling of being 'heavy duty' relative to regular airlocks, and is also how similiar doors would usually close IRL.

### CODE REVIEW

**Comment by Anewbe** [comment]
They're fine the way they are.

**Comment by Neerti** [comment]
Some blast doors are rotated already and I believe its intentional that some of them aren't vertical.

**Comment by Belsima** [comment]
I just had it suggested elsewhere and ported it- this does include directionals as well, as a note.

**Comment by Belsima** [comment]
image
Example of these taken from Aurora's discord.

**Comment by Anewbe** [comment]
General consensus seems to be "No, thank you." Closing.

**Pull request closed without merging**
