### PR TITLE
Makes flashes confuse and blind the person instead of stunning

### PR DESCRIPTION
**Pull request by Yoshax**
We have removed most of the previously existing instant stuns but kept flash as such. In its current state you can flash someone and pin them onto the floor, and there is basically nothing they can do. There is no reason for it, and it should go.

Flash will now:
Conufse for 5 seconds
Blind for 5 seconds
Blurry for 10 seconds

### CODE REVIEW

**Comment by Datraen** [comment]
Makes insta-stun the way of the dodo, :+1:

**Comment by Spookerton** [comment]
I'd be totally willing to give this a try.

I'm not sure if I agree with totally nixing stuns in general, because it moves away from being able to rely on anything but batons and tasers to actually **stop** someone; a move like this means that flashes in particular no longer prevent someone from running - it just reduces their ability to run effectively - and doesn't stop them from attacking effectively at all, which is probably half of what flashes are used for preventing in close quarters.

It's not a problem I think is easily fixed though, and pepper spray can still fill in the role. Just less effectively. Whiiiich I suppose could be a positive.

**Comment by Yoshax** [comment]
Instant stuns are never going to be a productive part of the game. They are anti-rp, and anti-fun. The only one that remotely makes sense, and could remain is the parapen because of it being a traitor item and costing TC.

**Comment by Spacemanspark** [comment]
Never liked instastun mechanics myself.
We have these on Paradise (Minus the blurring part) for our flashes. It doesn't render them unusable, but it makes them more of a side tool rather than an instastun device that fits into your pocket.

**Comment by Spookerton** [comment]
You're not wrong that instant stuns are a mechanical win button, but that doesn't mean that there's an alternative available that won't aggravate people even more. Removing the option to use something like a flash in its current format means that people will just jump straight to whacking and zapping. Regardless, though, I said: totally willing to give this a try.

**Comment by Spacemanspark** [comment]
One thing I will ask; does this have the AoE flash to it? Where you click a flash in hand and it flashes anyone in a 3x3 area around the user? The AoE flash is also weaker.

**Comment by EmperorJon** [comment]
Doesn't confusion etc. etc. have no impact on attack accuracy right now? I think if this change went in you'd want to alter that, because right now you can leave people blundering around running into things and hurting themselves whilst also accurately ripping the shit out of you with bursts of assault rifle fire.

**Comment by Yoshax** [comment]
If someone wants to go refactor how mobs are affected by various status effects, they're free to.

**Comment by zekesulastin** [comment]
It seems like that would be a pretty important prerequisite for this, then.

**Comment by Anewbe** [comment]
I don't think this affects mounted or portable flashes, is that intended?

**Comment by Hubblenaut** [comment]
Confusion lowers accuracy with weapons, but otherwise has no effect on combat to my knowledge.

**Comment by Yoshax** [comment]
Intended @Anewbe

**Comment by Anewbe** [comment]
I'd be willing to give it a try, then.

**Comment by FenodyreeAv** [comment]
You can still resist while flashed.
It's getting harder and harder to restrain someone safely.
They only have to get lucky once, because they'll kill you. An officer has to be lucky every time.
Very big -1, confused status doesn't do shit.

**Comment by Hubblenaut** [comment]
Can port Baystation#13381 and add a modifier for being confused.

**Comment by Yoshax** [comment]
Both have been @Hubblenaut https://github.com/PolarisSS13/Polaris/pull/1956

**Comment by SparklySheep** [comment]
I was always wary about doing this because of the hard counters to flashes (sunglasses, welding helmets, etc.) but since most of those have been removed from both the map and from the loadout, I'd approve of this. Instant stuns are not a fun game mechanic especially with the reduced speed on this server compared to others.

I give my cautious :+1:

**Comment by Anewbe** [comment]
Still willing to at least give this a try.

**Comment by kimiza** [comment]
I would say this is a bad idea. As is, the flash has an incredibly common hard-counter. A welding helmet, goggles or glasses(which are fairly easy to obtain) all utterly negate the flash, and further nerfing it will probably relegate it to the stage where it is completely unused.

**Comment by Yoshax** [comment]
@Neerti @EmperorJon 

This is a thing. This thing requires attention.

**Comment by EmperorJon** [comment]
So now the accuracy penalties are through we're totally fine for this, right? It still has Requires Staff Input but idk if there was anyone who said no? I'm certainly happy to give it a try.

**Comment by Anewbe** [comment]
#2134 was merged for this, yes. Still willing to give this a try.

**Comment by Neerti** [comment]
We can revert if it turns out that the change goes poorly.

**Comment by EmperorJon** [comment]
Well merge it then! :P

**Comment by Woodratt** [comment]
As someone who has been on both ends of this. It does not work.

People can still disarm spam, people can use baseball bats. People can still melee at close range. 

Make them do halloss or something, cause if you're close enough to use a flash then you're going to get punched, pushed down and dead.

**Comment by Rand0mname** [comment]
So basically as a detective I now have to shoot every threat I run into? I can live with that.

**Pull request merged**
