### PR TITLE
Allows the dumping of drinks & beaker spill tweak

### PR DESCRIPTION
**Pull request by Cameron653**
- Allows you to splash your drink if on harm intent
- Requires you to be on harm intent in order to spill beakers or other glass/ variants.

This can be used by lazy bartenders to empty glasses, ~~since there seems to be no other way to do so.~~ Apparently you can use the sink.

Also allows people to dump a drink the bartender gives you incorrectly, just to be rude.

### CODE REVIEW

**Comment by Anewbe** [comment]
Yeah, you can use sinks for this...

**Comment by Neerti** [comment]
This is for dumping on people/other things I think.

**Comment by Cameron653** [comment]
This is so you can splash the drinks onto the ground/onto people/onto yourself like beakers.

**Comment by Wickedtemp** [comment]
... Can we actually have this feature for beakers as well? ONLY splashing on harm-intent? Or at least, ONLY splashing when on a non-help intent?

**Comment by Cameron653** [comment]
~~I mean, it's possible. The only purpose of this PR is to make it so glass2 can splash their contents. Could potentially mess with glass1 later on.~~

Ya know what, fuck it. I'll see about making beakers only splash on harm intent. Give me a bit.

**Comment by Cameron653** [comment]
@Wickedtemp Done. 
All glass/ variants (Beakers, bottles, and paint cans) now require you to be on harm intent in order to spill/dump their contents.

**Comment by Cyantime** [comment]
The beaker change removes any possibility of accidental chemical spills, which are a vital part of chemistry

**Comment by Cameron653** [comment]
A misclick while trying to put a beaker into cryo shouldn't waste an entire thing of clonexadone, or any other chemical for that matter.

Accidental chemical spills due to misclicks are just flat out poor design.

**Comment by Wickedtemp** [comment]
@Cyantime There have been many cases where beakers have been spilled on the floor, and even on people simply because I didn't have a mouse and was using a touchpad, a part of my hand bumps the pad and it registers as a click. Other medical players have also had problems with misclicks in the past, including one incident where the chem-masters design actually caused spills when you're clicking directly on the chem-master. Turns out, there was a small group of pixels that were "invisible", that was really just the floor, despite your cursor being over the chem-master. 

Other misclick mishaps include accidentally pouring medicine on a patient, spilling all 100u of phoron onto the floor (thus boning Medical until they get more), and many, many instances of "I tried to put the beaker into the chem-master, but ended up clicking the edge of a bottle that was over the chem-master, and ended up pouring the solution onto the bottle." 

As someone who only plays Chemistry/CMO, along with many other Med players, I'm happy about this change and I consider it to be warranted.

**Comment by Nalarac** [comment]
Does this mean you can drink from the beakers now as well?

**Comment by Cameron653** [comment]
I didn't bother to add drinking from breakers because ~~lab safety~~ I just was requested to add dumping to glasses and then harm intent only splashes to beakers.

**Pull request merged**
