### PR TITLE
Adds 3 new types of underwear

### PR DESCRIPTION
**Pull request by Yoshax**
Sprites courtesy of Serithi.

### CODE REVIEW

**Comment by zaredman** [comment]
eucifyy

**Comment by Fox-McCloud** [comment]
Pictures, if you don't mind?

**Comment by Serithi** [comment]
@Fox-McCloud http://i.imgur.com/LCvkjRC.png

**Comment by EmperorJon** [comment]
PRIORITY ONE MERGE BY EXPRESS ORDER OF SUPREME OVERSEER REDMAN.

**Pull request merged**
