### PR TITLE
Makes changeling recursive enhancement a passive power

### PR DESCRIPTION
**Pull request by Yoshax**
Right now, there is little use to use recursive enhancement because it is expensive, and does little for the price, because it costs chemical and only works for one ability before you have to pay it again. This is in the hope to re balance to be worth the price.

### CODE REVIEW

**Comment by Anewbe** [comment]
Your .dme is a bit odd.
I'd be willing to let this have a go, personally.

**Comment by Yoshax** [comment]
No idea what you're talking about, sonny.

**Comment by Anewbe** [comment]
Sleeper's capitalized, not sure why it's doing that, happening to everyone, apparently.

**Comment by Yoshax** [comment]
I blame Neerti.

**Comment by Yoshax** [comment]
And renaming it does nothing so yay, can't even commit the renamed file.

**Comment by SpadesNeil** [comment]
>Sleeper's capitalized, not sure why it's doing that, happening to everyone, apparently.

fix dis

**Comment by Neerti** [comment]
I have no clue why it's happening

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=DtRNg5uSKQ0

**Pull request merged**
