### PR TITLE
Blindness fix.

### PR DESCRIPTION
**Pull request by Zuhayr**
Readds blindness removal to imidazoline and organ surgery. 
Stops imidazoline healing robotic eyes.
Renames the autopsy scanner to the biopsy scanner to make it clear to people that it can be used on living patients.
Fixes oversight with O_APPENDIX.

Alternative to #744.

### CODE REVIEW

**Comment by Zuhayr** [comment]
Wasn't able to repro deafness, but I am 100% certain commenting out sdisabilities is not a proper fix.

**Comment by PsiOmegaDelta** [comment]
Yeah, the proper fix is probably me going over my vision handling rewrite. I evidently missed details.

**Comment by Datraen** [comment]
This one is better than mine by correcting the checks and targetting the correct life file, versus just ignoring sdisabilities during the check to handle healing.

**Comment by Datraen** [comment]
So, testing results:
Blindness remains, eye_blind does not decrease.

**Comment by Zuhayr** [comment]
I don't want to be rude but if your standard testing practices are using VV instead of player-facing mechanics then you are not going to get useful or indicative results. The whole point of this PR was to add BLIND removals to procs called when repair was conducted.

**Comment by Datraen** [comment]
Worked under normal repair for synths, assuming will work for humans.

**Pull request merged**
