### PR TITLE
Skrell blood is now hemocyanin-based

### PR DESCRIPTION
**Pull request by listerla**
Inspired by Aurora.

Copper now serves the role of Iron for Skrell for the sake of bloodloss, and their blood is now colored like horseshoe crab blood.

### CODE REVIEW

**Comment by elgeonmb** [comment]
have someone slap a note on the wiki and we're good

**Comment by Atermonera** [comment]
Needs documentation: As elge noted, wiki updates to medical, skrell list of mechanics necessary. Will hopefully have a discord role you can ping for assistance on this tomorrow after the staff meeting.

**Comment by listerla** [comment]
@Atermonera Now on the Skrell page. Where else should it be?

**Comment by listerla** [comment]
On both pages now.

**Pull request merged**
