### PR TITLE
Center_of_mass for snacks/dishes

### PR DESCRIPTION
**Pull request by Hubblenaut**
* Updates all snack definitions with center_of_mass vars.
 * Fixes food placement that doesn't use center_of_mass (salt shakers, sugar dispensers ect).
 * Roughly orders food.dmi after category of food.
 * Gets rid of a duplicate pretzel definition.

### CODE REVIEW

**Comment by Zuhayr** [comment]
Why in the Hell isn't it showing the changes in snacks.dm..? 222 lines shouldn't be enough to make it refuse to show the diff, surely.

**Comment by GinjaNinja32** [comment]
It's maybe a file size cutoff, IIRC snacks.dm is the largest non-map text file in the entire repo.

**Comment by PsiOmegaDelta** [comment]
IIRC GitHub doesn't show diffs for files with more than 200 changes (this file in particular has 222+15).

**Comment by PsiOmegaDelta** [comment]
https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/

**Comment by Datraen** [comment]
So, I didn't see anything missing in food.dmi, save for the duplicate.
Most of the changes involved adding center_of_mass and some spaces.

**Pull request merged**
