### PR TITLE
Solitary Sleepers 2: Electric Boogaloo: The Redemption: Revengeance

### PR DESCRIPTION
**Pull request by Mark9013100**
* Adds cyrogenic storage cells to the solitary cells on Z-1. Also gives the cells actual flooring.

* Gives Brig Control standard security door access on Z-1.

* Gives armory lockers(excluding lethal ammo) standard security door access on Z-1.

* Adds a few more floor decals I forgot to add on Z-2. And lino flooring to the tram lounge.

* Fixes a few /areas on Z-4.

* Fixes a few /areas on Z-5.

* Link to previous attempt: https://github.com/PolarisSS13/Polaris/pull/1205

### CODE REVIEW

**Comment by Kelenius** [comment]
Maybe you should put everything except sleepers into a different PR so it can get merged.

**Comment by Mark9013100** [comment]
Eh, it's fine as is. Sides, only took 10 minutes for the other stuff in the PR.

**Comment by Neerti** [comment]
Conflicts.

**Comment by Mark9013100** [comment]
Will be dealt with when I can.

**Comment by Mark9013100** [comment]
Alright, take three.

**Pull request closed without merging**
