### PR TITLE
Fixes ghost riders

### PR DESCRIPTION
**Pull request by Heroman3003**
--...and other riders. Fixes the bike verbs to allow human-only interaction.--

Fixes to allow only living non-mice to interact, rather than human-only. Still fixes ghost riders.

### CODE REVIEW

**Comment by Anewbe** [comment]
Code's fine; Mechoid may have further thoughts on this, so I'm going to let him give input before I give any further thoughts.

**Comment by Mechoid** [comment]
I'm mostly concerned about removing more things that borgs can use, since the spacebike is the only vehicle currently operable by them. (Which is something I would like to expand upon in the future)

**Comment by Heroman3003** [comment]
Well, I mostly added the check matching the other vehicles moreso than just blocking off. That lack of check is reason ghosts could do stuff. I will just limit it to living/not-mouse instead if thats desired.

**Comment by Mechoid** [comment]
You are my hero

**Pull request merged**
