### PR TITLE
Adds teargas grenades, currently aspawn only

### PR DESCRIPTION
**Pull request by Anewbe**
Ported from Baystation

### CODE REVIEW

**Comment by Yoshax** [comment]
Did you try using these and testing the effectiveness?

I previously have multiple times, and never was able to have something suitable and appropriate.

**Comment by Anewbe** [comment]
That's why they're aspawn only, it will let us test and tweak before it gets into common use.

**Comment by Yoshax** [comment]
Well, in my experience and testing they do nothing when actually exposed to them until about 60-120 seconds afterwards, wherein your pain builds up till you're slow as hell, which takes another 60-120 second, then after a little bit more you're dropped into paincrit, for about... 400+ seconds.

**Comment by Anewbe** [comment]
Yep.

**Comment by Yoshax** [comment]
That's kinda ridiculous to put in even as aspawn only.

**Comment by ParadoxSpace** [comment]
Pls tweak

**Comment by MagmaRam** [comment]
These aren't going to be added to the proper game until they're properly tweaked and tested, and this'll help with getting that done.

**Pull request merged**
