### PR TITLE
Playing card improvement  - Take two

### PR DESCRIPTION
**Pull request by Anasari**
Basically same as #4104 but I freaked out over Travis. This PR is after I applied grammatical fixes and to_chat to well, everything. Unfortunately I cannot test-run as something's wrong with the master build locally.

A small rework of the polaris card to make it better and easier to use. 

What this PR does:
**Add:** 
1. Deal multiple cards function, you can deal up to 10 cards (or how many cards there are in the deck)
2. Clicking on a deck with empty hand automatically draw cards. It will add it to your existing hand
3. Deck is now picked up by drag-click, code from paper-bin
4. Card shuffle cooldown (10 ticks)
5. Port in card shuffle sound from tg.
6. Shuffle verb for the playing card
7. Ability to discard multiple card (one by one due to limitation of my coding skills)
8. Ability to right-click remove one card from a hand.
9. Cards from different deck cannot be mixed anymore. Exception for Spaceball and Cardemon

**Remove:**
1. Drag-click card dealing because it was tedious

**Changed:**
1. Hand of Card in hand that's concealed no longer visible if you examine it. No cheating / peeking. This is to allow for people to take / draw someone else's card and give it to them without knowing the contents.

I'm also thinking of adding in instructions to the description that you can pick up the card by dragging it over your sprite

Feedback highly welcome!

Screenshots:

### CODE REVIEW

**Comment by Anasari** [comment]
..Honestly speaking no idea why travis is failing this.

**Comment by Anewbe** [comment]
And this is feature complete now?

**Comment by Anasari** [comment]
Feature complete and ready for review.

**Comment by Anewbe** [comment]
Where did that sound come from?

Other than that, seems fine to me, will have to play with it to really see.

**Comment by Anasari** [comment]
The sound came from https://github.com/tgstation/tgstation/pull/1872

**Pull request merged**
