### PR TITLE
Loadout additions + fixes.

### PR DESCRIPTION
**Pull request by Belsima**
https://github.com/PolarisSS13/Polaris/pull/4111

This except I also fix headtail cloth.

Closes https://github.com/PolarisSS13/Polaris/issues/3990.

### CODE REVIEW

**Comment by Belsima** [comment]
...I don't understand what broke.

**Comment by Belsima** [comment]
Oddly, it compiled on my PC, even though it upset travis.

**Comment by Atermonera** [comment]
The thing that failed was a unit test, which is specific to travis. The thing with comments within a multi-line list needing to end in a comma is also an example of something that travis catches, but the compiler doesn't.

**Comment by Belsima** [comment]
Ah, thanks.

**Pull request merged**
