### PR TITLE
Adds non-head of staff department cloaks

### PR DESCRIPTION
**Pull request by Mewchild**
Adds general cloaks for the following departments/jobs: cargo, mining, security, service, engineer, atmos, research, and medical. The head of each department has access to these cloaks in loadout, for more options.
Sprites made by @CameronWoof.

### CODE REVIEW

**Comment by CameronWoof** [comment]
I am CameronWoof, and I approve this PR.

**Comment by Anewbe** [comment]
@Mewchild You seem to have missed the item sprites for these.

**Comment by Mewchild** [comment]
I'm actually not sure why it's doing this. I can't see a code difference between the HoS cloak and the Security cloak, as two examples: https://i.imgur.com/2JwEg8q.png
Cloaks use the north facing item equipped state as their item state, which is why icon and item states match. Confused on this

**Comment by Anewbe** [comment]
The sprites it tries to use when it's not being worn aren't in the file they need to be in, is the issue.

https://github.com/PolarisSS13/Polaris/blob/master/icons/obj/clothing/ties.dmi

**Comment by Mewchild** [comment]
Oh. I'm fucking dumb

**Comment by Mewchild** [comment]
Fixed via #5400

**Pull request merged**
