### PR TITLE
Adds snowsuits.

### PR DESCRIPTION
**Pull request by Belsima**
Does not touch department jacket access.

http://i.imgur.com/rAI7gPg.png

I got the sprites from a folder of sprites my friend gave me. Looked through just about every repo I could, didn't find any source- I assume it was from a forum dump.

### CODE REVIEW

**Comment by Belsima** [comment]
I see the issue. I'll fix when I get home.

**Comment by Anewbe** [comment]
I'm not really seeing the point over the winter coats we have?

**Comment by Belsima** [comment]
...shit. Huh. You're right. I thought a snowsuit was different until I googled it.

**Comment by Belsima** [comment]
No, it is different. Also, I like how these look better so I'll open until I get told no.

**Comment by Anewbe** [comment]
Don't restrict the department jacket access, please, that's deliberately open.

**Comment by Belsima** [comment]
Alright.

**Comment by Belsima** [comment]
That should fix her.

**Pull request merged**
