### PR TITLE
Adds Neerti's Law Book

### PR DESCRIPTION
**Pull request by Anewbe**
- With any luck, it should have all of our laws and regs.
- When we finish new SOP, we will add those to the same book.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
If you want ideas for SOP, Virgo's already got a pretty comprehensive one.

https://wiki.vore-station.net/Standard_Operating_Procedure

**Comment by Anewbe** [comment]
We've had our own project running for some time, we just need to sort it. Thank you, though.

**Comment by SpadesNeil** [comment]
Cheers, then.

**Comment by Belsima** [comment]
you made it all satchels

**Comment by Anewbe** [comment]
Satchels happen, fix is up.

**Pull request merged**
