### PR TITLE
Adds the white webbing for paramedics

### PR DESCRIPTION
**Pull request by Mark9013100**
* Adds the white webbing, an edit of the brown webbing with a medical cross on the back. Available in the EMT closets and their relevant cargo crate.

* Paramedics/the Chief Medical Officer can select white webbings from custom loadout.

* Adds white webbings to the Mercenary base and ERT Medical Prep.

### CODE REVIEW

**Comment by Kelenius** [comment]
>Paramedics can now select brown and black webbings from custom loadout.

This one stands out. Only paramedics can get white, security and paramedics can get black, engineering and paramedics can get brown. This is either all or nothing - either allow all three departments to pick any of the three colors or limit paramedics to white.

**Comment by Mark9013100** [comment]
White webbings will still be medical exclusive, but I'll allow engineering and security to get each other's webbings.

**Comment by Datraen** [comment]
I'd prefer them to be exclusive, as the permitting of black and brown, specific webbings for engineering and security, were meant for those departments alone.

**Comment by Yoshax** [comment]
It's also pretty unfair how everyone in the other departments gets their webbing, but only paramedics get the medical one.

Also, you should add it to the webbing supply crate.

**Comment by Mark9013100** [comment]
The white webbing is exclusive to medical due to the medical cross on it, but I'll remove it and make it available to engineering and security if it's that wanted.

**Comment by Kelenius** [comment]
Or just keep engineering webbings to engineering and security to security.

**Comment by Datraen** [comment]
The exclusivity of the webbings is better to keep.

**Comment by Mark9013100** [comment]
Alrighty then.

**Comment by Yoshax** [comment]
Keep the exclusivity, and add it to the crate you can order. Along with sorting the problem of the unfairness of job availability. It's slightly odd.

**Comment by Kelenius** [comment]
Also, CMO should have access to those. Since he's their boss, after all.

**Comment by Mark9013100** [comment]
Just going to throw this up again later.

**Pull request closed without merging**
