### PR TITLE
ᵗᵉᵉⁿʸ ᶠˡᵃˢʰˡᶦᵍʰᵗ ᵗʷᵉᵃᵏ

### PR DESCRIPTION
**Pull request by lbnesquik**
A small noise now plays when your flashlight runs out of power. I didn't find any noise online which fitted my desire of a small, hushed electric fizzling so i used spark3 on very low volume.

### CODE REVIEW

**Comment by lbnesquik** [comment]
https://github.com/VOREStation/VOREStation/pull/4326

**Comment by lbnesquik** [comment]
This is a new button.

**Comment by Anewbe** [comment]
And where did that sound come from?

**Comment by lbnesquik** [comment]
This is a noise from virgo.

**Comment by lbnesquik** [comment]
https://github.com/lbnesquik/VOREStation/commit/6e56fc99c6a954896dc34c53ea4ca4e5a2af7554

**Comment by lbnesquik** [comment]
@Anewbe Do not merge tag is outdated

**Comment by Atermonera** [comment]
And it's possible for real life to steal people for extended periods of time.

**Comment by SpadesNeil** [comment]
Nyet! You exist only to serve! -nods sagely-

But really I'm just being an ass. :P Don't take either of these posts seriously. Just making sure you didn't forget about us.

**Comment by lbnesquik** [comment]
Technically, it's been 27 days.

**Comment by elgeonmb** [comment]
there's a dev freeze up IIRC

**Comment by lbnesquik** [comment]
Really? If it's the AI thing, i don't think this PR will walk on their toes.

**Pull request merged**
