### PR TITLE
Gender tweaks and adjustments

### PR DESCRIPTION
**Pull request by Yoshax**
Ports:
Baystation12/Baystation12#12669
Baystation12/Baystation12#12702

Splits gender into biological gender and gender identity.
- allows species' gender selection to be limited
- biological gender determines sprite where appropriate
- both are shown in medical records
- gender identity determines pronouns upon examine and suchlike to allow for androgynous/agender/other things

### CODE REVIEW

**Comment by nachomeep** [comment]
Best pull request in the past months.

**Comment by Kelenius** [comment]
>No apache helicopter option

**Comment by EmperorJon** [comment]
Please, the "I identify as an attack helicopter" meme got old several years ago.

**Comment by Yoshax** [comment]
Can we keep the stupid jokes and comments out of the discussion? They're not helpful.

**Comment by PsiOmegaDelta** [comment]
This is technically an improvement over the current Polaris situation, were the main gender var can be set to male/female/neuter/plural for any and all species during character setup, and were the neuter/plural options tend to cause interesting effects for human-like (not humanoid) mobs as some sections of the code checks if the mob is male and otherwise assumes female while other locations switch it around.

There is certainly a compromise baked in here, allowing people to select their preferred gender identity and having it show up when examined, however, if you really do want to identify as an Apache helicopter that is now possible without breaking BYOND.

**Comment by RoseCG** [comment]
If this works, would it be possible to do the same thing for hair colors?

This was something discussed on Bay, and I know some characters only have their hair dyed instead of genetically modified. Once they're cloned, they come to life with their original hair color.

**Comment by Yoshax** [comment]
Probably wouldn't be too difficult. But I'm not sure where hair color is used or checked or anything of the sort. But likely simple.

**Comment by Datraen** [comment]
:+1:

**Comment by Neerti** [comment]
One possible issue I can imagine with this is that for certain FBP synthetics, their 'sex' would be locked to MALE or FEMALE, which might be odd for some people.

**Comment by PsiOmegaDelta** [comment]
That's a tricky one, as I assume FBPs are not their own species template anymore but simply a full body prosthesis?

**Comment by Neerti** [comment]
Yes, as FBP is an anagram of that.  Unfortunately I can't think of a nice way to 'test' for being an FBP for a character that exists as a preference setup instead of a mob instance.

**Comment by PsiOmegaDelta** [comment]
I have an idea, that should do the trick, just need some spare time.

**Comment by Yoshax** [comment]
To do:
- Change appearance changer to check for and allow FBPs to select genders other than male and female.

**Comment by EmperorJon** [comment]
DNM pending (to do)?

**Comment by Yoshax** [comment]
To do is done.

**Comment by Datraen** [comment]
I didn't notice any glaring at a quick glance, someone else might want to look at it.

**Comment by Zuhayr** [comment]
@Neert belatedly - check if the chest is set to prosthetic in the preferences robot limb data.

**Comment by nachomeep** [comment]
Do neuters use the male chest, female face still?

**Comment by Yoshax** [comment]
I didn't change any of the sprites, or where they're used.

**Pull request merged**
