### PR TITLE
Xenoarch adjustments.

### PR DESCRIPTION
**Pull request by Belsima**
Some xenoarch tools can now be built in the protolathe and also deconstructed. (Ported from Bay.) Replaced some xenoarch sprites with ones from VORE.

New Sprites: image image image image

### CODE REVIEW

**Comment by Anewbe** [comment]
When you say xenoarch tools you mean things that are used to dig up relics, or things that are relics that can be dug up?

**Comment by Belsima** [comment]
The first- things such as GPS, anomaly scanners, depth scanners, that bunch.

**Comment by Anewbe** [comment]
Which sprites did you replace?

**Comment by Belsima** [comment]
I'd get screenshots of them but DM is borked for me. All the ones I gave screenshots for are the ones replaced, though.

**Pull request merged**
