### PR TITLE
Adds Grayson Manufactories FBPs.

### PR DESCRIPTION
**Pull request by Belsima**
images

Taken from Paradise.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Looks nice.

**Comment by Belsima** [comment]
[5:51 PM] Baguette: i would bone a robot like that

just one of our many shining reviews

**Comment by SpadesNeil** [comment]
>[5:51 PM] Baguette: i would bone a robot like that
>just one of our many shining reviews

Vorestation players be like, "Give me a minute."

**Comment by SilverTalismen** [comment]
Now does the eyecolor change?

**Comment by Belsima** [comment]
No. I might add such in a later PR, but not as of now.

**Comment by Anewbe** [comment]
Yeah... That eye isn't going to work, if I remember how the species code works.

**Comment by Belsima** [comment]
Could I ask why that is?

**Comment by Anewbe** [comment]
The eyes are pasted on as an overlay, based on the species (or maybe bodypart) in question. So this FBP will have the green "eye" and two eyes of whatever color the player chooses.

**Comment by Belsima** [comment]
(So I can fix it, obviously.)

**Comment by Belsima** [comment]
How do other FBPs get away with it, such as alternate Heph or w/ever?

**Comment by Anewbe** [comment]
I don't actually know.

**Comment by Belsima** [comment]
Fixed by setting it to use monitors rather than eyes, I think. Also ports these. https://github.com/Baystation12/Baystation12/pull/17484

**Comment by MagmaRam** [comment]
Is this ready to go?

**Comment by Belsima** [comment]
I'll test it one more time then poke you on discord.

**Pull request merged**
