### PR TITLE
Fixes #702

### LINKED ISSUE #702: Chief medical officer's office privacy shutters are useless because there is a glass door.

### PR DESCRIPTION
**Pull request by Yoshax**
Fixes #702 

Chapel office looks kinda icky, but it's the best that can be done without a convoluted solution.

### CODE REVIEW

**Comment by Zuhayr** [comment]
Screenshots?

**Comment by Yoshax** [comment]
CMO Before: https://i.gyazo.com/13604603b2dbef57c78770f173a016d9.png
CMO After: https://i.gyazo.com/d0284f6e119aeff6713a5b88c297075f.png

Chapel Before: https://i.gyazo.com/ce22fbb8d0262cd960f89d3c88046373.png
Chapel After: https://i.gyazo.com/74eaa056be7ad88e4d6533eaf34bb0fb.png

CE Before: https://i.gyazo.com/11438703fd7877c10b01a0575588bcb0.png
CE After: https://i.gyazo.com/7d124b542c6093c4b71075452628f8dd.png

RD Before: https://i.gyazo.com/b9c27daaa4646f90f06057b8618fe040.png
RD After: https://i.gyazo.com/1a8c3b1c0e2357f1f5727bc1639ae07a.png

Gives all the heads actual privacy, along with the chaplain by removing the glass doors.

**Comment by sabiram** [comment]
Head of security also has a glass door, I believe.

**Comment by Yoshax** [comment]
HoS' door has a nornal one. Conflicts should be fixed.

**Pull request merged**
