### PR TITLE
 Tooltip framework + Mob tooltips

### PR DESCRIPTION
**Pull request by Leshana**
There's also a verb to toggle it, if you like to switch it in certain situations, so you can macro it. Also shows health in % under name if you're wearing a health hud, and arrest status if wearing a sec hud.

Port of VOREStation/VOREStation#3225, VOREStation/VOREStation#3249 and VOREStation/VOREStation#3275

### CODE REVIEW

**Comment by elgeonmb** [comment]
incredibly good

**Comment by BillyBangles** [comment]
p r a i s e

**Comment by Neerti** [comment]
```
code/_helpers/mobs.dm:283:error: cached_character_icons: undefined var
code/_helpers/mobs.dm:284:error: cached_character_icons: undefined var
code/_helpers/mobs.dm:287:error: cached_character_icons: undefined var
polaris.dmb - 3 errors, 0 warnings (3/21/18 1:46 am)
```

**Comment by Leshana** [comment]
@Neerti @Atermonera Was a mistake in resolving a merge conflict due to end-of-file whitespace. Fixed now.

**Pull request merged**
