### PR TITLE
Build-able DLC + Frame Unification

### PR DESCRIPTION
**Pull request by SinTwo**
Not entirely sure how to compact commits but here it is.
EDIT: I now know how to, however it will not let me compact all the commits without a dreadful amount of work.

Unifies frame code.

Adds the ability to build:
- ATM
- Newscaster
- Guest pass console
- Holopad
- Intercoms
- Status displays
- Notice boards
- Fire extinguisher cabinets
- Mirrors
- Entertainment monitors
- IV drips
- Roller beds
- Shower curtains
- Plastic flaps

At a later point when not mega tired I will make a guide on how to build/deconstruct these and with it revamp the construction page on the wiki.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
>Plastic flaps

Are those even deconstructable?

**Comment by SinTwo** [comment]
All of them should be able to be constructed and deconstructed.

**Comment by Mark9013100** [comment]
For combining commits:

Step 13 - Clean commits (Optional)

This is a guide specifically for TortoiseGit, our recommended client
Navigate to your local version of the branch
Ensure it is up to date with the remote
Go to Show log
Select all the commits associated with this change or PR
Right click and choose Combine to one commit
This will open up the standard commit interface for TortoiseGit, with the commit logs of the selected commits merged together
Perform the normal routine for a commit
Go to push your branch to the remote branch
Ensure Force Overwrite Existing Branch/Overwrite known changes (may discard changes) is selected to make sure the PR/Remote updates to contain just this squashed commit

**Comment by Lorwp** [comment]
I could probably compact these for you in my fork later, with a `git rebase -i`

**Comment by Lorwp** [comment]
@SinTwo What do you want Changed? I currently (With merge commits squashed into one line) see this.

```git
# Merge Commits are actually The Full list of commits merged in my view, with no single squashed commit
pick 94d4bb6 Frame Rewrite map fix
pick 6e56eeb Sprite, Map, and bugsmash 2.
pick 618d4c7 Frame Fix 3(?)
# merge commits
pick a58ef9e Fixed the extra frame parts that caused bad merge
pick a639838 Fixes rebuildable machine bug and tweaks a few moves as per PsiOmegaDelta's suggestions.
pick 24997f2 Fixes parts deleting after being crowbar'd out.
#merge commits
pick fed38f8 Because Cards Are Jerks
pick 66985da Buildables and fixes.
#merge commits
pick af6398b Buildables Compile Fix

# Rebase beb54f9..af6398b onto beb54f9 (327 command(s))
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

Can you reorder this to what you want to compress these into?

**Comment by Neerti** [comment]
This has been sitting for over a month and not much seems to have happened.  Feel free to open a new PR once you get back around to this.

**Pull request closed without merging**
