### PR TITLE
Update Chat System to use to_chat(src, "") instead of src << ""

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Massive refactor to assist in upgrading our chat client to incorporate either goonchat or TG's Dark Mode.

Removes all instances of src << "" and replaces with better to_chat(src, "") method

### CODE REVIEW

**Comment by Rykka-Stormheart** [comment]
In case it isn't clear, I *do* need help with this, but I thought I'd lay the groundwork by removing all instances of `src << ""` and then going from there

**Comment by Atermonera** [comment]
I know that `<< browse()` is a valid thing for opening html windows, and I believe that there is similar syntax when outputting sounds to the client.

**Comment by Rykka-Stormheart** [comment]
It should be functionally done, afaik.

**Comment by Atermonera** [comment]
Thank the gods for the addition of the `viewed` tickboxes

**Comment by GeneriedJenelle** [comment]
Badass, did you guys use regex for this? And if so, what regex code? 

... Or did you painstakingly go through every line and change it manually?

**Comment by Rykka-Stormheart** [comment]
> Badass, did you guys use regex for this? And if so, what regex code?
> 
> ... Or did you painstakingly go through every line and change it manually?

Every line was done by hand/manually, to prevent any errors or replacements of stuff like "src << browse"

**Comment by GeneriedJenelle** [comment]
> > Badass, did you guys use regex for this? And if so, what regex code?
> > ... Or did you painstakingly go through every line and change it manually?
> 
> Every line was done by hand/manually, to prevent any errors or replacements of stuff like "src << browse"

I can almost feel the tediousness. God bless you.

**Pull request merged**
