### PR TITLE
Adds fannypacks.

### PR DESCRIPTION
**Pull request by nachomeep**
Also adds them to custom loadout.

Ported from https://github.com/tgstation/tgstation/pull/7246

### CODE REVIEW

**Comment by nachomeep** [comment]
Do note I'm a terrible coder. I probably used the wrong setup for the selection, as I recall there being two ways in use.

**Comment by Kasuobes** [comment]
Mind if I steal the sprites?

**Comment by Anewbe** [comment]
Have you tested this?

**Comment by nachomeep** [comment]
@Kasuobes I stole them from Paradise Station- was unable to find their PR. Discovered they stole it from https://github.com/tgstation/tgstation/pull/7246.

@Anewbe Yes. It works fine.

**Comment by Anewbe** [comment]
I assume I will come to regret this, but eh.

**Comment by nachomeep** [comment]
How could you possibly regret fannypacks?

**Comment by Anewbe** [comment]
It's more free storage, but eh.

**Comment by nachomeep** [comment]
It's only twice that of a hoodie, though.

**Pull request merged**
