### PR TITLE
[WIP] Shuttletwo

### PR DESCRIPTION
**Pull request by Kelenius**
tl;dr: those are shuttles that can fly to custom coordinates. The part that moves the area is working, with some issues, and they can also dock/undock, but there's still a lot of work to do.

### CODE REVIEW

**Comment by Minijar** [comment]
Is this similar to the old helm control console?

**Comment by Kelenius** [comment]
>Is this similar to the old helm control console?

No idea, what did it do?

**Comment by Minijar** [comment]
> No idea, what did it do?
Let you fly a ship around using coordinates, it also showed you your ships position on a map and you had to use little arrow buttons to jump tiles forward/backward etc.

**Comment by Kelenius** [comment]
Yes and no. I want to remove pre-defined zones for the shuttles and replace them with saved coordinates, plus you could add your own - e.g. mercs will start with the same set of points they can move to, but they can also set their own. That would also allow you to have overlapping locations for merc and heist shuttle.

In a long-term, constructible shuttles.

**Comment by Minijar** [comment]
Probably unfeasible, but what about crashing a shuttle into the colony using this system?

**Comment by Kelenius** [comment]
Hmm... Well, what it does is determine the shape of the shuttle, then pick all turfs in the target area that would be covered by it, generate a new zone out of those turfs, move the shuttle there, then delete the old shuttle area. Doing it with turfs that are already filled with something would be no different. At the moment, however, it's set to only accept space turfs in a space area and abort the move if the target differs.

**Comment by comma** [comment]
Can check for overlaps (solid turf here and at destination) and call ex_act(1) or something.

**Comment by Kelenius** [comment]
It uses ``move_contents_to`` which AFAIK overwrites the old tiles.

**Comment by Kelenius** [comment]
This is too much work to do at once, I'll need to clean up docking first. The transfer isn't the problem, the docking system is.

**Pull request closed without merging**
