### PR TITLE
Replaces solar panel sprites.

### PR DESCRIPTION
**Pull request by Belsima**
Taken from a russian paradise branch. I don't believe it's the origin, being a nazy pony ERP server without a name, but still.

images

### CODE REVIEW

**Comment by Woodratt** [comment]
Does it keep the old sprites listed as old? Or outright removes them?

**Comment by Belsima** [comment]
Removes them. Would you prefer them marked as old? I assumed in the case of the tracker and sp_base at least, it was a direct upgrade.

**Comment by Woodratt** [comment]
Leave them in the dmi marked as old, we may find a use for them in the future.

**Comment by Belsima** [comment]
Alright.

**Comment by Belsima** [comment]
Done.

**Pull request closed without merging**
