### PR TITLE
Disable breaking fragile floor tiles with the crowbar

### PR DESCRIPTION
**Pull request by lbnesquik**
It's not fun, it adds nothing to the gameplay and it isn't clear what breaks and what does. I see seriously zero reasons to keep this.
This include wood and some of the floor in robotics for example.

### CODE REVIEW

**Comment by Greenjoe12345** [comment]
maybe set it to only do it on harm intent, so it's still possible, but you can't do it quite so easily on accident

**Comment by lbnesquik** [comment]
Why would you willingly want to do that? And you can just stuff it into an autolathe, disposal or chuck it into a corner if you don't want to see it.

**Comment by Cyantime** [comment]
Not all flooring types have tiles, without the ability to do this there'd be no way to get to the plating under certain floors.

**Comment by lbnesquik** [comment]
This doesn't disable crowbaring them. It disables BREAKING them. You can still use a crowbar to get everything out.

**Comment by lbnesquik** [comment]
Updated my PR after testing. This one does work to pry off wooden tiles.

**Comment by Atermonera** [comment]
Staff input: Yae

**Pull request merged**
