### PR TITLE
Turns the station into 420-station 13.

### PR DESCRIPTION
**Pull request by BillyBangles**
Adds rolling papers, allowing for craftable joints. Anything you can dry with the drying rack you can roll into a joint and smoke. You can buy a box of 14 papers for a mere 10 thaler at your nearest cigarette vending machine. Now you can live out all of your stoner fantasies on station! Better not let Dave McSecurity see you with that doobie, else you're in a world of trouble.

~~The in-hand sprites for the joint are really bad please send help~~

### CODE REVIEW

**Comment by Anewbe** [comment]
#BlazeIt

**Comment by Magneld** [comment]
Turn off the scrubbers, hotbox the bar. I support.

**Comment by BillyBangles** [comment]
aw fuck i didn't even think about that.
dunno enough about atmos code to make that happen though. Some Day(tm)

**Comment by Nerezza** [comment]
Think we could get tobacco tins in the machines for rolling normal cigarettes, for the hip crowd of course?

**Comment by Anewbe** [comment]
Do we even have tobacco?

**Comment by BillyBangles** [comment]
We don't have tobacco at all. That's fixable, but I'm gonna take a look at stealing some /tg/ plants in a future PR, so not for now.

**Pull request merged**
