### PR TITLE
Reagents use pathing instead of strings

### PR DESCRIPTION
**Pull request by Anewbe**
Heavily inspired by and partially ported from work done on Baystation.
- Reagent commands use the paths of the chemicals instead of strings. This means that you need to use /datum/reagent/dylovene instead of "anti_toxin". It also means that the compiler will catch you if you mess up.
- Swaps the reagent dispenser cartridge sprites for fancier ones that were apparently made long ago by Mechoid.

- [ ] More testing. First tests have been done, but this is gonna break basically anything at random, so I need to spend more time on hunting.

### CODE REVIEW

**Comment by MisterLayne** [comment]
It is the pathing revolution.

**Comment by Anewbe** [comment]
Viva.

**Comment by Wickedtemp** [comment]
Finally, no more abnormal looking giant grey squares.

**Comment by Anewbe** [comment]
I'll get back to this eventually, tired of all of these old PRs cluttering the Git.

**Pull request closed without merging**
