### PR TITLE
Removes species restrictions on shoes and gloves for Taj and Unathi

### PR DESCRIPTION
**Pull request by Anewbe**
Rejoice, for you are no longer limited to 2 shoes and magboots.

### CODE REVIEW

**Comment by serenemelody** [comment]
yes but how am i supposed to oppress those filthy xenos now?

**Comment by Anewbe** [comment]
Harmbaton.

**Comment by serenemelody** [comment]
what, and dirty my stun baton? what am I, some kind of peasant?

**Comment by Anewbe** [comment]
If your baton doesn't match your bright red uniform, then yes, you peasant.

**Comment by ParadoxSpace** [comment]
why not leave the restriction and have loadout gloves come pre-snipped

**Comment by zekesulastin** [comment]
What ParadoxSpace said

**Comment by Anewbe** [comment]
Because both of the lore heads for the affected species want it gone.

**Comment by Zuhayr** [comment]
Just make them human resprites again and be fucking done with it.

**Pull request merged**
