### PR TITLE
Monkey cubes now expand in showers

### LINKED ISSUE #1025: Shower Doesn't Put Out Mob Fires
**Brief description of the issue:** While on fire, standing in a shower that is turned on will not put the fire out.

**What you expected to happen:** The fire to be put out.

**What actually happened:** The fire did not go out.

**Steps to reproduce:** 
1.) Catch fire
2.) Turn on shower
3.) Step into shower

### PR DESCRIPTION
**Pull request by Kelenius**
Port of https://github.com/Baystation12/Baystation12/pull/12107 and
https://github.com/Baystation12/Baystation12/pull/12183

Edit: fixes #1025.

### CODE REVIEW

**Comment by Telvayne** [comment]
Does this preserve showers cleaning blood off of people?  Actually, do they still do that?  I don't think they remove blood/oil from clothes..

**Comment by Kelenius** [comment]
I didn't touch that, and I think they do.

**Comment by Telvayne** [comment]
Second question, will this resolve #1025?

**Comment by Kelenius** [comment]
Yes.

**Pull request merged**
