### PR TITLE
Loyalty implant for HoP

### PR DESCRIPTION
**Pull request by SpadesNeil**
I'm pretty sure this used to be the case and I don't know why it was changed.

Why would you NOT give a loyalty implant to the guy who can give himself (and others) all access, is second in command to the Captain, and has access to everyone's bank accounts?

HoS, HoP, and Captain all have the power to individually single handedly doom the entire station if they decide they want to be jerks at work that day. If NanoTrasen is going to buy loyalty implants for them, they should have implants for all three of them or none at all.

### CODE REVIEW

**Comment by Serithi** [comment]
Because we're not grimderp?

**Comment by SpadesNeil** [comment]
Grimderp? So, loyalty implanting the guy with access to all of the station's weapons, and implanting the guy with access to the whole station, but we're not implanting the guy who can give himself access to the whole station just because he feels like it?

Respectfully, that doesn't sound like a sensible and consistent way of doing things. Considering this is how it is on other servers I've played, this seems like an oversight.

**Comment by mwerezak** [comment]
I think you missed the point.

**Comment by SpadesNeil** [comment]
Then let's remove them entirely instead if that's the opinion of them.

I like the idea of loyalty implants but that's just me.

**Comment by Yoshax** [comment]
AFAIK, Loyalty implants aren't used at all.

**Comment by zekesulastin** [comment]
@SpadesNeil It actually is a config option in game_options.txt; the implant_loyalty function checks that option.  USE_LOYALTY_IMPLANTS is commented by default.

**Comment by SpadesNeil** [comment]
Well then I'm going to re-open this after all. :U

**Comment by Serithi** [comment]
I'm still failing to see how this would be legally accepted in the slightest.

**Comment by zekesulastin** [comment]
@Serithi It's not on for Polaris or by default in Polaris code: https://github.com/PolarisSS13/Polaris/blob/master/config/example/game_options.txt#L66 - Spades is just trying to fix an inconsistency for when that config option is enabled.

I'm not really for or against it, as it's mainly a balance discussion that does not affect Polaris since we do not have those implants available.

**Comment by Datraen** [comment]
There's no real reason not to, but also no real reason for us to.

I'm good with the change going through for downstreams, as it's not overridden in implementation here.

:+1:

**Comment by EmperorJon** [comment]
If downstream maintenance of loyalty implant mechanics is wanted, then this makes sense, yes.

**Comment by Spookerton** [comment]
There's no real value in this change for Polaris, but it does represent correctness for a feature that we have retained, if only because it can be disabled. Sure why not. :+1:

**Comment by Yoshax** [comment]
I'll probably not run the changelog for this when I do so, cause it'll no doubt confuse people. But all is well.

**Pull request merged**
