### PR TITLE
Skrell sprite updates.

### PR DESCRIPTION
**Pull request by Belsima**
Adds two headtentacle styles, and updates the ugliness that was skrellsprites. Also makes gold chains shinier.

New: image
Old: image

Edited from: https://github.com/ParadiseSS13/Paradise/pull/6245

### CODE REVIEW

**Comment by Anewbe** [comment]
Couple thoughts from the Staff:
- Looks like they've got breasts or pecs, that's not how Skrell work.
- Outline is really dark

**Comment by Belsima** [comment]
Those markings are actually currently on our female skrell sprite. 1ce told me to take the female sprite and use that to replace the male one, which is the 'old'. 
image

**Comment by Belsima** [comment]
Fixed it.

**Comment by Anewbe** [comment]
Looks like your previews are off.

**Comment by Belsima** [comment]
Ooh, right.

**Comment by SilverTalismen** [comment]
I like these changes, looks nicer atleast.

**Comment by Belsima** [comment]
Preview fixed.

**Pull request merged**
