### PR TITLE
Gives Diona pay the same as Taj and Unathi

### PR DESCRIPTION
**Pull request by Yoshax**
I was playing a Diona chef, and I couldn't even buy ramen to make hell ramen. What is this.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
why do dionaea need as much money

**Comment by Yoshax** [comment]
Because slavery is bad. And because none of those numbers actually matter.

**Comment by ParadoxSpace** [comment]
it's not slavery my man
i'm pretty sure dionaea lorewise don't need to be paid all that much from a corporate standpoint

**Comment by Yoshax** [comment]
The numbers are worthless lorewise. They don't mean anything, neither does the amount of money anyone starts with. Just having no money is limiting in-game when you want to do certain things.

**Pull request merged**
