### PR TITLE
Keekenox's vents + scrubbers 2.0

### PR DESCRIPTION
**Pull request by listerla**
img

### CODE REVIEW

**Comment by Atermonera** [comment]
image are those supposed to be animated? New sprites don't appear to be on icon diff. Issue occurs on a few different files.

**Comment by listerla** [comment]
oh fuck me how did i even break that

**Comment by listerla** [comment]
@Atermonera Fixed. Files that weren't animated prior still aren't animated.

**Comment by Atermonera** [comment]
All the spinny sprites are now spinny :+1:

**Pull request merged**
