### PR TITLE
Resprites Health Analyzers and Adds Scanning Animations

### PR DESCRIPTION
**Pull request by Michiyamenotehifunana**
:cl: Toriate
add: Health analyzers now have scanning animations
imageadd: Resprited all tiers of health analyzers
/:cl:

Hanal Poster2

This PR will resprite all health analyzers (Regular, Improved, Advanced, and Phasic) and give them scanning animations that will be played if it successfully scans a mob.

In-game view:
dreamseeker_NlGCoIth8g
dreamseeker_RJXs0xiaIc

All assets included in this PR are licensed under CC-BY-SA unless otherwise noted.

Old image:
Hanal Poster

### CODE REVIEW

**Comment by Wickedtemp** [comment]
I kinda like the current ones more. The basic one here looks okay, but the others kinda... look as if they'd electrocute you.

**Comment by Novacat** [comment]
I only feel that way about the Phasic one, but, the phasic one is adminbus only so I am not going to be too concerned about it.

**Comment by Atermonera** [comment]
I think they're nice sprites, but I'm not sure how well they fit the visual style of the rest of medical's equipment. Definitely something that's going to take [further discussion](https://forum.ss13polaris.com/viewtopic.php?f=14&t=827)

**Comment by Wickedtemp** [comment]
Style-wise, yeah, it's more of grey-silver-sleekness that.. could work for Science, but most of Medical's stuff isn't greyscale. Maybe its mostly just the color? If they were white, it might fit a little more nicely.

**Comment by Woodratt** [comment]
Copy pasta'ing from the thread

> I like the little animation that plays when it scans someone.
> 
> But the color feels a bit off. It feels like it'd fit in with science more than medical currently. Maybe tweak the grey more towards medical white or just flat out replace it with a white might help.
> 
> I also feel a bit off put by the basic scanner. Its the one that's going to get seen the most, and feels almost, too basic/generic. The older sprite had a teeny bit of color with the red yellow and green dots (which I assume were lights) and the shape wasn't a basic rectangle. The new one feels a bit flat and brickish, I almost want to argue they lack the 'personality' of the old one. Changing up the color might help with that, but it could just be bias after being used to the old scanner for so long. The new ones don't quite scream 'medical tool' to me. If it wasn't for the blue plus on the screen one could almost argue they're some new research scanner and I'd believe them.

Question, guessing that these don't have a on mob or in hand sprite?

**Comment by Michiyamenotehifunana** [comment]
> Question, guessing that these don't have a on mob or in hand sprite?

Yeah, they're just using the original inhands.

Anyways, I've taken a quick look over all the feedback, and I've come up with some changes. It would be great if someone could forward these to the forums as well ~~because I'm lazy~~.

Health Analyzer Proposed Changes

Hanal Poster2

In particular, all the main colors of the analyzers have been significantly brightened up, and the outlines have much more contrast than they did. In addition, I have added the three colored dot thingies to all the analyzers.

I have also decided to tack on an antenna to the basic model, seeing as the original also had one. I have also made the Advanced model's antennae more stubby and plastic-y, in order to attempt to make it look less 'lectric-y.

I'll wait for additional feedback before proceeding with these modifications. Also, thanks in advance to whoever forwards this to the forums, and thank you all for discussing this.

**Comment by Woodratt** [comment]
No further complaints from my end. +1

**Comment by Wickedtemp** [comment]
Yeh. I like it.

**Comment by Michiyamenotehifunana** [comment]
Alright, the new sprites have been committed. Thanks again to everyone who participated in the discussions (especially the ones who brought it to the forums).

**Comment by Atermonera** [comment]
Staff say yay

**Pull request merged**
