### PR TITLE
Disarm spam is less effective

### PR DESCRIPTION
**Pull request by Anewbe**
There's a timer between chances to actually do anything with disarm intent.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
I'm all for this, ive watched people disarm spam shove people down so they could kill them and keep them down.

**Comment by Yoshax** [comment]
Couldn't you just make disarm intent just have normal attack cooldown, since I'm pretty sure it doesn't.

**Comment by Anewbe** [comment]
In testing it has the same delay as fists, from what I can tell.
Also wouldn't stop the main issue, which is just using disarm until you roll the lucky number and ends the fight. Actual delay for the push is TBD, though.

**Comment by Yoshax** [comment]
It doesn't really resolve the issue. If you push someone down, you don't have to push them again. You just pin them down, and the fight is over.

**Comment by Anewbe** [comment]
This makes it so if you don't knock them down on the first click the next several will be useless.

**Comment by Yoshax** [comment]
I misunderstood the var name.

I'm not sure this is a good idea, disarm stuff can be a huge problem, but I do not believe that tacking on a six second cooldown is the way to resolve the issue. Six seconds is a lot of time.

**Comment by Iamgoofball** [comment]
Completely kills hand to hand combat meta

**Comment by SpadesNeil** [comment]
Disarm spam does piss me off to no end to be honest. I can often disarm a security officer faster than they can stun me.

You get one chance, I say. If you fail, you shouldn't have time to IMMEDIATELY try again.

**Comment by Anewbe** [comment]
@Yoshax Yeah, I'm probably going to drop it to around 3~4 seconds, still need to discuss.

**Comment by Yoshax** [comment]
You could do more interesting options than a straight cooldown such as dynamically calculating the chance to push based on multiple factors including a persons health, pain, mob size, etc. Make it a lower chance than now at perfect health conditions. 

Or introduce a counter using intents, like pushing a person who is on help intent would be easier than pushing someone who is on harm intent, and pushing someone else on disarm intent would be more difficult.

I feel as though a different solution than a flat cooldown would be optimal, something that adds to the feel and the flow of the game at the same time as resolving the issue.

**Comment by Anewbe** [comment]
I could (and would like to) do that, at some point, but I don't have the time and energy right now to go and essentially rewrite hand-to-hand.

**Comment by SpadesNeil** [comment]
3-4 seconds seems reasonable. Even 2 seconds.

**Comment by Anewbe** [comment]
Time's dropped to ~3 seconds.

**Comment by SpadesNeil** [comment]
I like this. 3 seconds is completely reasonable.

It negates the spamming abuse of disarm, while still allowing disarm to be combat effective.

**Pull request merged**
