### PR TITLE
Adds 24 new skirt versions of suit sprites.

### PR DESCRIPTION
**Pull request by Cerebulon**
Adds 24 new skirt versions of existing suit sprites.

Adds them to loadout options and departmental uniform lockers as appropriate.
One new (Old Woman Attire) as equivalent to old man suit.

Full List:
Detective skirt: loadout option for detectives, added to detective gear supply crate and detective wardrobe.
Internal Affairs skirt: loadout option for IA agents.
bartender skirt: loadout option for bartender, added to formal closet.
Shiny-black skirt suit: loadout option, added to lawyer and HoP closets.
Lawyer-red skirt suit: Loadout option, added to lawyer and HoP closets.
Blue skirt: Loadout option, added to lawyer closets.
Purple skirt: Loadout option, added to lawyer closets.
Executive skirt: Loadout option, added to suit locker.
Colony Director's Skirt: Added to colony director's closets.
Red Suit: Loadout option, added to suit locker.
Head of Personnel's Skirt: Added to HoP closets
White skirt suit: Loadout option, added to suit locker
white (alt): Unused sprites.
Blue blazer with skirt: Loadout option.
Old woman attire: Loadout option.
Lady's suit: Loadout option
Charcoal skirt: Loadout option, added to formal closet.
Navy skirt: Loadout option, added to formal closet.
Burgundy skirt: Loadout option, added to formal closet.
Checkered skirt: Loadout option, added to formal closet.
White-blue: Loadout option, added to lawyer closets.
Black skirt: Unused but coded.
Tan skirt: Loadout option, added to formal closet.
Official Skirt Uniform: Unused but coded.

### CODE REVIEW

**Comment by Cerebulon** [comment]
Missed a bunch of hand sprites. Bear with me.

**Comment by Cerebulon** [comment]
Ok, that should be it.

**Comment by Woodratt** [comment]
pictures?

**Comment by Cerebulon** [comment]
Pictures: https://i.gyazo.com/6361538ff46967e4e92e215e2b2d9388.png

**Comment by Anewbe** [comment]
I think there's already an executive skirt... I'm pretty sure I made it.

**Comment by Cerebulon** [comment]
There's a womens executive pantsuit which is what the skirt version is modified from iirc, but I can check if there's a skirt version already that wasn't grouped with the other suits when I get home.

**Comment by Cerebulon** [comment]
Oh you were right, the one I took a screenshot of was the one that was already in there, but I did make a skirt variant of the other executive suit rather than the womens one, the really_black_suit. I think I might've stuck it in with the "coloured suits" in the screenshots because of the item path name.

**Comment by SilverTalismen** [comment]
The current Exec skiirt doesn't function like most of our suits, you can't remove it's jacket or tie, which is annoying, Do you think you could fix it if possible, or replace it Cerebulon? :)

**Comment by Cerebulon** [comment]
That applies to at least half of all the suits in the game. There's modular suits and there's not-modular suits and that's not something I'm changing with this PR.

**Comment by Anewbe** [comment]
Fair point, is this ready to go?

**Comment by Cerebulon** [comment]
It should be all good with the fixes in that last commit, yeah.

**Pull request merged**
