### PR TITLE
Add several new events

### PR DESCRIPTION
**Pull request by ReddeyfishVor**
These are some of the events we've added have have been using on CHOMPStation.
* window break, causing a single window to fail, and all connected nearby windows to take heavy damage
* electrified door, which causes a door to be damaged and electrified
* escaped slimes, which distributes slimes over the station, with the recommendation to return them to xenobiology
* wormholes, which is the R-UST failure turned into event form, covering the map with portals for a short period of time. If you don't move, you don't get teleported to a random spot nearby the station.
Also includes 
* a refactor of a common function to randomly select an area on the station.
* a minor change to wallrot to report its position after a long duration.

### CODE REVIEW

**Comment by elgeonmb** [comment]
Lorewise I'd rather not wormholes but as ever I bow to the gods of Gameplay in this matter.

**Comment by ReddeyfishVor** [comment]
Apologies for the failed travis build, chose to not include the dme so that these events would remain unused in your codebase, but forgot that I refactored one of the used events and would require a change to the dme.

You don't have to use these events (such as wormhole), but they are available if you want to. As is, your current enabled events will not change, requiring a modification to code/modules/events/event_container.vr

**Comment by Atermonera** [comment]
Escaped slimes also don't particularly make sense on a map where xenobio is a 2 minute shuttle ride away from the main station.

**Comment by Atermonera** [comment]
Close and comment looked SUSPICIOUSLY LIKE CANCEL COMMENT

**Comment by elgeonmb** [comment]
No objection to having them in the code for bus shenanigens

**Comment by Anewbe** [comment]
Have these been tested?

**Comment by Leshana** [comment]
@Reddeyfish The window break one is a cool idea.

**Pull request merged**
