### PR TITLE
SMES tweaks

### PR DESCRIPTION
**Pull request by Cyantime**
Some minor tweaks to SMES, and cleanup of smes_construction.dm

Actual changes-

- Constructed SMES start with output off. SMES coils can now be added before adding a terminal, if wanted.
- The first two levels of shocks from hacking filled SMES will only knockdown, instead of causing unconsciousness.
- Switches the deconstruction system to the normal machine one, unbuilding SMES won't vanish the 5 coils used in the frame anymore.

Other notable things-
to_chat() throughout smes_construction.dm
Improved some sentances

### CODE REVIEW

**Comment by Anewbe** [comment]
Has this been tested?

Also, I feel like the hardcoded Weaken/Paralyze might be possible to replace with a scaling electrocute_act(), maybe?

**Comment by Cyantime** [comment]
Tested, but electrocute_act doesn't seem to have a way to ignore the siemens_coefficient on a bodypart, which would stop the arc flash from ignoring your gloves and burn hands.

**Comment by Anewbe** [comment]
Hmm... Maybe have it target the torso?
It's very much not a big deal, one way or another.

**Comment by Cyantime** [comment]
Replaced the ones that don't specifically mention targeting the hand with electrocute_act on the torso, and replaces the other ones with fireloss actually on the hand.

**Comment by Anewbe** [comment]
Fabulous. Will review soon.

**Pull request merged**
