### PR TITLE
Fixes stupid naming of weapon crates

### PR DESCRIPTION
**Pull request by SpadesNeil**
This was confusing and dumb. Now it's not.

### CODE REVIEW

**Comment by Yoshax** [comment]
Munitions literally means Weapons. The group name being Weapons and Weapons makes no sense.

**Comment by Anewbe** [comment]
http://www.dictionary.com/browse/munitions
Going to agree with Yosh here, in that I think it's fine as is.

**Comment by SpadesNeil** [comment]
:U Fiiiine.

**Comment by SpadesNeil** [comment]
The other corrections are still there. Why is this tagged unwanted feature removal?

**Comment by Anewbe** [comment]
I don't consider it a bugfix, and I don't think it's a feature, and I don't have a tag for an in-between.
Not sure the capitalization on those crate names is appropriate, if memory serves there are issues that come up when you do things like that.

**Comment by SpadesNeil** [comment]
That doesn't make any sense. We have an inconsistent, confusing naming, and the capitalization doesn't make a lick of difference except again not being inconsistent with every other crate name.

**Comment by Anewbe** [comment]
Fair enough.

**Pull request merged**
