### PR TITLE
Adds Multiple Alternative Titles

### PR DESCRIPTION
**Pull request by redstryker**
Adds the following alt titles:

HoS:
    - Commander

RD:
    - Research Supervisor

QM:
    - Supply Chief

Janitor:
    - Sanitation Technician 

Librarian:
    - Historian 
    - Professor

### CODE REVIEW

**Comment by Yoshax** [comment]
Commander - Fine and makes sense, I like it.

Brig Officer - Makes sense I guess, but I don't really see the point.
Sergeant - Implies the Warden is a superior, which they are not. Not a fan.

Research Supervisor - Is a decent one, I suppose.

Computer Scientist - Makes sense but there isn't exactly much for them to do actual game-wise.

Life Support Engineer -Makes sense, but sounds kinda convoluted and potentially unclear. Indifferent.

Supply Officer - Is a decent one, but perhaps not 100% clear that they're in charge.

Courier - Not a fan at all. It is a tiny portion of the job and sounds like a very different job entirely.

Historian - Indifferent.
Professor - Indifferent, sounds science-oriented though.

Supply Assistant - Not a fan. There's no need to have Supply Assistant when Cargo Tech exists.

**Comment by redstryker** [comment]
Brig Officer - I actually don't mind removing that one if need be.

Sergeant - I do see the issue in that, stand by for me to ask some questions regarding it to staff because, IIRC, Redman did like the idea of calling them 'Sergeant'.

Computer Scientist - I understand that, but maybe when/if we have modular computers there will be more for them to do.  Regardless, is there really a problem with adding that title?

Courier- I get what you're saying, I personally like the title.  It does only cover a small part of the job, but I still feel like Cargo Tech at least needs one alt title.  I'll remove it if that causes there to be such an issue that the PR won't be merged.

Supply Assistant - I don't really care about this one either, I can remove it if need be, especially since Cargo Tech is such a low-maintenance job.

**Comment by EmperorJon** [comment]
Commander (Never personally liked Commander for security but apparently I'm unique in that regard.)

Sergeant (No.)

Research Supervisor (I... guess? But it's not really any different from Director.)

Computer Scientist (We don't really have computer science to do)

Life Support Engineer (Once again this is pretty much the exact same job expectations just a different name)

**Comment by Anewbe** [comment]
HoS:
- Commander - I like, but I expect they'll keep being called Commander regardless.

Warden:
- Brig Officer - Okay I guess
- Sergeant - Don't really want this

RD:
- Research Supervisor - See Jon

Scientist:
- Computer Scientist - Meh? Don't see the need.

Atmos tech:
- Life Support Engineer - Maybe, might be confusing.

QM:
- Supply Officer - Sure?

Cargo Tech:
- Courier - Meh

Janitor:
- Sanitation Technician - No opinion

Librarian:
- Historian - Sure?
- Professor - Why not?

Assistant:
- Supply Assistant - That's a Cargo Tech.

**Comment by redstryker** [comment]
FYI, I did remove Sergeant and Supply Assistant.

**Comment by redstryker** [comment]
Updated description.

**Comment by Hubblenaut** [comment]
Not really a fan of any of these, to be quite honest.
It feels like having alt titles for the sake of having alt titles.

**Comment by redstryker** [comment]
Since everyone and their mother seems opposed to this PR for one name or other, I am going to explain why I think that these titles would be a nice addition.  

I agree with Hubble in the fact that titles should refer to a different way to do a job with the same tools (unless we are referring to Medical, of course).  However, an alt title can also refer to a different form of training or way of getting to a job.

Regardless, I'll go over every alt title I'm currently proposing and I'll explain why I think it should be added.  

HoS:
- Commander: It is how Hubble says it, it's a more militaristic title.  That's not the only reason I'm proposing it, however.  Many people already refer to the HoS as the 'Commander', so I think adding it as an alt title would be a good idea.  In the way of doing the job, I'd think that they'd be a tad more militaristic than the HoS (if that's even possible :stuck_out_tongue_closed_eyes:).  The title comes with the assumption that the person with it comes from either a military background, or is contracted to NT from a paramilitary company.  All in all, I would like this one as an alt title, but I have no problem removing this from the PR if need be, especially if it's to 'militaristic' for staff's idea of Security, which I don't think it is.

Warden:
- Brig Officer: The current title of 'Warden' comes with the assumption that the person in the job works for a prison or at least did work for a prison.  'Brig Officer' first of all, has less of a ring of authority to it than 'Warden'.  Second of all, it has the connotation that the Warden is similar, if not, the same as other Security Officers in the means of training.  Wardens would probably have had law-enforcement training while Brig Officers would have had similar, if not the same training as Security Officers, with the assumption that they are also trained to manage prisoners.  All in all, I don't particularly mind removing this one either.  I just want an alt title for Warden at some point.

RD:
- Research Supervisor: This is one of those that I'm more particular towards.  As opposed to RD, the Research Supervisor would most likely have training in safety, scientific ethics, the Scientific Method, and basically anything that a person would need to make sure that experiments going on do not get too out of hand, crazy, unethical, or dangerous.  They would be more focused on making sure Research runs smoothly than performing their own crazy experiments.  I don't want to remove this one at all as I quite like it, but if I have to, I will. :frowning: 

Atmos tech:
- Life Support Engineer: This is another one I really like.  Life Support has different connotations than Atmospherics.  Not only does Life Support handle Atmospherics, but it also maintains temperature as well as biological waste disposal.  Now, we obviously have no way of handling plumbing ICly (thank God), but Life Support Engineers would handle that.  In regards to the issue with them being called 'Engineers', I think it fits, personally.  Especially considering the fact that they would have to find ways to make the systems work during a crisis in unideal times.  I can change 'Engineer' to 'Technician' if worse comes to worst, but I'm hesitant to.  I really don't like the idea of removing this title from the PR outright, however, since I think that this is an interesting title and I never really liked the title 'Atmospheric Technician' personally, but that's probably just me.

QM:
- Supply Officer:  I... really don't think that this sounds militaristic, but if you do, *shrug*.  Honestly, I have no idea about this one.  I can remove this if need be, I really wouldn't care. 

Cargo Tech:
- Courier:  This one is one that I personally like, even if it doesn't cover most of what the job is.  I'd think that Couriers would be more focused on safe delivery and the like.  They'd probably be more certified than Cargo Techs, at least in the area of transportation of goods.  Now, I don't want to remove this one from the PR because I feel like Cargo doesn't get as much stuff, including alt titles as the other departments.   Not only that, but I personally get tired of the title 'Cargo Technician.'  I suppose that if it is needed, I can remove it.  I just want other titles for Cargo Tech though,... Something like 'Warehouse Worker' or something.. *shrug*

Janitor:
- Sanitation Technician:  This title implies that the person is more focused on making the station-germ free than 'clean'.  Now, that does mean that they will probably still run around with a mop and bucket, but their main focus will be on sterilization of areas where germs could live (i.e. bathrooms, kitchen, surgery rooms).  They may have different training than Janitors or Custodians, such as certifications in the disposal of biological waste or in killing germs.  I am hesitant to remove this one, but I can if need be.

Librarian:
- Historian: This one's kind-of self-explanatory, plus I don't think many people are opposed to it.  Basically, it's just a person who specializes in history.  They'd obviously have different training from a Librarian, but they'd still stock the library.  I reeeally don't want to get rid of this one.
- Professor: Now, I get the complaint that this sounds like it should be in the Research department, but the thing is, professors can be specialized in really any area of study.  Giving 'Professor' as an alt title to 'Scientist' would make no sense, since a person who has a PhD in, say, Early Celtic History would have no idea what to do when thrown into R&D.  The library has that room above it as well, so it could work as a classroom in a pinch.  This is another title I really don't want to get rid of, as this is probably my favorite one.

**Comment by Hubblenaut** [comment]
With your thorough explanation I'm a lot more inclined toward some of these titles, namely the Research Supervisor, Commander, Courier and Sanitation Technician. Though for the first two, it might be a nicer solution to completely replace our current titles with these.

For Professor, yes, it has roleplay potential and many players already do have characters that are Professors. I just don't dig how being a Professor is a job occupation in itself outside of the research department on a colony station.
And if an occupation 'Professor' would ever be a thing, I can already see the lots of people asking 'Professor for what?' each time. In the very least, it could be made a completely separate job, so they could choose the subject they are professor for at the start of a shift, similar to how the chaplain chooses a religion.

**Comment by redstryker** [comment]
I ho

**Comment by redstryker** [comment]
(Accidentally closed that because I'm on my phone and I have large thumbs.)

**Comment by redstryker** [comment]
I honestly don't agree with you, Hubble.  Research has always been centered around the Sciences.  Making 'Professor' connected to research would make no sense.  I do understand your sentiment with making it a new job entirely, I just don't agree with it.  I think that Professor would fit just fine in the Librarian slot.

**Comment by serenemelody** [comment]
I'd support changing the QM alt title to Requisitions Officer.

**Comment by redstryker** [comment]
Perhaps, Serena, that sounds better.  I'll think about it.

**Comment by SkowronX** [comment]
Wheres my Master at Arms title for Warden.

**Comment by redstryker** [comment]
Removed controversial titles.

**Comment by Anewbe** [comment]
Merging as per High Command

**Pull request merged**
