### PR TITLE
Bar remap

### PR DESCRIPTION
**Pull request by Albens**
Updated.
Current Picture:
http://i.imgur.com/OB7smUI.png
Topic:
http://ss13polaris.com/forums/viewtopic.php?f=17&t=557

### CODE REVIEW

**Comment by Minijar** [comment]
I like it!

**Comment by Mark9013100** [comment]
Looks nice, but might be a good idea to put this up to a vote on the forums.

**Comment by PsiOmegaDelta** [comment]
Shouldn't those bar shutters be rotated 180 degrees?

**Comment by Earthcrusher** [comment]
Definitely a more efficient use of the space. I always hated how the bartender could only see half the bar.

**Comment by comma** [comment]
That's pretty awesome, bathroom is a good idea.

**Comment by Datraen** [comment]
Like Psi said, the shutters are backwards.

**Comment by Lorwp** [comment]
Does sorta bother me that cba6f10 doesn't have any author infomation included, though this could probably be fixed with something such as [this](https://help.github.com/articles/changing-author-info/)

**Comment by GinjaNinja32** [comment]
```shell
git config --global user.name "Your Name Or Username Here"
git config --global user.email "Your GitHub Email Here"
# check out the branch here, then:
git commit --amend --reset-author
```

**Pull request closed without merging**
