### PR TITLE
DNA injectors cause cloneloss.

### PR DESCRIPTION
**Pull request by Belsima**
Port from https://github.com/VOREStation/VOREStation/pull/921. Being hulk's gotta have some kinda downside, eh?

### CODE REVIEW

**Comment by Belsima** [comment]
@Anewbe May want to bring up to Higher Powers, if this matters.

**Comment by Arokha** [comment]
This was mostly to prevent brute-forcing genetics because people were building the old genetics equipment, I didn't want to REMOVE that from the game, but also didn't want to make a secret genetics lab always able to make hulks

**Comment by Belsima** [comment]
Yeah, I worry the same, so I liked the adjustment.

**Comment by Atermonera** [comment]
If the user doesn't have any cloneloss, it'll apply 2.
After that it'll double the existing cloneloss.
Intended?

**Comment by Belsima** [comment]
@Atermonera Yes, intended behavior. Meant to make getting all mutations stack Badly.

**Pull request merged**
