### PR TITLE
Loadout stuff, but done right!

### LINKED ISSUE #3542: Scientist can't start with prescription mesons
See title, scientists, especially anomalist or xenoarch would benefit from permission to use that in custom loadout

### PR DESCRIPTION
**Pull request by mistyLuminescence**
- Ties are now /accessory/tie, not /accessory. Same with striped scarves (/accessory/scarf/x).
- Fixed a typo in railing.dm
- Armbands, waistcoats, holsters, jackets, ties and scarves now come in selection menus (declutters loadout).
- Renamed webbing and drop pouches to black/brown/white in the loadout, since it's not job-restricted to specific departments.
- Psychiatrists can now take medical boots, winter coat, EMT labcoat, and the medical poncho, like the rest of medical. Still can't have MedHUDs from the loadout, though.
- Scientists and Research Directors can now take mesons.
- Scrubs are now no longer limited to medical staff; pregnant Tajaran can take them too.
- Added the bathrobe, bunny slippers, kitty ears to the loadout.
- Only Detectives can take forensic gloves - this has been clarified.
- Cowboy hats are now worth the same as every other hat.
- Prescription Command sunglasses are now worth the same as regular Command sunglasses.

Fixes #3542 by letting Scientists and RD take mesons.

### CODE REVIEW

**Comment by Belsima** [comment]
Loadout stuff, but done right!

`5 commits and not passing Travis`

**Comment by mistyLuminescence** [comment]
shhhhh it might work this time

**Comment by Atermonera** [comment]
!! FAILURE !! [LOADOUT: Entries shall have name, cost, and path definitions]: One or more /datum/gear definitions had invalid display names, costs, or path definitions

**Comment by mistyLuminescence** [comment]
okay I think I fixed it this time but tortoisegit doesn't like me

**Comment by mistyLuminescence** [comment]
_there we go_

**Comment by SubberTheFabulous** [comment]
>kitty ears

**Comment by mistyLuminescence** [comment]
why _wouldn't_ you take kitty ears

**Comment by Anewbe** [comment]
You've tested all of this, yes?

**Comment by mistyLuminescence** [comment]
All tested, and it actually works this time.

**Pull request merged**
