### PR TITLE
Fixes missing sprites on forensic scanner

### PR DESCRIPTION
**Pull request by Heroman3003**
Title

### CODE REVIEW

**Comment by Atermonera** [comment]
Icondiff seems wonky, can you post the changes yourself? icondiff

**Comment by Heroman3003** [comment]
I didn't actually change anything in icon file. Only renamed them. forensic2 became forensic1, forensic1 became forensic and forensic0 remained unchanged. Originally, forensic2 being scanner with green flash, forensic0 being with red flash and forensic1 being its idle state.

**Comment by Atermonera** [comment]
And now it's mysteriously vanished altogether...

**Comment by Heroman3003** [comment]
Something seems to be up with bot itself

**Pull request merged**
