### PR TITLE
Makes the engine room slightly more consistent.

### PR DESCRIPTION
**Pull request by Belsima**
Before: image

After: image

Specifically referring to the blast doors (such as the one on the bottom) that don't line up with the rest in the room, and the lack of decals for the radiator stuff unlike the other gas.

### CODE REVIEW

**Comment by Anewbe** [comment]
I can't for the life of me tell what changed in those pictures.

**Comment by Belsima** [comment]
The Phoron/Carbon have a yellow decal under them and the port they're made to go with; the blast door for the vent is rotated to be inline with the rest in the room.

**Comment by Anewbe** [comment]
I'd appreciate if you left the blast door the way it was.

**Comment by Belsima** [comment]
Would you rather I rotated the rest, then? It bothers me how it's not consistent with literally every other blast door in the room. e.g. the 5 north of it.

**Comment by Anewbe** [comment]
I would rather you leave the blast doors as they are.

**Comment by Belsima** [comment]
I'll adjust the PR as soon as I hear that from staff besides you.

**Comment by Hubblenaut** [comment]
Why does it have to open vertically instead of horizontally? Why is it even grounds for discussion?

**Comment by Belsima** [comment]
Vent returned to it's vertical state. Rotated other doors e.g. waste handling and engi lockdown to line up with eachother instead.

**Comment by Anewbe** [comment]
Would you mind updating the images?

**Comment by Belsima** [comment]
I will either later today or tomorrow. Can't right this moment.

**Comment by Anewbe** [comment]
Thank you very much.

**Comment by Anewbe** [comment]
Closing at the request of the author.

**Pull request closed without merging**
