### PR TITLE
Shortens cryosleep timer

### PR DESCRIPTION
**Pull request by Anewbe**
Drops cryosleep timer to around 15, also affects robot storage timer

### CODE REVIEW

**Comment by Yoshax** [comment]
Isn't 15 minutes basically no change? Elevator is still immensely quicker, and more appealing. It just takes up a job slot for longer for no good reason.

**Comment by Anewbe** [comment]
Admins said drop it to 15, I dropped it to 15.

**Comment by EmperorJon** [comment]
I'd rather we just got rid of cryo. It doesn't really serve any purpose?

**Comment by Yoshax** [comment]
It's nice fluffwise for some people.

**Comment by Datraen** [comment]
It's also a nice escape pod, if you're in the area.

**Comment by EmperorJon** [comment]
1. I don't really see why? If you really want to make it so you're cryogenically frozen between shifts or something, just say that happens on the lower level (which makes more sense, honestly).

2. And then put an escape pod in its place. :P

**Comment by Kelenius** [comment]
I think this is better taken to forums.

**Comment by Datraen** [comment]
So, nothing wrong with this, changing the cryo pod shuttle's outside of the scope of this PR. Merging.

**Pull request merged**
