### PR TITLE
Shapeshifter color selection knows default/current

### PR DESCRIPTION
**Pull request by Arokha**
QOL for shapeshifters with color choice

### CODE REVIEW

**Comment by Arokha** [comment]
Apparently this usage of num2text was added in 513.1514, which is 000.0001 versions higher than current Travis. What's your server run?

**Comment by Atermonera** [comment]
We're on 1513 as well. What're you folks running on?

**Comment by Arokha** [comment]
Ye, we moved to 513.1520. Seems to work fine.

**Comment by Shadow-Quill** [comment]
Stale PR @Arokha

**Pull request closed without merging**
