### PR TITLE
Lowers natural wound healing rate

### PR DESCRIPTION
**Pull request by Yoshax**
After discussing it with @Woodratt  in relation to wounds over 50 damage not healing, he said he wanted the natural healing rate to be lower.

### CODE REVIEW

**Comment by Woodratt** [comment]
>_>

+1

**Comment by mwerezak** [comment]
You know, there's a `config.organ_regeneration_multiplier` that handles this. On Bay's main server we have it set to 0.25.

**Comment by Yoshax** [comment]
Huh, wasn't aware. Probably a nicer way to do it.

**Comment by EmperorJon** [comment]
Being handled in the config.

**Pull request closed without merging**
