### PR TITLE
Move planets to SSplanets

### PR DESCRIPTION
**Pull request by Arokha**
Fuggit! Just make this into a subsystem. It probably works.

If it doesn't, what's the worst that will happen? ;v

### CODE REVIEW

**Comment by Anewbe** [comment]
Notice any lag with this?

**Comment by Arokha** [comment]
Nop, SSplanets since it's now an SMC subsystem shows the % tick used by the planets subsystem and it's generally averaging to like 1%.

**Comment by Anewbe** [comment]
This is sort of on hold, need to have some background discussion about the possible IC side-effects, and how we'll adjust for them.

While this is happening, could you make a quick changelog that says something like "Weather processes faster now." so people get at least some warning about it?

**Comment by Anewbe** [comment]
Staff seems to be generally in favor, but we'll need to change a few weather things before it gets implemented. If you care to help us out on that front, I can list them, otherwise it will take some small amount of time.

**Comment by Anewbe** [comment]
Waiting on #5350, sorry for the delay.

**Comment by Anewbe** [comment]
And I can't actually test my thing properly without this, so merging!

**Pull request merged**
