### PR TITLE
Dead SifGuard patrol PoI

### PR DESCRIPTION
**Pull request by Cerebulon**
Very small PoI but I get the impression more never hurts
https://i.gyazo.com/5bbaade6ff99f8557343e18ebc73425c.png
(Footprints and baldie aside)

### CODE REVIEW

**Comment by Anewbe** [comment]
Is the chainsaw part of it?

**Comment by Cerebulon** [comment]
Yes, should that be changed? I hear there's some issues with those right now.

**Comment by Anewbe** [comment]
Yeah, just remove that, if you don't mind.

**Comment by Neerti** [comment]
Note that #4557 will probably mess with this.

**Comment by Cerebulon** [comment]
Alright, I'll hold onto it and make changes once that PR is put through.

**Comment by Magneld** [comment]
Picture looks like the bullets are unfired, intended or did you mean to have those be spent shellcasings?

**Comment by Cerebulon** [comment]
Closing this since it's a huge pain to fix version conflicts with the new file structure apparently, and putting it up fresh.

**Pull request closed without merging**
