### PR TITLE
Allow Simple Animals to have armor in a normal sensible way

### PR DESCRIPTION
**Pull request by Arokha**
Replaces their 'resistances' list with a normal 'armor' list. Works exactly the same as armor does on every other item in the game, which is why it's a Good Idea:tm:

### CODE REVIEW

**Comment by Anewbe** [comment]
Any chance I can bug you to implement the armor soak bit on them, too?

**Comment by Arokha** [comment]
I dunno what armor soak is. Explain?

They do have a var that is a flat damage reduction var, if that's what you want. I think it's called `resistance`

**Comment by Anewbe** [comment]
Soak is an armor mechanic that is checked just before normal armor, that reduces the incoming damage by a flat amount, capped at I think 80% and affected by armor penetration.

I'm not sure `resistance` actually works, because I've never been able to get it to function in testing, though I might be doing it wrong.

**Comment by Arokha** [comment]
To be honest, it may not have worked before. I don't know. It should work now, as it's passed whenever we're passing the armor check thing and the armor check thing should take care of it.

You can see it being passed as the `blocked` parameter when we're doing armor checks, so it should function as a flat soak.

**Comment by Anewbe** [comment]
Works for me.

**Pull request merged**
