### PR TITLE
Fixes ventcrawling for spiderbots/implants/etc.

### PR DESCRIPTION
**Pull request by LorenLuke**

### CODE REVIEW

**Comment by LorenLuke** [comment]
Note: HAS been tested with spiderbots, implants, and borers.

I assume the other things work as well.

**Comment by Anewbe** [comment]
I feel like it'd be more sensible to make this into procs for the correct subtype of mob, rather than having the proc check where you have it doing so.

**Comment by LorenLuke** [comment]
@Anewbe It used to be that way, and I aggregated this just to have it be a master proc rather than have a bunch of 
return ..() 
after each one of them, plus it made it easier for me to re-order the events and not necessarily have it try to sort itself.

Additionally, ventcrawling happens so little, there's not massive amounts of overhead in doing this this way.

**Comment by LorenLuke** [comment]
@Anewbe requesting review.

**Comment by Anewbe** [comment]
Did you test this?

**Comment by LorenLuke** [comment]
@Anewbe I have.

**Pull request merged**
