### PR TITLE
Removes melee damage from snacks.

### PR DESCRIPTION
**Pull request by Verkister**
Not gonna ask why it was there but someone nearly lit the place on fire after jokingly mashing their sandwich at a borg downstream lmao.

### CODE REVIEW

**Comment by PrismaticGynoid** [comment]
It's there to allow stinging plants, such as nettles, to be used as a weapon. You couldn't use them as such otherwise.

**Comment by Verkister** [comment]
Did anyone ever consider that maybe they could define that var for those specific subtypes rather than _everyting_?

**Comment by Atermonera** [comment]
They can't, because hydroponics procedurally generates the fruit

**Comment by Verkister** [comment]
I think my fix here would make the part that assigns the stinginess to assign the force var as well while at it or something like that (gonna make it so if it doesn't already). Anyway they could have just as well assigned the force to the grown produce subtype in order to get it even a little bit closer to the stinging gimmick rather than just slap it to the _root of all snacks_.

**Comment by Atermonera** [comment]
The real solution was always to rewrite hydroponics, but this'll do

**Pull request merged**
