### PR TITLE
Allow AI to use custom holograms

### PR DESCRIPTION
**Pull request by Arokha**
Adds a third hologram button choice, allowing the AI player to load their current character slot as the hologram so they can custom tailor their AI character to look like whatever. Also fixes it so that when using existing crew as a hologram you can face all four directions and the picture is not based on their records and thus probably terribly inaccurate and old. To compensate, you can only generate a hologram from crew you can currently track, so presumably you take a few pictures with your cameras or something.

I think the blue looks ugly with this, if you want my advice, comment out https://github.com/PolarisSS13/Polaris/blob/master/code/_helpers/icons.dm#L814 (change not included in PR). We have a whole holodeck that can project solid objects. I'm gonna say color holograms is not stretching the lore. :P Holograms are obviously holograms what with the transparency and scanlines. The ones in AI.dmi are "pre-blue" already so those would still be blue.

### CODE REVIEW

**Comment by Anewbe** [comment]
Apologies in advance, there's another PR up that's been under review for a while that touches the same files, so if that one doesn't have issues it'll probably cause conflicts on this one. Brief look doesn't seem to show anything glaring.

**Comment by Arokha** [comment]
@Anewbe Which PR?

**Comment by Anewbe** [comment]
https://github.com/PolarisSS13/Polaris/pull/3086

**Comment by Arokha** [comment]
@Anewbe I have rights on his repo. Merge whichever first and I can fix the conflicts on either.

**Comment by Anewbe** [comment]
Fabulous.

**Pull request merged**
