### PR TITLE
Changes 'undislocate' to 'relocate'

### PR DESCRIPTION
**Pull request by Cameron653**
Because undislocate sounds clunky and awful, and who in their right minds calls relocating a limb undislocating a limb.
[A video of relocating a limb.](https://www.youtube.com/watch?v=FElcYZ3YT8o)

### CODE REVIEW

**Comment by Belsima** [comment]
I can't find a use of 'relocate', but I can find a use of 'undislocate'. Can you give a source for the word 'relocate' being used in this context?

**Comment by Arokha** [comment]
> Bikeshed label

Not saying whether or not I agree with the word change, but are you discouraging PRs that don't fix some major issue now, or am I misinterpreting that?

**Comment by Atermonera** [comment]
Whether it's undislocate or relocate, it'll still be pretty clear that this is the step to take to make the limb not-dislocated, so any argument over it is very minor

**Comment by Belsima** [comment]
Oh, yeah. It's minor, but I need to procrastinate and avoid doing my french homework somehow.

**Comment by Cameron653** [comment]
Well, I've always heard popping a shoulder/arm/leg back into place as 'relocating' instead of 'undislocating'

Some examples of it being used:
https://www.wikihow.com/Fix-a-Dislocated-Shoulder (Created by Dr. Jones Demuro, a surgeon with 21 years of practice. https://health.usnews.com/doctors/jonas-demuro-475466 "Moving the shoulder is not possible until it is relocated.")

https://medlineplus.gov/ency/patientinstructions/000524.htm (Under What to Expect. 
"In the emergency room, your arm was placed back (**relocated** or reduced) into your shoulder socket."))

https://www.medicinenet.com/dislocated_shoulder/article.htm (Under "How do physicians diagnose dislocated shoulders?" "...prepare for a potential anesthetic administration to help relocate, or reduce, the shoulder dislocation."

There's a lot more examples I can get, but this should be sufficient. Not once have I heard anyone say undislocate.

**Comment by Belsima** [comment]
Thank you. Must have just had issues on my end, since I could only find the less common term.

**Comment by Cerebulon** [comment]
According to my friend who knows medical stuff, the correct medical term is "Reduce".
On the other hand, both "reduce" and "relocate" both have alternate meanings and might be confusing in a game context.

**Comment by Belsima** [comment]
"Reduce" sounds best to me in that case if we're gonna change it? Either use the proper term or leave it as the least vague one I guess

**Comment by Cameron653** [comment]
Mm, I can see about changing it to reduce, as that is technically the most proper/used out of the bunch.

**Comment by Anewbe** [comment]
I'd prefer either leaving it be or making it Relocate. Reduce is very unclear to people who aren't familiar with medical terminology.

**Comment by Cameron653** [comment]
There we go, changed it back to relocate.

**Pull request merged**
