### PR TITLE
Alien Autopsy (Help Wanted)

### PR DESCRIPTION
**Pull request by SpadesNeil**
So, many mobs in the game, when killed, will now have internal organs which can be harvest for **SCIENCE**™.

To harvest a creature's organs, kill it, and use a scalpel (or bone saw for exoskeleton creatures) to extract an organ. The organs have fun little fluff blurbs on their descriptions, telling you how the creature works. In the future there will be tech levels attached to each organ maybe, or some unique items can only be found in the organs of dead aliens.

Still got shit to do.

- [ ] Make it possible to read a list that is part of a list-of-lists. I don't know how to do this.
- [ ] Check if mob is on an operating table--or regular table is fine too. Don't know how to do this.
- [x] Add custom organs to any mobs that should have custom organs.
- [x] Prevent conflicts with slime mob mechanics.

**Needs testing.**

Resolves https://github.com/PolarisSS13/Polaris/issues/3569

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Actually closing this because it's shit. I should be making it with a list of lists.

**Comment by SpadesNeil** [comment]
Completely rewrote this. It's much less shitty now.

**Comment by Belsima** [comment]
I think the ÿ� thing shows up with Zippo lighters in some places too. Are you using /improper or other tags?

**Comment by SpadesNeil** [comment]
ignore that, that's just the fucky way that it copypasted over to Github

The problem lies in the fact I don't have lists inside of lists.

**Comment by Belsima** [comment]
Ah, alright. I was hoping I knew at least part of some issue somewhere.

**Comment by Anewbe** [comment]
@SpadesNeil Any intention to finish this?

**Comment by SpadesNeil** [comment]
Lists inside of lists aren't working the way I thought they would work. Classic case of I know how to get the solution, but I don't know the format. Otherwise this would be done by now...

If nobody has any ideas on how to correctly do this, I'm going to close it.

**Comment by Anewbe** [comment]
Closing this, if you come up with a fix let me know.

**Comment by SpadesNeil** [comment]
Shall do. <_> I am sad I couldn't figure out wtf I did wrong.

Well, no, I know what I did wrong, I just don't know how to do it _right_.

**Pull request closed without merging**
