### PR TITLE
Sprites for drying racks, bees for hydroponics

### PR DESCRIPTION
**Pull request by Kelenius**
Adds distinct sprites for drying racks, taken from /tg/.
Remaps hydroponics a bit and adds a crate with beekeeping necessities.
Fixes a typo in the smoker.
http://imgur.com/eaDmbPE
http://imgur.com/wywJ9j3

### CODE REVIEW

**Comment by Minijar** [comment]
Bees work?? I thought they were removed eons ago.

**Comment by Kelenius** [comment]
https://github.com/Baystation12/Baystation12/pull/10033

**Comment by Zuhayr** [comment]
:+1:

**Comment by Kelenius** [comment]
Resolved.

**Pull request merged**
