### PR TITLE
Updates all medical sprites to Bluebay

### PR DESCRIPTION
**Pull request by Burrito-Justice**
I'm sure everyone's tired of seeing the inconsistent color scheme of medbay; blue floor tiles, green medical cross, red lockers. This PR updates pretty much everything (sans syndicate stuff) that has a medical cross to be blue instead of green.
thing

### CODE REVIEW

**Comment by Cyantime** [comment]
Not redbay, 0/10

**Comment by Wickedtemp** [comment]
Would support. I enjoy the consistency.

**Comment by Atermonera** [comment]
We can't do a consistent redbay because we can't use the red cross because Geneva Conventions actually actively encodes that as a warcrime

**Comment by Cyantime** [comment]
Better to be a literal war criminal than to suffer the travesty that is greenbay or bluebay.

**Comment by mistyLuminescence** [comment]
👌 love it

**Comment by Atermonera** [comment]
[Ok, maybe not an actual warcrime, but still technically a criminal offense that simply isn't enforced](https://en.m.wikipedia.org/wiki/Emblems_of_the_International_Red_Cross_and_Red_Crescent_Movement)

Just go to use of the emblems

**Comment by Arokha** [comment]
https://www.law.cornell.edu/uscode/text/18/706

[b i k e s h e d   i n t e n s i f i e s]

We're not using it to deceive, and as long as it's not on a white background we could use a red cross. So SOME of the uses, probably. Also the server is in Germany so who knows what the law is there, anyway.

**Comment by mistyLuminescence** [comment]
honestly blue is prettier anyway

**Comment by Burrito-Justice** [comment]
Whoops, one sec, forgot the Odysseus

**Comment by Burrito-Justice** [comment]
Currently the Vey-Med voidsuit still uses the dual green helmet lights. I was about to adjust the hue to be blue, but I've been informed that syndicate voidsuits use the same helmet light sprites, and that obviously wouldn't fit too well. I was going to create a new version of the lights in both light_overlays.dmi files that were blue while still preserving the green ones used for the syndicate voidsuits, and going into spacesuits/void/station.dm and editing the Vey-Med voidsuit to use the new blue lights. I'd like to know if I should go ahead and do that or just toss the idea out.

**Comment by Burrito-Justice** [comment]
heck it doing it anyway

**Comment by Burrito-Justice** [comment]
This is what I'll be committing, blue helmet lights and all, plus a minor description change.
blue vm suit

**Comment by Belsima** [comment]
Just as a note, staff have stated we intend to respect US law as well, hence the change of red crosses to blue on medkits and such- this is to make everything else finally consistent.

**Comment by Burrito-Justice** [comment]
Gee no one said anything about a poll regarding the switch. I'll get some more screenshots together.

**Comment by Burrito-Justice** [comment]
Here's some more sprites and stuff. 
ba66ecc7aad934efdfabb5bcc0ba4e1d

**Comment by Anewbe** [comment]
Poll's leaning towards Blue, and if someone wants to go back and change this, they can. Is this PR feature-complete?

**Comment by Burrito-Justice** [comment]
I've done what I can to change all of the medical sprites that I've seen and dug through to blue, so I'd say yes, but I haven't really touched on description changes all that much. I can accomplish that in another PR.

**Comment by Anewbe** [comment]
Works for me.

**Pull request merged**
