### PR TITLE
Supply pack QoL

### PR DESCRIPTION
**Pull request by Datraen**
Splits the supply packs into their own categories to ease adding supply packs in the future and potentially preventing conflicts if two separate categories have open pull requests.

Also adds subtyping to the supply packs, for less copy-paste.

Answers #1823

Yaaay.

### CODE REVIEW

**Comment by SpadesNeil** [comment]
:+1:

**Comment by Datraen** [comment]
This is likely on hold due to #1883.

**Comment by SpadesNeil** [comment]
Yup. Conflicts because of that.

**Comment by Datraen** [comment]
Closing to start from another branch. Will link PRs.

**Pull request closed without merging**
