### PR TITLE
Add DCS & Runechat

### PR DESCRIPTION
**Pull request by ShadowLarkens**
DCS: https://github.com/ParadiseSS13/Paradise/pull/8901
DCS Improvements: https://github.com/ParadiseSS13/Paradise/pull/13594

Runechat PR: https://github.com/ParadiseSS13/Paradise/pull/14141

Downstream: https://github.com/VOREStation/VOREStation/pull/9111

Added Runechat from /tg/, which shows speech messages from atoms and players alike over their head.
Additionally, added the whole datum component system from /tg/ as a side note to go along with it. It's just used for runechat to clean up messages when it's source gets deleted, for now, but you can [see all the uses that are possible here.](https://github.com/tgstation/tgstation/tree/master/code/datums/components)

There's a preference to turn it off here 

# Screenshots

Runechat messages have a 110 character limit. After that, it gets replaced with an ellipsis. That looks like this:

### CODE REVIEW

**Comment by ShadowLarkens** [comment]
DNM For now, I realize there's quite a bit missing from Paradise's PR

**Comment by ShadowLarkens** [comment]
So as it turns out, the missing stuff from Paradise's PR is intentional. At 150 players, /tg/'s full Runechat absolutely destroyed their server. This is an optimized version. I'll keep it that way, but I did go ahead and readd showing emotes and the preference to turn that on and off accordingly. Additionally, VV now allows you to arbitrarily add components and elements. Useful for debugging in the future.

No longer DNM, this is ready.

**Comment by lolman360** [comment]
>dcs

amazing work

**Comment by ShadowLarkens** [comment]
I'm too concerned about the performance issues runechat has to have this for now. I'll open a new PR with just DCS.

**Pull request closed without merging**
