### PR TITLE
Ports headpats and handshakes from VORE.

### PR DESCRIPTION
**Pull request by Belsima**
https://github.com/VOREStation/VOREStation/pull/2076

At their recommendation.

### CODE REVIEW

**Comment by Anewbe** [comment]
Mmm... Maybe.

**Comment by Belsima** [comment]
Seems innocent enough to me, personally. Don't see any harm in adding it. ~~I just wanna pat Taj on the head until they get upset.~~

**Comment by Cyantime** [comment]
Be sure to fix it so you can't pat someone who has no head or shake hands with a handless person.

**Comment by Belsima** [comment]
Closing this, found better alternative way to do it.

**Pull request closed without merging**
