### PR TITLE
Display monitors and manufacturer fixes.

### PR DESCRIPTION
**Pull request by Zuhayr**
- Readds IPC head icons as a loadout item for FBPs.
- Allows heads to be customised independently of the body.
- Fixes issues with robotize() ordering overriding prefs.

### CODE REVIEW

**Comment by Spacemanspark** [comment]
:+1:

**Comment by Earthcrusher** [comment]
Hooray! Bee having steel legs was bugging me.

**Comment by Zuhayr** [comment]
@EmperorJon 
@Datraen 

Can someone please look this over?

**Comment by Datraen** [comment]
Tested, works, merging.

**Pull request merged**
