### PR TITLE
Adds Stimm, a homemade hyperzine; makes hyperzine toxic

### PR DESCRIPTION
**Pull request by Anewbe**
Stimm is 1 part sugar, 1 part fuel, with 5 fuel as a catalyst. Doesn't last as long as hyperzine, and it hurts, but it should be much easier to make.
Makes hyperzine lightly toxic

### CODE REVIEW

**Comment by Screemonster** [comment]
Making hyper slightly toxic is a neat way to discourage lightning chemist roadrunner moments, but anyone with access to hyperzine (outside of zoom pills) can get dylov-

oh. OH. Just noticed the path change under /toxin. Outstanding.

**Comment by Yoshax** [comment]
It doesn't really make it slightly toxic though, it's more like pretty highly toxic. But maybe that's just me. I believe this will make it a lot less used, not that it's used much currently.

**Comment by Screemonster** [comment]
Eh, a full syringe of it will do 5%-ish of an absolute max of 45, so... 2.25 points of organ damage? Not really much more dangerous than getting wasted at the bar and if you can make hyper, you can pop a peridaxon pill once you're done with it.

I'm curious as to why it's organ damage and not straight toxloss though.

**Comment by Yoshax** [comment]
It's not, it's both already. The ..() parent call calls the base toxin affect_blood which does `M.adjustToxLoss(strength * removed)`

Therefore each tick, or every second, I forget how oftten affect_blood happens, it will do a small amount of building toxloss, along with the organ damage chance. take_organ_damage() isn't internal damage anyway, it's external. It picks a random external organ and does `3 * removed` damage. 

It does damage, yes, and is the wrong choice to resolve a non-existent problem.

**Comment by Anewbe** [comment]
It's 2 tox per unit, (which isn't a big deal because it's 30 TOX for a full syringe, and 30 TOX won't kill you) and a somewhat low chance to take minor brute damage. Doesn't cause organ damage unless you somehow pass 60 TOX total.

**Comment by Yoshax** [comment]
I really fail to see the need for it, nor the why. Making something that is rarely used even worse isn't productive to good balance or gameplay. 

Why is this necessary?

**Comment by Screemonster** [comment]
Because #2691 - there's been a small rash of infrequent but _incredibly_ annoying players essentially using it to piss off security and yakketysax away at turbo sanic speeds (mostly along the lines of "hey I've got contraband whaddaya gonna do 'bout it copper?" _nyoooom_), then when we tell them to cut that shit out they scream at us about banning them for using a feature of the game.

**Comment by Yoshax** [comment]
And I'll say the same thing I said elsewhere, if people are being annoying and abusing something to just be annoying, then the staff should do their job and deal with the player, instead of spoiling the feature for everyone else. If they're screaming at you, then slap them around and get some respect out of them.

**Comment by Anewbe** [comment]
We've not had a problem with Hyperzine ourselves, but it's currently very, very strong. As in, it doesn't really have any downsides.

**Comment by Yoshax** [comment]
I'm just not sure I see the need to resolve a problem that does not the exist. The preemptive measures make something already unused, and not entirely appealing even less appealing.

That, or have a stable version that exists also. With all the chemicals we have, with no down sides, It's not very believable that we can produce a chemical to cure all injuries, or brain damage, or anything of the sort but not a stimulant of the same level. I'd either like a stable version to exist also, or for the side-effects to only exist for the ghetto version. But that's just my opinion.

**Comment by Anewbe** [comment]
Removed the brute damage from hyperzine, but it's still too easy to get hyperzine for the zero downsides it has.
Made the damage chance from stimm bigger, and it gives its own message now.
Upped the tox damage from drinking fuel, because it was waaaay too low and relates to this PR as an ingredient.

**Comment by Anewbe** [comment]
Staff polled, results positive.

**Comment by Magneld** [comment]
Damnit why did I go to bed before checking this D:

**Pull request merged**
