### PR TITLE
Adds Chief of Security alt title for HoS

### PR DESCRIPTION
**Pull request by Anewbe**

### CODE REVIEW

**Comment by Belsima** [comment]
Why tho?

**Comment by Neerti** [comment]
A chieftain is needed to manage Red Tribe.

**Comment by Belsima** [comment]
I feel like Alt Titles should have notable differences, like Medical Doctor VS Virologist, personally. This is just another wording for 'Head of Security'.

**Comment by SilverTalismen** [comment]
Well chief of Security seems fitting enough, better than Commander atleast.

**Comment by Belsima** [comment]
Certainly, but what's the difference between it and HoS?

**Pull request merged**
