### PR TITLE
Adds Vox Sprites from Paradise - Minor Renames and Fixes

### PR DESCRIPTION
**Pull request by HawkerTheGreat**
**Step 1 for -
#3101** 

- Imports Paradise sprites that we don't currently have.
- Renames a moderate amount (not all) of incorrect state names to match our codebase.
- Rename Old files, Insert updated versions.
- Zero sprite changes from originals, Just imported.
- Adds back.dmi - its not used from what I know in this codebase but if we make changes, it will fit the Vox sprites a lot better. So I'll keep them here.

I've got a couple of zips if you'd like to look over them, the first being the files I uploaded - which contain our sprites first then added Paradise sprites. I've tried my best not to make copies and gone through to delete any copies I have found from my importing.

I've previously tested these and plenty of them work right out of the box, there is only a few that really need their state names changed. There is also a lot of unused files in here, but they may or may not be wanted in later ports.

[VoxUpdt Change.zip](https://github.com/PolarisSS13/Polaris/files/853379/VoxUpdt.Change.zip)
[Vox ParadiseRiP.zip](https://github.com/PolarisSS13/Polaris/files/853380/Vox.ParadiseRiP.zip)

### CODE REVIEW

**Comment by Anewbe** [comment]
Have you checked if these sprite names

**Comment by HawkerTheGreat** [comment]
I've checked quite a few of the sprites, not all of them work with the current states, but I'll have to change them - The Virgo code base uses a Vox crew white list, which is why I'd like to get this pushed. As they cannot use most clothing on how it stands.

- While I am planning on going through a second time, I thought I'd throw in the base sprites for now so I can go back and clean up some of the names.
- Quite a few work right off the bat and match up well - others just not coded in to begin with, which I'll either remove or can be used for other stuff (Small files so I thought it best just to add whatever did not overlap.)
- The Space suits, except for the soft suit will not work until they are added to map or suit converter.

Either way, I didn't change anything from the current port files except for importing the paradise files. I can scrap this and throw in bay instead, but I'm sure they lack most of the sprites just like most servers who focus solely on Vox as raiders.

- The only change made to the current port states is the old merc suit which I renamed both to old_vox_syndi -.
- As it stands though, quite a few of these states do not work, but as we speak I look through the code to figure out which states are not in use.

Thanks!,
HTG

**Comment by Anewbe** [comment]
If you're going to add new sprites, make sure they work.

Bay has Vox crew, but they way they're written lorewise made them incredibly disruptive, and the Polaris Staff decided not to keep them way back wen.

**Comment by nachomeep** [comment]
The mercenary hardsuits and mercenary voidsuits are seperate things, by the way. I see old_vox_syndi, but I don't see any replacement.

**Comment by HawkerTheGreat** [comment]
Okay, Took some time to review to ensure I knew what was not going to work. From what I've found, most of it works... I'll state what does not so its a bit more straight forward and I know for future reference what I'm looking to re-name.

- All wintercoats, their state names do not merge with the code base.
- All suit coats, not including the normal job coats and armors or overcoats, are all referenced under a different name.
- Hoods work like helms on paradise, they're added over the head rather than attached to the suit sprite.
- Sadly, the Vox rigsuits - other than the ones already in there, because I have not changed them at all, will not work because paradise considers these hardsuits and we consider ours rigs/softsuits/armor.

So, there is a few that have incorrect state names and don't work, but they don't directly conflict and I'll be able to name their states when I can. Since I started with what does not work, I'll also add what works.

- Uniforms, I've made no change to them and either way, we're base to base with paradise except for some silly props which I don't see a need to add in quite yet because they're not even coded.
- Softsuits/Overcoats/Department Suit items/Security Armour all work just fine with their default state names - there is no need to change them as they work perfectly and fit in with the style. (I assume most of these are directly from baycode, too.)
- Basic head items work just fine... But, most aren't coded in so they're useless.
- Default Mask states match up too, but... I'm not sure if we have the ability to move them all out of the way, so some of those states can be saved for later.
- Shoes - there is not many, but thank god! - All but the rigsuit boots match up.

Thanks, I know the Vox players and I will appreciate this on Virgo. - As is why I plan to rename the states for the coats eventually. But I'd like at least basic items to work, which this does. >:)

**Comment by HawkerTheGreat** [comment]
@nachomeep 
These in the suits.dmi (and the helm in the head.dmi) are the red hardsuit or rig replacements... Though they're not coded in because Vox are not usually known as Nuke Squad. It will need to be added in the code... Or simply re-stated.

- hardsuit0-syndi
- hardsuit1-syndi

**Comment by Anewbe** [comment]
Let me restate this: If I know there are things getting in with this PR, I'm going to mark it as Work In Progress and not merge it until it's complete.

This game has a long and storied history of people making incomplete things, getting them pushed through, and then vanishing, so we do that as a precaution.

**Comment by nachomeep** [comment]
hardsuit-syndi is for the RIG.
The old ones were for the voidsuit.

**Comment by HawkerTheGreat** [comment]
**Step 2 for -
#3101**
So I just re-did everything, Checked Bay - we're up to date with them, then I went ahead and copied stuff one at a time to our codebase from Paracode icons. I've purposefully removed certain items because they do not match up to our existing items and ensured states for what does match up are correctly named... It will now pull the correct sprites and all of the sprites except about 4-5 unused and old/new sprites which have not made it in. They will stick in there so they can be used to either compare sprites to or fall back on in case we change our minds.

Vox do not have hardsuits, its simply not coded in besides the arkship spawned suits, but I plan on putting them back... For now, they're in my gitissue folder named VoxUpdt Change.zip which I will post because it contains what was not committed.

- Removes Paradise specific items which will never be coded in because they are simply not needed!
- Removes Vox hardsuits for a later date, so I can add sprites to turn them into proper rigs! (Besides, they're not needed at all yet, Vox survive in space regardless.)
- Removes Paradise hood sprites&winter suits - they cannot be used. They have to be re-sprited or they'll need to function differently than any other hoods, I'd rather re-sprite them.
- Ensures State names match up with Polaris code if the clothing obj is existent for the Vox race.
- Stores un-needed sprites in their own .dmi - which I wont be adding because a lot of it is not needed or built for Bay Code.
- Confirms that we indeed have every sprite for Vox uniforms.

@nachomeep Indeed, they were the old voidsuits - probably from old baycode when they used the vox in the nuclear game mode. I've changed their name from _"these have been left here in case vox"_ to a shorter tag so they're easier to glance at.

Anyways, As always, heres the dump - everything needed is pushed to my branch except for the old and later files.
[VoxUpdt Change.zip](https://github.com/PolarisSS13/Polaris/files/853529/VoxUpdt.Change.zip)
[Vox ParadiseRiP.zip](https://github.com/PolarisSS13/Polaris/files/853530/Vox.ParadiseRiP.zip)

**Comment by HawkerTheGreat** [comment]
@anewbe

Whenever your free, I threw up the update last night and I'd appreciate a re-review!, Thanks.

**Comment by Anewbe** [comment]
Back.dmi is still missing a load of our sprites, namely one of the backpack types. Additionally, what's a Voxcaster supposed to be?
The Merc RIG in head.dmi isn't going to work.
Can't tell what changed in shoes.dmi, other than the syndie magboots.
Merc RIG in suit.dmi won't work either.
Double check the sprite names for gasmasks, I'm pretty sure we don't use the same ones as Bay.

Not sure what else I missed, sprite PRs are a pain to review, but if the sprite name doesn't match what the item's looking for it won't work.

**Comment by HawkerTheGreat** [comment]
@anewbe
- We probably don't even need back.dmi as the bags have no real difference, the Vox also don't have a back.dmi to begin with
- Masks have not been changed... Only the bandanas and face wear(which work, but idk why you would want to risk your life for them) - I removed the wrestling masks and odd paradise items we don't have. 
- As I said, Merc suits do not work, nor do hardsuits, and they did not work before either. I added the sprite in case it's decided to have Vox characters on the main branch. VOREStation doesn't plan to use them I don't think... Yet. 
- Quite a few of the shoes were removed... Most of them are not coded in, so we don't need them. They also are the same and didn't need changing because someone put simple names for them. Or ripped them right off human bay items like a few of the track jackets. 

I've no idea what the Vox Caster is or don't remember. - Which dmi is it. 

Also, I've gone through and checked, ALL of them one by one, what was removed will not work and what Is in will work on the second fix.

**Comment by Anewbe** [comment]
Voxcaster is in back.dmi. As you said, probably don't need that file, they're more or less the same back size as everyone else.
RE: Merc suit; May as well make it work, so we don't have to go back in and play with it again later. Just because they're not an option now doesn't mean I want a non-functional spriteset.

**Comment by HawkerTheGreat** [comment]
Windows Update just broke my Internet... Anyhow. 

- If you'd like, I'll go ahead remove the back.dmi since it's really not needed. 
- I'll put the merc rig in since I've got most of the parts for it. It's just a state change anyways. 

I'd type up a bit better, but I'm having issues with my pc because of the update (thanks to Microsoft as per usual...). Is there anything else you want to see in the last fix for the sprites? I'll go ahead and start shortly.

**Comment by Anewbe** [comment]
As long as you didn't remove anything that was already there, yeah, looks good.

**Comment by Anewbe** [comment]
@HawkerTheGreat Are you still working on this?

**Comment by HawkerTheGreat** [comment]
@Anewbe 
Still working on it, but Ive been a little busy with real life these past few days so you'll need to give my a tad longer.

**Comment by Anewbe** [comment]
No worries.

**Comment by Anewbe** [comment]
@HawkerTheGreat if I don't get a response to this or work on this PR within the next two days I will be closing it. You may reopen it if you get back around to working on it.

**Comment by Anewbe** [comment]
No response, closing.

**Pull request closed without merging**
