### PR TITLE
New Shotguns/Rifles

### PR DESCRIPTION
**Pull request by GhostActual**
Changes and ports new rifles and adds in all new pump/cycle animations for each. Some code was modified but not to a major extent.

New Shotgun/Rifle sprites:

### CODE REVIEW

**Comment by GhostActual** [comment]
Need to merge other gun-based PRs before I fix this

**Comment by Schnayy** [comment]
Was this just waiting on stun revolvers? Merged now.

I'm a little meh on the rifle sprites in the 3rd row, the brown looks really flat. If you're willing to see about a little touch up, that'd be aces, but I'll accept them as-is if you'd rather not.

**Comment by GhostActual** [comment]
> Was this just waiting on stun revolvers? Merged now.
> 
> I'm a little meh on the rifle sprites in the 3rd row, the brown looks really flat. If you're willing to see about a little touch up, that'd be aces, but I'll accept them as-is if you'd rather not.

I'll be honest, I'd rather not, they're meant to match the colors of the OG mosin. I'll fix conflicts as soon as I figure out this other project I am working on.

**Comment by GhostActual** [comment]
Should work now

**Review by MistakeNot4892 — APPROVED** [review]
Schnayy said sprites are acceptable, code looks fine.

**Pull request merged**
