### PR TITLE
Adds communicator watch

### PR DESCRIPTION
**Pull request by BillyBangles**
It's just a normal communicator, but you can equip it in your glove slot. Useless? Maybe, but I think it's a nice little bit of fluff. It's the 26th century, you'd think we'd have smart watches by now.

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
Add it to the loadout too?

**Comment by BillyBangles** [comment]
Doin that now.

**Comment by BillyBangles** [comment]
also what did i do wrong why is it conflicting

**Comment by Belsima** [comment]
device sprites were changed in another PR

**Comment by BillyBangles** [comment]
fuck it

**Comment by Wutnold124** [comment]
same

**Comment by mistyLuminescence** [comment]
big mood

**Pull request closed without merging**
