### PR TITLE
[DNM] Component-based gun system.

### PR DESCRIPTION
**Pull request by Zuhayr**
image
image

- Guns are made of five parts (barrel, stock, chamber, grip, body) which determine the properties of the weapon.
- Parts may have a model/manufacturer which gives bonuses and fluff when all components share a model.
- Manufacturers modify the properties of guns produced by their company, increasing or decreasing accuracy, fire rate, damage, etc.

**TODO**
- [x] Get really bored of guns.
- [x] Reimplement speedloaders.
- [x] Fix the double-barrelled shotgun fire selection/fire.
- [x] Implement laser shotguns.
- [x] Move fire-mode selection to alt-click so it doesn't overlap with opening/closing the breech.
- [x] Update firemodes from the gun barrels rather than faking the caliber changes.
- [x] Reimplement firemode charge cost changes for energy weapons.
- [x] Implement stolen accessory list from CM.
- [x] Implement scopes.
- [ ] Implement launcher class.
- [ ] Fix issues with component/assembly names and strings generating oddly.
- [x] Add spellstaff components to staves that fit into guns.
- [ ] Implement all component sprites.
- [x] Implement all ammo overlay sprites.
- [ ] Implement all accessory sprites.
- [ ] Implement all model-specific sprites.
- [ ] Clean up, optimize and condense all the hacky spamcode spaghetti.
- [ ] Balance revision and testing.
- [ ] Balance revision and testing again.
- [ ] Remove the outdated guns/guncode and remap the premade composite guns into place.

### CODE REVIEW

**Comment by Zuhayr** [comment]
This is on hold for a while due to serious difficulties with existing guncode.

**Comment by OhEmGee** [comment]
> Get really bored of guns

literally impossible

**Comment by Zuhayr** [comment]
Murder toys are not really something I have an interest in. The main purpose of this PR is mechanical not thematic. :P

**Comment by comma** [comment]
Meanwhile, examples of what kind of stuff you can make with this system (once you remove sanity checks)

14.5mm pistols, 20mm SMGs.

**Comment by Spacemanspark** [comment]
This looks awesome.

**Comment by DerptheStewpidGoat** [comment]
Awesome work lad, this is the type of stuff most SS13 coders can only dream of.

**Comment by Fox-McCloud** [comment]
>The grip and stock both modify accuracy and recoil and may increase overall weapon size.

If you're aiming for accuracy to firearm mechanics, both of these have zero impact on recoil of a gun or accuracy--both of those have to do with the barrel and how gas ejection is handled; the only thing a stock is going to is how much it *feels* like it recoiled to your shoulder; the actual recoil amount will be objectively the same.

**Comment by Zuhayr** [comment]
I don't care about realism.

**Comment by Anewbe** [comment]
Is there a components what-goes-where sort of template anywhere in there?


"I don't care about realism." - Zuhayr Quote of the Century

**Comment by Zuhayr** [comment]
This PR is kinda out of date with the branch that the actual dev work is happening on (Europa) so I am  not going to put up any kind of guide or whatever till that's done.

If you mean the sprites, each of the model .dmi files shows the rough location of each of the five parts.

**Comment by Zuhayr** [comment]
This will be reopened when it's actually ready for backporting.

**Pull request closed without merging**
