### PR TITLE
Ports GinjaNinja32's drinks rewrite from Bay

### PR DESCRIPTION
**Pull request by Yoshax**
Ports Baystation12/Baystation12#13131

To-do
- [x] Find out why coffee cups turn into square glasses when they have reagents and fix it
- [x] Convert the protein shakers/port Ginja's thing for them
- [x] Listen to the tears of the damned because no more snowflake icons
- [x] Cry because coffee cups dont work

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Coffee cups won't work!? Cannot merge. Broken update. I hate it. :U PR closed.

(I'm kidding. This should be neat once it's fixed.)

**Comment by EmperorJon** [comment]
I'd much rather have different glass types and general fun like this than special snowflake icons for each drink.

**Comment by SpadesNeil** [comment]
Yea the icons changing was always immersion breaking for me.

**Comment by Hubblenaut** [comment]
Will this still work with prices for retail scanners?

**Comment by Datraen** [comment]
:+1:

**Pull request merged**
