### PR TITLE
Hardsuit gauntlets cover gloves

### PR DESCRIPTION
**Pull request by Anewbe**
Adds a new glove type called gauntlets, that cover gloves. All RIG gloves are now gauntlets.

### CODE REVIEW

**Comment by Datraen** [comment]
:+1:

**Comment by Hubblenaut** [comment]
Wearing them over insulated gloves will not actually protect the user from electricity, which is kind of counter-intuitive.

**Comment by FenodyreeAv** [comment]
Would be neat if arm guards were considered gauntlets.

**Comment by Anewbe** [comment]
That's intended Hubble, staff didn't want it to work that way for balance reasons. Plus, most if not all RIGs have a siemens of 0.2 or higher, so you're already shock resistant. The RIGs that are most likely to play around with zappy stuff either already have or will soon have insulated gauntlets anyway.
Also, if it's a bigass piece of metal and stuff that covers a whole glove, it's likely to make contact with skin, or some other part of the suit that's not necessarily insulated, so whatever.

Feno: that's the exact reason I added the base gauntlet item, rather than just adding the stuff to glove/rig/, but people had reservations about making the armguards work that way. If they feel the need to explain further, they can and probably will here. Plus the base gauntlet has some odd behaviors that the hardsuit version does not, and I cannot for the life of me figure it out right now, so it's probably best that the armguards remain as is for the time being.

**Comment by Spookerton** [comment]
:+1:

**Comment by Anewbe** [comment]
Tag this with a DNM for now please, found a critical issue in testing that wasn't happening yesterday.

**Comment by Anewbe** [comment]
Alright, only bug I have now is as follows:
Using the equip hotkey (e) with gauntlets, while not wearing gloves, causes the gauntlets to enter the back slot, instead of the hands. This does not happen with magboots.

**Comment by Anewbe** [comment]
Ready to go as is, base item doesn't actually exist outside of adminnery.

**Comment by Screemonster** [comment]
On the insulated glove thing - fun fact: people working on high-voltage lines wear conductive suits specifically so the current passes through the suit instead of the person wearing it.
This is, of course, assuming that rigsuits are actually metal and not some space-age polymer or something.

**Pull request merged**
