### PR TITLE
Surplus crates will no longer make more surplus crates

### PR DESCRIPTION
**Pull request by Anewbe**
The chance was fairly small, but it still happens, and that's not desired behavior.

### CODE REVIEW

**Comment by Yoshax** [comment]
There's a blacklisting feature. Use that.

**Comment by Anewbe** [comment]
What would that look like?

**Comment by Yoshax** [comment]
Like this should do it: https://github.com/PolarisSS13/Polaris/blob/master/code/datums/uplink/announcements.dm#L6

**Comment by Anewbe** [comment]
Thank you.

**Comment by Yoshax** [comment]
You should add it to Random Items as well, it does not inherit from single random item, and as such, surplus crates will be able to order many random items.

**Comment by Anewbe** [comment]
Excluded all Badassery items, don't see a reason to have balloons spawn in crates.

**Comment by Yoshax** [comment]
Fine assuming it obeys the blacklist, see no reason it shouldn't. In the logs from the round there were instances of blacklisted items being bought, but I believe that's from the legacy random items purchasable thing that doesn't adhere to the blacklist.

**Comment by ParadoxSpace** [comment]
I don't see why it should be removed if it's such an infinitesimally small chance.

**Comment by Anewbe** [comment]
Staff doesn't want that chance to be a thing, you already get a lot of stuff, cost-wise, from a single crate.

**Pull request merged**
