### PR TITLE
Adds more flavor to maintenance

### PR DESCRIPTION
**Pull request by Yoshax**
This adds more items and some little rooms to the eastern side of the map. Western side will be done at a later date when I have more ideas.

### CODE REVIEW

**Comment by EmperorJon** [comment]
This kind of thing will really need pictures.

**Comment by Yoshax** [comment]
Rooms:

https://i.gyazo.com/4c1c9710b9a49c1874c94d00845d0ce5.png
https://i.gyazo.com/655d98188d1f5a521fd54feea5ce6235.png
https://i.gyazo.com/98c19c13a6dcfb0b7b5df8d11ff219ed.png
https://i.gyazo.com/aaf06475739e8ccfadd63703509145ae.png
https://i.gyazo.com/7fd1cd983605b4f56990a10264d985ab.png
https://i.gyazo.com/69d991c3e3143ee781a01133ea23c503.png

There's some more additional closets and crates in maintenance with some things in them.

**Comment by Datraen** [comment]
Is that... Mime gear?

**Comment by Yoshax** [comment]
Maybe.

**Comment by Datraen** [comment]
I'm not entirely against this.

**Comment by Yoshax** [comment]
My thoughts on design and such are that if someone made a modifcation like carving out a room, or say a Chief Engineer or whatnot starting a construction plan or such, if they weren't finished or failed or whatnot they'd stay and probably just be sealed off or such, rather vanishing. Which is why a few of the things are behind walls/sealed airlocks with tape/cones. I was hoping to add a more... Used theme to the station.

**Comment by Datraen** [comment]
Yeah. It makes sense.

**Comment by Yoshax** [comment]
Is ready to be merged.

**Pull request merged**
