### PR TITLE
Removes visible blood pixels from female vatborns

### PR DESCRIPTION
**Pull request by listerla**
Minor edit; current sprite leads to the part intended to be hidden and used when libs are gibbed to be visible. Only female sprite does this; male sprite is fine.

Current sprite:
image

### CODE REVIEW

**Review by Spookerton — COMMENTED** [review]
single commit is preferable for the sake of repo cleanliness, but product do what say

**Comment by listerla** [comment]
i have no idea how to make it a single commit

**Review by Spookerton — APPROVED** [review]
does the thing, either way

**Comment by Atermonera** [comment]
inb4 squash-merge fixes cleanliness anyways

**Pull request merged**
