### PR TITLE
Makes R-UST machines deconstructable, some more fixes

### PR DESCRIPTION
**Pull request by Cyantime**
Makes the R-UST core, fuel injector, fuel compressor, and gyrotron deconstructable.
Makes the R-UST core actually connect to power cables when secured.
Slightly improves the collision checking from #4616

### CODE REVIEW

**Comment by Andromeda-K22** [comment]
So THAT'S why it wasn't working.

May want to look into why the computers don't link properly when constructed.

**Comment by Cyantime** [comment]
All of the computers don't start tagged when constructed, you need to multitool them and the machines to assign tags.

**Comment by Andromeda-K22** [comment]
Negative. 
Core control computer does not link properly, and the fuel injection computer does not even present a UI.

**Comment by Cyantime** [comment]
r-ust
I don't know what to tell you, everything works perfectly here.

**Comment by Mechoid** [comment]
I assume this has been tested, from that screenshot? (The machines, currently here, do not actually seem to link / let the console update properly. This means you can't build them in-round, for some reason. I know because I've tried.)

**Comment by Cyantime** [comment]
I built all those machines in current code and they worked fine, I haven't experienced any issues linking or using the computers

**Pull request merged**
