### PR TITLE
Adds Recently Cloned Modifier to Cloners

### PR DESCRIPTION
**Pull request by Neerti**
Makes new clones receive a substantial malus on combat ability, which will last between 25 to 40 minutes.
The malus proposed is:
-40% max health.
10% more incoming damage.
30% less melee damage.
Stuns last 25% longer.
2 more slowdown.
15% easier to hit.

This time can be reduced by upgrading the cloner.  A fully upgraded cloner can reduce the time to 5 to 8 minutes.
Also makes new clones receive a 'cloned' modifier, which doesn't actually do anything besides act as a sort of counter for how many times they've been cloned that only admins can see at the moment.  This will be more relevant in The Future(tm), when modifiers can be shown on the HUD.
Makes modifiers with the 'genetic' flag get copied to cloned mobs.  So far only the 'cloned' modifier uses it.
Adds admin utility/testing/badmin verb to give any modifier to any living mob.

Now you may be asking why this is being added, and it should be obvious.  Security.

It used to be a meme for them to say they get cloned and then immediately charge back into the fray, but lately I've seen things uncomfortably start to trend towards this becoming a reality.  Sometimes the lone sec officer who was cloned and had to go respond to something was actually justified in doing so, so I'm uncomfortable just giving a blanket ban to those who I see do it, so I feel mechanics can help provide an incentive for cloned people to take it easy for a little while, or at the very least play more cautiously if they really do need to fight someone.

For non-sec people who get cloned, most of those maluses won't really matter, except for the slowdown one.

Another benefit is that it also might provide an incentive for Medical to prefer to use the Defib to bring people back verses the cloner when possible, which will hopefully also kill the meme of 'just clone them its easier', which I don't actually see happen but it'll hopefully stop it from ever becoming a real thing.

I wanted to make the permanent 'cloned' modifier also provide a very minor malus (-5% max health or something like that), so dying would objectively be bad from a mechanics standpoint, but this provided rather unpopular, so for now it just does nothing, however I still feel it would be a good addition, especially if we add a 'cloned' Trait later on when/if Traits become a thing.

### CODE REVIEW

**Comment by SilverTalismen** [comment]
Sure I'm all for this.

**Comment by SpadesNeil** [comment]
25 minutes seems fair. 40 seems a bit much.

I disagree with a permanent debuff, but that's just me.

**Comment by Anewbe** [comment]
I feel like slowdown 2 is a bit much, and that this seems a bit harsh in general. Will need discussion.

**Comment by FenodyreeAv** [comment]
You can respawn in five minutes. If this goes in you might as well add an 'elevator, shuttle and gateway
 disorientation' modifier as well, that's applied to people who respawn.
This strikes me as an overreaction.

**Comment by Yoshax** [comment]
If they die and are dead, the job slot is gone. That's the point of them dying. Can't respawn if there's no job slot.

**Comment by Screemonster** [comment]
I'm with Ace on this. Permanent debuffs no, but a short period of feeling like shit while you recuperate makes sense.
Surgery, likewise. People hopping off a surgery table and back into the fray? Nah, you get your ass to the recovery ward.

**Comment by SpadesNeil** [comment]
So what's the word on this?

**Comment by Neerti** [comment]
Nobody knows.

**Comment by Anewbe** [comment]
I'll bring it up to the staff again, changes may need to be made.

**Comment by SpadesNeil** [comment]
I'm just gonna restate my position for the record.

Permanent debuff == bad.
Temp debuff == good.

**Comment by MagmaRam** [comment]
Any one of these debuffs alone would be fine as a combat malus, having them all together is just making someone totally useless for up to 40 minutes. Maybe make it so that the more times someone is cloned, the more effects they get?

**Comment by SpadesNeil** [comment]
This has been here since May...

**Comment by Belsima** [comment]
So... how's she going?

**Comment by Wickedtemp** [comment]
Looking at Polaris' population, I don't really think this should be implemented. Neerti's example of "a lone sec officer needing to jump back into the fray" can essentially be applied to almost every round on Polaris.

Instead of a 'recently cloned modifier', I would suggest a 'clone counter' that applies debuffs the more someone is cloned within a round or timeframe. This would allow the one or two sec members some leeway should they be killed once, but if they're cloned twice they begin experiencing debuffs, with every instance of cloning becoming more severe.

**Comment by zekesulastin** [comment]
@Wickedtemp When this was written 5 months ago, we had actual sec regulars to nerf like this.  That's why the entire essay to go with this pull request is all about how it affects sec with one throwaway line about "It won't hurt not-sec except for the slowdown lol".

**Comment by SpadesNeil** [comment]
All I care about is that the effects are **temporary**. Is that the case? Otherwise I'm pretty much gonna immediately disable permanent debuffs when this hits vorecode, 'cuz that's just not fun.

**Comment by Anewbe** [comment]
The effects are **temporary.**

**Comment by SpadesNeil** [comment]
okay good 👍

**Pull request merged**
