### PR TITLE
Splints no longer perfectly prevent negative effects from broken bones

### PR DESCRIPTION
**Pull request by Anewbe**
- Splinted bodyparts act broken 30% of the time.
- Splinted legs still slow you down like broken ones.
- Hardsuits are mostly unaffected. Power Armor is Power Armor.

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
Have you tested how this works with picking up items with broken-but-splinted arms, and walking with broken-but-splinted legs? How long can you hold an item for/walk for on average with this before something goes wrong?

**Comment by Anewbe** [comment]
About 70% longer than if you don't have a splint.

**Comment by mistyLuminescence** [comment]
Pretty sure you drop things near-instantly with a broken hand/arm, and testing broken legs/feet has been pretty weird on my end (sometimes you fall over, sometimes nothing happens at all). Making it only work 30% of the time (read: 'you still drop things near-instantly' and 'broken legs/feet are still weird'), just wanted to check if that was the case during testing or not.

**Comment by Atermonera** [comment]
Changelog to be written in about 10 minutes when I'm running the script

**Comment by Rand0mname** [comment]
I mean it is a broken arm after all. Even with a splint I doubt there is much you could do with it that doesn't involve pain/making it worse.

**Comment by Screemonster** [comment]
How will this handle traumatic_shock? Spikes of pain on 30% of life ticks?

**Comment by Anewbe** [comment]
@screemonster Anywhere the game checks for a broken limb, if you're splinted by anything other than a hardsuit, is going to trigger a little less than a third of the time.

**Comment by Nalarac** [comment]
If you had a broken limb splinted and taking painkillers, would you still have the negative effects? I ask because broken ribs can be temporarily "dealt" with by taking tramadol.

**Pull request merged**
