### PR TITLE
Allows lighting of smokeables on burning people

### PR DESCRIPTION
**Pull request by Yoshax**

### CODE REVIEW

**Comment by Magneld** [comment]
How?

**Comment by Yoshax** [comment]
Click a burning mob with your cigarette/cigar in hand, bask in the glory.

**Comment by Zuhayr** [comment]
Bad pun in message is not appreciated. We removed the dumb messages from lighting cigs on welding tools for a reason.

**Comment by Yoshax** [comment]
Gotcha.

**Comment by Fox-McCloud** [comment]
A-a-a-ahem. https://github.com/ParadiseSS13/Paradise/pull/3652

Credit where credit is do.

What a shame that @Zuhayr is so cold to the pun---but I doubt he'll warm up to it. =p

**Comment by Crazylemon64** [comment]
;_;

**Comment by Zuhayr** [comment]
:+1:

**Pull request merged**
