### PR TITLE
New Medical Belt Sprites

### PR DESCRIPTION
**Pull request by Hubblenaut**
**Before:**
Image

**After:**
Image

They are mostly white now, with just a tint of blue color the hue of the EMT labcoats. This way they will visually fit to most, if not all, medical uniforms.

### CODE REVIEW

**Comment by Kelenius** [comment]
But why? Security belt is not red, engineering belt is not yellow. All belts are secondary uniform colors.

**Comment by Yoshax** [comment]
Because the orange/pink/yellow or whatever you want to call it is an eye-sore.

:+1:

**Comment by Anewbe** [comment]
Leave the old belt sprite as like medbelt_old or something, I like it for reasons. But yeah, white one looks nice.
Might want to take this one to the community, but it gets a :+1: from me.

**Comment by SinTwo** [comment]
Make sure to update the in-hand icon.

**Comment by Hubblenaut** [comment]
Good call, updated.

**Comment by EmperorJon** [comment]
Looks much less "what?" than the original. Seconding Yosh on the weird salmon colour we have right now... :+1:

**Pull request merged**
