### PR TITLE
Change to first-aid post system

### PR DESCRIPTION
**Pull request by zaredman**
Suggested this be listed as do-not-merge pending staff meeting discussion since I can imagine this ruffling feathers on top of verification that I somehow didn't fuck this one up too. Time will tell. Still ironing out bugs on my end with my git setup. So far results look promising.

The purpose of this request is to try to coax crew from exceeding their general level of knowledge for anything medical (eg: knowing how to use a paddle-style defib and sleeper thinking it is at a 'first aid' level). That, and the Big Boss Medical is very close to just about everything on this new map.

If someone wants to be awesome and add AED-style defibs, that would be sweet. As those don't exist and my only real familiarity (may be a stretch) is with mapping, doing this instead. **This is only for the station level** and does (or should do) the following:

- Removes all first-aid stations with the exception of the one by the bar.

- Re-names the door of the one by the bar to "Triage Station," changes access requirements to those that already have medical access, and adds a spawn for an advanced medkit and a random medkit.

- Places numerous "first aid" wall lockers around the station containing a stretcher, stasis bag, first-aid medkit, and pill bottle of spaceacillin.

- Places numerous "defibrillator" wall lockers around the station, typically beside the above "first aid" wall lockers. These are locked to anyone with medical access.

- Moves pilot gear-up a bit up to where the old first-aid station was.

- Expands maint and re-zones some areas where appropriate.

### CODE REVIEW

**Comment by zaredman** [comment]
example setup
pilot change

**Comment by zaredman** [comment]
God damnit I forgot to change the door at the pilot nook.

**Comment by Woodratt** [comment]
Part of the reason for the existence of the first aid stations is due to the fact it allows crew members to bring someone to a aid station that they have access to stabilize with the bandages and or await medical's arrival. If these are locked to medical only access I have concerns they won't be used at all by anyone. Except maybe by the forgetful emt that did not bring along a rollerbed. The only First Aid station that had more advanced kit is on deck one, and that is locked behind access restricted windoors. 

Another concern of mine is if a hallway is breached due to whatever reason (meteors, bombing, carp) it can be very easy to be cut off from medical. Or if there's simply no medical, then that means the only reliable source of band-aids that civilian crew can expect is if they go to medical and smash though the windows. 

--

Unrelated to above, is that ship shown in the new pilot's area, "/obj/item/weapon/orion_ship" ? Cause if it is you're going to want to unmap that since it's a small bomb, not a toy. If not, ignore.

**Comment by Arokha** [comment]
I coded AED defibs a long while ago. They were replaced by the current ones I think. You basically slapped the patches on and waited.

**Comment by zaredman** [comment]
@woodratt - There is a minimum of one all-access first aid locker on each wing. There are actually more first-aid lockers in total vs those first-aid posts. Contents of each are listed above. 

All this does is consolidate those rooms into boxes while limiting sleeper/defib access. Sleepers and defibs are not first-aid level equipment.

The only thing med-locked are the defibs as a full paddle-style defib is most definitely not a first-aid skill. If one wants to argue technicalities, paddle defibs are’t even a BLS skill and ALS barely meets the mark. 

As for the ship - That’s just the icon for the random toy spawner.

@Arohka those would be awesome for first aid. Were they different than the main defibs in other ways?

**Comment by zaredman** [comment]
Looking over the map now. Will have:

- Med-locked Defib & All-access First Aid outside Hangar 1

- Med-locked Defib & All-access First Aid outside Hangar 2

- All-access First Aid kit in Pilot Prep

- All-access First Aid kit out by the vending machines/elevator on z1

- Med-locked Defib & All-access First Aid on the bottom bit of z1 closer to the stairwell

- All-access First Aid outside the Triage Station (which still has the defib and sleeper)

- Med-locked Defib & All-access First Aid on the Cargo/Engineering wing of z2

- Med-locked Defib & All-access First Aid just beside the Janitor's area on z2

- Security medical post is not changed at all.

- Med-locked Defib & All-access First Aid on the Bridge between the noticeboard and fireaxe.

All in all more opportunities for emergency medical equipment while bringing everything back to a "first aid" level without any meaningful loss in quality of care rendered to the patient.

**Comment by mistyLuminescence** [comment]
IMO sleepers and defibs _are_ basic first-aid level; sleepers are easy enough to use that the Sif shuttles get them, and defibs IRL are as simple as "follow the simplified instructions on the defib screen". Making it locked to medical only means less civilians have access to it, which might not be a good thing if we want them to be able to keep someone stable until the paramedic arrives.

As a medical main, the only time I actually use the first-aid posts is when I forget to bring a roller or defib; everything else, I have with me already. They're only really useful for civvies to stabilise someone until I arrive, or to grab emergency supplies from if medical gets hit before I can gear up.

**Comment by zaredman** [comment]
AEDs are stupid simple, yea. With the "realism" argument that I'm not really advocating for, what we have in-game are not AEDs. If we get them and there is an actual mechanical difference (ex: two shocks and that's it, no ability to overcharge or harm-defib), then we can slap them in the first-aid boxes. My main issue is with with them all over the place where anyone can access them. Not only does it give the risk of death a bit less of an impact but it continues to promote an environment where everyone can do BLS-level work because "they have access to the room."

First aid should be just that. First aid. Not BLS, ALS, ACLS or the such.

Likewise, sleepers were not supposed to be/originally were not technically "first aid" - A complex machine that can both administer and synthesize various medications should require a greater knowledge to use when compared to an autoinjector or even a vial/syringe.

And if you still forget gear that you need, there's more places to pick up rollers/stasis bags with this.

**Comment by Wickedtemp** [comment]
One of the reasons I fawned over this map was the first aid station placement.

It's insanely helpful as it provides a few bits of basic gear, a roller, defib, stasis bag, and of course, a sleeper. 

The sleeper, you could argue, is at least easy enough for an explorer/pilot to make use of. I know the ones on the shuttles may be *intended* for SAR, but let's be honest, if that were enforced, they'd hardly be used, ever. For non medical personnel, their main use would be the stasis levels, and from what I can tell, that's generally what non medical personnel do. 

Another reason why I really hope you don't mess with the aid stations is that it provides a checkpoint of sorts. "The patient is at the port Aid station!" is a hell of a lot easier to picture than "The patient is at the port Medical Locker In The Wall." 

The AED's that we had before were neat, I'd personally prefer if we had both versions ingame. 

Coming from a med main, the only time Medical doesn't have anything to do from my own experience is when Planetside makes use out of whatever Med gives them(which is what I personally prefer, because I don't usually have fun spending 8 minutes on a shuttle to get rid of an infection), or they simply die and nobody ever figures out. Stationside, I've had plenty to do. People using the first aid stations doesn't really factor into that, because if someone uses them, *I'm going to check on them anyway, because due to their Not Being Medical, there's a rather high chance they missed something*. Most of them come by medical on their own, or simply wait at the aid station for a physician to check them out. If it was completely fixed by a sleeper, then it literally only required a single syringe of any medicine I have onhand, and...to be honest, that isn't a whole lot to do, it isn't a whole lot to miss, and I don't really care if it was already done by someone else or not. 

Onto whether or not sleepers count as first-aid, the most advanced thing they do would be the stasis setting - which I *want* Non med to know how to use, as its the most useful part of the sleepers existing on the shuttles, and dialysis, and there's no reason for NonMed at all to use that unless you're gonna drain someones blood for an antag gimmick (Which I also support). Everything else is chemical, and those *are* basic chemicals. Dexalin, Paracetamol (literally tylenol), dylovene, inaprovaline, all reagents that we allow civ crew to use in the Oxy and Toxin kits. 

For gear placement, we already have that, and we have plenty as far as I can tell. There are stasis bags, defibs, etc at each aid station. Some med players have those onhand anyway, so the ones in the stations are often left untouched. The times we *do* use them are generally few in number. The times we use them all and need more, even fewer. 

The "risk of death" bit only matters to people who want it to matter. I'll be honest, some days I'm tired, I just want to do chemistry and when a crew member dies the greatest fuck I can muster is "Aw bummer dude rip", other days I can actually get Huxley to pause a moment before going back to work. Sometimes, he gets broken up about it and leaves the round if it was a particularly sad, brutal and preventable death that he failed to prevent. The risk of death is going to be unaffected in general. If a patient can be saved by a sleeper, you can defib them when a doctor reaches the scene should a sleeper be unavailable. Doesn't matter. Same risk of death. These aid stations are just convenient for Medical. Insanely convenient. I hardly ever used them on the Northern Star because the placement was odd.

On the Southern Cross, the placement makes sense, it's convenient, I use them often essentially as a stabilization room so I don't have to stabilize them on the floor in the *hallway*. Please don't take these away when they just started to get used.

**Comment by Atermonera** [comment]
Could cut the nooks in half, have the basic locker on the outside where crew can get them and then the sleeper and aed locker behind med-access? Would allow for more smattering of basic med supplies where crew can access it, while keeping the stabilization stations.

**Comment by zaredman** [comment]
So my git just got porked good due to software incompatibilities. Will repost this in a bit.

**Pull request closed without merging**
