### PR TITLE
Changes NT brand cyberlimbs, adds NT brand alt. head

### PR DESCRIPTION
**Pull request by SubberTheFabulous**
I don't like NT brand cyberlimb sprites.
That is all.
https://i.imgur.com/0k39Ktr.png

### CODE REVIEW

**Comment by SilverTalismen** [comment]
What does the new look look like?

**Comment by Anewbe** [comment]
Give me images.

**Comment by SubberTheFabulous** [comment]
Link added.

**Comment by Anewbe** [comment]
Eh... Gonna be honest, I'm not a huge fan of this change. Admittedly, I'm biased, but the NanoTrasen frame is supposed to look very, very basic.

**Comment by SubberTheFabulous** [comment]
My main problem with current sprites is that they look kind of _meh_, but that's just me, probably.

**Comment by SilverTalismen** [comment]
I think it looks nice, the NT brand itself just looks kinda meh atm, with not a whole lot of detail just differing shades of grey and black.

**Comment by Anewbe** [comment]
They're supposed to look Meh.

**Comment by SubberTheFabulous** [comment]
Well, I am not the one to decide.
¯\_(ツ)_/¯

**Comment by Belsima** [comment]
Personally, I MUCH prefer these.

**Comment by elgeonmb** [comment]
I like the sprites however I love variety so I don't see why we can't just

change what company these are supposed to be

**Comment by Woodratt** [comment]
Cybermen? 

Serious note. are the old sprites kept in the files in the off chance they get used for something again or were they outright deleted?

**Comment by SubberTheFabulous** [comment]
Welp, due to those sprites being added in another PR, I am closing this one.

**Pull request closed without merging**
