### PR TITLE
Makes HUDs toggleable.

### PR DESCRIPTION
**Pull request by Belsima**
Now you can turn them off. If they're projector-huds, tell me so I can redo the sprites- I assumed they were colored glass like Mesons.

### CODE REVIEW

**Comment by Anewbe** [comment]
Did you test this?

**Comment by Belsima** [comment]
I did.

**Comment by Anewbe** [comment]
You made the sechud grey and the off hud red, don't think that was intended.

**Comment by Belsima** [comment]
Are you sure? I tested with the sechud- I'll test it again once I get home, but I'm pretty sure it works fine.

**Comment by Anewbe** [comment]
Sorry, meant for the prescription ones.

**Comment by Belsima** [comment]
This is super ugly and was a bad idea.

**Pull request closed without merging**
