### PR TITLE
More alt title purges

### PR DESCRIPTION
**Pull request by Anewbe**
The following titles have been removed:
- Resident has been commented out because it no longer fits the map. Not removed in the off chance we figure out multiple maps.
- Investigator has been removed, it didn't serve a specific purpose.
- Colony Director has been removed, the default is now Site Manager, because I don't want to have to change it again any time soon.

### CODE REVIEW

**Comment by PrismaticGynoid** [comment]
Whatever happened to Station Administrator?

**Comment by Nalarac** [comment]
And thus comes all the renaming of the captain's items from colony director's [x] to site manager's [x].

**Comment by Anewbe** [comment]
Ah, fuck, you're right.

**Comment by Anewbe** [comment]
This'll be redone in a better way sooner or later.

**Pull request closed without merging**
