### PR TITLE
[Don't merge this yet.] Moves atmospherics onto SSair.

### PR DESCRIPTION
**Pull request by chaoko99**

### CODE REVIEW

**Comment by Atermonera** [comment]
What's SSair?

**Comment by chaoko99** [comment]
Subsystem. It just moves the Air controller onto StonedMC.

**Comment by chaoko99** [comment]
https://github.com/vgstation-coders/vgstation13/pull/15313

**Comment by chaoko99** [comment]
This is gonna be a bit... Troublesome.

**Comment by chaoko99** [comment]
Bay is porting this. Closing until their port is complete. Then we will port the port.

**Pull request closed without merging**
