### PR TITLE
Adds a sexy maid uniform~!

### PR DESCRIPTION
**Pull request by MatchaFrappe**
Adds a sexy maid uniform. This also adds the uniform to the loadout.

http://i.imgur.com/0VwyLRl.png

P.S. This is my first clothing sprite for SS13

### CODE REVIEW

**Comment by MatchaFrappe** [comment]
Sorry for closing it momentarily, was just rechecking the sprite. Thank you.

**Comment by Iamgoofball** [comment]
:-1:

:thinking:

**Comment by Iamgoofball** [comment]
although welcome to github, this is your first PR according to the repo

have you made sure to compile this locally to ensure it works? as i noticed you added files via the web editor.

**Comment by MatchaFrappe** [comment]
Oh thanks for the advice! I'll close this for further review then. Thank you!

**Comment by MatchaFrappe** [comment]
It works. :)

**Comment by SubberTheFabulous** [comment]
This is all, that everyone ever needed.

**Comment by Anewbe** [comment]
I'm very conflicted on this, going to pass it to the Staff.

**Comment by SpadesNeil** [comment]
Hey if you don't want it, us ~~perverts~~ players at Vorestation will take it.

**Comment by Anewbe** [comment]
Staff doesn't mind, so here we go.

**Comment by Belsima** [comment]
By the way, a Teshari sprite would be dank and cool. Been hoping for a maid suit for the birds, even if it is _this_ one.

**Comment by Iamgoofball** [comment]
Please revert

**Comment by Neerti** [comment]
Please don't necro two month old PRs.

**Pull request merged**
