### PR TITLE
Fixes Diona Light Gain

### PR DESCRIPTION
**Pull request by ParadoxSpace**
No more starving in broad hallway light.

### CODE REVIEW

**Comment by Hubblenaut** [comment]
Aside from changing the else statement to a value to make diona unable to heal in unsimulated areas like Central, what you're changing here affects far more than just the nutrition values.

**Comment by ParadoxSpace** [comment]
Elaborate.
https://github.com/Baystation12/Baystation12/pull/12405

**Comment by Hubblenaut** [comment]
I don't see anyone claiming there to merely change nutrition values.

**Comment by ParadoxSpace** [comment]
Unsimulated turfs should now function.

**Comment by Datraen** [comment]
:+1: I see no obvious problems.

**Pull request merged**
