### PR TITLE
Port computer and 'machine' frame icons from Bay

### PR DESCRIPTION
**Pull request by Arokha**
Kinda. I modified them. The console frames are fully directional so you can tell wtf way you're building them, and the machine frames, I added a little chevron to the front that points in their direction so you can tell.

Depends on https://github.com/PolarisSS13/Polaris/pull/6859 to look right

image

### CODE REVIEW

**Comment by Cerebulon** [comment]
For computer frames we'd probably want the actual computer sprites in at the same time, otherwise they're probably going to look suddenly different when they're fully built.

**Comment by Arokha** [comment]
Oh, do you not use those sprites? I thought you used the current Bay-originally-Eris style ones?

**Comment by listerla** [comment]
Right now we use the old ass ones, aye.

**Comment by Arokha** [comment]
Ok well gimme a minute then.

**Comment by Arokha** [comment]
Ok, https://github.com/PolarisSS13/Polaris/pull/6859

**Comment by Atermonera** [comment]
staff input mostly as a corollary to 6859, since this is generally dependent upon that to make sense.

**Pull request merged**
