### PR TITLE
Species var that enables eyes to glow

### PR DESCRIPTION
**Pull request by Arokha**
By glow I mean be drawn above the darkness plane, not actually generate and illuminate turfs. Just set the var to 1. Covered up by anything that also covers up your facial hair, so opaque helmets and such. If you wear transparent facemasks or anything, your eyes will be on top of them, piercingly glowy.

Adjusting eyes are from https://github.com/PolarisSS13/Polaris/pull/4626

### CODE REVIEW

**Comment by MisterLayne** [comment]
Will this be enabled by default for Tajaran?

**Comment by Arokha** [comment]
I didn't enable it for anyone by default. To be honest, I've never played on Polaris. Just whenever I code a new feature I put it here too since we're a downstream. Y'all are welcome to enable it on whichever species you want, though!

**Comment by Arokha** [comment]
@Anewbe @Neerti Did you have any requests for species to have it on? I can just throw the var in if you want, free of charge

**Comment by Anewbe** [comment]
I think just leave it be, for now.

**Pull request merged**
