### PR TITLE
Item force tweaks

### PR DESCRIPTION
**Pull request by Yoshax**
Many tools and other items have their force set low. For example, toolboxes. They are heavy, metal boxes yet they did 5 damage.

### CODE REVIEW

**Comment by Kelenius** [comment]
Let's break bones with two smacks of fire extinguisher? There is a reason why these were nerfed.

**Comment by Yoshax** [comment]
Changed? Nerfed? They haven't been touched since pre-2012.

**Comment by Kelenius** [comment]
I believe that a lot of items were nerfed from their tg values to what we have now a long time ago.

**Comment by Yoshax** [comment]
Perhaps. But I do feel some were a tad heavy-handed, so I have made a few more adjustments.

**Comment by EmperorJon** [comment]
I don't really have an issue with these. :+1:

**Pull request merged**
