### PR TITLE
Change chemmaster custom preset to 15 and adds options for 30 and 60 units

### PR DESCRIPTION
**Pull request by Dibasic**
60 is more commonly used for filling a whole bottle. The preset was 30 back when bottles only held 30.

### CODE REVIEW

**Comment by Datraen** [comment]
I still use 30 at times for things, but it's not that important and it's easily changed.

**Comment by Dibasic** [comment]
Better way would just be to add 30 and 60 buttons since they are commonly used

**Comment by Datraen** [comment]
So why not do that?

**Comment by Dibasic** [comment]
I will do that, should I make a separate PR or add a commit to this one?

**Comment by Datraen** [comment]
Might as well add it to this one, as this would be a moot point otherwise. We can squash commits on Github now, instead of having to have someone do it on their own client.

**Comment by Dibasic** [comment]
did that. added options for 30 and 60 units. set the default to 15 because that's a reasonable value I think.

**Comment by Datraen** [comment]
:+1:

**Pull request merged**
