### PR TITLE
Adds the Anti-Surveillance Tool for Traitors.

### PR DESCRIPTION
**Pull request by Neerti**
Adds a traitor device to warn the traitor if they're being spied or are about to be spied on by the AI or anyone using a camera console.
It will warn the holder by changing color, beeping a specific tone, and sending a message to their chat log.  It only does this when the state of spying changes, so it will not spam the chatlog if nothing changes.  Only the holder can hear the warnings.  It also functions like a regular multitool.

Also changes cameras slightly to enable seeing if they're being used cleanly.

Inspired by /tg/'s AI detectors, with more bells and whistles added.

### CODE REVIEW

**Comment by Fox-McCloud** [comment]
TG port? https://github.com/tgstation/tgstation/pull/965

**Comment by Neerti** [comment]
It's mostly a port, yes.

**Comment by Anewbe** [comment]
Tested and all that?

**Comment by Neerti** [comment]
Yes, me and Mechoid tested on a local server and it seemed to work really well.

**Pull request merged**
