### PR TITLE
Shotgun boxes now have 8 shells, uplink gives said boxes

### PR DESCRIPTION
**Pull request by Anewbe**
Adds some of the shotgun ammo box and uplink changes from #2514

### CODE REVIEW

**Comment by Yoshax** [comment]
Those large boxes will give 24 rounds.

**Comment by Anewbe** [comment]
That explains a lot, thank you. Will change.

**Comment by Yoshax** [comment]
You're adding 8 to the box in the `..()` then adding 16 in the actual proc. Just needs both numbers to be 8.

**Comment by Anewbe** [comment]
Problem solved.

**Comment by SpadesNeil** [comment]
Can we please make shotgun boxes smaller so they fit in pockets? It's exceedingly obnoxious to reload shotguns because your only option is to shove your shotgun into your backpack or put it down while reloading.

**Comment by Neerti** [comment]
You can wrack the box against the shotgun to reload it as well.

**Comment by SpadesNeil** [comment]
https://youtu.be/cgwlJIo0In0

**Comment by Anewbe** [comment]
#2502

**Comment by SpadesNeil** [comment]
Oh. Well. I feel stupid.

**Pull request merged**
