### PR TITLE
[WIP]The Open World - Completely overhauls Economy, Cargo/Supply, and Organizations/Companies/Factions

### PR DESCRIPTION
**Pull request by kevinz000**
### THIS IS THE LAST TIME I OPEN A MASSIVELY WIP PR WITHOUT FINISHING MY CURRENT ONES, PLEASE DO NOT SMITE ME
Disclaimer: The parts wher eI say "configurable" may also mean "Might need a configuration refactor (which is another project) to work properly". I'll probably open that after I finish instruments and DCS

Other disclaimer: This seems like a massive PR but really it's just three refactors, two-three medium-large features. No big deal, it's not even as of a "oh god oh fuck" as that pixel projectiles PR which has been open for 3 months.

Other other disclaimer: I'm not aiming to force everyone to use economy and for money to be used for the smallest things. I want money to be more useful and developed but not to the point where you have literally everything capitalist mode at which point it turns into a business simulator/annoyance and not spessmens

### Economy overhaul:
All jobs' paygrade/crap is tweaked. Starting money tweaked, etc etc, all configurable. Generally, the higher rank you are, the more money you get at roundstart. This will be lower than now, probably way lower, because:
Station gets a set payroll. This may change in in round events, etc etc, not decided yet. It will be configurable, and probably support limited randomization/variance that's also configured.
You get paid in 10 minute/configurable intervals. This is taken out of the station payroll. The system will most likely be designed to also assign how much each person is paid.
The HoP will be able to adjust all this. Yay! Piss everyone off, get lynched, whatever. Or don't, because this is HRP and you probably shouldn't do that. Antags could probably have a jolly time with it or something, IDK. Think of the possibilities!
Almost all economy backend code is being refactored in this PR. More details to come, but economy will be subsystemized, stuff will be tweaked and modernized. Yay! 

### Organizations/factions
See that busyspace organizations.dm or whatever?
Yeah, it's currently only used for making everyone think the entire server isn't AFK by spamming radio.
Well now the organizations are shuffled under modules/organizations.
Organizations are all initialized at start like before, but in general this is being separated and moved onto its own subsystem for things like:
Relations: How friendly a norganization is to NanoTrasen and the station. This will affect multiple things, but the first thing that I can think of is trading/cargo shipping/etc
Will probably add more to this when I think of stuff to be doing about it

### Cargo overhaul
datum/supply_item is added. Yes, now cargo can order individual items. It will incur a shipping charge for containers used (which means if you try to buy guns you're going to get charged for the secured locker or whatever it comes in. No free guns, nerds.) Space Amazon, woot!
All existing supply packs will stay.
Both supply items and supply packs can be assigned to an organization. This defaults to Nanotrasen.
Cargo will be able to order from all normal organizations. The price you pay has to do with that organization's relations with Nanotrasen and the station, and potentially other factors, added later
Supply credits are gone. Supply account is now in thalers.
Instanced supply is now a thing. I don't know why or how you would need more than one kind of cargo account/cargo bay, but uh, the option is there I guess?
Exports are being datumized. Yes, you can now sell.. stuff.. for the materials that make them up. How I'll prioritize this stuff so it's realistic (so you don't get multiple payouts for the same thing from multiple datums when they shouldn't stack) .. uhhh, get back to you on that.

Again, this seems big, but the biggest thing that is going to be gotten out of this is the framework for expanding on later. I'm not going to code every possible export/supply item/relationship feature/organizational supply pack in this one. I don't have nearly enough time, or energy, to make literally everything. It's designed to allow for expansions later on, from any coder that wishes to use this. Of course, it'll contain initial content so it's not empty, but what I'm saying is, if this is merged feel free to go crazy with it :)

### CODE REVIEW

**Comment by Hatterhat** [comment]
kkeVIIIIIIIIIIIIINZ

**Comment by elgeonmb** [comment]
:pray:

**Comment by Keekenox** [comment]
Absolute legend.

**Comment by Atermonera** [comment]
>800 lines
>comparing size as equivalent to 2000 line prs
pls

**Comment by krumpmeboyz** [comment]
bless

**Comment by Anewbe** [comment]
Closing at the request of the author.
This one, however, I will be stealing ASAP.

**Pull request closed without merging**
