### PR TITLE
Gives staff more accesses.

### PR DESCRIPTION
**Pull request by Datraen**
Devs - Aghost
Mods - Allow respawn + Direct Narrate

### CODE REVIEW

**Comment by Datraen** [comment]
Updating to more accesses

**Comment by Datraen** [comment]
Tested, everything working fine.

**Comment by Zuhayr** [comment]
Assuming aghost works without +MOD, :+1:

**Comment by Datraen** [comment]
Tested as just Developer, which has no +MOD
Testing as a Dev Mod would have been pointless.

**Comment by Zuhayr** [comment]
Oh god dammit I seriously just read my own :+1: as a merge approval.

I need to sleep.

**Pull request merged**
