### PR TITLE
The great rock update.

### PR DESCRIPTION
**Pull request by Ketrai**
- Still a WIP, please do not merge until the work in progress tag is removed from the title.

- Adds rock outcrops. These can be placed to guarantee a certain ore to spawn whilst mapping. There's also a random variant for when you just want the outcrops mapped somewhere, but don't want to pre-determine the ores spawned. (Fully Implemented)

- Adds a whole new type of rock wall, complete with borders. Much lighter and with more depth. (fully implemented)
- Adds a series of rock ledges to add depth to a map. (wip)
- Adds some rock stairs to add depth to a map. (wip)
- Adds a new type of sand that fits with the new rocks, there's also trandition tiles if you want to mix in both styles.

image

image

### CODE REVIEW

**Comment by Heroman3003** [comment]
While the new rocks do look good, I think the sprites for diamonds/phoron are overly cartoonish and not really fitting with either ore sprites or even rest of rock outcrops/rock sprites in general.

**Comment by Schnayy** [comment]
Colors all feel a little too... light? And yeah some of them are too cartoony.

**Comment by Ketrai** [comment]
The colours will feel too light with full lighting, which is pretty much impossible outside. ingame they should be fine.

**Comment by Schnayy** [comment]
I'm going to be honest, I don't like these sprites. They're too cartoony and inconsistent with the rest of the sprites we have.

**Comment by Woodratt** [comment]
The ore sprites feel a bit, game-ish in my opinion. Something just feels off on them to me.

Sand sprites sorta seem find, but would need a picture of them in the wild to really get a accurate judge.

Same with the rock sprites. But the distinct repeating pattern is offputting and they feel a bit too, bright and pastel as a first impression.

**Comment by Ketrai** [comment]
Well everything should look 2 shades darker in game, as stuff isn't ever really perfectly lit especially not outside. If it's still too brig then I can look into just making the shade a bit darker. 

if repetiveness is an issue I can always make a few variations of the main sprite that perfectly fits in with the others. Though it would require a firm refactor of the way mining turf are generated. And it would require unique sprites for ores too of I ever decide to implement ore overlays for these rocks. 

The aim for this or is to offer an alternative style of rocks for people to toy with. Naturally it won't fit in with the existing rock sprites as you're not meant to mix the two together. That's what the transition tiles are for.

**Comment by Schnayy** [comment]
That doesn't change the cartoony nature, and you haven't presented pictures of how it looks in game, which is the important part if you're insisting it looks better in different lighting.

**Comment by Ketrai** [comment]
> That doesn't change the cartoony nature, and you haven't presented pictures of how it looks in game, which is the important part if you're insisting it looks better in different lighting.

that's because it's a WIP pr, I have to implement each individual feature first before I can load up a test map and show it off lol.

**Comment by Anewbe** [comment]
For sprites, at least, that's not strictly necessary. It's probably actually better to show the work-in-progress sprites in the not-first-post so comments can be made in response to it.

**Comment by Ketrai** [comment]
image

**Comment by Ketrai** [comment]
anyways, i'm increasing contrast and making the crystals smaller.

**Comment by Ketrai** [comment]
image

Latest image, yes the rock patterns ended up looking repetetive but that's rng for ya, the bottom side is a much better example. 

In any case I just have to figure out how to make ledges slow folks down or make them climb it. because they're a structure and not a turf I'm having difficulties...

**Comment by Ketrai** [comment]
Ledges work decently enough now to be used in mapping. Should be good for merging now.

**Pull request merged**
