### PR TITLE
Bone Break Sound

### PR DESCRIPTION
**Pull request by redstryker**
Adds a sound that plays when a bone is broken.  Adds it to the list of sounds that can be played by the Technomancer.

### CODE REVIEW

**Comment by Neerti** [comment]
Where was this sound obtained?

**Comment by redstryker** [comment]
http://www.zapsplat.com/music/horror-bone-break-arm-or-leg/
http://www.zapsplat.com/license-agreement/

**Comment by Hubblenaut** [comment]
I don't really like this one actually.

**Comment by Yoshax** [comment]
Do not want. It's off-putting to many people, and you do not need to provide more reason or ways to alienate players.

**Comment by Mark9013100** [comment]
How the fuck does it alienate people.

**Comment by Hubblenaut** [comment]
Tone.

**Comment by Yoshax** [comment]
The sound is off-putting to many people, including myself. Some people do not like these kinds of sounds. It alienates them by forcing them into a situation where there choices are be exposed to these very off-putting things or attempt to ignore them, or put themselves into situations where they cannot experience them. Such as by not playing. Your tone is rude, and unappreciated.

**Comment by ParadoxSpace** [comment]
It's supposed to be off putting, it's the sound of a bone breaking.

**Comment by Yoshax** [comment]
It's disgusting. Sure, it should be, but you're forcing players to be exposed to it. The sound is very grating, and off-putting to people as I have said. People do not come to play to be exposed to these things. If you wish to do so, it would come as no surprise if people found elsewhere, where it does not happen.

**Comment by Mark9013100** [comment]
Then just mute your headphones/speakers/whatever.

**Comment by SpadesNeil** [comment]
Or maybe add a feature to let players toggle gore sounds off instead of muting **the entire game** because some coder was being a jerk.

Or just don't add this. :-1:

**Comment by Mark9013100** [comment]
I don't see how adding one sound makes someone a jerk.

**Comment by SpadesNeil** [comment]
Hence my redaction of that part a split second before you posted. I somehow misread it as you and OP being the same person. I'm sleepy. Sorry.

Still don't add this.

**Comment by Anewbe** [comment]
I like it, but I can understand why it makes people uncomfortable.

**Comment by Hubblenaut** [comment]
@Mark9013100 I guess it just doesn't get into your head that some people have their own opinions and feelings about something and the right to express them for consideration.

Don't come barging in blurting 'the fuck is XY'. This is no place for that tone. Either participate in a discussion the civil way or stay out of it.

**Comment by Serithi** [comment]
I'm not saying that sound won't elicit certain reactions, but i would like to point out that in this game where you can dismember, decapitate, wrench joints out and pluck out internal organs, your complaint is that you can hear some of it?

By all means, add in a toggle for the sounds, but i personally like them because they add some actual weight to the actions.

**Comment by SpadesNeil** [comment]
> I'm not saying that sound won't elicit certain reactions, but i would like to point out that in this game where you can dismember, decapitate, wrench joints out and pluck out internal organs, your complaint is that you can hear some of it?
> 
> By all means, add in a toggle for the sounds, but i personally like them because they add some actual weight to the actions.

Dude makes a valid argument.

**Comment by Yoshax** [comment]
There's a big difference between sounds and a vague description.

**Comment by Datraen** [comment]
Whether or not this is something that is off-putting or not is null and void, this breaks their licensing agreement and cannot be added.

http://www.zapsplat.com/license-agreement/
"What you can’t use our free sound effects for:
You may not use our sound effects for the following purposes under any circumstances…

1.Our sound effects can not be used as raw material and edited or mixed with other sounds to form new sounds for sale or distribution.
2.Our sound effects must not be shared with any person.
**3.Our sound effects must not be distributed in any form including on other websites, on social networks, file sharing platforms, CD, DVD or any other ROM.**
4.Our sound effects can not be loaned, rented, sub-licensed or sold to any third party.
We retain the copyright to our sound effects at all times. Sound effects are licensed to you on a non-exclusive basis and subject to the terms detailed above."

Case closed, pack it up.

**Comment by redstryker** [comment]
Closing until I find/make a better sound.

**Comment by PsiOmegaDelta** [comment]
Record breaking some celery. Is apparently pretty similar to the real deal.

**Comment by redstryker** [comment]
@PsiOmegaDelta that's actually the plan.  I have some at my desk with me right now.

**Pull request closed without merging**
