### PR TITLE
Adds the IA jacket/fake sunglasses to custom loadout

### PR DESCRIPTION
**Pull request by Mark9013100**
Full list of changes:
:cl:
Makes the purple suit jacket toggle-able.
Renames the IAA jacket to black suit jacket, adds it custom loadout.
Adds a subtype of glasses, 'stylish sunglasses' to custom loadout, doesn't have flash protection.
Adds sprites for the purple suit jacket.
Adds more clothing to the IA wardrobe.
Adds the black & purple jacket to the cargo formal wear crate.
Adds toggles for the thermonocle and thermal eyepatch.
Adds the normal forensics jackets to custom loadout.
:cl:

### CODE REVIEW

**Comment by Mark9013100** [comment]
oh shit I made a spelling mistake

**Comment by PsiOmegaDelta** [comment]
I don't think Polaris actually has setup webhook to check for online changelog entries, their collaborators will have to confirm.
Even if they do each line should look like:
```
add: Added a feature.
tweak: Tweaked a feature.
del: Removed a feature.
```
etc. See https://tgstation13.org/wiki/Guide_to_Changelogs#Online_auto-creation.

**Comment by Mark9013100** [comment]
Hm, thanks for the info.

**Comment by Neerti** [comment]
We currently lack a online changelog maker, I'll have to see if we can get one sometime soon, since it seems neat and probably less of a hassle than the current method.  For now, don't bother with the CL stuff.

Anyways, about this PR, I don't see any obvious faults with it.

**Pull request merged**
