### PR TITLE
Nerfs the Unathi knife, adds the harness to loadout.

### PR DESCRIPTION
**Pull request by Zuhayr**
This needs admin approval before merge since Neerti was not sure if it would be desirable or not.
The knives are weapons, but they are also exceptionally weak ones, and the item has a pretty high cost. You can get a more effective weapon by taking hatchet or kitchen knife from the cafeteria.

### CODE REVIEW

**Comment by ParadoxSpace** [comment]
I got a pretty dire need for this. They are whitelisted exclusively for unathi usage, right?

**Comment by Zuhayr** [comment]
````
+	whitelisted = "Unathi"
````

**Comment by Neerti** [comment]
I wouldn't mind adding this if the harness started empty, since I don't believe the custom loadout should be the place to get weapons, no matter how weak they are, since it also begs the question of 'how did this get pass customs' etc.

**Comment by Yoshax** [comment]
Same reason Sikhs are allowed to have Kirpans, or Scots in full outfit are allowed Sgian-dubhs. Religious or cultural reasons. But that would probably be Sledge's call.

**Comment by ParadoxSpace** [comment]
Yoshax does have a point about kirpans. It's a traditional thing for Sikhs. Even in the shower they take them. It's simply cultural for Unathi to be able to bring their dueling knives. They aren't dangerous, neither are Kirpans or Sgian-dubhs.

**Comment by sabiram** [comment]
Sikhs have extreme reservations about actually using their knife, even in defense. I wonder if the same could be said of unathi.

**Comment by ParadoxSpace** [comment]
I assumed it would only be used in honorable or utility contexts like actually dueling, cutting food, self defense, etc.

**Comment by Zuhayr** [comment]
For clarity the knives are wooden with teeth set into them, akin to http://australianmuseum.net.au/uploads/images/19319/ih000359_big.jpg - they're not going to be something that poses a credible death threat to anyone wearing anything heavier than a T-shirt.

**Comment by Zuhayr** [comment]
Additionally without the knives this is pointless. It adds two extremely specific storage slots (knives only) and a barely visible accessory icon.

**Comment by Zuhayr** [comment]
As discussed, closing this for now.

**Pull request closed without merging**
