### PR TITLE
ice cream

### PR DESCRIPTION
**Pull request by MisterLayne**
Please ignore the title. That was an error on my part.

Adds secondary hair colors for hair, and a gradient- sort of like highlights.

VJttN8mfeX

### CODE REVIEW

**Comment by Mechoid** [comment]
I could fix the title. But due to how much I am in pain from laughing, I for some reason can't make myself do it.

**Comment by Greenjoe12345** [comment]
how do these secondary colors look?

**Comment by TheFurryFeline** [comment]
Mmmm, ice cream. As Medibots are wont to say: "Delicious!"

**Comment by Neerti** [comment]
:ice_cream:

**Pull request merged**
