### PR TITLE
Removes duplicate internal organs

### PR DESCRIPTION
**Pull request by Cameron653**
Heart is actually defined here
https://github.com/PolarisSS13/Polaris/blob/master/code/modules/organs/internal/heart.dm
- Removes duplicate internal organs and leaves comments of where to actually find them.
- The file was commented out, but contained old code.

### CODE REVIEW

**Comment by Wutnold124** [comment]
god i wish that were me

**Comment by Cameron653** [comment]
...mark this DNM I've been notified that _this is the case for a bunch of organs._ Going to fix.

**Comment by Cameron653** [comment]
Anewbe you got it RIGHT after I finished it ahhh.

Anyways this isn't WIP anymore. Good to go.

**Comment by Anewbe** [comment]
Did you double check that those definitions are actually elsewhere, and did you test that code doesn't expect them to be in this file?

**Comment by Cameron653** [comment]
Yes. I made sure that they were defined elsewhere. They'll all conveniently in the files contained in the 
https://github.com/PolarisSS13/Polaris/tree/master/code/modules/organs/internal
folder.

**Comment by Anewbe** [comment]
o7

**Comment by Wutnold124** [comment]
the hero we need, but not the one we deserve

thanks Cameron653, you cured Multipleorganitis.

**Comment by Cameron653** [comment]
I was trying to figure out how to tear out organs (Kali ma) and saw that the heart was defined twice and led me on this tangent.

**Comment by Cameron653** [comment]
AS IT TURNS OUT, internal/organ_internal is the one that is checked, this one isn't in the .dme

Not actually that big of an issue though as the comments will direct people to the correct place of where to find it, instead of having old, unused code and processes.

**Pull request merged**
