### PR TITLE
Solars start wired

### PR DESCRIPTION
**Pull request by Kelenius**

### CODE REVIEW

**Comment by Ithalan** [comment]
Did you also make the solar consoles and SMES units start out correctly set up like the one on the telecomm satellite is? If solar power is flowing from the start, it'd do a great deal to prevent the total blackout that happens if the round starts without an engineer

**Comment by Kelenius** [comment]
They don't, because the station's powergrid is more complicated than the telecomms. You'd need to play with the SMES settings for a better result.

**Comment by redstryker** [comment]
Meh, I don't like this, personally.  It gives the engineers something to do besides set up the engine, but that's just me. *shrug*

**Comment by Nalarac** [comment]
As an engineer, I can say almost no one ever wants to set up the solar arrays.

**Comment by Hubblenaut** [comment]
I'd rather having the SMES set along with this, so power is also sustained a while longer when no engineer is in the round.

Some charge on the SMES for buffer, then Input = max. possible input with our solar array setup (I believe 120 kW?), output roughly half of it. We can see where this goes.

**Comment by Kelenius** [comment]
Outside of the scope.

**Comment by Nerezza** [comment]
As an engineer I can't remember the last time solars were wired 'just because'. Nobody does it like that anymore, you have to have either a captain tell you or some power emergency for it to happen.

Furthermore, it's just strange that someone goes along and cuts all the solar wires between shifts. I can get that the engine would be offline while the operations deck is unmanned, but I don't get why someone would go out on the arrays, cut all the wire, and leave it laying by the arrays.

**Comment by Telvayne** [comment]
I agree.  As Xica/Penance, I have never once wired solars for fun, because that stopped being fun a few weeks after I first played SS13.  It's dull, the airlocks are slow, there are no carp to make it !!FUN!!.  It's tedious clicking, with occasional frustration that you slightly misclicked by a pixel and have to cut the wire an redo it.

I absolutely, 100% support this PR.

**Comment by Datraen** [comment]
:+1:

**Pull request merged**
