### PR TITLE
Sell thaler for cargo points!

### PR DESCRIPTION
**Pull request by mistyLuminescence**
So you know those departmental fund accounts that nobody uses? They're now relevant. You can put thalers in a crate and ship them off in Cargo, for 0.02 points each - that's 50 thaler for 1 cargo point.

For comparison...
Departmental accounts have 5000 Thaler (100 points)
Station funds have 75000 Thaler (1500 points)
Colony Director starts with about 10000 Thaler (200 points)
A fancy laptop is about 600 Thaler (12 points)
A crate of clotting agent is 2000 Thaler (40 points)
A hat crate is 10000 Thaler (200 points)

So now Cargo can _charge_ for their services!
Disclaimer: misty will not be held responsible for any deaths that occur from paperwork.

### CODE REVIEW

**Comment by Atermonera** [comment]
Why did you change the indent on all of those lines and why isn't byond throwing a fit that they aren't proper tabs?

**Comment by mistyLuminescence** [comment]
I-I didn't do it on purpose I swear it just.. happened

**Comment by Anewbe** [comment]
Other than the updates, looks fine to me. Did you test this?

**Comment by mistyLuminescence** [comment]
Yep, works great. Money goes in crate goes on shuttle makes bank.

**Comment by Anewbe** [comment]
Alrighty.

**Pull request merged**
