### PR TITLE
Item placement tweaks

### PR DESCRIPTION
**Pull request by LorenLuke**
Ported from Bay12.

- Allows items (not just food) to be placed where clicked on on tables.

- Randomises item placement when dropped or on spawn

- Adds a few param functions.

### CODE REVIEW

**Comment by Yoshax** [comment]
The random item placement is one of the ugliest things to ever happen. Please no.

**Comment by LorenLuke** [comment]
@Yoshax Be that as it may, the ability to not have everything be on top of each other far outweighs the downside, IMO.

**Comment by Yoshax** [comment]
I don't really think there's any benefit. It looks nice when it's all of one thing stacked, assuming this uses the exact same as Bay where they stack nicely. Like so:
Bay

But when it's different things, it starts to look really messy and rather ugly.

**Comment by Anewbe** [comment]
I don't really have a desire for this right now. Item clutter is fine as is, in my mind.

**Comment by LorenLuke** [comment]
@Anewbe 

I'd like to be able to arrange things in a table. If you don't mind it, and I do, them not merging will be one person upset and one apathetic. Merging means one person happy and one apathetic. Just because you see no issue does not mean it affects nobody else. I went through the effort to add it... If there's no issue on your end, there's no harm in merging it.

**Comment by Anewbe** [comment]
I'm antipathic, not apathetic. I do not want this code, because I agree with Yoshax, it'd look bad.

**Comment by LorenLuke** [comment]
@Anewbe 
If I remove the random placement but keep the ability to place things on tables (which is what I was thinking for in the first place), would that suit you as a fair compromise?

**Comment by LorenLuke** [comment]
@Anewbe Still waiting on that answer

**Comment by Anewbe** [comment]
Maybe if you recode it so it's just that, I'll review it and change my mind, but as is I'm not merging this.

**Comment by LorenLuke** [comment]
@Anewbe Done.

**Comment by Anewbe** [comment]
Gonna close this for the time being, as no progress is being made.

**Pull request closed without merging**
