### PR TITLE
Synth Coloring

### PR DESCRIPTION
**Pull request by shazbot194**
Hello, So this is my first PR here, so if I make a mistake, please tell me and I will correct it. This PR is rather small, but adds in a massive feature. It adds in the ability to color synth parts seperatly from everything else, or to be able to disable it and use the default colors. This also adds in two sets of parts, the Xion Whiteout series, which are standard Xion parts and Xion Breach head painted white to allow for better coloring.

Here are the new parts and how the menu looks with the option disabled.
o9zjkdegqnas5ymgsenzza
jxoagba4qu2nj3eav3mcvg
Here are the same parts but with the option enabled and set to a blue color.
dpamab3uq8mbdcgtdmyobq
tzz3xrfbqk2ntenqyrikew
And because of how it's coded, parts that are meant to look like your organic parts, and are labeled as such, are excluded from this coloring. As you might notice, the skin colored arm looks different, that is because it's a Very-Med arm.
vyw4fbprsaa5ytki_yktcw
And to just show it works in game.
ow6i9seosvuljazvqvdd-w

Please if you have any feedback, give it to me so I can make corrections if needed.

### CODE REVIEW

**Comment by Anewbe** [comment]
How does this interact with the VeyMed bodies?

**Comment by Mechoid** [comment]
'And because of how it's coded, parts that are meant to look like your organic parts, and are labeled as such, are excluded from this coloring. As you might notice, the skin colored arm looks different, that is because it's a Very-Med arm.'
From the OP

**Comment by Anewbe** [comment]
Disregard Anewbe, he skim-reads the first time he sees a PR.

**Comment by Wutnold124** [comment]
dude, dude

hell yeah

**Comment by shazbot194** [comment]
If you have any questions of concerns, I can answer them.

**Comment by Anewbe** [comment]
I might when I've actually read the code in full.

**Pull request merged**
