### PR TITLE
Biohazard Voidsuit

### PR DESCRIPTION
**Pull request by redstryker**
Adds a Biohazard variety of the Medical voidsuit. It is a direct child of the suit and can be created by cycling a voidsuit with Medical access. Emags will also allow you to make your suit into it.

Sprites:
http://puu.sh/r5zFh/e1a3cb45db.png

### CODE REVIEW

**Comment by nachomeep** [comment]
What's the point of this, exactly?

Just asking- what situation would you use this in?

**Comment by redstryker** [comment]
It's a reskin, so there is really no mechanical difference with it.  The point is to add different variations of the voidsuits so that players have something else to use besides the current voidsuits.  I suppose it could be used for like.. a blob or something, but since there's no real mechanical difference, *shrug*.

**Comment by nachomeep** [comment]
This also brings up minor concerns that I have- heisters start with suits of certain departments. If we were to add variations to, say, the mining suit, it'd be harder for them to fake being a crewmember- something I actually see done very often.

**Comment by redstryker** [comment]
I do plan to have a variation for the Mining suit.  I have plans for variations for all of the voidsuits.

**Comment by nachomeep** [comment]
So, will heisters be given a suit cycler and access to these variations to make up for it?

**Comment by redstryker** [comment]
I don't know much about heist, TBH.  If they currently have a suit cycler?  I suppose so.  But if they don't, who knows?  Mercs will definitely have access to all of these variations, however.

**Comment by Anewbe** [comment]
Heisters should already have a suit cycler, if memory serves.

**Pull request merged**
