### PR TITLE
Replaces robot storage pod.

### PR DESCRIPTION
**Pull request by Belsima**
images
images

Now rather than a stolen guest console and a wider suit storage, it's a CEV-Eris guest console and an FTL-13 recolored suit storage.

### CODE REVIEW

**Comment by Cyantime** [comment]
Why would you get rid of a unique sprite and replace it with a palette swap of something else?

**Comment by Belsima** [comment]
It's not a unique sprite. They literally took the original and copy + pasted it to widen it.

**Comment by Atermonera** [comment]
Can't look at the .dmi from my phone, but in case you totally removed the old sprites, common (or at least common in days of yore) practice was to rename the old sprites to x_old or something, so that they're still in the code.
If you did just rename the old sprites, then disregard.

@Cyantime, it's mostly just matter of preference. Both sprites involved are minor modifications to an existing sprite, it's just the nature of how they were altered that differs

**Comment by Belsima** [comment]
I'll add the _old ones, smart idea.

**Comment by Cyantime** [comment]
I really feel that the wider version fits better, it looks like a big box that you shove a whole robot into, instead of just a blue suit storage unit.

**Comment by Belsima** [comment]
That's fair enough. If anyone else puts in input, i'll just replace the console.

**Comment by Belsima** [comment]
Actually, I agree tbh. Gonna shut this down.

**Pull request closed without merging**
