### PR TITLE
Blind port of Bay Radiation Subsystem

### PR DESCRIPTION
**Pull request by Novacat**
Figured I would do my part to move everything over to subsystems.

Cursory tests suggest it works just fine.

### CODE REVIEW

**Comment by Atermonera** [comment]
How does this differ from the current system, if I may ask?

**Comment by Novacat** [comment]
There are some minor changes but otherwise it is exactly the same, unfortunately I could not find documentation on those changes, my guess is optimization?

**Comment by chaoko99** [comment]
extremely major optimization and solid structures actually stopping radiation.

**Comment by chaoko99** [comment]
I think it hooks into the material system in some way, but I can't remember.

**Comment by Novacat** [comment]
Solid structures actually stopping radiation was a separate change that I did not port, though if it is desired I could attempt to seek it out and port it.

**Comment by chaoko99** [comment]
It is desired. *VASTLY.*

**Comment by Atermonera** [comment]
I mean the code looks mostly fine so if travis says it's ok then it probably won't set everything on fire? :+1:

**Pull request merged**
