### PR TITLE
Fix Baystation12/Baystation12#11955, fix #479

### LINKED ISSUE #479: Solar SMES don't charge
Discovered while wiring solar as drone this morning.
Wired solars as previously would, SMES remained red even during peak stellar orientation.
Disconnected  and reconnected wires to SMES and terminal.
Disassembled and reassembled terminal, SMES and terminal after.
Would not charge if set to anything greater than 0w input.

### PR DESCRIPTION
**Pull request by GinjaNinja32**
Cherry-pick of Baystation12/Baystation12#11958
Fix Baystation12/Baystation12#11955
fix #479
makes #752 pointless

### CODE REVIEW

**Comment by Yoshax** [comment]
#752 makes the room the same as the others too, makes sense from an architectural standpoint

**Comment by GinjaNinja32** [comment]
*shrug.
Makes it not required for functioning solars.

**Comment by Yoshax** [comment]
Up to whoever, I'll leave it open.

**Comment by Zuhayr** [comment]
:+1:

**Pull request merged**
