### PR TITLE
Slime brains now actually have container settings!

### PR DESCRIPTION
**Pull request by Belsima**
orgam

### CODE REVIEW

**Comment by mistyLuminescence** [comment]
our 5000th PR for an orgam

**Comment by Belsima** [comment]
orgam

**Comment by Belsima** [comment]
what the fuck.

**Comment by Atermonera** [comment]
Cue a fleeting notion to rewrite mining code to be some sort of minigame, and call it 'orgam' in code, because that's two keypresses fewer than 'oregame'
(No I'm not signing up for this, there's other things I need to do first)

**Pull request merged**
