### PR TITLE
Adds food bags!

### PR DESCRIPTION
**Pull request by mistyLuminescence**
Adds food bags - you can hold lots of food in them. They're like chem/plant/ore bags but for food. That's pretty much it. Found in the kitchen vendor and the chef's wardrobe.

fight me travis

### CODE REVIEW

**Comment by Anewbe** [comment]
I'm really, really not seeing the need for this.

**Comment by mistyLuminescence** [comment]
Request from @MisterLayne who knows how to code but asks me to do it anyway for some reason, but it seems like it adds a way for chefs to easily and conveniently move around food items in bulk. Not exactly gamebreaking by any means, and if it makes moving food a little less tedious, if it improves the experience of at least one person without upsetting anyone else, it's worth having.

**Comment by MisterLayne** [comment]
Elaborating off of Misty, who I am very grateful pushed this for me because I was busy cooking in game.

When I cut a pie or cake, I usually have about six pieces, and I only put one on display on the counter. Meaning that I have a bunch of pieces of cake cluttering my cooking space. It would be a whole lot easier to hold all this stuff in my chef's bag so that I could pull it out when somebody wanted a piece of cake. Another example would be if I made a bunch of dough, and it's messily lying around in the kitchen; I would love to be able to hold it somewhere nice for when I need a piece of dough.

This doesn't mass effect the station, and it's just a tiny 'make things easier' bag for the cook.

**Comment by SilverTalismen** [comment]
I would personally suggest a rack of some sort to store excess food in, click it and it'll tell you what foods in there and how many pieces of it is there?

**Comment by Anewbe** [comment]
I thought the Smartfridge did that?

**Comment by mistyLuminescence** [comment]
The smartfridge doesn't let you pick up and move items, only store them - same as a closet or a table. This would also allow chefs to, say, move items in bulk from the smartfridge to the counter, from the counter to the smartfridge, or to the bar, or one of the tables where people are sitting for a meal.

**Comment by Atermonera** [comment]
So it functions like the plant bag except for cooked foods // foods in general?

**Comment by mistyLuminescence** [comment]
Yep, it's exactly like the plant bag, except for foods. Click on something on a tile to pick up all food items on that tile.

**Comment by Woodratt** [comment]
Picture of sprites? Or is it just a recolored bag?

**Comment by mistyLuminescence** [comment]
Recolored food bag, looks like [this](https://image.prntscr.com/image/_2ccF-cOSKCnoK2cJScnpA.png).

**Pull request merged**
