### PR TITLE
Ports the Stasis Only Sleeper

### PR DESCRIPTION
**Pull request by Anewbe**
Ported from Virgo.
Actually mapping them in will come later.

### CODE REVIEW

**Comment by Arokha** [comment]
Those have special sprites they use, too. You mightcould grab them. They are from /tg/ so open source yadda yadda.

**Comment by Anewbe** [comment]
Honestly not a fan of those sprites, don't fit in too well in my opinion.

**Comment by Arokha** [comment]
Maybe? But to what end? There's no control panel to control injections/dialysis/etc.

**Comment by Atermonera** [comment]
Unless someone builds a console next to it, in which case it will automatically link afaik

**Comment by Atermonera** [comment]
It also doesn't override the `stasis_choices` list, so if you build a sleeper console next to it, it'll function exactly the same as a regular sleeper

**Pull request merged**
