### PR TITLE
New Player/Character Setup (Fake)NanoUI

### PR DESCRIPTION
**Pull request by Arokha**
Used the fake NanoUI 'browser' datum to render the pages for the New Player panel and the Character Setup screen.

While I consider Polaris' character setup screen to be mechanically better than others, it wasn't prettier. Well. It was a bit. But now it's more pretty-er. Did this since we're switching to your codebase, so, this is the first upstream PR.

@Datraen mentioned this might be desired here.

Fake Nano Setup

### CODE REVIEW

**Comment by Datraen** [comment]
:+1: It's better than white background and black text.

**Comment by EmperorJon** [comment]
It certainly is an improvement, that's for sure.

**Comment by Spacemanspark** [comment]
When you first log into the server, and click the character setup button, does it take three minutes to open?
Paradise had and fixed that issue for awhile.

**Comment by Arokha** [comment]
After the server is done starting (as in, done initializing geometry and ZAS) the button works just as fast as the black/white character setup screen. I don’t notice any difference in speed. This isn’t really even NanoUI, just the fake CSS styles that make it look like it, so if they had some shortfall in NanoUI, this would be unlikely to have the same issue.

**Comment by Arokha** [comment]
Also I should mention the colored text for the toggle between "Join as assistant if pref unavailable/Return to lobby if pref unavailable/Join as random if pref unavailable" on the occupations screen is now just white text for all three choices. Sorry. There's just no colors that look good on NanoUI buttons.

**Comment by Spacemanspark** [comment]
Gotcha, thanks.

**Pull request merged**
