### PR TITLE
Revert "Fixes two issues on map for Security"

### PR DESCRIPTION
**Pull request by Yoshax**
Reverts PolarisSS13/Polaris#2224

### CODE REVIEW

**Comment by Neerti** [comment]
To those that are curious as to why, the PR being reverted had inadvertently reverted some other stuff.

**Comment by SpadesNeil** [comment]
:(

**Comment by ParadoxSpace** [comment]
For instance, the deep fryer.

**Comment by SpadesNeil** [comment]
https://github.com/PolarisSS13/Polaris/pull/2236 This time I did it correctly.

**Pull request merged**
