### PR TITLE
revert chemical dispenser revert

### PR DESCRIPTION
**Pull request by GinjaNinja32**
- adds base chemical regeneration to cartridge dispensers (i.e. your carbon cartridge will slowly be refilled with carbon, but your phoron cartridge will stay how you left it)
- removes energy-only dispensers

this lets chemists use the cartridge system to put whatever they want in the dispenser, while maintaining the chems-from-energy infinite-chem setup. Bonus: you can still replace the cartridges from cargo if you really don't want to wait for the recharge.

### CODE REVIEW

**Comment by zaredman** [comment]
Just pointing out that the cartridge chem dispensers should still be in polaris-code BUT were intentionally not used per preference/planned direction of the founding staff.

**Comment by zaredman** [comment]
After discussion, internal opinion is that they are ok with this -- but not as a flat-out replacement for 'energy dispensers.' If you want to make it as an alternative but not a replacement, go for that.

**Comment by Hubblenaut** [comment]
I'm not sure why this is debated on so much - the new dispensers have been way more realistic, a quality of life for chemists and open a way for modular construction in the future.

If people had a problem with ordering new supplies from cargo because of the finite supply, they should be relaxed to find that this PR doesn't get rid of the energetic synthetize of reagents, but only adds a level of complexion.

**Comment by GinjaNinja32** [comment]
>this allows unlimited supply of non-standard reagents.

@Hubblenaut, I'm not sure what you mean here. Unlimited supply of what, exactly?

**Comment by Hubblenaut** [comment]
If I'm not wrong, doesn't this allow to fill a cartridge with a custom reagent of your choice and the machine will attempt to synthetize more of it?

**Comment by GinjaNinja32** [comment]
No, it will only fill cartridges labelled with the name of a starting reagent (carbon, oxygen, etc), and it will only fill with the reagent the cartridge is labelled as.

Carbon-containing cartridge labeled 'stuff' -> no change
Carbon-containing cartridge labeled 'Carbon' -> fills up with carbon
Phoron-containing cartridge labeled 'stuff' -> no change
Phoron-containing cartridge labeled 'Carbon' -> carbon is added to the phoron

**Comment by Hubblenaut** [comment]
I see then, got no other concerns.

**Comment by GinjaNinja32** [comment]
archgadfishoghfouahsoa

mapmerge pls

**Comment by GinjaNinja32** [comment]
ok so afaict either maptools are entirely broken or #566 broke everything

**Comment by GinjaNinja32** [comment]
in theory #624 being merged *should* fix the conflicts with this PR? Maybe? I have no idea.

**Comment by zaredman** [comment]
@GinjaNinja32 poll to close Tue Dec 22, 2015 12:51 pm - Current standings 9yes/1no.

**Comment by Hubblenaut** [comment]
Can somebody deliver reasons for *why* this is a bad idea and where the issues are?

**Comment by GinjaNinja32** [comment]
Conflict fixed.

**Comment by Datraen** [comment]
Given the latest results, pulling contravertial and DNM tags.

**Comment by Neerti** [comment]
Just waiting for Ala to sign off now, hopefully it'll be within a day.

**Comment by GinjaNinja32** [comment]
aaaaaaa

**Comment by GinjaNinja32** [comment]
aaaAAAAAA

**Comment by Zuhayr** [comment]
>within a day

**Comment by Datraen** [comment]
It was "hopefully [the ruling will] be within a day."

**Pull request merged**
