### PR TITLE
Sky is not a 'skiy'

### LINKED ISSUE #5342: Falling Out of the Skiy

### PR DESCRIPTION
**Pull request by MisterLayne**
I believe I can **skiy**.
Fixes #5342

### CODE REVIEW

**Comment by MisterLayne** [comment]
Why is it tracking **all** of these merges. Help please.

**Comment by Atermonera** [comment]
You branched off of your clandestine gamemode branch, instead of master. Hence the `Clandestine (Original Commit)` and revert commits.

**Comment by MisterLayne** [comment]
Git is saying i'm branching off of master. Is there, uh.. How do I fix this?

**Comment by Atermonera** [comment]
Once this gets merged it should fix itself, but the actual solution is to rebase your master branch onto upstream master. See the advanced guide to git I wrote a month or two ago, on the github wiki

**Pull request merged**
