### PR TITLE
Research Machines can use Plastic and Osmium

### PR DESCRIPTION
**Pull request by Mechoid**
Allows Research machines (Protolathe, Circuit Printer, Mech Fab, and Pros Fab) to store and use plastic and osmium sheets. No recipes currently use these.

### CODE REVIEW

**Comment by MisterLayne** [comment]
Will any recipes be updated to include either of these two ingredients? I can forsee a lot of stuff using this.

**Comment by Mechoid** [comment]
Plastic, yes, Osmium less so due to platinum being just less rare than diamond, it's more of an in-between tier from silver/gold to diamond.

**Comment by Anewbe** [comment]
Tested?

**Comment by Mechoid** [comment]
Unless my memory is faulty, yep! Even tested it on live.

**Pull request merged**
