### PR TITLE
Removes cameras from private places

### PR DESCRIPTION
**Pull request by Yoshax**
Removes cameras from:
- Bedrooms
- Visitor rooms
- Bathrooms

Violating the privacy of both employees, visitors and anyone else is inappropriate, and suited for a workplace, or anything of the sort. In general real life, cameras are only placed in these places when trouble, or such is expected, or where there has been previous occurrences of this.

### CODE REVIEW

**Comment by Nerezza** [comment]
Or when the person watching a hentai~

Also there used to not be cameras in these places iirc, kinda funny that they're a thing now.

**Comment by SpadesNeil** [comment]
But but but... how else is security going to fap to pixel ERP in the dorrrrms? :-1: 

I'm kidding, this is fine.

**Comment by Woodratt** [comment]
What restrooms had their cameras removed? The only ones that I know of that have ones right now is the locker room main area (showers and stalls have no cameras). And the Rec Area main area, (again showers and stalls have no cameras). Since you labeled bedrooms separately from visitor rooms, also curious as to what bedrooms currently have cameras that you removed?

**Comment by Yoshax** [comment]
All of the restrooms on station that had a camera, locker room, one beside the pool. Bedrooms should probably be singular, only removed from captain's bedroom. Removed them from all the places one can expect privacy in. It's kinda odd to have cameras installed in bathrooms and what are basically hotel rooms.

**Comment by Anewbe** [comment]
Can we get images?

**Comment by Woodratt** [comment]
There really isn't any images to add Anewbe, considering what it changes is removing cameras.

**Comment by Anewbe** [comment]
Fair enough.

**Pull request merged**
