### PR TITLE
Fax, Prayer, and Emergency Comms

### LINKED ISSUE #1862: Admin prayer, admin fax, and admin emergency comms should make a noise.
#### Brief description of the issue
Not an obnoxious BOINK like the current adminhelp does, but the fax alert should make fax noises, the comms alert should make a gentle beeping telecomm-ish sound, and the prayer should be a nice holy-sounding 'ding'.

This makes it easier for admins to not lose track of IC events when people are trying to contact CentCom--or the gods.

I have some sounds sitting around that I can use for this and will do this myself when I stop being lazy.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/574f96639a5bafbb1062f77022d1878e8c7457be

### PR DESCRIPTION
**Pull request by SpadesNeil**
Resolves #1862

Also fax machines sound like actual fax machines now instead of cameras.

### CODE REVIEW

**Comment by Datraen** [comment]
Sources for the two audio files?

**Comment by SpadesNeil** [comment]
The prayer ping is the sound of flicking a glass goblet, and the fax machine sound is a recording of a laser printer.

**Comment by Datraen** [comment]
So you are the creator of those files, then?

**Comment by SpadesNeil** [comment]
Correct, unless I've gone crazy and am remembering wrongly.

**Pull request merged**
