### PR TITLE
Gives renegade the LeMat.

### PR DESCRIPTION
**Pull request by Belsima**
I was thinking this was a bad idea, but it doesn't use .357 and they already get a damn strong revolver option anyway.

### CODE REVIEW

**Comment by Yoshax** [comment]
It's a pretty weak weapon in comparison to the Revolver or suchlike, so it shouldn't really be a worry. You get (9 * 20) + 50 = 360 vs the Revolver which is 6 * 60 = 360. Only upside really is you have 10 total shots, and of course the swagger that comes with having a Revolver with an underbarrel Shotgun.

**Comment by Belsima** [comment]
Oh, that's not too bad at all. The 'revolver with a shotgun' basic idea just spooked me a good bit.

**Comment by Yoshax** [comment]
You could probably get away with adding it to the uplink as well. Pricing it may be a little difficult though.

**Comment by Belsima** [comment]
I'll add it to the uplink in my uplink PR.

**Pull request merged**
