### PR TITLE
adds the MTV Get Off the Air

### PR DESCRIPTION
**Pull request by Belsima**
[if you dont merge this i will personally stand up and fight you. get over here, Devs. This iS Art.](https://open.spotify.com/track/5wQ6zZPJnqI9DAXv4qcRjL)

### CODE REVIEW

**Comment by AranBelami793** [comment]
why MTV gota?

**Comment by AranBelami793** [comment]
Soup is Good Food's so much more appropriate

**Comment by Belsima** [comment]
because of the morpheus MTV prefix, duh
though youre right

**Comment by AranBelami793** [comment]
yeah, that's like a far longer stretch than a song talking about computers replacing humans

**Comment by AranBelami793** [comment]
I mean, take just about any Dead Kennedys song and it fits SS13 imo

**Comment by AranBelami793** [comment]
So instead of MTV get off the air I propose we add the entire DK discography

**Comment by Belsima** [comment]
it's because ingame the ships have an "MTV" prefix

**Comment by MarinaGryphon** [comment]
The name of the ship is "Get Off The Air", while the full name of the song is "MTV Get Off The Air". The game adds the prefix to form the "MTV Get Off The Air". It's because of the name, not for symbolism - which fits Morpheus naming pretty well, honestly.
(I support this, if that wasn't clear.)

**Pull request merged**
