### PR TITLE
Sensible Job Titles

### PR DESCRIPTION
**Pull request by SpadesNeil**
Basically #3986 except condensed to the ones that were actually good, plus one more.

- Gardener is now Botanist. Gardener has been moved to an alt title.
This is more fitting for what the role actually does. Besides, who calls them the gardener? I call them botanists.
- The alt title Commander is now _Security_ Commander, to avoid confusion. The title of "Commander" alone implies a role equal to Captain or Colony Director, which is not correct.
- ~~Research Director is now Research _Supervisor_ by default which was formerly an alt-title. It's also much more fitting for what the Research head of staff actually does, which is generally just supervise.~~
- ~~_Head of Research_ has been added as an alt title in place of the old alt title. Either of these could be the new default, I don't care which.~~
- ~~Research _Director_ has been removed entirely to stop confusion with Colony Director.~~

### CODE REVIEW

**Comment by SpadesNeil** [comment]
Also, can I add Deputy Director back to the HoP's alt titles? Because I feel it fits. @Anewbe @Neerti

**Comment by Cerebulon** [comment]
I'm not a fan of removing RD as a title entirely. Whether they "just supervise" or actively organize research efforts is entirely up to the player (who can pick an alt title to match if they like) and not something built into the role. My RD character(s) have always been more on the active involvement side.

**Comment by Anewbe** [comment]
I uh... Sort of specifically requested that you only change the two titles, being Security Commander and Gardener. This'll need to go back for review, again.

**Comment by SpadesNeil** [comment]
I was under the impression that you disliked the confusion between RD and CD so I sought to fix that.

**Comment by Anewbe** [comment]
I do, but that's not how I'd like to fix it, and I don't have a great need to fix it at this moment.

**Comment by SpadesNeil** [comment]
¯\_(ツ)_/¯

**Comment by Techhead0** [comment]
"Maid" got axed? I was kinda-sorta looking forward to knowing it existed somewhere.

**Comment by Anewbe** [comment]
@SpadesNeil There's a PR in the works that is going to touch these files, probably, and I've specifically been waiting for this PR for a while now, so your PR will probably be merged after that is. Other than that I don't see a reason not to merge this, so hang tight.

**Comment by Anewbe** [comment]
@SpadesNeil Conflicts, sorry. Would you mind terribly giving this a fix?

**Pull request merged**
