### PR TITLE
Adds Vey-Med ship names

### PR DESCRIPTION
**Pull request by elgeonmb**
In the previously agreed upon "way too long Diona style".

(I actually compiled this time)

### CODE REVIEW

**Comment by Anewbe** [comment]
Not entirely sure why this has the just-added ship names highlighted as changes.

**Comment by elgeonmb** [comment]
Eugh probably because of me fucking up a syncing pr?

**Comment by Anewbe** [comment]
Did you manually add the old names, or did you pull it from the master? Also, when did you make the branch?

**Comment by elgeonmb** [comment]
Pulled from master and then like, ten minutes ago

**Comment by elgeonmb** [comment]
I did a squash merge which is I think the issue?

**Comment by Anewbe** [comment]
Maaaaybe try updating your master and making the branch again?

**Pull request closed without merging**
