### PR TITLE
Rainbow Slime Fix + Skrell Lang Color

### PR DESCRIPTION
**Pull request by MisterLayne**
Fixes [Issue#3836](https://github.com/PolarisSS13/Polaris/issues/3836), as well as changes the color of the Skrell Language to something a little bit darker, because I don't know if it's just me, but, the Skrell color is way too bright to be seen against the white background in game.

### CODE REVIEW

**Comment by Anewbe** [comment]
Please do not blend PRs. These are two unrelated pieces of code, it's preferable that they go in separate Pull Requests.

**Comment by elgeonmb** [comment]
I like Skrellian speech color as it is.

**Comment by Magneld** [comment]
Can agree with the language colour being a bit eye-stabby.

**Comment by Belsima** [comment]
I love the current Skrellian speech color, personally.

**Comment by Belsima** [comment]
For reference.

Old: image
New: image

**Comment by MisterLayne** [comment]
I think it's a nice color, but even with as big a monitor I have, it still seems too bright to be easily readable.

**Comment by elgeonmb** [comment]
Yes, just like the Skrellian language on the whole.

**Pull request closed without merging**
